import assert from 'node:assert/strict';
import test from 'node:test';
import { newDb } from 'pg-mem';
import { CrmActivityService, PostgresCrmActivityRepository } from '../src/crm-activity.js';
import { createPostgresRuntimeConfig, PostgresRuntime } from '../src/postgres-runtime.js';
import { FOUNDATION_MIGRATIONS, PostgresMigrationRunner } from '../src/migrations.js';
import { DOMAIN_MIGRATIONS } from '../src/domain-migrations.js';

async function fixture(){const db=newDb({autoCreateForeignKeyIndices:true,noAstCoverageCheck:true});const {Pool}=db.adapters.createPg(),secrets={getSecret:async()=> 'test-only'},base={environment:'test',host:'localhost',database:'atlas_crm_test',user:'atlas',passwordSecretRef:'x',tls:{required:false}};const app=new PostgresRuntime(await createPostgresRuntimeConfig({...base,role:'APPLICATION'},{secretProvider:secrets}),{PoolCtor:Pool}),migration=new PostgresRuntime(await createPostgresRuntimeConfig({...base,role:'MIGRATION'},{secretProvider:secrets}),{PoolCtor:Pool});const runner=new PostgresMigrationRunner({runtime:migration,migrations:FOUNDATION_MIGRATIONS,lock:{acquire:async()=>async()=>{}}});await runner.apply();return {app,migration,service:new CrmActivityService({repository:new PostgresCrmActivityRepository({runtime:app}),clock:()=>new Date('2026-09-01T12:00:00Z')})};}
async function seed(f){await f.app.query("INSERT INTO atlas_installation(installation_id,tenant_id) VALUES('INSTALL-A','TENANT-A'),('INSTALL-B','TENANT-B')");await f.app.query("INSERT INTO atlas_users(user_id,display_name) VALUES('USER-A','Alex'),('USER-B','Blair')");await f.app.query("INSERT INTO atlas_customers(tenant_id,customer_id,company_name,normalized_name) VALUES('TENANT-A','CUSTOMER-A','Dealer A','dealer a'),('TENANT-A','CUSTOMER-B','Customer B','customer b'),('TENANT-B','CUSTOMER-X','Other','other')");await f.app.query("INSERT INTO atlas_contacts(tenant_id,contact_id,customer_id,display_name,normalized_display_name) VALUES('TENANT-A','CONTACT-11111111-1111-4111-8111-111111111111','CUSTOMER-A','Dana','dana'),('TENANT-A','CONTACT-22222222-2222-4222-8222-222222222222','CUSTOMER-B','Casey','casey')");await f.app.query("INSERT INTO atlas_rfqs(tenant_id,rfq_id,customer_id,status) VALUES('TENANT-A','RFQ-A','CUSTOMER-A','OPEN')");await f.app.query("INSERT INTO atlas_quotes(tenant_id,quote_id,customer_id,status) VALUES('TENANT-A','QUOTE-A','CUSTOMER-A','DRAFT')");await f.app.query("INSERT INTO atlas_jobs(tenant_id,job_id,customer_id,status) VALUES('TENANT-A','JOB-A','CUSTOMER-A','DRAFT')");}
const context={authoritative:true,tenantId:'TENANT-A',userId:'USER-A',correlationId:'CORR-134',capabilities:['CRM_ACTIVITY_READ','CRM_ACTIVITY_WRITE','CRM_FOLLOW_UP_WRITE']};

test('ordered migration extends the canonical activity/follow-up domain and indexes',async()=>{const f=await fixture();const migration=DOMAIN_MIGRATIONS.find(x=>x.id==='0009_crm_activity_follow_up');assert.ok(migration);for(const value of ['direction','source_channel','related_rfq_id','next_action_due_at','atlas_crm_activity_events','atlas_sales_activities_contact_timeline_idx','atlas_follow_ups_owner_due_idx'])assert.match(migration.sql,new RegExp(value));const tables=(await f.app.query("SELECT table_name FROM information_schema.tables WHERE table_schema='public'")).rows.map(x=>x.table_name);assert.ok(tables.includes('atlas_crm_activity_events'));await f.app.close();await f.migration.close();});

test('activity creation preserves Customer/Contact consistency, commercial links and one canonical follow-up',async()=>{const f=await fixture();await seed(f);const created=await f.service.createActivity(context,{customerId:'CUSTOMER-A',contactId:'CONTACT-11111111-1111-4111-8111-111111111111',ownerUserId:'USER-A',activityType:'DEALER_VISIT',direction:'OUTBOUND',occurredAt:'2026-09-01T10:00:00Z',summary:'Discussed dealer program',notes:'Requested pricing.',sourceChannel:'MOBILE_QUICK_ENTRY',relatedRfqId:'RFQ-A',relatedQuoteId:'QUOTE-A',relatedJobId:'JOB-A',nextAction:'Send updated pricing',nextActionDueAt:'2026-09-02T16:00:00Z'});assert.match(created.activity.sales_activity_id,/^CRM-ACT-/);assert.match(created.followUp.follow_up_id,/^CRM-FUP-/);assert.equal(created.followUp.sales_activity_id,created.activity.sales_activity_id);assert.equal((await f.app.query('SELECT count(*)::int count FROM atlas_crm_activity_events')).rows[0].count,2);await assert.rejects(()=>f.service.createActivity(context,{customerId:'CUSTOMER-A',contactId:'CONTACT-22222222-2222-4222-8222-222222222222',activityType:'CALL',summary:'Wrong contact'}));await assert.rejects(()=>f.service.createActivity({...context,tenantId:'TENANT-B'},{customerId:'CUSTOMER-A',activityType:'CALL',summary:'Cross tenant'}));await f.app.close();await f.migration.close();});

test('follow-up due, reschedule, complete and stale version paths are deterministic',async()=>{const f=await fixture();await seed(f);const created=await f.service.createActivity(context,{customerId:'CUSTOMER-A',activityType:'CALL',direction:'OUTBOUND',occurredAt:'2026-08-31T10:00:00Z',summary:'Called purchasing',nextAction:'Call again',nextActionDueAt:'2026-09-01T11:00:00Z'});const due=await f.service.dueQueue(context,{through:'2026-09-02T00:00:00Z'});assert.equal(due.length,1);assert.equal(due[0].dueState,'OVERDUE');const moved=await f.service.rescheduleFollowUp(context,{followUpId:created.followUp.follow_up_id,expectedVersion:1,nextAction:'Send email',dueAt:'2026-09-03T09:00:00Z'});assert.equal(moved.version,2);const done=await f.service.completeFollowUp(context,{followUpId:created.followUp.follow_up_id,expectedVersion:2});assert.equal(done.status,'COMPLETED');await assert.rejects(()=>f.service.completeFollowUp(context,{followUpId:created.followUp.follow_up_id,expectedVersion:2}));await f.app.close();await f.migration.close();});

test('timeline is tenant scoped, contact filterable and bounded with a stable cursor',async()=>{const f=await fixture();await seed(f);for(let i=0;i<3;i++)await f.service.createActivity(context,{customerId:'CUSTOMER-A',contactId:i===0?'CONTACT-11111111-1111-4111-8111-111111111111':null,activityType:'NOTE',summary:`Note ${i}`,occurredAt:`2026-09-01T0${i}:00:00Z`});const first=await f.service.timeline(context,{customerId:'CUSTOMER-A',limit:2});assert.equal(first.items.length,2);assert.ok(first.nextCursor);const second=await f.service.timeline(context,{customerId:'CUSTOMER-A',after:first.nextCursor,limit:2});assert.equal(second.items.length,1);const contact=await f.service.timeline(context,{customerId:'CUSTOMER-A',contactId:'CONTACT-11111111-1111-4111-8111-111111111111'});assert.equal(contact.items.length,1);const otherTenant=await f.service.timeline({...context,tenantId:'TENANT-B'},{customerId:'CUSTOMER-A'});assert.equal(otherTenant.items.length,0);await assert.rejects(()=>f.service.timeline(context,{customerId:'CUSTOMER-A',limit:101}));await f.app.close();await f.migration.close();});

test('service requires authoritative capabilities and never accepts browser TenantID or synthetic Contact data',async()=>{const repository={createActivity:async(_s,x)=>x};const service=new CrmActivityService({repository});await assert.rejects(()=>service.createActivity({...context,authoritative:false},{customerId:'CUSTOMER-A',activityType:'NOTE',summary:'No'}));await assert.rejects(()=>service.createActivity({...context,capabilities:[]},{customerId:'CUSTOMER-A',activityType:'NOTE',summary:'No'}));const result=await service.createActivity(context,{tenantId:'FORGED',customerId:'CUSTOMER-A',contactName:'Synthetic',contactEmail:'fake@example.test',activityType:'NOTE',summary:'Safe'});assert.equal(result.contactId,null);assert.equal(result.tenantId,undefined);});
