import assert from 'node:assert/strict';
import test from 'node:test';
import { CustomerContactCutoverControl, CustomerContactMigration, LegacyCustomerContactSourceReader, PostgresCustomerContactMigrationTarget } from '../src/customer-contact-migration.js';

const TENANT = 'TENANT-A';
const CONTEXT = Object.freeze({ authoritative: true, tenantId: TENANT, userId: 'USER-A', capabilities: ['CUSTOMER_CONTACT_MIGRATE', 'CUSTOMER_CONTACT_CUTOVER'] });
const READY = Object.freeze({ state: 'READY', checks: { applicationRole: { state: 'PASS' }, migrationRole: { state: 'PASS' } } });
const NOW = '2026-08-29T12:00:00.000Z';
const CUSTOMER = Object.freeze({ sourceId: 'ROW-C1', CustomerID: 'CUST-1', TenantID: TENANT, 'Company Name': ' Acme Manufacturing ', 'Primary Contact': 'Pat Legacy', Email: 'sales@acme.test', Phone: '555-0100', Status: 'ACTIVE', Version: 1, 'Created At': '2025-01-01T00:00:00Z', 'Updated At': '2026-01-01T00:00:00Z' });
const CONTACT = Object.freeze({ sourceId: 'ROW-P1', ContactID: 'LEGACY-PAT', TenantID: TENANT, CustomerID: 'CUST-1', DisplayName: 'Pat Smith', Email: 'pat@acme.test', Phone: '555-0101', TitleRole: 'Buyer', Status: 'ACTIVE', Version: 1, CreatedAt: '2025-02-01T00:00:00Z', UpdatedAt: '2026-02-01T00:00:00Z' });
const TARGET_CUSTOMER = Object.freeze({ tenantId: TENANT, customerId: 'CUST-1', companyName: 'Acme Manufacturing', normalizedName: 'acme manufacturing', primaryContactDisplay: 'Pat Legacy', email: 'sales@acme.test', phone: '555-0100', status: 'ACTIVE', version: 1, createdAt: '2025-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z', archivedAt: null });

function data(overrides = {}) { return { customers: [CUSTOMER], contacts: [CONTACT], rfqs: [{ sourceId: 'RFQ-1', TenantID: TENANT, CustomerID: 'CUST-1', ContactID: 'LEGACY-PAT' }], salesActivities: [{ sourceId: 'SACT-1', TenantID: TENANT, CustomerID: 'CUST-1', ContactID: 'LEGACY-PAT' }], ...overrides }; }
function reader(rows = data(), batchSize = 2, calls = []) {
  const names = ['customers', 'contacts', 'rfqs', 'salesActivities'];
  return new LegacyCustomerContactSourceReader({ batchSize, readChunk: async ({ tenantId, cursor, limit }) => { calls.push({ tenantId, cursor, limit }); const page = Number(cursor || 0); const chunk = Object.fromEntries(names.map((name) => [name, (rows[name] || []).slice(page * limit, page * limit + limit)])); const more = names.some((name) => (rows[name] || []).length > (page + 1) * limit); return { ...chunk, nextCursor: more ? String(page + 1) : null }; } });
}
function key(row, name) { return row[name === 'customers' ? 'customerId' : 'contactId']; }
class FakeTarget {
  constructor({ customers = [], contacts = [], fail = false, missing = false, unexpected = false, partial = false, sourcePreservation = 'DEFINED' } = {}) { this.customers = new Map(customers.map((row) => [row.customerId, { ...row }])); this.contacts = new Map(contacts.map((row) => [row.contactId, { ...row }])); this.fail = fail; this.missing = missing; this.unexpected = unexpected; this.partial = partial; this.sourcePreservation = sourcePreservation; this.mutations = 0; this.audit = []; this.references = []; }
  async inspect(plan) { return { customers: plan.customers.map((row) => this.customers.get(row.customerId)).filter(Boolean), contacts: plan.contacts.map((row) => this.contacts.get(row.contactId)).filter(Boolean), foreignTenant: [] }; }
  async recordRun(run, outcome) { this.audit.push({ ...run, outcome }); }
  async migrate(plan, run) { this.mutations += 1; if (this.fail) throw new Error('password=not-returned'); for (const row of plan.customers) if (!this.customers.has(row.customerId)) this.customers.set(row.customerId, { ...row }); for (const row of plan.contacts) if (!this.contacts.has(row.contactId)) this.contacts.set(row.contactId, { ...row }); this.references = plan.references.filter((row) => row.classification === 'RESOLVED'); return { state: 'COMPLETED', runId: run.runId }; }
  async verify(plan) { const missingCustomers = plan.customers.filter((row) => !this.customers.has(row.customerId)).map((row) => row.customerId); const missingContacts = plan.contacts.filter((row) => !this.contacts.has(row.contactId)).map((row) => row.contactId); if (this.missing && plan.customers[0]) missingCustomers.push(plan.customers[0].customerId); return { state: !missingCustomers.length && !missingContacts.length && !this.unexpected ? 'PASS' : 'FAIL', missingCustomers, missingContacts, targetCounts: { customers: this.customers.size + (this.unexpected ? 1 : 0), contacts: this.contacts.size }, expectedCounts: { customers: plan.customers.length, contacts: plan.contacts.length }, unexpectedTargetRows: this.unexpected, activePartialRun: this.partial, sourcePreservation: this.sourcePreservation }; }
}
function migration({ rows = data(), target = new FakeTarget(), readiness = READY, prerequisites = { overall: 'READY_FOR_NEXT_STEP' }, cutoverControl = null, batchSize = 2 } = {}) { return { service: new CustomerContactMigration({ sourceReader: reader(rows, batchSize), target, installationReadiness: { inspect: async () => readiness }, installationPrerequisites: async () => prerequisites, cutoverControl, clock: () => new Date(NOW), softwareVersion: '982a79e' }), target }; }
async function run(mode, options = {}, config = {}) { return migration(config).service.run(mode, CONTEXT, options); }

test('empty source produces a side-effect-free ready plan', async () => { const target = new FakeTarget(); const report = await migration({ rows: data({ customers: [], contacts: [], rfqs: [], salesActivities: [] }), target }).service.run('PLAN', CONTEXT); assert.equal(report.state, 'READY'); assert.equal(report.sourceCounts.customers, 0); assert.equal(target.mutations, 0); });
test('valid Customer normalizes deterministically', async () => { const report = await run('PLAN'); assert.equal(report.customerCounts.valid, 1); assert.equal(report.customerCounts.inserts, 1); assert.equal(report.blocking, 0); });
test('multiple Customers remain tenant scoped', async () => { const second = { ...CUSTOMER, sourceId: 'ROW-C2', CustomerID: 'CUST-2', 'Company Name': 'Beta' }; const report = await run('PLAN', {}, { rows: data({ customers: [CUSTOMER, second], contacts: [], rfqs: [], salesActivities: [] }) }); assert.equal(report.customerCounts.valid, 2); });
test('archived Customer preserves archive semantics', async () => { const report = await run('PLAN', {}, { rows: data({ customers: [{ ...CUSTOMER, Status: 'ARCHIVED' }], contacts: [], rfqs: [], salesActivities: [] }) }); assert.equal(report.customerCounts.archived, 1); });
test('canonical Customer ID is preserved', async () => { const report = await run('PLAN'); assert.equal(report.issues.some((item) => item.code === 'CUSTOMER_ID_MAPPED'), false); });
test('invalid legacy Customer ID receives a stable canonical mapping', async () => { const rows = data({ customers: [{ ...CUSTOMER, CustomerID: 'bad id' }], contacts: [], rfqs: [], salesActivities: [] }); const first = await run('PLAN', {}, { rows }); const second = await run('PLAN', {}, { rows }); assert.equal(first.sourceFingerprint, second.sourceFingerprint); assert.equal(first.issues.some((item) => item.code === 'CUSTOMER_ID_MAPPED'), true); });
test('legacy Customer ID mapping carries into Contact and RFQ reconciliation', async () => { const rows = data({ customers: [{ ...CUSTOMER, CustomerID: 'bad id' }], contacts: [{ ...CONTACT, CustomerID: 'bad id' }], rfqs: [{ ...data().rfqs[0], CustomerID: 'bad id' }], salesActivities: [] }); const report = await run('PLAN', {}, { rows }); assert.equal(report.contactCounts.valid, 1); assert.equal(report.referenceCounts.resolved, 1); assert.equal(report.blocking, 0); });
test('duplicate Customer canonical ID blocks migration', async () => { const report = await run('VALIDATE', {}, { rows: data({ customers: [CUSTOMER, { ...CUSTOMER, sourceId: 'ROW-C2', 'Company Name': 'Conflict' }], contacts: [], rfqs: [], salesActivities: [] }) }); assert.equal(report.state, 'NOT_READY'); assert(report.issues.some((item) => item.code === 'DUPLICATE_CANONICAL_ID')); });
test('malformed Customer record is rejected', async () => { const report = await run('VALIDATE', {}, { rows: data({ customers: [{ ...CUSTOMER, 'Company Name': '' }], contacts: [], rfqs: [], salesActivities: [] }) }); assert.equal(report.customerCounts.rejected, 1); assert(report.issues.some((item) => item.code === 'CUSTOMER_NAME_REQUIRED')); });
test('cross-tenant Customer source fails closed', async () => { const report = await run('VALIDATE', {}, { rows: data({ customers: [{ ...CUSTOMER, TenantID: 'TENANT-X' }], contacts: [], rfqs: [], salesActivities: [] }) }); assert(report.issues.some((item) => item.code === 'CROSS_TENANT_SOURCE')); });
test('valid Contact maps to its Customer', async () => { const report = await run('PLAN'); assert.equal(report.contactCounts.valid, 1); assert.equal(report.referenceCounts.resolved, 2); assert.equal(report.referenceCounts.byEntity.RFQ.resolved, 1); assert.equal(report.referenceCounts.byEntity.SALES_ACTIVITY.resolved, 1); });
test('duplicate Contact email is allowed', async () => { const second = { ...CONTACT, sourceId: 'ROW-P2', ContactID: 'LEGACY-P2' }; const report = await run('VALIDATE', {}, { rows: data({ contacts: [CONTACT, second], rfqs: [], salesActivities: [] }) }); assert.equal(report.blocking, 0); });
test('duplicate Contact phone is allowed', async () => { const second = { ...CONTACT, sourceId: 'ROW-P2', ContactID: 'LEGACY-P2', Email: 'other@acme.test' }; const report = await run('VALIDATE', {}, { rows: data({ contacts: [CONTACT, second], rfqs: [], salesActivities: [] }) }); assert.equal(report.blocking, 0); });
test('blank RFQ ContactID maps to NULL', async () => { const report = await run('PLAN', {}, { rows: data({ rfqs: [{ sourceId: 'RFQ-1', TenantID: TENANT, CustomerID: 'CUST-1', ContactID: '' }], salesActivities: [] }) }); assert.equal(report.referenceCounts.blank, 1); });
test('resolved legacy ContactID maps deterministically', async () => { const report = await run('PLAN'); assert.equal(report.referenceCounts.resolved, 2); assert.equal(report.unresolvedReferences.length, 0); });
test('unresolved ContactID preserves reconciliation evidence', async () => { const report = await run('PLAN', { runId: 'RUN-1' }, { rows: data({ contacts: [], rfqs: [{ sourceId: 'RFQ-1', TenantID: TENANT, CustomerID: 'CUST-1', ContactID: 'ORPHAN' }], salesActivities: [] }) }); assert.equal(report.referenceCounts.unresolved, 1); assert.deepEqual(Object.keys(report.unresolvedReferences[0]), ['sourceEntity', 'sourceRecordIdentity', 'legacyContactId', 'tenantId', 'customerId', 'reason', 'migrationRunId', 'resolutionStatus']); });
test('ambiguous legacy ContactID blocks', async () => { const other = { ...CONTACT, sourceId: 'ROW-P2', DisplayName: 'Other' }; const report = await run('VALIDATE', {}, { rows: data({ contacts: [CONTACT, other], salesActivities: [] }) }); assert.equal(report.referenceCounts.conflicting, 1); assert(report.issues.some((item) => item.code === 'CONTACT_REFERENCE_AMBIGUOUS')); });

for (const [label, customer] of [['primaryContact', { 'Primary Contact': 'Pat Smith' }], ['name similarity', { 'Primary Contact': 'Pat' }], ['email', { Email: 'pat@acme.test' }], ['phone', { Phone: '555-0101' }]]) test(`${label} evidence never synthesizes a Contact`, async () => { const report = await run('PLAN', {}, { rows: data({ customers: [{ ...CUSTOMER, ...customer }], contacts: [], rfqs: [], salesActivities: [] }) }); assert.equal(report.contactCounts.valid, 0); });

test('RFQ same-tenant same-Customer Contact is resolved', async () => { const report = await run('PLAN', {}, { rows: data({ salesActivities: [] }) }); assert.equal(report.referenceCounts.resolved, 1); });
test('RFQ cross-Customer Contact conflict blocks', async () => { const rows = data({ customers: [CUSTOMER, { ...CUSTOMER, sourceId: 'ROW-C2', CustomerID: 'CUST-2', 'Company Name': 'Beta' }], rfqs: [{ sourceId: 'RFQ-1', TenantID: TENANT, CustomerID: 'CUST-2', ContactID: 'LEGACY-PAT' }], salesActivities: [] }); const report = await run('VALIDATE', {}, { rows }); assert(report.issues.some((item) => item.code === 'CONTACT_REFERENCE_CUSTOMER_CONFLICT')); });
test('RFQ cross-tenant evidence fails closed', async () => { const report = await run('VALIDATE', {}, { rows: data({ rfqs: [{ sourceId: 'RFQ-1', TenantID: 'TENANT-X', CustomerID: 'CUST-1', ContactID: 'LEGACY-PAT' }], salesActivities: [] }) }); assert(report.issues.some((item) => item.code === 'CROSS_TENANT_SOURCE')); });
test('Sales Activity Contact consistency is enforced', async () => { const report = await run('PLAN', {}, { rows: data({ rfqs: [] }) }); assert.equal(report.referenceCounts.resolved, 1); });
test('PLAN never mutates PostgreSQL target state', async () => { const target = new FakeTarget(); await migration({ target }).service.run('PLAN', CONTEXT); assert.equal(target.mutations, 0); assert.equal(target.audit.length, 0); });
test('VALIDATE never mutates PostgreSQL target state', async () => { const target = new FakeTarget(); await migration({ target }).service.run('VALIDATE', CONTEXT); assert.equal(target.mutations, 0); });
test('MIGRATE requires explicit trusted capability', async () => await assert.rejects(() => migration().service.run('MIGRATE', { ...CONTEXT, capabilities: [] }, { confirmed: true, runId: 'RUN-1' }), /authority/i));
test('MIGRATE requires confirmation and run correlation', async () => await assert.rejects(() => migration().service.run('MIGRATE', CONTEXT, { confirmed: false, runId: 'RUN-1' }), /confirmation/i));
test('MIGRATE rechecks D-A readiness before mutation', async () => { const target = new FakeTarget(); const report = await migration({ target, readiness: { state: 'CONFIGURATION_ERROR', checks: {} } }).service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-1' }); assert.equal(report.state, 'BLOCKED'); assert.equal(target.mutations, 0); assert.equal(target.audit.length, 0); });
test('MIGRATE rechecks D-B installation prerequisites before mutation', async () => { const target = new FakeTarget(); const report = await migration({ target, prerequisites: { overall: 'NOT_READY' } }).service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-1' }); assert.equal(report.installationReadiness, 'NOT_READY'); assert.equal(target.mutations, 0); });
test('migration failure leaves no partial target writes in transactional adapter contract', async () => { const target = new FakeTarget({ fail: true }); const report = await migration({ target }).service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-FAIL' }); assert.equal(report.state, 'FAILED'); assert.equal(target.customers.size, 0); });
test('idempotent retry recognizes already-present records', async () => { const { service, target } = migration(); assert.equal((await service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-1' })).state, 'PASS'); const retry = await service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-2' }); assert.equal(retry.customerCounts.alreadyPresent, 1); assert.equal(target.customers.size, 1); });
test('active interrupted run blocks cutover readiness', async () => { const target = new FakeTarget({ partial: true }); await migration({ target }).service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-1' }); const ready = await migration({ target }).service.run('CUTOVER_READINESS', CONTEXT); assert.equal(ready.state, 'NOT_READY'); });
test('already-migrated exact target is safe', async () => { const target = new FakeTarget({ customers: [TARGET_CUSTOMER], contacts: [] }); const report = await migration({ target }).service.run('PLAN', CONTEXT); assert.equal(report.customerCounts.alreadyPresent, 1); });
test('partially migrated compatible target plans only missing inserts', async () => { const target = new FakeTarget({ customers: [TARGET_CUSTOMER] }); const report = await migration({ target }).service.run('PLAN', CONTEXT); assert.equal(report.customerCounts.alreadyPresent, 1); assert.equal(report.contactCounts.inserts, 1); });
test('conflicting canonical target blocks', async () => { const target = new FakeTarget({ customers: [{ tenantId: TENANT, customerId: 'CUST-1', companyName: 'Wrong', primaryContactDisplay: '', email: null, phone: null, status: 'ACTIVE', version: 1 }] }); const report = await migration({ target }).service.run('VALIDATE', CONTEXT); assert(report.issues.some((item) => item.code === 'TARGET_CONFLICT')); });
test('installation identity mismatch blocks cutover', async () => { const target = new FakeTarget(); await migration({ target }).service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-1' }); const report = await migration({ target, readiness: { state: 'SECURITY_ERROR', checks: {} } }).service.run('CUTOVER_READINESS', CONTEXT); assert.equal(report.state, 'NOT_READY'); });
test('schema checksum failure blocks cutover', async () => { const target = new FakeTarget(); await migration({ target }).service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-1' }); const report = await migration({ target, readiness: { state: 'CONFIGURATION_ERROR', remediationCode: 'MIGRATION_CHECKSUM_DRIFT', checks: {} } }).service.run('CUTOVER_READINESS', CONTEXT); assert.equal(report.state, 'NOT_READY'); });
test('application role boundary blocks cutover', async () => { const target = new FakeTarget(); await migration({ target }).service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-1' }); const report = await migration({ target, readiness: { state: 'READY', checks: { applicationRole: { state: 'FAIL' }, migrationRole: { state: 'PASS' } } } }).service.run('CUTOVER_READINESS', CONTEXT); assert.equal(report.applicationRole, 'ACTION_REQUIRED'); });
test('migration role boundary blocks cutover', async () => { const target = new FakeTarget(); await migration({ target }).service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-1' }); const report = await migration({ target, readiness: { state: 'READY', checks: { applicationRole: { state: 'PASS' }, migrationRole: { state: 'FAIL' } } } }).service.run('CUTOVER_READINESS', CONTEXT); assert.equal(report.migrationRole, 'ACTION_REQUIRED'); });
test('verification reconciles exact source and target counts', async () => { const { service } = migration(); await service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-1' }); const report = await service.run('VERIFY', CONTEXT); assert.equal(report.verification.state, 'PASS'); assert.deepEqual(report.verification.targetCounts, { customers: 1, contacts: 1 }); });
test('verification detects missing target row', async () => { const target = new FakeTarget({ missing: true }); const report = await migration({ target }).service.run('VERIFY', CONTEXT); assert.equal(report.verification.state, 'FAIL'); });
test('verification detects unexpected target row', async () => { const target = new FakeTarget({ unexpected: true }); const report = await migration({ target }).service.run('VERIFY', CONTEXT); assert.equal(report.verification.unexpectedTargetRows, true); });
test('cutover readiness passes only after verified migration', async () => { const target = new FakeTarget(); const { service } = migration({ target, cutoverControl: {} }); await service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-1' }); const report = await service.run('CUTOVER_READINESS', CONTEXT); assert.equal(report.state, 'READY_FOR_CUSTOMER_CONTACT_CUTOVER'); });
test('unresolved references block cutover readiness', async () => { const rows = data({ contacts: [], rfqs: [{ sourceId: 'RFQ-1', TenantID: TENANT, CustomerID: 'CUST-1', ContactID: 'ORPHAN' }], salesActivities: [] }); const report = await migration({ rows }).service.run('CUTOVER_READINESS', CONTEXT); assert.equal(report.state, 'NOT_READY'); });
test('browser-forged TenantID is rejected', async () => await assert.rejects(() => migration().service.run('PLAN', { authoritative: false, tenantId: 'TENANT-X', userId: 'BROWSER' }), /Trusted tenant/i));
test('repeated source cursor is rejected as stale/unsafe', async () => { const source = new LegacyCustomerContactSourceReader({ batchSize: 1, readChunk: async () => ({ customers: [CUSTOMER], contacts: [], rfqs: [], salesActivities: [], nextCursor: 'same' }) }); await assert.rejects(() => source.read(CONTEXT), /cursor/i); });
test('migration errors and reports never expose credentials', async () => { const target = new FakeTarget({ fail: true }); const report = await migration({ target }).service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-1' }); assert.doesNotMatch(JSON.stringify(report), /password=|not-returned/i); });

test('cutover activates both domains atomically without dual-write', async () => { let state = { version: 1 }; const store = { get: async () => state, compareAndSet: async (_tenant, version, next) => { assert.equal(version, 1); state = { ...next, version: 2 }; return state; } }; const control = new CustomerContactCutoverControl({ store, authorizer: async () => true, readinessProvider: async () => ({ state: 'READY_FOR_CUSTOMER_CONTACT_CUTOVER' }), clock: () => new Date(NOW) }); const result = await control.activate(CONTEXT, 1); assert.equal(result.customer, 'POSTGRESQL'); assert.equal(result.contact, 'POSTGRESQL'); assert.equal(result.legacySheets, 'READ_ONLY_MIGRATION_EVIDENCE'); });
test('cutover never automatically falls back to Sheets writes', () => { const control = new CustomerContactCutoverControl({ store: { get() {}, compareAndSet() {} }, authorizer: async () => true, readinessProvider: async () => ({ state: 'READY_FOR_CUSTOMER_CONTACT_CUTOVER' }) }); assert.throws(() => control.failClosedAfterCutover(), /fallback is disabled/i); });
test('cutover recomputes readiness and rejects a forged caller value', async () => { const control = new CustomerContactCutoverControl({ store: { get: async () => ({}), compareAndSet() {} }, authorizer: async () => true, readinessProvider: async () => ({ state: 'NOT_READY' }) }); await assert.rejects(() => control.activate(CONTEXT, 1, { state: 'READY_FOR_CUSTOMER_CONTACT_CUTOVER' }), /not authorized/i); });
test('cutover requires explicit readiness and authority', async () => { const control = new CustomerContactCutoverControl({ store: { get: async () => ({}), compareAndSet() {} }, authorizer: async () => false, readinessProvider: async () => ({ state: 'NOT_READY' }) }); await assert.rejects(() => control.activate(CONTEXT, 1), /not authorized/i); });
test('pre-cutover routing remains Sheets authoritative', async () => { const control = new CustomerContactCutoverControl({ store: { get: async () => ({ customer: 'SHEETS', contact: 'SHEETS' }), compareAndSet() {} }, authorizer: async () => true, readinessProvider: async () => ({ state: 'READY_FOR_CUSTOMER_CONTACT_CUTOVER' }) }); assert.equal(await control.route(CONTEXT, 'CUSTOMER'), 'SHEETS'); });
test('post-cutover routing is PostgreSQL and fail closed', async () => { const control = new CustomerContactCutoverControl({ store: { get: async () => ({ customer: 'POSTGRESQL', contact: 'POSTGRESQL' }), compareAndSet() {} }, authorizer: async () => true, readinessProvider: async () => ({ state: 'READY_FOR_CUSTOMER_CONTACT_CUTOVER' }) }); assert.equal(await control.route(CONTEXT, 'CONTACT'), 'POSTGRESQL'); });
test('missing or unavailable routing state fails closed without credential leakage', async () => { const control = new CustomerContactCutoverControl({ store: { get: async () => { throw new Error('password=hidden'); }, compareAndSet() {} }, authorizer: async () => true, readinessProvider: async () => ({ state: 'READY_FOR_CUSTOMER_CONTACT_CUTOVER' }) }); await assert.rejects(() => control.route(CONTEXT, 'CONTACT'), (error) => /unavailable/i.test(error.message) && !/password|hidden/i.test(error.message)); });
test('bounded source reader paginates with authoritative tenant and configured limit', async () => { const calls = []; await reader(data({ customers: [CUSTOMER, { ...CUSTOMER, sourceId: 'ROW-C2', CustomerID: 'CUST-2' }, { ...CUSTOMER, sourceId: 'ROW-C3', CustomerID: 'CUST-3' }] }), 2, calls).read(CONTEXT); assert.equal(calls.length, 2); assert(calls.every((call) => call.tenantId === TENANT && call.limit === 2)); });
test('source fingerprint is deterministic and raw evidence remains immutable', async () => { const first = await reader().read(CONTEXT); const second = await reader().read(CONTEXT); assert.equal(first.sourceFingerprint, second.sourceFingerprint); assert.equal(Object.isFrozen(first.customers[0]), true); });
test('migration audit records running and completed results', async () => { const target = new FakeTarget(); await migration({ target }).service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-AUDIT', schemaMigrationLevel: '0005' }); assert.deepEqual(target.audit.map((row) => row.outcome), ['RUNNING', 'COMPLETED']); assert.equal(target.audit[0].softwareVersion, '982a79e'); });
test('failed migration audit is distinguishable from completed run', async () => { const target = new FakeTarget({ fail: true }); await migration({ target }).service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'RUN-FAIL' }); assert.deepEqual(target.audit.map((row) => row.outcome), ['RUNNING', 'FAILED']); });
test('invalid migration mode is rejected', async () => await assert.rejects(() => migration().service.run('RUN_EVERYTHING', CONTEXT), /mode/i));
test('PostgreSQL adapter uses fixed parameterized bounded inspection SQL', async () => { const calls = []; const runtime = { query: async (sql, values, operation) => { calls.push({ sql, values, operation }); return { rows: [] }; }, withTransaction() {} }; const target = new PostgresCustomerContactMigrationTarget({ runtime, batchSize: 1 }); await target.inspect({ customers: [{ customerId: 'CUST-1' }], contacts: [{ contactId: 'CONTACT-00000000-0000-5000-8000-000000000000' }] }, CONTEXT); assert.equal(calls.length, 2); assert(calls.every((call) => call.sql.includes('$1') && call.sql.includes('$2::text[]'))); assert.deepEqual(calls[0].values, [TENANT, ['CUST-1']]); });
test('PostgreSQL inspection retains normalized fields for exact idempotency comparison', async () => { const databaseRow = { tenant_id: TENANT, customer_id: 'CUST-1', company_name: 'Acme Manufacturing', normalized_name: 'acme manufacturing', primary_contact_display: 'Pat Legacy', email: 'sales@acme.test', phone: '555-0100', status: 'ACTIVE', version: 1, created_at: '2025-01-01T00:00:00Z', updated_at: '2026-01-01T00:00:00Z', archived_at: null }; const runtime = { query: async (_sql, _values, operation) => ({ rows: operation === 'MIGRATION_INSPECT_CUSTOMERS' ? [databaseRow] : [] }), withTransaction() {} }; const target = new PostgresCustomerContactMigrationTarget({ runtime }); const state = await target.inspect({ customers: [{ customerId: 'CUST-1' }], contacts: [] }, CONTEXT); assert.equal(state.customers[0].normalizedName, 'acme manufacturing'); });
test('PostgreSQL adapter returns the planned action summary after transactional migration', async () => { const tx = { query: async (_sql, _values, operation) => ({ rows: operation === 'MIGRATION_INSTALLATION_IDENTITY' ? [{ tenant_id: TENANT }] : [] }) }; const runtime = { query() {}, withTransaction: async (_operation, work) => work(tx) }; const target = new PostgresCustomerContactMigrationTarget({ runtime }); const actions = { customers: { inserts: 0 }, contacts: { inserts: 0 } }; const result = await target.migrate({ customers: [], contacts: [], references: [], actions }, { runId: 'RUN-1' }, CONTEXT); assert.equal(result.actions, actions); });
test('PostgreSQL adapter writes BLANK references as NULL in a fixed statement', async () => { const calls = []; const tx = { query: async (_sql, values, operation) => { calls.push({ values, operation }); return { rows: operation === 'MIGRATION_INSTALLATION_IDENTITY' ? [{ tenant_id: TENANT }] : [] }; } }; const runtime = { query() {}, withTransaction: async (_operation, work) => work(tx) }; const target = new PostgresCustomerContactMigrationTarget({ runtime }); await target.migrate({ customers: [], contacts: [], references: [{ entity: 'RFQ', sourceId: 'RFQ-1', customerId: 'CUST-1', contactId: null, classification: 'BLANK' }], actions: {} }, { runId: 'RUN-1' }, CONTEXT); const call = calls.find((row) => row.operation === 'MIGRATION_RECONCILE_RFQ_REFERENCES'); assert.equal(JSON.parse(call.values[1])[0].contactId, null); });
test('PostgreSQL adapter rejects arbitrary table selection by exposing no table input', () => { const runtime = { query() {}, withTransaction() {} }; const target = new PostgresCustomerContactMigrationTarget({ runtime }); assert.equal(Object.hasOwn(target, 'table'), false); });
test('actual repository contact-source absence yields unresolved evidence rather than synthesis', async () => { const report = await run('PLAN', {}, { rows: data({ contacts: [], rfqs: [{ sourceId: 'RFQ-1', TenantID: TENANT, CustomerID: 'CUST-1', ContactID: 'LEGACY-PAT' }], salesActivities: [] }) }); assert.equal(report.contactCounts.valid, 0); assert.equal(report.unresolvedReferences[0].resolutionStatus, 'UNRESOLVED'); });
test('actual RFQID and SalesActivityID headings remain the reference source identity', async () => { const rows = data({ contacts: [], rfqs: [{ RFQID: 'RFQ-LEGACY', TenantID: TENANT, CustomerID: 'CUST-1', ContactID: 'ORPHAN-RFQ' }], salesActivities: [{ SalesActivityID: 'SACT-LEGACY', TenantID: TENANT, CustomerID: 'CUST-1', ContactID: 'ORPHAN-SALES' }] }); const report = await run('PLAN', {}, { rows }); assert.deepEqual(report.unresolvedReferences.map((row) => row.sourceRecordIdentity), ['RFQ-LEGACY', 'SACT-LEGACY']); });
