import assert from 'node:assert/strict';
import test from 'node:test';
import { INSTALLATION_STEPS, TenantInstallationGuide, renderInstallationGuide } from '../src/installation-guide.js';

const PASS_CHECKS = Object.freeze({ configuration: { state: 'PASS', code: 'SERVER_CONTROLLED' }, connectivity: { state: 'PASS', code: 'DATABASE_REACHABLE' }, version: { state: 'PASS', code: 'POSTGRESQL_17_SUPPORTED' }, tls: { state: 'PASS', code: 'TLS_CONFIGURATION_VALID' }, installation: { state: 'PASS', code: 'INSTALLATION_TENANT_MATCHED' }, applicationRole: { state: 'PASS', code: 'APPLICATION_ROLE_LEAST_PRIVILEGE' }, migrationRole: { state: 'PASS', code: 'MIGRATION_ROLE_SEPARATE_AND_READY' }, migration: { state: 'PASS', code: 'MIGRATIONS_CURRENT' }, foundationSchema: { state: 'PASS', code: 'FOUNDATION_SCHEMA_PRESENT' }, domainSchema: { state: 'PASS', code: 'DOMAIN_SCHEMA_PRESENT' }, sessionSchema: { state: 'PASS', code: 'SESSION_SCHEMA_PRESENT' }, transactionSmoke: { state: 'PASS', code: 'TRANSACTION_ROLLBACK_PROVEN' }, tenantScope: { state: 'PASS', code: 'TENANT_SCOPE_MATCHED' } });
function readiness(state = 'READY', remediationCode = state, checks = {}) { return { state, remediationCode, checks: { ...PASS_CHECKS, ...checks } }; }
function readyGuide(options = {}) { return new TenantInstallationGuide({ readinessValidator: { inspect: async () => readiness() }, bootstrap: { state: 'READY', tenantScoped: true, platformAuthority: false }, deploymentTarget: 'AWS_RDS_POSTGRESQL', clock: () => new Date('2026-01-01T00:00:00.000Z'), ...options }); }
function deferred() { let resolve; return { promise: new Promise((done) => { resolve = done; }), resolve }; }

test('requires the D-A readiness validator', () => assert.throws(() => new TenantInstallationGuide(), /readiness validator/i));
test('defines the complete ordered eighteen-step package', () => assert.deepEqual(INSTALLATION_STEPS.map(({ id }) => id), ['WELCOME', 'TARGET', 'VERSION', 'CONNECTION', 'TLS', 'SECRETS', 'APPLICATION_ROLE', 'MIGRATION_ROLE', 'CONNECTIVITY', 'DATABASE', 'IDENTITY', 'MIGRATION_PREFLIGHT', 'MIGRATION_EXECUTION', 'POST_MIGRATION', 'RUNTIME', 'FIRST_ADMIN', 'BACKUP', 'SUMMARY']));
test('initializes deterministically without a blank state', () => { const report = readyGuide().snapshot(); assert.equal(report.state, 'NOT_STARTED'); assert.equal(report.overall, 'NOT_READY'); assert.ok(report.message); });
test('requires separate responsibility and backup acknowledgements', () => { const guide = readyGuide(); assert.equal(guide.acknowledge({ tenantResponsibilities: true }).readinessSummary.BACKUP_RESPONSIBILITY, 'ACTION_REQUIRED'); assert.equal(guide.acknowledge({ tenantResponsibilities: true, backupRestore: true }).readinessSummary.BACKUP_RESPONSIBILITY, 'PASS'); });

for (const [target, label, secrets] of [
  ['AWS_RDS_POSTGRESQL', 'Amazon RDS for PostgreSQL', 'AWS Secrets Manager'],
  ['AZURE_POSTGRESQL_FLEXIBLE_SERVER', 'Azure Database for PostgreSQL Flexible Server', 'Azure Key Vault'],
  ['GENERIC_POSTGRESQL', 'Compatible PostgreSQL (advanced)', 'Approved server-side secret storage']
]) test(`supports ${target} as guidance without provisioning`, () => { const report = readyGuide({ deploymentTarget: target }).snapshot(); assert.equal(report.deploymentTargetLabel, label); assert.equal(report.secretStorageGuidance, secrets); assert.match(report.deploymentGuidance, /tenant|same PostgreSQL/i); });

test('rejects an unsupported deployment target', () => assert.equal(readyGuide({ deploymentTarget: 'FORGED_PROVIDER' }).snapshot().deploymentTarget, ''));
test('happy path is ready only for the next step and never claims production go-live', async () => { const guide = readyGuide(); guide.acknowledge({ tenantResponsibilities: true, backupRestore: true }); const report = await guide.validate(); assert.equal(report.overall, 'READY_FOR_NEXT_STEP'); assert.equal(report.readyForNextStep, true); assert.equal(report.goLiveEligible, false); assert.equal(report.productionGoLive, 'PENDING'); });
test('invokes D-A without browser-provided arguments', async () => { let args; const guide = readyGuide({ readinessValidator: { inspect: async (...values) => { args = values; return readiness(); } } }); await guide.validate({ tenantId: 'FORGED', readiness: 'READY' }); assert.deepEqual(args, []); });

for (const [name, state, code, category] of [
  ['database unavailable', 'DATABASE_UNAVAILABLE', 'DATABASE_UNAVAILABLE', 'DATABASE_UNREACHABLE'],
  ['TLS failure', 'SECURITY_ERROR', 'TLS_CONFIGURATION_INVALID', 'TLS_CONFIGURATION'],
  ['unsupported version', 'INCOMPATIBLE', 'POSTGRESQL_VERSION_UNSUPPORTED', 'VERSION_UNSUPPORTED'],
  ['invalid application role', 'SECURITY_ERROR', 'APPLICATION_ROLE_OVERPRIVILEGED', 'APPLICATION_ROLE_INVALID'],
  ['invalid migration role', 'SECURITY_ERROR', 'MIGRATION_ROLE_INSUFFICIENT_OR_OVERPRIVILEGED', 'MIGRATION_ROLE_INVALID'],
  ['migration required', 'MIGRATION_REQUIRED', 'MIGRATION_REQUIRED', 'MIGRATION_REQUIRED'],
  ['checksum mismatch', 'CONFIGURATION_ERROR', 'MIGRATION_CHECKSUM_DRIFT', 'CHECKSUM_FAILURE'],
  ['incompatible schema', 'INCOMPATIBLE', 'SCHEMA_AHEAD_INCOMPATIBLE', 'SCHEMA_INCOMPATIBLE'],
  ['installation identity conflict', 'SECURITY_ERROR', 'INSTALLATION_TENANT_MISMATCH', 'INSTALLATION_IDENTITY_CONFLICT']
]) test(`maps ${name} to safe remediation`, async () => { const report = await readyGuide({ readinessValidator: { inspect: async () => readiness(state, code) } }).validate(); assert.equal(report.remediationCategory, category); assert.ok(report.remediation.owner); assert.ok(report.remediation.action); });

test('converts an unexpected D-A exception into a redacted unavailable result', async () => { const report = await readyGuide({ readinessValidator: { inspect: async () => { throw new Error('password=secret host=db.internal'); } } }).validate(); assert.equal(report.state, 'UNAVAILABLE'); assert.doesNotMatch(JSON.stringify(report), /password=secret|db\.internal/i); });
test('classifies an empty compatible database', async () => assert.equal((await readyGuide({ readinessValidator: { inspect: async () => readiness('INITIALIZATION_REQUIRED', 'ATLAS_SCHEMA_UNINITIALIZED') } }).validate()).databaseClassification, 'EMPTY_COMPATIBLE'));
test('classifies a foundation-only outdated database', async () => assert.equal((await readyGuide({ readinessValidator: { inspect: async () => readiness('MIGRATION_REQUIRED', 'MIGRATION_REQUIRED', { domainSchema: { state: 'FAIL', code: 'DOMAIN_SCHEMA_MISSING' } }) } }).validate()).databaseClassification, 'ATLAS_FOUNDATION_ONLY'));
test('classifies a current Atlas domain schema', async () => assert.equal((await readyGuide().validate()).databaseClassification, 'ATLAS_DOMAIN_SCHEMA'));
test('classifies checksum drift without exposing SQL', async () => { const report = await readyGuide({ readinessValidator: { inspect: async () => readiness('CONFIGURATION_ERROR', 'MIGRATION_CHECKSUM_DRIFT') } }).validate(); assert.equal(report.databaseClassification, 'CHECKSUM_MISMATCH'); assert.doesNotMatch(JSON.stringify(report), /CREATE TABLE|ALTER TABLE/i); });
test('late validation responses cannot overwrite newer configuration attempts', async () => { const first = deferred(), second = deferred(); let count = 0; const guide = readyGuide({ readinessValidator: { inspect: async () => (++count === 1 ? first.promise : second.promise) } }); const a = guide.validate(); const b = guide.validate(); second.resolve(readiness('DATABASE_UNAVAILABLE', 'DATABASE_UNAVAILABLE')); assert.equal((await b).state, 'UNAVAILABLE'); first.resolve(readiness()); assert.equal((await a).ignored, true); assert.equal(guide.snapshot().state, 'UNAVAILABLE'); });
test('cancelling validation rejects the stale result and returns a stable state', async () => { const pending = deferred(); const guide = readyGuide({ readinessValidator: { inspect: async () => pending.promise } }); const attempt = guide.validate(); assert.equal(guide.cancelValidation().state, 'NOT_STARTED'); pending.resolve(readiness()); assert.equal((await attempt).ignored, true); });
test('bounded session and runtime smoke can pass after D-A readiness', async () => { const report = await readyGuide({ runtimeSmoke: async () => ({ sessionStore: 'PASS', runtime: 'PASS' }) }).validate(); assert.equal(report.readinessSummary.SESSION_STORE, 'PASS'); assert.equal(report.readinessSummary.RUNTIME, 'PASS'); });
test('runtime smoke failure blocks readiness without replacing D-A', async () => { const report = await readyGuide({ runtimeSmoke: async () => ({ sessionStore: 'FAIL', runtime: 'FAIL' }) }).validate(); assert.equal(report.remediationCategory, 'RUNTIME_NOT_READY'); assert.equal(report.readiness.state, 'READY'); });
test('first-admin remains pending when no bootstrap is prepared', async () => { const report = await readyGuide({ bootstrap: {} }).validate(); assert.equal(report.readinessSummary.FIRST_ADMIN, 'PENDING'); assert.equal(report.readyForNextStep, false); });
test('first-admin cannot grant PLATFORM authority', async () => { const report = await readyGuide({ bootstrap: { state: 'READY', tenantScoped: true, platformAuthority: true } }).validate(); assert.equal(report.firstAdmin, 'PENDING'); });
test('migration preflight shows level, checksum, backup, and explicit authority', async () => { const guide = readyGuide({ readinessValidator: { inspect: async () => readiness('MIGRATION_REQUIRED', 'MIGRATION_REQUIRED', { migration: { state: 'FAIL', code: 'MIGRATION_REQUIRED' } }) } }); await guide.validate(); const preflight = guide.migrationPreflight(); assert.equal(preflight.currentLevel, 'MIGRATION_REQUIRED'); assert.equal(preflight.targetLevel, 'CURRENT_ATLAS_RELEASE'); assert.equal(preflight.explicitAuthorizationRequired, true); assert.equal(preflight.backupAcknowledged, false); });
test('migration execution requires an explicit confirmation', async () => { const guide = readyGuide({ readinessValidator: { inspect: async () => readiness('MIGRATION_REQUIRED', 'MIGRATION_REQUIRED') } }); guide.acknowledge({ backupRestore: true }); await guide.validate(); assert.equal((await guide.executeMigrations()).state, 'ACTION_REQUIRED'); });
test('migration execution requires backup acknowledgement', async () => { const guide = readyGuide({ readinessValidator: { inspect: async () => readiness('MIGRATION_REQUIRED', 'MIGRATION_REQUIRED') } }); await guide.validate(); assert.equal((await guide.executeMigrations({ confirmed: true })).state, 'ACTION_REQUIRED'); });
test('migration execution remains pending when no trusted executor is installed', async () => { const guide = readyGuide({ readinessValidator: { inspect: async () => readiness('MIGRATION_REQUIRED', 'MIGRATION_REQUIRED') } }); guide.acknowledge({ backupRestore: true }); await guide.validate(); assert.equal((await guide.executeMigrations({ confirmed: true })).state, 'PENDING'); });
test('migration execution rejects missing server authorization', async () => { let applied = false; const guide = readyGuide({ readinessValidator: { inspect: async () => readiness('MIGRATION_REQUIRED', 'MIGRATION_REQUIRED') }, migrationExecutor: { apply: async () => { applied = true; } }, migrationAuthorizer: async () => false }); guide.acknowledge({ backupRestore: true }); await guide.validate(); assert.equal((await guide.executeMigrations({ confirmed: true })).state, 'NOT_AUTHORIZED'); assert.equal(applied, false); });
test('migration authorization errors fail closed and duplicate execution is rejected', async () => { const gate = deferred(); const guide = readyGuide({ readinessValidator: { inspect: async () => readiness('MIGRATION_REQUIRED', 'MIGRATION_REQUIRED') }, migrationExecutor: { apply: async () => gate.promise }, migrationAuthorizer: async () => true }); guide.acknowledge({ backupRestore: true }); await guide.validate(); const first = guide.executeMigrations({ confirmed: true }); assert.equal((await guide.executeMigrations({ confirmed: true })).code, 'MIGRATION_ALREADY_IN_PROGRESS'); gate.resolve(); await first; const denied = readyGuide({ readinessValidator: { inspect: async () => readiness('MIGRATION_REQUIRED', 'MIGRATION_REQUIRED') }, migrationExecutor: { apply: async () => {} }, migrationAuthorizer: async () => { throw new Error('secret'); } }); denied.acknowledge({ backupRestore: true }); await denied.validate(); assert.equal((await denied.executeMigrations({ confirmed: true })).state, 'NOT_AUTHORIZED'); });
test('authorized migration uses the accepted runner and revalidates with D-A', async () => { let applied = 0, inspections = 0; const guide = readyGuide({ readinessValidator: { inspect: async () => (++inspections === 1 ? readiness('MIGRATION_REQUIRED', 'MIGRATION_REQUIRED') : readiness()) }, migrationExecutor: { apply: async () => { applied += 1; } }, migrationAuthorizer: async ({ tenantAdmin }) => tenantAdmin === true }); guide.acknowledge({ tenantResponsibilities: true, backupRestore: true }); await guide.validate(); const result = await guide.executeMigrations({ confirmed: true, authorizationContext: { tenantAdmin: true, tenantId: 'IGNORED' } }); assert.equal(result.state, 'PASS'); assert.equal(applied, 1); assert.equal(inspections, 2); });
test('migration failure is redacted and requires reconciliation before retry', async () => { const guide = readyGuide({ readinessValidator: { inspect: async () => readiness('MIGRATION_REQUIRED', 'MIGRATION_REQUIRED') }, migrationExecutor: { apply: async () => { throw new Error('password=secret'); } }, migrationAuthorizer: async () => true }); guide.acknowledge({ backupRestore: true }); await guide.validate(); const result = await guide.executeMigrations({ confirmed: true }); assert.deepEqual(result, { state: 'MIGRATION_FAILED', retrySafe: false }); assert.doesNotMatch(JSON.stringify(guide.snapshot()), /password=secret/i); });
test('safe readiness projection drops unexpected credential-bearing fields', async () => { const report = await readyGuide({ readinessValidator: { inspect: async () => ({ ...readiness(), password: 'secret-value', connectionString: ['postgres', '://user:pass@db'].join(''), checks: { ...PASS_CHECKS, injected: { state: 'PASS', code: 'password=secret' } } }) } }).validate(); assert.doesNotMatch(JSON.stringify(report), /secret-value|postgres:\/\/|injected/i); });
test('browser-forged tenant, provider, and readiness values cannot become authority', async () => { const guide = readyGuide(); const report = await guide.validate({ tenantId: 'PLATFORM_ROOT', provider: 'SHEETS', readiness: { state: 'READY' } }); assert.equal(report.deploymentTarget, 'AWS_RDS_POSTGRESQL'); assert.equal(report.readiness.state, 'READY'); assert.doesNotMatch(JSON.stringify(report), /PLATFORM_ROOT|SHEETS/); });
test('final summary includes every required readiness dimension and pending activation work', async () => { const report = await readyGuide().validate(); assert.deepEqual(Object.keys(report.readinessSummary), ['DATABASE', 'TLS', 'APPLICATION_ROLE', 'MIGRATION_ROLE', 'SCHEMA', 'CHECKSUMS', 'INSTALLATION_IDENTITY', 'SESSION_STORE', 'RUNTIME', 'FIRST_ADMIN', 'BACKUP_RESPONSIBILITY', 'LIVE_OIDC', 'BUSINESS_DATA_MIGRATION']); assert.equal(report.readinessSummary.LIVE_OIDC, 'PENDING'); assert.equal(report.readinessSummary.BUSINESS_DATA_MIGRATION, 'PENDING'); });
test('render contract is semantic, keyboard-visible, responsive to busy state, and not color-only', () => { const html = renderInstallationGuide(readyGuide().snapshot()); assert.match(html, /<main aria-busy="false">/); assert.match(html, /<nav aria-label="Installation progress">/); assert.match(html, /<h2 id="readiness-summary">/); assert.match(html, /aria-live="polite"/); assert.match(html, /focus-visible/); assert.match(html, /min-height:44px/); assert.match(html, /role="status"/); assert.match(html, /web application.*no desktop client/i); assert.doesNotMatch(html, /password|connection string|postgres:\/\//i); });
