import assert from 'node:assert/strict';import test from'node:test';import{newDb}from'pg-mem';import{CrmActivityService,PostgresCrmActivityRepository}from'../src/crm-activity.js';import{LeadIntakeService,LEAD_SOURCES,PostgresLeadRepository}from'../src/lead-intake.js';import{createPostgresRuntimeConfig,PostgresRuntime}from'../src/postgres-runtime.js';import{FOUNDATION_MIGRATIONS,PostgresMigrationRunner}from'../src/migrations.js';import{DOMAIN_MIGRATIONS}from'../src/domain-migrations.js';
async function fixture(){const db=newDb({autoCreateForeignKeyIndices:true,noAstCoverageCheck:true}),{Pool}=db.adapters.createPg(),secrets={getSecret:async()=> 'x'},base={environment:'test',host:'localhost',database:'atlas_leads',user:'atlas',passwordSecretRef:'x',tls:{required:false}},app=new PostgresRuntime(await createPostgresRuntimeConfig({...base,role:'APPLICATION'},{secretProvider:secrets}),{PoolCtor:Pool}),migration=new PostgresRuntime(await createPostgresRuntimeConfig({...base,role:'MIGRATION'},{secretProvider:secrets}),{PoolCtor:Pool});await new PostgresMigrationRunner({runtime:migration,migrations:FOUNDATION_MIGRATIONS,lock:{acquire:async()=>async()=>{}}}).apply();const crm=new CrmActivityService({repository:new PostgresCrmActivityRepository({runtime:app}),clock:()=>new Date('2026-09-01T12:00:00Z')});return{app,migration,service:new LeadIntakeService({repository:new PostgresLeadRepository({runtime:app}),crmActivity:crm,clock:()=>new Date('2026-09-01T12:00:00Z')}),crm};}
async function seed(f){await f.app.query("INSERT INTO atlas_installation(installation_id,tenant_id) VALUES('I-A','TENANT-A'),('I-B','TENANT-B')");await f.app.query("INSERT INTO atlas_users(user_id,display_name) VALUES('USER-A','Alex'),('USER-B','Blair')");await f.app.query("INSERT INTO atlas_customers(tenant_id,customer_id,company_name,normalized_name) VALUES('TENANT-A','CUSTOMER-A','A','a'),('TENANT-A','CUSTOMER-B','B','b')");await f.app.query("INSERT INTO atlas_contacts(tenant_id,contact_id,customer_id,display_name,normalized_display_name) VALUES('TENANT-A','CONTACT-11111111-1111-4111-8111-111111111111','CUSTOMER-A','Alex C','alex c'),('TENANT-A','CONTACT-22222222-2222-4222-8222-222222222222','CUSTOMER-B','Blair C','blair c')");}
const context={authoritative:true,tenantId:'TENANT-A',userId:'USER-A',correlationId:'CORR-139',capabilities:['LEAD_INTAKE_WRITE','LEAD_WORKFLOW_WRITE','LEAD_CONVERT','LEAD_READ','CRM_ACTIVITY_WRITE','CRM_ACTIVITY_READ','CRM_FOLLOW_UP_WRITE']};
const input=(source,key)=>({source,idempotencyKey:key,sourceReference:`REF-${key}`,companyName:`Company ${key}`,contactName:'Prospect',email:`${key.toLowerCase()}@example.test`,summary:'Requested a callback'});

test('ordered migration adds unified Lead identity and reuses canonical activity/follow-up tables',async()=>{const f=await fixture(),m=DOMAIN_MIGRATIONS.find(x=>x.id==='0010_unified_lead_intake');assert.ok(m);for(const x of['atlas_leads','atlas_lead_events','ingestion_key_hash','atlas_sales_activities ADD COLUMN lead_id','atlas_follow_ups ADD COLUMN lead_id','atlas_leads_queue_idx'])assert.ok(m.sql.includes(x),x);const tables=(await f.app.query("SELECT table_name FROM information_schema.tables WHERE table_schema='public'")).rows.map(x=>x.table_name);assert.ok(tables.includes('atlas_leads')&&tables.includes('atlas_lead_events'));await f.app.close();await f.migration.close();});

test('all intake sources are unified, idempotent and conflicting replay fails closed',async()=>{const f=await fixture();await seed(f);for(const source of LEAD_SOURCES){const first=await f.service.ingest(context,input(source,source));assert.equal(first.created,true);const replay=await f.service.ingest(context,input(source,source));assert.equal(replay.created,false);assert.equal(replay.lead.lead_id,first.lead.lead_id);}await assert.rejects(()=>f.service.ingest(context,{...input('MANUAL','MANUAL'),summary:'Changed payload'}));assert.equal((await f.app.query('SELECT count(*)::int count FROM atlas_leads')).rows[0].count,LEAD_SOURCES.length);await f.app.close();await f.migration.close();});

test('concurrent idempotent insert loss re-reads the canonical Lead instead of duplicating it',async()=>{const calls=[],row={lead_id:'LEAD-existing',ingestion_payload_hash:'payload'};const runtime={query:async()=>({}),withTransaction:async(_operation,work)=>work({query:async(sql)=>{calls.push(sql);return calls.length===1?{rowCount:0,rows:[]}:calls.length===2?{rowCount:0,rows:[]}:{rowCount:1,rows:[row]};}})};const repo=new PostgresLeadRepository({runtime});const result=await repo.ingest({tenantId:'TENANT-A',userId:'USER-A',correlationId:'C'},{leadId:'LEAD-new',eventId:'LEAD-EVT-new',source:'MANUAL',ingestionKeyHash:'key',ingestionPayloadHash:'payload',sourceReference:null,companyName:null,contactName:null,email:null,phone:null,summary:'S',ownerUserId:'USER-A',createdByUserId:'USER-A',createdAt:'2026-09-01T00:00:00Z'});assert.equal(result.created,false);assert.equal(result.lead.lead_id,'LEAD-existing');assert.match(calls[1],/ON CONFLICT \(tenant_id,ingestion_key_hash\) DO NOTHING/);});

test('lead workflow and bounded callback-first queue are deterministic and audited',async()=>{const f=await fixture();await seed(f);const a=(await f.service.ingest(context,input('PHONE','A'))).lead,b=(await f.service.ingest(context,input('WEBSITE','B'))).lead;const callback=await f.service.transition(context,{leadId:b.lead_id,expectedVersion:1,status:'CALLBACK_REQUIRED'});assert.equal(callback.status,'CALLBACK_REQUIRED');const queue=await f.service.queue(context,{limit:10});assert.equal(queue[0].lead_id,b.lead_id);const qualified=await f.service.transition(context,{leadId:a.lead_id,expectedVersion:1,status:'QUALIFIED'});assert.equal(qualified.version,2);await assert.rejects(()=>f.service.transition(context,{leadId:a.lead_id,expectedVersion:1,status:'WON'}));assert.equal((await f.app.query('SELECT count(*)::int count FROM atlas_lead_events')).rows[0].count,4);await assert.rejects(()=>f.service.queue({...context,capabilities:[]},{}));await f.app.close();await f.migration.close();});

test('lead activity and callback reuse MOS-134 timeline, Follow-Up and audit primitives',async()=>{const f=await fixture();await seed(f);const lead=(await f.service.ingest(context,input('DEALER_REFERRAL','D'))).lead;const recorded=await f.service.recordActivity(context,{leadId:lead.lead_id,activityType:'CALL',direction:'OUTBOUND',summary:'Called referral',nextAction:'Call owner tomorrow',nextActionDueAt:'2026-09-02T16:00:00Z'});assert.equal(recorded.activity.lead_id,lead.lead_id);assert.equal(recorded.followUp.lead_id,lead.lead_id);const timeline=await f.crm.timeline(context,{leadId:lead.lead_id});assert.equal(timeline.items.length,1);const due=await f.crm.dueQueue(context,{through:'2026-09-03T00:00:00Z'});assert.equal(due[0].lead_id,lead.lead_id);assert.equal((await f.app.query('SELECT count(*)::int count FROM atlas_crm_activity_events')).rows[0].count,2);await assert.rejects(()=>f.crm.createActivity(context,{leadId:lead.lead_id,contactId:'CONTACT-11111111-1111-4111-8111-111111111111',activityType:'NOTE',summary:'No synthetic contact'}));await f.app.close();await f.migration.close();});

test('conversion is explicit, same-Customer Contact safe and never synthesizes identity',async()=>{const f=await fixture();await seed(f);const first=(await f.service.ingest(context,input('MANUAL','C1'))).lead;await assert.rejects(()=>f.service.convert(context,{leadId:first.lead_id,expectedVersion:1,customerId:'CUSTOMER-A',contactId:'CONTACT-22222222-2222-4222-8222-222222222222'}));const converted=await f.service.convert(context,{leadId:first.lead_id,expectedVersion:1,customerId:'CUSTOMER-A',contactId:'CONTACT-11111111-1111-4111-8111-111111111111',contactName:'Forged'});assert.equal(converted.status,'WON');assert.equal(converted.customer_id,'CUSTOMER-A');assert.equal(converted.contact_id,'CONTACT-11111111-1111-4111-8111-111111111111');const second=(await f.service.ingest(context,input('SOCIAL','C2'))).lead;const noContact=await f.service.convert(context,{leadId:second.lead_id,expectedVersion:1,customerId:'CUSTOMER-A',contactName:'Do not create'});assert.equal(noContact.contact_id,null);assert.equal((await f.app.query('SELECT count(*)::int count FROM atlas_contacts')).rows[0].count,2);await assert.rejects(()=>f.service.get({...context,tenantId:'TENANT-B'},first.lead_id));await f.app.close();await f.migration.close();});
