import assert from 'node:assert/strict';
import test,{after,before}from'node:test';
import pg from'pg';
import{createPostgresRuntimeConfig,PostgresRuntime}from'../src/postgres-runtime.js';
import{FOUNDATION_MIGRATIONS,PostgresMigrationRunner}from'../src/migrations.js';

const ON=process.env.ATLAS_MOS140A_REAL_POSTGRES==='1',DB='atlas_preprod_vitality_mos133h',MU='atlas_mos133h_migration',AU='atlas_mos133h_application';
if(!ON)test('MOS-140A real PostgreSQL validation requires explicit disposable opt-in',{skip:true},()=>{});else{
  for(const name of['MOS133H_MIGRATION_PASSWORD','MOS133H_APPLICATION_PASSWORD'])if(!process.env[name])throw new Error('Protected role handoff unavailable.');
  const secrets={getSecret:async ref=>ref==='migration'?process.env.MOS133H_MIGRATION_PASSWORD:process.env.MOS133H_APPLICATION_PASSWORD},base={environment:'development',host:'localhost',port:5432,database:DB,tls:{required:false}};let migration,app,runner;
  before(async()=>{migration=new PostgresRuntime(await createPostgresRuntimeConfig({...base,user:MU,passwordSecretRef:'migration',role:'MIGRATION'},{secretProvider:secrets}));app=new PostgresRuntime(await createPostgresRuntimeConfig({...base,user:AU,passwordSecretRef:'application',role:'APPLICATION'},{secretProvider:secrets}));runner=new PostgresMigrationRunner({runtime:migration,migrations:FOUNDATION_MIGRATIONS});});
  after(async()=>{await app?.close();await migration?.close();});
  test('applies MOS-140A on PostgreSQL 17 with the non-superuser migration role',async()=>{const identity=(await migration.query("SELECT current_database() database,current_setting('server_version_num')::int version,(SELECT rolsuper FROM pg_roles WHERE rolname=current_user) super",[],'MOS140A_ID')).rows[0];assert.equal(identity.database,DB);assert.equal(identity.super,false);assert.ok(identity.version>=170000&&identity.version<180000);await runner.apply();assert.deepEqual(await runner.status(),{state:'CURRENT',ready:true});assert.equal((await migration.query("SELECT count(*)::int count FROM atlas_schema_migrations WHERE migration_id='0011_contextual_attachments'",[],'MOS140A_MIG')).rows[0].count,1);});
  test('metadata, audit and manual-entry tables cross the application role boundary without blob columns',async()=>{const tables=new Set((await app.query("SELECT table_name FROM information_schema.tables WHERE table_name IN ('atlas_contextual_attachments','atlas_contextual_attachment_events','atlas_tool_manual_entry_events')",[],'MOS140A_TABLES')).rows.map(x=>x.table_name));assert.equal(tables.size,3);const columns=new Set((await app.query("SELECT column_name FROM information_schema.columns WHERE table_name='atlas_contextual_attachments'",[],'MOS140A_COLUMNS')).rows.map(x=>x.column_name));for(const required of['parent_type','parent_id','storage_provider','storage_reference','checksum_sha256','upload_status','processing_status','idempotency_key_hash','version'])assert.ok(columns.has(required),required);for(const forbidden of['blob','body','binary','content_bytes'])assert.ok(!columns.has(forbidden),forbidden);const indexes=new Set((await migration.query("SELECT indexname FROM pg_indexes WHERE schemaname='public' AND indexname LIKE 'atlas_contextual_attachment%'",[],'MOS140A_INDEX')).rows.map(x=>x.indexname));for(const required of['atlas_contextual_attachments_parent_idx','atlas_contextual_attachments_status_idx','atlas_contextual_attachment_events_history_idx'])assert.ok(indexes.has(required),required);});
  test('real composite FK rejects cross-tenant attachment stitching and fixture rolls back',async()=>{const client=new pg.Client({host:'localhost',port:5432,database:DB,user:MU,password:process.env.MOS133H_MIGRATION_PASSWORD,ssl:false});await client.connect();try{await client.query('BEGIN');const tenant=(await client.query('SELECT tenant_id FROM atlas_installation ORDER BY tenant_id LIMIT 1')).rows[0].tenant_id;await client.query("INSERT INTO atlas_users(user_id,display_name) VALUES('USER-MOS140A','MOS140A') ON CONFLICT DO NOTHING");const type='TOOL-TYPE-140a0000-0000-4000-8000-000000000001',tool='TOOL-140a0000-0000-4000-8000-000000000002';await client.query("INSERT INTO atlas_tool_types(tenant_id,tool_type_id,description,tool_class,unit_system,created_by_user_id) VALUES($1,$2,'Fixture','END_MILL','INCH','USER-MOS140A')",[tenant,type]);await client.query("INSERT INTO atlas_tool_instances(tenant_id,tool_instance_id,tool_type_id,condition,created_by_user_id) VALUES($1,$2,$3,'NEW','USER-MOS140A')",[tenant,tool,type]);await assert.rejects(()=>client.query("INSERT INTO atlas_contextual_attachments(tenant_id,attachment_id,parent_type,parent_id,tool_instance_id,file_name,media_type,byte_size,storage_provider,storage_reference,idempotency_key_hash,uploaded_by_user_id) VALUES('TENANT-CROSS','ATTACH-140a0000-0000-4000-8000-000000000003','TOOL_INSTANCE',$1,$1,'x.jpg','image/jpeg',1,'TEST','opaque',repeat('a',64),'USER-MOS140A')",[tool]),error=>error.code==='23503');}finally{await client.query('ROLLBACK');await client.end();}});
}
