import assert from 'node:assert/strict';
import { randomBytes } from 'node:crypto';
import test, { after, before } from 'node:test';
import pg from 'pg';
import { CustomerContactCutoverControl, CustomerContactMigration, LegacyCustomerContactSourceReader, PostgresCustomerContactMigrationTarget } from '../src/customer-contact-migration.js';
import { TenantInstallationGuide } from '../src/installation-guide.js';
import { FOUNDATION_MIGRATIONS, PostgresMigrationRunner } from '../src/migrations.js';
import { PostgresInstallationReadinessValidator } from '../src/postgres-readiness.js';
import { createPostgresRuntimeConfig, PostgresRuntime } from '../src/postgres-runtime.js';
import { PostgresSessionStore } from '../src/postgres-session-store.js';
import { hash } from '../src/security.js';

const ENABLED = process.env.ATLAS_MOS133G_REAL_POSTGRES === '1';
const DATABASE = 'atlas_preprod_mos133g';
const DATABASE_MARKER = 'DISPOSABLE LOCAL MOS-133G PREPRODUCTION DATABASE';
const MIGRATION_USER = 'atlas_mos133g_migration';
const APPLICATION_USER = 'atlas_mos133g_application';
const ROLE_MARKER = 'DISPOSABLE LOCAL MOS-133G ROLE';
const TENANT = 'TENANT-MOS133G';
const INSTALLATION = 'INSTALL-MOS133G';
const CONTEXT = Object.freeze({ authoritative: true, tenantId: TENANT, userId: 'OPERATOR-MOS133G', capabilities: ['CUSTOMER_CONTACT_MIGRATE', 'CUSTOMER_CONTACT_CUTOVER'] });
const NOW = '2026-08-29T20:00:00.000Z';
const qid = (value) => { if (!/^[a-z][a-z0-9_]{0,62}$/.test(value)) throw new Error('Unsafe PostgreSQL identifier.'); return `"${value}"`; };
const qlit = (value) => `'${String(value).replaceAll("'", "''")}'`;
const evidence = {
  timingsMs: {},
  plans: {},
  differences: [
    'ADVISORY_LOCKS_ARE_SESSION_AFFINE',
    'PARAMETERIZED_MULTI_STATEMENT_QUERIES_ARE_REJECTED',
    'TIMESTAMPTZ_CLIENT_VALUES_REQUIRE_EXPLICIT_TIMEZONE_NORMALIZATION'
  ],
  defects: [{ classification: 'CODE_DEFECT', code: 'MIGRATION_ADVISORY_LOCK_SESSION_AFFINITY', fixed: true }]
};

if (!ENABLED) {
  test('MOS-133G real PostgreSQL rehearsal requires explicit opt-in', { skip: 'Set ATLAS_MOS133G_REAL_POSTGRES=1 with process-local PG* bootstrap credentials.' }, () => {});
} else {
  const required = ['PGHOST', 'PGPORT', 'PGDATABASE', 'PGUSER', 'PGPASSWORD'];
  for (const name of required) if (!process.env[name]) throw new Error(`MOS-133G requires process-local ${name}.`);

  let bootstrap;
  let admin;
  let applicationRuntime;
  let migrationRuntime;
  let applicationConfig;
  let migrationConfig;
  let migrations;
  let readiness;
  let guide;
  let sessionStore;
  let migrationTarget;
  let migrationPassword;
  let applicationPassword;
  let fSourceFingerprint;
  let fCanonicalIds;
  let fService;
  let fRowsWithReferences;
  let cutoverControl;

  const bootstrapConfig = (database = process.env.PGDATABASE) => ({ host: process.env.PGHOST, port: Number(process.env.PGPORT), database, user: process.env.PGUSER, password: process.env.PGPASSWORD, ssl: false, application_name: 'atlas-mos133g-bootstrap' });
  const roleConfig = (user, password) => ({ host: process.env.PGHOST, port: Number(process.env.PGPORT), database: DATABASE, user, password, ssl: false, application_name: 'atlas-mos133g-rehearsal' });
  const raw = async (user, password, work) => { const client = new pg.Client(roleConfig(user, password)); await client.connect(); try { return await work(client); } finally { await client.end(); } };
  const transaction = async (user, password, work) => raw(user, password, async (client) => { await client.query('BEGIN'); try { return await work(client); } finally { await client.query('ROLLBACK'); } });
  const expectSqlState = async (action, code) => { let caught; try { await action(); } catch (error) { caught = error; } assert(caught, `Expected PostgreSQL SQLSTATE ${code}.`); assert.equal(caught.code, code); };
  const time = async (name, work) => { const start = performance.now(); const value = await work(); evidence.timingsMs[name] = Number((performance.now() - start).toFixed(2)); return value; };

  async function resetDisposableDatabase() {
    bootstrap = new pg.Client(bootstrapConfig()); await bootstrap.connect();
    const authority = (await bootstrap.query('SELECT rolcreatedb, rolcreaterole FROM pg_roles WHERE rolname = current_user')).rows[0];
    assert.equal(authority?.rolcreatedb, true, 'Bootstrap role must have CREATEDB.');
    assert.equal(authority?.rolcreaterole, true, 'Bootstrap role must have CREATEROLE.');
    const priorDatabase = (await bootstrap.query("SELECT datname, shobj_description(oid, 'pg_database') AS marker FROM pg_database WHERE datname = $1", [DATABASE])).rows[0];
    if (priorDatabase) {
      assert.equal(priorDatabase.marker, DATABASE_MARKER, 'Refusing to reset a database without the exact MOS-133G disposable marker.');
      await bootstrap.query('SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()', [DATABASE]);
      await bootstrap.query(`DROP DATABASE ${qid(DATABASE)}`);
    }
    for (const role of [APPLICATION_USER, MIGRATION_USER]) {
      const priorRole = (await bootstrap.query("SELECT rolname, shobj_description(oid, 'pg_authid') AS marker FROM pg_roles WHERE rolname = $1", [role])).rows[0];
      if (priorRole) { assert.equal(priorRole.marker, ROLE_MARKER, 'Refusing to reset a role without the exact MOS-133G disposable marker.'); await bootstrap.query(`DROP ROLE ${qid(role)}`); }
    }
    migrationPassword = randomBytes(32).toString('hex'); applicationPassword = randomBytes(32).toString('hex');
    await bootstrap.query(`CREATE ROLE ${qid(MIGRATION_USER)} LOGIN PASSWORD ${qlit(migrationPassword)} NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION`);
    await bootstrap.query(`COMMENT ON ROLE ${qid(MIGRATION_USER)} IS ${qlit(ROLE_MARKER)}`);
    await bootstrap.query(`CREATE ROLE ${qid(APPLICATION_USER)} LOGIN PASSWORD ${qlit(applicationPassword)} NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION`);
    await bootstrap.query(`COMMENT ON ROLE ${qid(APPLICATION_USER)} IS ${qlit(ROLE_MARKER)}`);
    await bootstrap.query(`CREATE DATABASE ${qid(DATABASE)} OWNER ${qid(MIGRATION_USER)}`);
    await bootstrap.query(`COMMENT ON DATABASE ${qid(DATABASE)} IS ${qlit(DATABASE_MARKER)}`);
    admin = new pg.Client(bootstrapConfig(DATABASE)); await admin.connect();
    await admin.query('REVOKE CREATE ON SCHEMA public FROM PUBLIC');
    await admin.query(`GRANT USAGE, CREATE ON SCHEMA public TO ${qid(MIGRATION_USER)}`);
    await admin.query(`GRANT USAGE ON SCHEMA public TO ${qid(APPLICATION_USER)}`);
  }

  async function assembleRuntimes() {
    const secretProvider = { getSecret: async (reference) => reference === 'mos133g-migration' ? migrationPassword : reference === 'mos133g-application' ? applicationPassword : '' };
    const base = { environment: 'development', host: process.env.PGHOST, port: Number(process.env.PGPORT), database: DATABASE, tls: { required: false }, pool: { max: 4, connectionTimeoutMs: 5000, statementTimeoutMs: 10000, touchIntervalMs: 1000 } };
    migrationConfig = await createPostgresRuntimeConfig({ ...base, user: MIGRATION_USER, passwordSecretRef: 'mos133g-migration', role: 'MIGRATION' }, { secretProvider });
    applicationConfig = await createPostgresRuntimeConfig({ ...base, user: APPLICATION_USER, passwordSecretRef: 'mos133g-application', role: 'APPLICATION' }, { secretProvider });
    const safeLog = (entry) => { assert.doesNotMatch(JSON.stringify(entry), /password|postgres(?:ql)?:\/\//i); };
    migrationRuntime = new PostgresRuntime(migrationConfig, { log: safeLog }); applicationRuntime = new PostgresRuntime(applicationConfig, { log: safeLog });
    migrations = new PostgresMigrationRunner({ runtime: migrationRuntime });
    sessionStore = new PostgresSessionStore({ runtime: applicationRuntime, touchIntervalMs: 1000 });
    readiness = new PostgresInstallationReadinessValidator({ applicationRuntime, migrationRuntime, migrations, expectedTenantId: TENANT });
    migrationTarget = new PostgresCustomerContactMigrationTarget({ runtime: migrationRuntime, batchSize: 2 });
  }

  async function grantApplicationRuntimePrivileges() {
    await admin.query(`GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${qid(APPLICATION_USER)}`);
    await admin.query(`REVOKE INSERT, UPDATE, DELETE ON atlas_schema_migrations, atlas_installation FROM ${qid(APPLICATION_USER)}`);
    await admin.query(`ALTER DEFAULT PRIVILEGES FOR ROLE ${qid(MIGRATION_USER)} IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${qid(APPLICATION_USER)}`);
    await migrationRuntime.query('INSERT INTO atlas_installation (installation_id, tenant_id) VALUES ($1,$2)', [INSTALLATION, TENANT], 'MOS133G_INSTALLATION_IDENTITY');
  }

  function customer(id = 'CUST-CONSTRAINT-1', overrides = {}) { return { tenantId: TENANT, customerId: id, companyName: 'Constraint Customer', normalizedName: 'constraint customer', primaryContactDisplay: '', email: null, phone: null, status: 'ACTIVE', version: 1, createdAt: NOW, updatedAt: NOW, archivedAt: null, ...overrides }; }
  async function seedCustomer(client, row = customer()) { await client.query('INSERT INTO atlas_customers (tenant_id,customer_id,company_name,normalized_name,primary_contact_display,email,phone,status,version,created_at,updated_at,archived_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)', [row.tenantId, row.customerId, row.companyName, row.normalizedName, row.primaryContactDisplay, row.email, row.phone, row.status, row.version, row.createdAt, row.updatedAt, row.archivedAt]); }
  async function seedContact(client, id = 'CONTACT-00000000-0000-5000-8000-000000000001', customerId = 'CUST-CONSTRAINT-1', overrides = {}) { const row = { tenantId: TENANT, contactId: id, customerId, displayName: 'Constraint Contact', normalizedDisplayName: 'constraint contact', email: 'duplicate@example.test', normalizedEmail: 'duplicate@example.test', phone: '555-0199', titleRole: null, status: 'ACTIVE', version: 1, createdAt: NOW, updatedAt: NOW, archivedAt: null, ...overrides }; await client.query('INSERT INTO atlas_contacts (tenant_id,contact_id,customer_id,display_name,normalized_display_name,email,normalized_email,phone,title_role,status,version,created_at,updated_at,archived_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)', Object.values(row)); }

  function session(id, opaque, overrides = {}) { const issued = new Date(NOW); return { id, opaqueHash: hash(opaque), csrfHash: hash(`csrf-${id}`), userId: 'USER-SESSION', provider: 'GOOGLE', issuer: 'https://issuer.example', subject: `subject-${id}`, permittedTenants: [TENANT], activeTenant: TENANT, issuedAt: issued, authenticatedAt: issued, lastActivityAt: issued, idleExpiresAt: new Date(issued.getTime() + 30 * 60 * 1000), absoluteExpiresAt: new Date(issued.getTime() + 8 * 60 * 60 * 1000), status: 'ACTIVE', sessionVersion: 1, authenticationContext: { method: 'OIDC' }, ...overrides }; }

  const fBaseRows = () => ({
    customers: [
      { sourceId: 'ROW-C1', CustomerID: 'CUST-REAL-1', TenantID: TENANT, 'Company Name': 'Atlas Real One', 'Primary Contact': 'Legacy Display', Email: 'one@example.test', Phone: '555-0101', Status: 'ACTIVE', Version: 1, 'Created At': '2025-01-01T00:00:00Z', 'Updated At': '2026-01-01T00:00:00Z' },
      { sourceId: 'ROW-C2', CustomerID: 'legacy customer two', TenantID: TENANT, 'Company Name': 'Atlas Real Two', Email: 'two@example.test', Status: 'ACTIVE', Version: 2, 'Created At': '2025-02-01T00:00:00Z', 'Updated At': '2026-02-01T00:00:00Z' },
      { sourceId: 'ROW-C3', CustomerID: 'CUST-REAL-3', TenantID: TENANT, 'Company Name': 'Atlas Archived', Status: 'ARCHIVED', Version: 3, 'Created At': '2025-03-01T00:00:00Z', 'Updated At': '2026-03-01T00:00:00Z' }
    ],
    contacts: [
      { sourceId: 'ROW-P1', ContactID: 'LEGACY-PAT', TenantID: TENANT, CustomerID: 'CUST-REAL-1', DisplayName: 'Pat Real', Email: 'shared@example.test', Phone: '555-0200', Status: 'ACTIVE', Version: 1, CreatedAt: '2025-04-01T00:00:00Z', UpdatedAt: '2026-04-01T00:00:00Z' },
      { sourceId: 'ROW-P2', ContactID: 'LEGACY-SAM', TenantID: TENANT, CustomerID: 'legacy customer two', DisplayName: 'Sam Real', Email: 'shared@example.test', Phone: '555-0200', Status: 'ACTIVE', Version: 1, CreatedAt: '2025-05-01T00:00:00Z', UpdatedAt: '2026-05-01T00:00:00Z' },
      { sourceId: 'ROW-P3', ContactID: '', TenantID: TENANT, CustomerID: 'CUST-REAL-1', DisplayName: 'Blank Legacy ID', Status: 'ARCHIVED', Version: 1, CreatedAt: '2025-06-01T00:00:00Z', UpdatedAt: '2026-06-01T00:00:00Z' }
    ], rfqs: [], salesActivities: []
  });
  const fReferencedRows = () => { const rows = fBaseRows(); rows.rfqs = [{ RFQID: 'RFQ-REAL-1', TenantID: TENANT, CustomerID: 'CUST-REAL-1', ContactID: 'LEGACY-PAT' }, { RFQID: 'RFQ-BLANK', TenantID: TENANT, CustomerID: 'CUST-REAL-1', ContactID: '' }]; rows.salesActivities = [{ SalesActivityID: 'SACT-REAL-1', TenantID: TENANT, CustomerID: 'CUST-REAL-1', ContactID: 'LEGACY-PAT' }]; return rows; };
  const sourceReader = (rows) => new LegacyCustomerContactSourceReader({ batchSize: 10, readChunk: async () => ({ ...rows, nextCursor: null }) });
  const fMigration = (rows, target = migrationTarget) => new CustomerContactMigration({ sourceReader: sourceReader(rows), target, installationReadiness: readiness, installationPrerequisites: async () => guide.snapshot(), cutoverControl: {}, clock: () => new Date(NOW), softwareVersion: '22ba2b9' });

  async function plan(name, sql, values) {
    return raw(APPLICATION_USER, applicationPassword, async (client) => { const result = await client.query(`EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON) ${sql}`, values); const root = result.rows[0]['QUERY PLAN'][0]; const nodes = []; const visit = (node) => { nodes.push({ type: node['Node Type'], index: node['Index Name'] || null, rows: node['Actual Rows'] }); for (const child of node.Plans || []) visit(child); }; visit(root.Plan); evidence.plans[name] = { executionMs: Number(root['Execution Time'].toFixed(3)), nodes }; return evidence.plans[name]; });
  }

  before(async () => { await resetDisposableDatabase(); await assembleRuntimes(); });
  after(async () => { console.log(`MOS133G_EVIDENCE ${JSON.stringify(evidence)}`); await Promise.allSettled([applicationRuntime?.close(), migrationRuntime?.close(), admin?.end(), bootstrap?.end()]); });

  test('PostgreSQL 17 bootstrap connection and disposable identity are proven', async () => { const row = (await admin.query("SELECT current_setting('server_version_num') AS version_num, current_database() AS database, shobj_description(d.oid, 'pg_database') AS marker FROM pg_database d WHERE datname = current_database()")).rows[0]; assert.equal(Math.trunc(Number(row.version_num) / 10000), 17); assert.equal(row.database, DATABASE); assert.equal(row.marker, DATABASE_MARKER); });
  test('migration and application roles connect independently', async () => { assert.equal((await migrationRuntime.query('SELECT current_user AS role', [], 'MOS133G_MIGRATION_CONNECT')).rows[0].role, MIGRATION_USER); assert.equal((await applicationRuntime.query('SELECT current_user AS role', [], 'MOS133G_APPLICATION_CONNECT')).rows[0].role, APPLICATION_USER); });
  test('application role cannot create schema objects', async () => { await raw(APPLICATION_USER, applicationPassword, (client) => expectSqlState(() => client.query('CREATE TABLE mos133g_forbidden_table(id int)'), '42501')); });
  test('D-A classifies the real empty database without mutating it', async () => { const value = await readiness.inspect(); assert.equal(value.state, 'INITIALIZATION_REQUIRED'); assert.equal(value.remediationCode, 'ATLAS_SCHEMA_UNINITIALIZED'); assert.equal((await admin.query("SELECT count(*)::int AS count FROM information_schema.tables WHERE table_schema='public'")).rows[0].count, 0); });
  test('accepted migrations apply from empty PostgreSQL 17 in order', async () => { const result = await time('schemaMigration', () => migrations.apply()); assert.deepEqual(result, { state: 'CURRENT', ready: true }); const rows = (await migrationRuntime.query('SELECT migration_id,status FROM atlas_schema_migrations ORDER BY migration_id', [], 'MOS133G_MIGRATION_ORDER')).rows; assert.deepEqual(rows.map((row) => row.migration_id), FOUNDATION_MIGRATIONS.map((migration) => migration.id)); assert(rows.every((row) => row.status === 'APPLIED')); });
  test('application grants exclude installation and migration metadata writes', async () => { await grantApplicationRuntimePrivileges(); await raw(APPLICATION_USER, applicationPassword, async (client) => { await expectSqlState(() => client.query("UPDATE atlas_schema_migrations SET status='FAILED'"), '42501'); await expectSqlState(() => client.query("UPDATE atlas_installation SET tenant_id='BAD'"), '42501'); }); });
  test('migration rerun is already-applied and idempotent', async () => { const beforeRows = (await migrationRuntime.query('SELECT migration_id,applied_at FROM atlas_schema_migrations ORDER BY migration_id', [], 'MOS133G_MIGRATION_BEFORE')).rows; const result = await migrations.apply(); const afterRows = (await migrationRuntime.query('SELECT migration_id,applied_at FROM atlas_schema_migrations ORDER BY migration_id', [], 'MOS133G_MIGRATION_AFTER')).rows; assert.deepEqual(result, { state: 'CURRENT', ready: true }); assert.deepEqual(afterRows, beforeRows); });
  test('checksum verification passes for accepted migrations', async () => assert.deepEqual(await migrations.status(), { state: 'CURRENT', ready: true }));
  test('checksum mismatch fails closed without changing metadata', async () => { const altered = new PostgresMigrationRunner({ runtime: migrationRuntime, migrations: [{ ...FOUNDATION_MIGRATIONS[0], checksum: 'deliberate-mos133g-mismatch' }, ...FOUNDATION_MIGRATIONS.slice(1)] }); assert.deepEqual(await altered.status(), { state: 'CHECKSUM_MISMATCH', ready: false }); await assert.rejects(() => altered.apply(), (error) => error.code === 'SCHEMA_INCOMPATIBLE'); assert.deepEqual(await migrations.status(), { state: 'CURRENT', ready: true }); });
  test('double migration attempt completes under advisory-lock contract', { timeout: 10000 }, async () => { const second = new PostgresRuntime(migrationConfig); const secondRunner = new PostgresMigrationRunner({ runtime: second }); try { const results = await Promise.all([migrations.apply(), secondRunner.apply()]); assert(results.every((result) => result.ready)); } finally { await second.close(); } });
  test('installation identity is exact and tenant-scoped', async () => { const rows = (await applicationRuntime.query('SELECT installation_id,tenant_id FROM atlas_installation', [], 'MOS133G_INSTALLATION_VERIFY')).rows; assert.deepEqual(rows, [{ installation_id: INSTALLATION, tenant_id: TENANT }]); });
  test('D-A returns real PostgreSQL READY with least-privilege roles', async () => { const value = await readiness.inspect(); assert.equal(value.state, 'READY'); assert.equal(value.checks.version.code, 'POSTGRESQL_17_SUPPORTED'); assert.equal(value.checks.applicationRole.code, 'APPLICATION_ROLE_LEAST_PRIVILEGE'); assert.equal(value.checks.migrationRole.code, 'MIGRATION_ROLE_SEPARATE_AND_READY'); assert.equal(value.checks.transactionSmoke.code, 'TRANSACTION_ROLLBACK_PROVEN'); assert.doesNotMatch(JSON.stringify(value), /password|postgres(?:ql)?:\/\/|127\.0\.0\.1/i); });
  test('D-B safely consumes real D-A output without claiming go-live', async () => { guide = new TenantInstallationGuide({ readinessValidator: readiness, deploymentTarget: 'GENERIC_POSTGRESQL', bootstrap: { state: 'READY', tenantScoped: true, platformAuthority: false }, runtimeSmoke: async () => ({ sessionStore: 'PASS', runtime: 'PASS' }) }); guide.acknowledge({ tenantResponsibilities: true, backupRestore: true }); const value = await guide.validate(); assert.equal(value.overall, 'READY_FOR_NEXT_STEP'); assert.equal(value.goLiveEligible, false); assert.equal(value.productionGoLive, 'PENDING'); assert.doesNotMatch(JSON.stringify(value), /password|postgres(?:ql)?:\/\/|127\.0\.0\.1|atlas_preprod_mos133g/i); });

  test('Customer primary key, NOT NULL, status, and version constraints are real', async () => transaction(APPLICATION_USER, applicationPassword, async (client) => { await seedCustomer(client); await expectSqlState(() => seedCustomer(client), '23505'); }));
  test('Customer NOT NULL constraint rejects missing company name', async () => transaction(APPLICATION_USER, applicationPassword, (client) => expectSqlState(() => client.query("INSERT INTO atlas_customers(tenant_id,customer_id,normalized_name) VALUES($1,'CUST-BAD','bad')", [TENANT]), '23502')));
  test('Customer status check rejects invalid status', async () => transaction(APPLICATION_USER, applicationPassword, (client) => expectSqlState(() => seedCustomer(client, customer('CUST-BAD-STATUS', { status: 'UNKNOWN' })), '23514')));
  test('optimistic version check rejects zero', async () => transaction(APPLICATION_USER, applicationPassword, (client) => expectSqlState(() => seedCustomer(client, customer('CUST-BAD-VERSION', { version: 0 })), '23514')));
  test('archived Customer and timestamptz semantics are preserved', async () => transaction(APPLICATION_USER, applicationPassword, async (client) => { await seedCustomer(client, customer('CUST-ARCHIVED', { status: 'ARCHIVED', archivedAt: '2026-01-01T03:00:00-05:00' })); const row = (await client.query("SELECT status,to_char(archived_at AT TIME ZONE 'UTC','YYYY-MM-DD\"T\"HH24:MI:SS.MS') || 'Z' AS archived_utc FROM atlas_customers WHERE tenant_id=$1 AND customer_id='CUST-ARCHIVED'", [TENANT])).rows[0]; assert.equal(row.status, 'ARCHIVED'); assert.equal(row.archived_utc, '2026-01-01T08:00:00.000Z'); }));
  test('Contact belongs to Customer and canonical ID shape is enforced', async () => transaction(APPLICATION_USER, applicationPassword, async (client) => { await seedCustomer(client); await seedContact(client); await expectSqlState(() => seedContact(client, 'BAD-CONTACT-ID'), '23514'); }));
  test('duplicate Contact email and phone are permitted', async () => transaction(APPLICATION_USER, applicationPassword, async (client) => { await seedCustomer(client); await seedContact(client); await seedContact(client, 'CONTACT-00000000-0000-5000-8000-000000000002', 'CUST-CONSTRAINT-1', { displayName: 'Duplicate Details', normalizedDisplayName: 'duplicate details' }); assert.equal((await client.query('SELECT count(*)::int AS count FROM atlas_contacts WHERE tenant_id=$1', [TENANT])).rows[0].count, 2); }));
  test('cross-tenant Contact to Customer is rejected by composite FK', async () => transaction(MIGRATION_USER, migrationPassword, async (client) => { await seedCustomer(client); await client.query("INSERT INTO atlas_installation(installation_id,tenant_id) VALUES('INSTALL-OTHER','TENANT-OTHER')"); await expectSqlState(() => seedContact(client, 'CONTACT-00000000-0000-5000-8000-000000000003', 'CUST-CONSTRAINT-1', { tenantId: 'TENANT-OTHER' }), '23503'); }));
  test('RFQ same-Customer Contact succeeds and cross-Customer Contact fails', async () => transaction(APPLICATION_USER, applicationPassword, async (client) => { await seedCustomer(client); await seedCustomer(client, customer('CUST-CONSTRAINT-2', { companyName: 'Other', normalizedName: 'other' })); await seedContact(client); await client.query("INSERT INTO atlas_rfqs(tenant_id,rfq_id,customer_id,contact_id) VALUES($1,'RFQ-GOOD','CUST-CONSTRAINT-1','CONTACT-00000000-0000-5000-8000-000000000001')", [TENANT]); await expectSqlState(() => client.query("INSERT INTO atlas_rfqs(tenant_id,rfq_id,customer_id,contact_id) VALUES($1,'RFQ-BAD','CUST-CONSTRAINT-2','CONTACT-00000000-0000-5000-8000-000000000001')", [TENANT]), '23503'); }));
  test('Sales Activity same-Customer Contact succeeds and mismatch fails', async () => transaction(APPLICATION_USER, applicationPassword, async (client) => { await seedCustomer(client); await seedCustomer(client, customer('CUST-CONSTRAINT-2', { companyName: 'Other', normalizedName: 'other' })); await seedContact(client); await client.query("INSERT INTO atlas_sales_activities(tenant_id,sales_activity_id,customer_id,contact_id,activity_type) VALUES($1,'SACT-GOOD','CUST-CONSTRAINT-1','CONTACT-00000000-0000-5000-8000-000000000001','CALL')", [TENANT]); await expectSqlState(() => client.query("INSERT INTO atlas_sales_activities(tenant_id,sales_activity_id,customer_id,contact_id,activity_type) VALUES($1,'SACT-BAD','CUST-CONSTRAINT-2','CONTACT-00000000-0000-5000-8000-000000000001','CALL')", [TENANT]), '23503'); }));
  test('exact money and numeric quantity retain PostgreSQL precision', async () => transaction(APPLICATION_USER, applicationPassword, async (client) => { await seedCustomer(client); await client.query("INSERT INTO atlas_quotes(tenant_id,quote_id,customer_id) VALUES($1,'QUOTE-1','CUST-CONSTRAINT-1')", [TENANT]); await client.query("INSERT INTO atlas_quote_revisions(tenant_id,quote_revision_id,quote_id,customer_id,revision_number,total_minor) VALUES($1,'QREV-1','QUOTE-1','CUST-CONSTRAINT-1',1,9007199254740993)", [TENANT]); await client.query("INSERT INTO atlas_quote_lines(tenant_id,quote_line_id,quote_revision_id,sequence_number,line_type,quantity,unit_amount_minor,extended_amount_minor) VALUES($1,'QLINE-1','QREV-1',1,'ITEM',1.234567,9007199254740993,9007199254740993)", [TENANT]); const row = (await client.query("SELECT quantity::text,unit_amount_minor::text FROM atlas_quote_lines WHERE tenant_id=$1 AND quote_line_id='QLINE-1'", [TENANT])).rows[0]; assert.deepEqual(row, { quantity: '1.234567', unit_amount_minor: '9007199254740993' }); }));
  test('external identity active uniqueness permits revoked history only', async () => transaction(APPLICATION_USER, applicationPassword, async (client) => { await client.query("INSERT INTO atlas_users(user_id,display_name) VALUES('USER-IDENTITY','Identity')"); await client.query("INSERT INTO atlas_external_identities(external_identity_id,user_id,provider,issuer,subject,status) VALUES('EXT-1','USER-IDENTITY','GOOGLE','issuer','subject','ACTIVE')"); await expectSqlState(() => client.query("INSERT INTO atlas_external_identities(external_identity_id,user_id,provider,issuer,subject,status) VALUES('EXT-2','USER-IDENTITY','GOOGLE','issuer','subject','ACTIVE')"), '23505'); }));
  test('successful Customer and Contact transaction commits', async () => { await applicationRuntime.withTransaction('MOS133G_COMMIT', async (tx) => { await tx.query("INSERT INTO atlas_customers(tenant_id,customer_id,company_name,normalized_name) VALUES($1,'CUST-TX','Transaction','transaction')", [TENANT]); await tx.query("INSERT INTO atlas_contacts(tenant_id,contact_id,customer_id,display_name,normalized_display_name) VALUES($1,'CONTACT-00000000-0000-5000-8000-000000000010','CUST-TX','Transaction Contact','transaction contact')", [TENANT]); }); assert.equal((await applicationRuntime.query("SELECT count(*)::int AS count FROM atlas_contacts WHERE tenant_id=$1 AND customer_id='CUST-TX'", [TENANT], 'MOS133G_COMMIT_VERIFY')).rows[0].count, 1); await applicationRuntime.query("DELETE FROM atlas_contacts WHERE tenant_id=$1 AND customer_id='CUST-TX'", [TENANT], 'MOS133G_COMMIT_CLEANUP_CONTACT'); await applicationRuntime.query("DELETE FROM atlas_customers WHERE tenant_id=$1 AND customer_id='CUST-TX'", [TENANT], 'MOS133G_COMMIT_CLEANUP_CUSTOMER'); });
  test('injected transaction failure rolls back Customer and Contact together', async () => { await assert.rejects(() => applicationRuntime.withTransaction('MOS133G_ROLLBACK', async (tx) => { await tx.query("INSERT INTO atlas_customers(tenant_id,customer_id,company_name,normalized_name) VALUES($1,'CUST-ROLLBACK','Rollback','rollback')", [TENANT]); throw new Error('controlled failure'); })); assert.equal((await applicationRuntime.query("SELECT count(*)::int AS count FROM atlas_customers WHERE tenant_id=$1 AND customer_id='CUST-ROLLBACK'", [TENANT], 'MOS133G_ROLLBACK_VERIFY')).rows[0].count, 0); });

  test('PostgreSQL session create stores only hashes and reads by opaque value', async () => { await sessionStore.create(session('SESSION-1', 'opaque-session-one')); const found = await sessionStore.getByOpaque('opaque-session-one'); assert.equal(found.id, 'SESSION-1'); const rawRow = (await applicationRuntime.query("SELECT opaque_hash FROM atlas_auth_sessions WHERE session_id='SESSION-1'", [], 'MOS133G_SESSION_HASH')).rows[0]; assert.notEqual(rawRow.opaque_hash, 'opaque-session-one'); });
  test('PostgreSQL session rotation revokes the old session atomically', async () => { await sessionStore.rotate('SESSION-1', session('SESSION-2', 'opaque-session-two')); assert.equal((await sessionStore.get('SESSION-1')).status, 'REVOKED'); assert.equal((await sessionStore.get('SESSION-2')).status, 'ACTIVE'); });
  test('PostgreSQL session revoke-all is tenant-runtime durable', async () => { assert.equal(await sessionStore.revokeAllForUser('USER-SESSION'), 1); assert.equal((await sessionStore.get('SESSION-2')).status, 'REVOKED'); });
  test('expired sessions are cleaned with bounded deletion', async () => { await sessionStore.create(session('SESSION-EXPIRED', 'opaque-expired', { absoluteExpiresAt: new Date('2026-01-01T00:00:00Z') })); assert.equal(await sessionStore.cleanupExpired({ limit: 10 }), 1); assert.equal(await sessionStore.get('SESSION-EXPIRED'), null); });
  test('session persists across a new PostgreSQL runtime instance', async () => { await sessionStore.create(session('SESSION-PERSIST', 'opaque-persist')); const restarted = new PostgresRuntime(applicationConfig); try { const store = new PostgresSessionStore({ runtime: restarted }); assert.equal((await store.getByOpaque('opaque-persist')).id, 'SESSION-PERSIST'); } finally { await restarted.close(); } });
  test('session opaque-hash uniqueness rejects duplicate browser secrets', async () => { await assert.rejects(() => sessionStore.create(session('SESSION-DUPLICATE', 'opaque-persist')), (error) => error.code === 'CONFLICT'); });

  test('MOS-133F PLAN is side-effect free against real PostgreSQL', async () => { fService = fMigration(fBaseRows()); const beforeCount = (await migrationRuntime.query("SELECT count(*)::int AS count FROM atlas_customers WHERE tenant_id=$1", [TENANT], 'MOS133G_F_PLAN_BEFORE')).rows[0].count; const report = await fService.run('PLAN', CONTEXT); const afterCount = (await migrationRuntime.query("SELECT count(*)::int AS count FROM atlas_customers WHERE tenant_id=$1", [TENANT], 'MOS133G_F_PLAN_AFTER')).rows[0].count; assert.equal(report.state, 'READY'); assert.equal(beforeCount, afterCount); fSourceFingerprint = report.sourceFingerprint; });
  test('MOS-133F VALIDATE is side-effect free against real PostgreSQL', async () => { const report = await fService.run('VALIDATE', CONTEXT); assert.equal(report.state, 'READY'); assert.equal((await migrationRuntime.query("SELECT count(*)::int AS count FROM atlas_security_audit_events WHERE tenant_id=$1 AND operation='CUSTOMER_CONTACT_MIGRATION'", [TENANT], 'MOS133G_F_VALIDATE_AUDIT')).rows[0].count, 0); });
  test('MOS-133F MIGRATE loads synthetic Customer and Contact rows transactionally', async () => { const report = await time('customerContactInitialMigration', () => fService.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'MOS133G-F-1' })); assert.equal(report.state, 'PASS'); assert.deepEqual(report.verification.targetCounts, { customers: 3, contacts: 3 }); fCanonicalIds = (await migrationRuntime.query('SELECT customer_id FROM atlas_customers WHERE tenant_id=$1 ORDER BY customer_id', [TENANT], 'MOS133G_F_IDS')).rows.map((row) => row.customer_id); assert(fCanonicalIds.some((id) => /^CUST-[0-9a-f-]{36}$/i.test(id))); });
  test('MOS-133F identical retry is idempotent with stable IDs and fingerprint', async () => { const report = await fService.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'MOS133G-F-2' }); assert.equal(report.state, 'PASS'); assert.equal(report.customerCounts.alreadyPresent, 3); assert.equal(report.contactCounts.alreadyPresent, 3); assert.equal(report.sourceFingerprint, fSourceFingerprint); const ids = (await migrationRuntime.query('SELECT customer_id FROM atlas_customers WHERE tenant_id=$1 ORDER BY customer_id', [TENANT], 'MOS133G_F_IDS_RETRY')).rows.map((row) => row.customer_id); assert.deepEqual(ids, fCanonicalIds); });
  test('partial compatible target plans and restores only the missing Contact', async () => { const id = (await migrationRuntime.query("DELETE FROM atlas_contacts WHERE tenant_id=$1 AND display_name='Blank Legacy ID' RETURNING contact_id", [TENANT], 'MOS133G_F_PARTIAL_DELETE')).rows[0].contact_id; const report = await fService.run('PLAN', CONTEXT); assert.equal(report.contactCounts.inserts, 1); assert.equal(report.contactCounts.alreadyPresent, 2); assert(id); assert.equal((await fService.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'MOS133G-F-PARTIAL' })).state, 'PASS'); });
  test('resolved and blank RFQ plus Sales Activity references reconcile on real PostgreSQL', async () => { await migrationRuntime.query("INSERT INTO atlas_rfqs(tenant_id,rfq_id,customer_id,contact_id) VALUES($1,'RFQ-REAL-1','CUST-REAL-1',NULL),($1,'RFQ-BLANK','CUST-REAL-1',NULL)", [TENANT], 'MOS133G_F_RFQ_SEED'); await migrationRuntime.query("INSERT INTO atlas_sales_activities(tenant_id,sales_activity_id,customer_id,contact_id,activity_type) VALUES($1,'SACT-REAL-1','CUST-REAL-1',NULL,'CALL')", [TENANT], 'MOS133G_F_SALES_SEED'); fRowsWithReferences = fReferencedRows(); fService = fMigration(fRowsWithReferences); const report = await fService.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'MOS133G-F-REFS' }); assert.equal(report.state, 'PASS'); assert.deepEqual(report.referenceCounts.byEntity.RFQ, { resolved: 1, blank: 1, unresolved: 0, conflicting: 0 }); assert.equal(report.referenceCounts.byEntity.SALES_ACTIVITY.resolved, 1); const rfqs = (await migrationRuntime.query("SELECT rfq_id,contact_id FROM atlas_rfqs WHERE tenant_id=$1 ORDER BY rfq_id", [TENANT], 'MOS133G_F_RFQ_VERIFY')).rows; assert.equal(rfqs.find((row) => row.rfq_id === 'RFQ-BLANK').contact_id, null); assert.match(rfqs.find((row) => row.rfq_id === 'RFQ-REAL-1').contact_id, /^CONTACT-/); });
  test('MOS-133F VERIFY is repeatable and reconciles fields plus references', async () => { const first = await time('customerContactVerification', () => fService.run('VERIFY', CONTEXT)); const second = await fService.run('VERIFY', CONTEXT); assert.equal(first.state, 'READY'); assert.equal(first.verification.state, 'PASS'); assert.deepEqual(second.verification, first.verification); });
  test('unresolved Contact evidence is preserved and blocks cutover readiness', async () => { const rows = fReferencedRows(); rows.rfqs = [{ RFQID: 'RFQ-REAL-1', TenantID: TENANT, CustomerID: 'CUST-REAL-1', ContactID: 'ORPHAN' }]; rows.salesActivities = []; const service = fMigration(rows); const report = await service.run('PLAN', CONTEXT, { runId: 'MOS133G-UNRESOLVED' }); assert.equal(report.referenceCounts.unresolved, 1); assert.equal(report.unresolvedReferences[0].resolutionStatus, 'UNRESOLVED'); assert.equal((await service.run('CUTOVER_READINESS', CONTEXT)).state, 'NOT_READY'); });
  test('conflicting Contact reference blocks and cross-tenant reference fails closed', async () => { const conflict = fReferencedRows(); conflict.rfqs = [{ RFQID: 'RFQ-REAL-1', TenantID: TENANT, CustomerID: 'CUST-REAL-3', ContactID: 'LEGACY-PAT' }]; conflict.salesActivities = []; assert((await fMigration(conflict).run('VALIDATE', CONTEXT)).issues.some((issue) => issue.code === 'CONTACT_REFERENCE_CUSTOMER_CONFLICT')); const cross = fReferencedRows(); cross.rfqs = [{ RFQID: 'RFQ-REAL-1', TenantID: 'TENANT-OTHER', CustomerID: 'CUST-REAL-1', ContactID: 'LEGACY-PAT' }]; cross.salesActivities = []; assert((await fMigration(cross).run('VALIDATE', CONTEXT)).issues.some((issue) => issue.code === 'CROSS_TENANT_SOURCE')); });
  test('Customer primaryContact, email, phone, and name never synthesize Contacts', async () => { const rows = fBaseRows(); rows.customers = [rows.customers[0]]; rows.contacts = []; const report = await fMigration(rows).run('PLAN', CONTEXT); assert.equal(report.contactCounts.valid, 0); });
  test('controlled Customer target mismatch is detected beyond counts', async () => { await migrationRuntime.query("UPDATE atlas_customers SET normalized_name='controlled mismatch' WHERE tenant_id=$1 AND customer_id='CUST-REAL-1'", [TENANT], 'MOS133G_MISMATCH_SET'); try { const report = await fService.run('VERIFY', CONTEXT); assert.equal(report.state, 'NOT_READY'); assert(report.issues.some((issue) => issue.code === 'TARGET_CONFLICT')); } finally { await migrationRuntime.query("UPDATE atlas_customers SET normalized_name='atlas real one' WHERE tenant_id=$1 AND customer_id='CUST-REAL-1'", [TENANT], 'MOS133G_MISMATCH_RESTORE'); } });
  test('controlled Contact target conflict blocks safely', async () => { const contact = (await migrationRuntime.query("UPDATE atlas_contacts SET display_name='Controlled Mismatch' WHERE tenant_id=$1 AND display_name='Pat Real' RETURNING contact_id", [TENANT], 'MOS133G_CONTACT_CONFLICT_SET')).rows[0]; try { const report = await fService.run('VALIDATE', CONTEXT); assert(report.issues.some((issue) => issue.code === 'TARGET_CONFLICT')); } finally { await migrationRuntime.query("UPDATE atlas_contacts SET display_name='Pat Real' WHERE tenant_id=$1 AND contact_id=$2", [TENANT, contact.contact_id], 'MOS133G_CONTACT_CONFLICT_RESTORE'); } });
  test('controlled interrupted migration rolls back and records FAILED distinctly', async () => { const failingTarget = { inspect: migrationTarget.inspect.bind(migrationTarget), verify: migrationTarget.verify.bind(migrationTarget), recordRun: migrationTarget.recordRun.bind(migrationTarget), migrate: async () => migrationRuntime.withTransaction('MOS133G_F_INTERRUPTION', async (tx) => { await tx.query("UPDATE atlas_customers SET company_name='SHOULD ROLLBACK' WHERE tenant_id=$1 AND customer_id='CUST-REAL-1'", [TENANT]); throw new Error('controlled interruption'); }) }; const service = fMigration(fRowsWithReferences, failingTarget); const report = await service.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'MOS133G-F-FAIL' }); assert.equal(report.state, 'FAILED'); assert.equal((await migrationRuntime.query("SELECT company_name FROM atlas_customers WHERE tenant_id=$1 AND customer_id='CUST-REAL-1'", [TENANT], 'MOS133G_F_INTERRUPTION_VERIFY')).rows[0].company_name, 'Atlas Real One'); const audit = (await migrationRuntime.query("SELECT outcome FROM atlas_security_audit_events WHERE tenant_id=$1 AND correlation_id='MOS133G-F-FAIL'", [TENANT], 'MOS133G_F_FAILED_AUDIT')).rows[0]; assert.equal(audit.outcome, 'FAILED'); assert.equal((await fService.run('MIGRATE', CONTEXT, { confirmed: true, runId: 'MOS133G-F-RECOVER' })).state, 'PASS'); });
  test('migration audit distinguishes completed and failed runs without secrets', async () => { const rows = (await migrationRuntime.query("SELECT correlation_id,outcome,details_json FROM atlas_security_audit_events WHERE tenant_id=$1 AND operation='CUSTOMER_CONTACT_MIGRATION' ORDER BY correlation_id", [TENANT], 'MOS133G_F_AUDIT_VERIFY')).rows; assert(rows.some((row) => row.outcome === 'COMPLETED')); assert(rows.some((row) => row.outcome === 'FAILED')); assert.doesNotMatch(JSON.stringify(rows), /password|postgres(?:ql)?:\/\//i); });
  test('MOS-133F CUTOVER_READINESS evaluates real state without changing authority', async () => { const report = await fService.run('CUTOVER_READINESS', CONTEXT); assert.equal(report.state, 'READY_FOR_CUSTOMER_CONTACT_CUTOVER'); assert.equal(report.cutoverActionAvailable, true); const table = await migrationRuntime.query("SELECT to_regclass('public.atlas_mos133g_cutover_routes') AS name", [], 'MOS133G_CUTOVER_PRECHECK'); assert.equal(table.rows[0].name, null); });

  test('disposable persistent cutover CAS atomically switches Customer and Contact', async () => { await migrationRuntime.query('CREATE TABLE atlas_mos133g_cutover_routes(tenant_id text PRIMARY KEY,version int NOT NULL,customer text NOT NULL,contact text NOT NULL,legacy_sheets text NOT NULL,fallback text NOT NULL)', [], 'MOS133G_CUTOVER_STORE_CREATE'); await migrationRuntime.query("INSERT INTO atlas_mos133g_cutover_routes VALUES($1,1,'SHEETS','SHEETS','AUTHORITATIVE','FAIL_CLOSED')", [TENANT], 'MOS133G_CUTOVER_STORE_SEED'); const store = { get: async (tenantId) => (await migrationRuntime.query('SELECT * FROM atlas_mos133g_cutover_routes WHERE tenant_id=$1', [tenantId], 'MOS133G_CUTOVER_GET')).rows[0], compareAndSet: async (tenantId, version, next) => { const result = await migrationRuntime.query('UPDATE atlas_mos133g_cutover_routes SET version=version+1,customer=$3,contact=$4,legacy_sheets=$5,fallback=$6 WHERE tenant_id=$1 AND version=$2 RETURNING *', [tenantId, version, next.customer, next.contact, next.legacySheets, next.fallback], 'MOS133G_CUTOVER_CAS'); if (!result.rowCount) throw new Error('stale'); return result.rows[0]; } }; cutoverControl = new CustomerContactCutoverControl({ store, authorizer: async (context) => context.authoritative === true, readinessProvider: async () => fService.run('CUTOVER_READINESS', CONTEXT), clock: () => new Date(NOW) }); const result = await cutoverControl.activate(CONTEXT, 1); assert.equal(result.customer, 'POSTGRESQL'); assert.equal(result.contact, 'POSTGRESQL'); assert.equal(result.legacy_sheets, 'READ_ONLY_MIGRATION_EVIDENCE'); });
  test('stale cutover CAS and browser authority are rejected', async () => { await assert.rejects(() => cutoverControl.activate(CONTEXT, 1), /uncertain/i); await assert.rejects(() => cutoverControl.activate({ ...CONTEXT, authoritative: false }, 2), /trusted tenant/i); });
  test('post-cutover routing has no dual-write or automatic Sheets fallback', async () => { assert.equal(await cutoverControl.route(CONTEXT, 'CUSTOMER'), 'POSTGRESQL'); assert.equal(await cutoverControl.route(CONTEXT, 'CONTACT'), 'POSTGRESQL'); assert.throws(() => cutoverControl.failClosedAfterCutover(), /fallback is disabled/i); });

  test('representative real EXPLAIN plans are bounded and recorded', async () => { await plan('customerPk', 'SELECT customer_id,company_name FROM atlas_customers WHERE tenant_id=$1 AND customer_id=$2', [TENANT, 'CUST-REAL-1']); await plan('customerList', 'SELECT customer_id,company_name FROM atlas_customers WHERE tenant_id=$1 ORDER BY customer_id LIMIT 50', [TENANT]); await plan('contactPk', 'SELECT contact_id,display_name FROM atlas_contacts WHERE tenant_id=$1 AND contact_id=$2', [TENANT, (await applicationRuntime.query("SELECT contact_id FROM atlas_contacts WHERE tenant_id=$1 AND display_name='Pat Real'", [TENANT], 'MOS133G_PLAN_CONTACT_ID')).rows[0].contact_id]); await plan('contactsByCustomer', 'SELECT contact_id,display_name FROM atlas_contacts WHERE tenant_id=$1 AND customer_id=$2 AND status=$3 ORDER BY contact_id LIMIT 50', [TENANT, 'CUST-REAL-1', 'ACTIVE']); await plan('rfqReference', 'SELECT rfq_id,customer_id,contact_id FROM atlas_rfqs WHERE tenant_id=$1 AND rfq_id=$2', [TENANT, 'RFQ-REAL-1']); await plan('salesReference', 'SELECT sales_activity_id,customer_id,contact_id FROM atlas_sales_activities WHERE tenant_id=$1 AND sales_activity_id=$2', [TENANT, 'SACT-REAL-1']); await plan('sessionOpaque', 'SELECT session_id,status FROM atlas_auth_sessions WHERE opaque_hash=$1', [hash('opaque-persist')]); await plan('migrationRun', "SELECT correlation_id,outcome FROM atlas_security_audit_events WHERE tenant_id=$1 AND operation='CUSTOMER_CONTACT_MIGRATION' ORDER BY occurred_at DESC LIMIT 20", [TENANT]); assert(Object.values(evidence.plans).every((entry) => entry.executionMs >= 0 && entry.nodes.length > 0)); });
  test('required representative indexes exist with no material design gap', async () => { const names = new Set((await applicationRuntime.query("SELECT indexname FROM pg_indexes WHERE schemaname='public'", [], 'MOS133G_INDEXES')).rows.map((row) => row.indexname)); for (const name of ['atlas_customers_pkey', 'atlas_customers_name_idx', 'atlas_contacts_pkey', 'atlas_contacts_customer_status_idx', 'atlas_rfqs_pkey', 'atlas_sales_activities_pkey', 'atlas_auth_sessions_opaque_hash_key', 'atlas_security_audit_recent_idx']) assert(names.has(name), `Missing ${name}`); });
  test('all rehearsal evidence and logs remain credential-safe', async () => { const serialized = JSON.stringify(evidence); assert.doesNotMatch(serialized, /password|PGPASSWORD|postgres(?:ql)?:\/\/|MOS$/i); });
}
