import assert from 'node:assert/strict';
import test from 'node:test';
import { createHash } from 'node:crypto';
import { newDb } from 'pg-mem';
import { createPostgresRuntimeConfig,PostgresRuntime } from '../src/postgres-runtime.js';
import { FOUNDATION_MIGRATIONS,PostgresMigrationRunner } from '../src/migrations.js';
import { PostgresWipBinRepository,WipBinService } from '../src/wip-bin-tracking.js';

const ID={bin:'WIP-BIN-11111111-1111-4111-8111-111111111111',bin2:'WIP-BIN-22222222-2222-4222-8222-222222222222',assignment:'WIP-ASGN-33333333-3333-4333-8333-333333333333',assignment2:'WIP-ASGN-44444444-4444-4444-8444-444444444444',location:'WIP-LOC-55555555-5555-4555-8555-555555555555',identifier:'WIP-ID-66666666-6666-4666-8666-666666666666'};
const CONTEXT={authoritative:true,tenantId:'TENANT-A',userId:'USER-A',correlationId:'CORR-MOS137',capabilities:['WIP_BIN_READ','WIP_BIN_WRITE','WIP_BIN_OPERATE']};

async function fixture(){const db=newDb({autoCreateForeignKeyIndices:true,noAstCoverageCheck:true});const {Pool}=db.adapters.createPg();const secretProvider={getSecret:async()=> 'test'};const base={environment:'test',host:'localhost',database:'atlas_wip_test',user:'atlas',passwordSecretRef:'x',tls:{required:false}};const app=new PostgresRuntime(await createPostgresRuntimeConfig({...base,role:'APPLICATION'},{secretProvider}),{PoolCtor:Pool});const migration=new PostgresRuntime(await createPostgresRuntimeConfig({...base,role:'MIGRATION'},{secretProvider}),{PoolCtor:Pool});await new PostgresMigrationRunner({runtime:migration,migrations:FOUNDATION_MIGRATIONS,lock:{acquire:async()=>async()=>{}}}).apply();return {app,migration};}
async function reject(p){await assert.rejects(p);}
async function seed(f){for(const t of ['TENANT-A','TENANT-B'])await f.app.query('INSERT INTO atlas_installation(installation_id,tenant_id) VALUES($1,$2)',[`INSTALL-${t}`,t]);await f.app.query("INSERT INTO atlas_users(user_id,display_name) VALUES('USER-A','A'),('USER-B','B')");await f.app.query("INSERT INTO atlas_customers(tenant_id,customer_id,company_name,normalized_name) VALUES('TENANT-A','CUSTOMER-A','A','a')");await f.app.query("INSERT INTO atlas_jobs(tenant_id,job_id,customer_id,status) VALUES('TENANT-A','JOB-CUSTOMER','CUSTOMER-A','RELEASED')");await f.app.query("INSERT INTO atlas_jobs(tenant_id,job_id,work_classification,internal_work_type,title,status) VALUES('TENANT-A','JOB-INTERNAL','INTERNAL','FIXTURE_TOOLING','Fixture','PLANNED')");}

test('schema supports reusable bins, CUSTOMER and INTERNAL Jobs, release/reassignment and retained history',async()=>{const f=await fixture();await seed(f);await f.app.query('INSERT INTO atlas_wip_bins(tenant_id,wip_bin_id,bin_label,current_location,created_by_user_id) VALUES($1,$2,$3,$4,$5)',['TENANT-A',ID.bin,'BIN-014','RECEIVING','USER-A']);await f.app.query('INSERT INTO atlas_wip_bin_assignments(tenant_id,wip_bin_assignment_id,wip_bin_id,job_id,assigned_at,assigned_by_user_id,correlation_id) VALUES($1,$2,$3,$4,NOW(),$5,$6)',['TENANT-A',ID.assignment,ID.bin,'JOB-CUSTOMER','USER-A','CORR-1']);await reject(f.app.query('INSERT INTO atlas_wip_bin_assignments(tenant_id,wip_bin_assignment_id,wip_bin_id,job_id,assigned_at,assigned_by_user_id,correlation_id) VALUES($1,$2,$3,$4,NOW(),$5,$6)',['TENANT-A',ID.assignment2,ID.bin,'JOB-INTERNAL','USER-A','CORR-2']));await f.app.query("UPDATE atlas_wip_bin_assignments SET status='RELEASED',released_at=NOW(),released_by_user_id='USER-A' WHERE tenant_id='TENANT-A' AND wip_bin_assignment_id=$1",[ID.assignment]);await f.app.query('INSERT INTO atlas_wip_bin_assignments(tenant_id,wip_bin_assignment_id,wip_bin_id,job_id,assigned_at,assigned_by_user_id,correlation_id) VALUES($1,$2,$3,$4,NOW(),$5,$6)',['TENANT-A',ID.assignment2,ID.bin,'JOB-INTERNAL','USER-A','CORR-3']);const rows=(await f.app.query('SELECT job_id,status FROM atlas_wip_bin_assignments WHERE tenant_id=$1 AND wip_bin_id=$2 ORDER BY assigned_at,wip_bin_assignment_id',['TENANT-A',ID.bin])).rows;assert.equal(rows.length,2);assert.deepEqual(new Set(rows.map(x=>x.job_id)),new Set(['JOB-CUSTOMER','JOB-INTERNAL']));assert.equal(rows.filter(x=>x.status==='ACTIVE').length,1);await f.app.close();await f.migration.close();});

test('tenant FKs, active Job uniqueness, canonical IDs and quarantine/retire states fail closed',async()=>{const f=await fixture();await seed(f);await f.app.query('INSERT INTO atlas_wip_bins(tenant_id,wip_bin_id,bin_label,current_location,created_by_user_id) VALUES($1,$2,$3,$4,$5)',['TENANT-A',ID.bin,'BIN-A','HOLD','USER-A']);await f.app.query('INSERT INTO atlas_wip_bins(tenant_id,wip_bin_id,bin_label,current_location,created_by_user_id) VALUES($1,$2,$3,$4,$5)',['TENANT-A',ID.bin2,'BIN-B','RECEIVING','USER-A']);await f.app.query('INSERT INTO atlas_wip_bin_assignments(tenant_id,wip_bin_assignment_id,wip_bin_id,job_id,assigned_at,assigned_by_user_id,correlation_id) VALUES($1,$2,$3,$4,NOW(),$5,$6)',['TENANT-A',ID.assignment,ID.bin,'JOB-CUSTOMER','USER-A','C']);await reject(f.app.query('INSERT INTO atlas_wip_bin_assignments(tenant_id,wip_bin_assignment_id,wip_bin_id,job_id,assigned_at,assigned_by_user_id,correlation_id) VALUES($1,$2,$3,$4,NOW(),$5,$6)',['TENANT-A',ID.assignment2,ID.bin2,'JOB-CUSTOMER','USER-A','C2']));await reject(f.app.query("INSERT INTO atlas_wip_bin_assignments(tenant_id,wip_bin_assignment_id,wip_bin_id,job_id,assigned_at,assigned_by_user_id,correlation_id) VALUES('TENANT-B',$1,$2,'JOB-CUSTOMER',NOW(),'USER-B','X')",['WIP-ASGN-aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','WIP-BIN-bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb']));await reject(f.app.query("INSERT INTO atlas_wip_bins(tenant_id,wip_bin_id,bin_label,current_location,created_by_user_id) VALUES('TENANT-A','bad','BAD','HOLD','USER-A')"));await f.app.close();await f.migration.close();});

test('service hashes QR, rejects browser authority, validates concurrency inputs and normalizes configurable locations',async()=>{const calls=[];const repo={create:async(_s,x)=>{calls.push(x);return x;},createIdentifier:async(_s,x)=>{calls.push(x);return x;},resolveIdentifier:async(_s,h)=>{calls.push(h);return ID.bin;},projection:async()=>({wipBinId:ID.bin})};const service=new WipBinService({repository:repo,clock:()=>new Date('2026-09-01T12:00:00Z')});const created=await service.create(CONTEXT,{wipBinId:ID.bin,binLabel:'BIN 14',currentLocation:'machine queue'});assert.equal(created.currentLocation,'MACHINE_QUEUE');const token='opaque-wip-bin-token';await service.issueIdentifier(CONTEXT,{wipBinIdentifierId:ID.identifier,wipBinId:ID.bin,opaqueToken:token});await service.scan(CONTEXT,token);const hash=createHash('sha256').update(token).digest('hex');assert.equal(calls[1].tokenHash,hash);assert.equal(calls[2],hash);assert.ok(!JSON.stringify(calls).includes(token));await assert.rejects(()=>service.scan({...CONTEXT,capabilities:[]},token),e=>e.code==='FORBIDDEN');await assert.rejects(()=>service.get({...CONTEXT,authoritative:false},ID.bin),e=>e.code==='FORBIDDEN');await assert.rejects(()=>service.release(CONTEXT,{wipBinId:ID.bin,wipBinAssignmentId:ID.assignment,expectedBinVersion:0,expectedAssignmentVersion:1,releaseReason:'done'}),e=>e.code==='INVALID_REQUEST');});

test('provider keeps scan current, history/search bounded, and mutation SQL parameterized',async()=>{const calls=[];const runtime={query:async(sql,values,operation)=>{calls.push({sql,values,operation});if(operation==='WIP_BIN_PROJECTION')return {rowCount:1,rows:[{wip_bin_id:ID.bin,bin_label:'BIN',bin_status:'AVAILABLE',current_location:'RECEIVING',version:1}]};return {rowCount:0,rows:[]};},withTransaction:async(_n,work)=>work({query:runtime.query})};const repo=new PostgresWipBinRepository({runtime});const p=await repo.projection({tenantId:'TENANT-A'},ID.bin);assert.equal(p.readiness,'EMPTY');assert.match(calls[0].sql,/status='ACTIVE'/);assert.match(calls[0].sql,/LATERAL/);await repo.search({tenantId:'TENANT-A'},'BIN',25);assert.deepEqual(calls.at(-1).values,['TENANT-A','%BIN%',25]);assert.match(calls.at(-1).sql,/LIMIT \$3/);await repo.history({tenantId:'TENANT-A'},ID.bin,25);assert.match(calls.at(-1).sql,/ASSIGNED/);assert.match(calls.at(-1).sql,/MOVED/);assert.match(calls.at(-1).sql,/LIMIT \$3/);});
