/** MOS-117D Apple/iCloud adapter. It uses a CalDAV-compatible injected gateway and polling, not assumed push APIs. */
function AppleIcloudCalendarProviderAdapter_(gateway,registry){this.gateway=gateway;this.registry=registry||new CalendarProviderRegistry_();}
AppleIcloudCalendarProviderAdapter_.prototype.capabilities=function(){var caps=this.registry.get('APPLE_ICLOUD_CALENDAR');caps.provider='APPLE_ICLOUD_CALENDAR';caps.twoWaySync=caps.supportsTwoWayReschedule;caps.canVersion=caps.supportsVersioning;caps.readOnlyPublication=caps.supportsReadOnlyPublication;return caps;};
AppleIcloudCalendarProviderAdapter_.prototype.discoverCalendars=function(connection){return this.gateway.discoverCalendars({connection:connection});};
AppleIcloudCalendarProviderAdapter_.prototype.upsert=function(payload){var follow=payload.followUp,connection=payload.connection;if(!connection||connection.provider!=='APPLE_ICLOUD_CALENDAR'||!connection.externalCalendarId)throw new VmosConfigurationError_('A connected Apple/iCloud calendar selection is required.');var event={summary:follow.title,startAt:follow.startAt,endAt:follow.endAt,timeZone:follow.timeZone,privateMetadata:{mosFollowUpId:follow.id,mosCorrelationId:payload.correlationId}};return this.gateway.upsertEvent({connection:connection,externalEventId:payload.externalEventId,expectedEtag:payload.expectedExternalVersion,event:event});};
AppleIcloudCalendarProviderAdapter_.prototype.fetchEvent=function(connection,eventId){return this.gateway.fetchEvent({connection:connection,externalEventId:eventId});};
AppleIcloudCalendarProviderAdapter_.prototype.pollChanges=function(connection,cursor){return this.gateway.pollChanges({connection:connection,syncCursor:cursor||''});};
AppleIcloudCalendarProviderAdapter_.prototype.remove=function(payload){if(!this.gateway.deleteEvent)throw new VmosConfigurationError_('Apple/iCloud calendar cleanup is not configured.');return this.gateway.deleteEvent({connection:payload.connection,externalEventId:payload.externalEventId,expectedEtag:payload.expectedExternalVersion,correlationId:payload.correlationId});};
function AppleIcloudCalendarFollowUpService_(deps){this.deps=deps||{};this.followUps=this.deps.followUps;this.links=this.deps.links;this.connections=this.deps.connections;this.routing=this.deps.routing;this.sync=this.deps.sync;this.provider=this.deps.provider;this.clock=this.deps.clock||function(){return new Date();};this.timer=this.deps.timer||function(){return new Date().getTime();};}
AppleIcloudCalendarFollowUpService_.prototype.listCalendars=function(connectionId){var connection=this.connections.get(connectionId);if(!connection||connection.connectionStatus!=='CONNECTED'||connection.provider!=='APPLE_ICLOUD_CALENDAR')return {result:'NOT_CONNECTED',calendars:[]};try{return {result:'OK',calendars:this.provider.discoverCalendars(connection)||[]};}catch(error){this.connections.update(connectionId,{lastError:error.message});return {result:'FAILED',calendars:[],error:error.message};}};
AppleIcloudCalendarFollowUpService_.prototype.project=function(followUpId,correlationId){var follow=this.followUps.repository.get(followUpId);if(this.followUps.schedulingClassification_(follow)!=='SCHEDULED')return {result:'NOT_SCHEDULED',followUpId:followUpId};var route=this.routing.destinationFor(follow);if(route.state!=='CONNECTED'||route.connection.provider!=='APPLE_ICLOUD_CALENDAR')return {result:'NOT_CONNECTED',followUpId:followUpId};return this.sync.syncToExternal(followUpId,correlationId,route.connection);};
AppleIcloudCalendarFollowUpService_.prototype.removeExternalEvent=function(connection,externalEventId,externalVersion,correlationId){try{var response=this.provider.remove({connection:connection,externalEventId:externalEventId,expectedExternalVersion:externalVersion,correlationId:correlationId});return {result:response&&response.notFound?'ALREADY_REMOVED':'REMOVED',externalEventId:externalEventId};}catch(error){return {result:'FAILED',error:error.message,externalEventId:externalEventId};}};
AppleIcloudCalendarFollowUpService_.prototype.removeProjection=function(followUpId,connection,correlationId){var link=this.links.findByFollowUpId(followUpId);if(!link||!link.externalEventId)return {result:'NOT_LINKED'};return this.removeExternalEvent(connection,link.externalEventId,link.externalVersion,correlationId);};
AppleIcloudCalendarFollowUpService_.prototype.reconcileEvent=function(connectionId,externalEventId,correlationId){var connection=this.connections.get(connectionId),link=this.links.findByExternalEvent('APPLE_ICLOUD_CALENDAR',externalEventId);if(!connection||connection.connectionStatus!=='CONNECTED')return {result:'NOT_CONNECTED'};try{var started=this.timer(),event=this.provider.fetchEvent(connection,externalEventId),duration=this.timer()-started;return this.sync.syncFromExternal({provider:'APPLE_ICLOUD_CALENDAR',externalEventId:externalEventId,externalVersion:event&&event.etag||'',changeType:!event||event.deleted?'DELETED':'UPSERT',startAt:event&&event.startAt||'',endAt:event&&event.endAt||'',timeZone:event&&event.timeZone||'',actor:event&&event.actor||'',mosVersion:link&&link.lastSyncedFollowUpVersion,correlationId:correlationId,providerCorrelationId:event&&event.privateMetadata&&event.privateMetadata.mosCorrelationId||'',providerDurationMs:duration});}catch(error){this.connections.update(connectionId,{lastError:error.message,lastSyncAt:this.clock()});return {result:'FAILED',error:error.message};}};
AppleIcloudCalendarFollowUpService_.prototype.poll=function(connectionId,correlationFactory){var connection=this.connections.get(connectionId);if(!connection||connection.connectionStatus!=='CONNECTED')return {result:'NOT_CONNECTED',processed:0};try{var page=this.provider.pollChanges(connection,connection.syncCursor),self=this,processed=[];(page.events||[]).forEach(function(event,index){var correlation=correlationFactory?correlationFactory(event,index):'poll:'+connectionId+':'+event.externalEventId+':'+(event.etag||index);processed.push(self.reconcileEvent(connectionId,event.externalEventId,correlation));});this.connections.update(connectionId,{syncCursor:page.nextSyncCursor||connection.syncCursor,lastSyncAt:this.clock(),lastSuccessfulSyncAt:this.clock(),lastError:''});return {result:'RECOVERED',processed:processed.length,changes:processed};}catch(error){this.connections.update(connectionId,{lastError:error.message,lastSyncAt:this.clock()});return {result:'FAILED',processed:0,error:error.message};}};
