/** MOS-117D Apple/iCloud adapter. It uses a CalDAV-compatible injected gateway and polling, not assumed push APIs. */
function AppleIcloudCalendarProviderAdapter(gateway,registry){this.gateway=gateway;this.registry=registry||new CalendarProviderRegistry();}
AppleIcloudCalendarProviderAdapter.prototype.capabilities=function(){var caps=this.registry.get('APPLE_ICLOUD_CALENDAR');caps.provider='APPLE_ICLOUD_CALENDAR';caps.twoWaySync=caps.supportsTwoWayReschedule;caps.canVersion=caps.supportsVersioning;caps.readOnlyPublication=caps.supportsReadOnlyPublication;return caps;};
AppleIcloudCalendarProviderAdapter.prototype.discoverCalendars=function(connection){return this.gateway.discoverCalendars({connection:connection});};
AppleIcloudCalendarProviderAdapter.prototype.upsert=function(payload){var follow=payload.followUp,connection=payload.connection;if(!connection||connection.provider!=='APPLE_ICLOUD_CALENDAR'||!connection.externalCalendarId)throw new VmosConfigurationError('A connected Apple/iCloud calendar selection is required.');var event={summary:follow.title,startAt:follow.startAt,endAt:follow.endAt,timeZone:follow.timeZone,privateMetadata:{mosFollowUpId:follow.id,mosCorrelationId:payload.correlationId}};return this.gateway.upsertEvent({connection:connection,externalEventId:payload.externalEventId,expectedEtag:payload.expectedExternalVersion,event:event});};
AppleIcloudCalendarProviderAdapter.prototype.fetchEvent=function(connection,eventId){return this.gateway.fetchEvent({connection:connection,externalEventId:eventId});};
AppleIcloudCalendarProviderAdapter.prototype.pollChanges=function(connection,cursor){return this.gateway.pollChanges({connection:connection,syncCursor:cursor||''});};
AppleIcloudCalendarProviderAdapter.prototype.remove=function(payload){if(!this.gateway.deleteEvent)throw new VmosConfigurationError('Apple/iCloud calendar cleanup is not configured.');return this.gateway.deleteEvent({connection:payload.connection,externalEventId:payload.externalEventId,expectedEtag:payload.expectedExternalVersion,correlationId:payload.correlationId});};
function AppleIcloudCalendarFollowUpService(deps){this.deps=deps||{};this.followUps=this.deps.followUps;this.links=this.deps.links;this.connections=this.deps.connections;this.routing=this.deps.routing;this.sync=this.deps.sync;this.provider=this.deps.provider;this.clock=this.deps.clock||function(){return new Date();};}
AppleIcloudCalendarFollowUpService.prototype.listCalendars=function(connectionId){var connection=this.connections.get(connectionId);if(!connection||connection.connectionStatus!=='CONNECTED'||connection.provider!=='APPLE_ICLOUD_CALENDAR')return {result:'NOT_CONNECTED',calendars:[]};try{return {result:'OK',calendars:this.provider.discoverCalendars(connection)||[]};}catch(error){this.connections.update(connectionId,{lastError:error.message});return {result:'FAILED',calendars:[],error:error.message};}};
AppleIcloudCalendarFollowUpService.prototype.project=function(followUpId,correlationId){var follow=this.followUps.repository.get(followUpId);if(this.followUps.schedulingClassification_(follow)!=='SCHEDULED')return {result:'NOT_SCHEDULED',followUpId:followUpId};var route=this.routing.destinationFor(follow);if(route.state!=='CONNECTED'||route.connection.provider!=='APPLE_ICLOUD_CALENDAR')return {result:'NOT_CONNECTED',followUpId:followUpId};return this.sync.syncToExternal(followUpId,correlationId,route.connection);};
AppleIcloudCalendarFollowUpService.prototype.removeExternalEvent=function(connection,externalEventId,externalVersion,correlationId){try{var response=this.provider.remove({connection:connection,externalEventId:externalEventId,expectedExternalVersion:externalVersion,correlationId:correlationId});return {result:response&&response.notFound?'ALREADY_REMOVED':'REMOVED',externalEventId:externalEventId};}catch(error){return {result:'FAILED',error:error.message,externalEventId:externalEventId};}};
AppleIcloudCalendarFollowUpService.prototype.removeProjection=function(followUpId,connection,correlationId){var link=this.links.findByFollowUpId(followUpId);if(!link||!link.externalEventId)return {result:'NOT_LINKED'};return this.removeExternalEvent(connection,link.externalEventId,link.externalVersion,correlationId);};
AppleIcloudCalendarFollowUpService.prototype.reconcileEvent=function(connectionId,externalEventId,correlationId){var connection=this.connections.get(connectionId),link=this.links.findByExternalEvent('APPLE_ICLOUD_CALENDAR',externalEventId);if(!connection||connection.connectionStatus!=='CONNECTED')return {result:'NOT_CONNECTED'};try{var event=this.provider.fetchEvent(connection,externalEventId);if(event&&event.privateMetadata&&event.privateMetadata.mosCorrelationId&&link&&event.privateMetadata.mosCorrelationId===link.lastCorrelationId)return {result:'IGNORED',details:'Loop prevented.'};if(!event||event.deleted)return this.sync.syncFromExternal({provider:'APPLE_ICLOUD_CALENDAR',externalEventId:externalEventId,externalVersion:event&&event.etag||'',changeType:'DELETED',mosVersion:link&&link.lastSyncedFollowUpVersion,correlationId:correlationId});return this.sync.syncFromExternal({provider:'APPLE_ICLOUD_CALENDAR',externalEventId:externalEventId,externalVersion:event.etag||'',changeType:'UPSERT',startAt:event.startAt,endAt:event.endAt,timeZone:event.timeZone,actor:event.actor||'',mosVersion:link&&link.lastSyncedFollowUpVersion,correlationId:correlationId});}catch(error){this.connections.update(connectionId,{lastError:error.message,lastSyncAt:this.clock()});return {result:'FAILED',error:error.message};}};
AppleIcloudCalendarFollowUpService.prototype.poll=function(connectionId,correlationFactory){var connection=this.connections.get(connectionId);if(!connection||connection.connectionStatus!=='CONNECTED')return {result:'NOT_CONNECTED',processed:0};try{var page=this.provider.pollChanges(connection,connection.syncCursor),self=this,processed=[];(page.events||[]).forEach(function(event,index){var correlation=correlationFactory?correlationFactory(event,index):'poll:'+connectionId+':'+event.externalEventId+':'+(event.etag||index);processed.push(self.reconcileEvent(connectionId,event.externalEventId,correlation));});this.connections.update(connectionId,{syncCursor:page.nextSyncCursor||connection.syncCursor,lastSyncAt:this.clock(),lastSuccessfulSyncAt:this.clock(),lastError:''});return {result:'RECOVERED',processed:processed.length,changes:processed};}catch(error){this.connections.update(connectionId,{lastError:error.message,lastSyncAt:this.clock()});return {result:'FAILED',processed:0,error:error.message};}};
