/** Manual ADMIN_CONFIG diagnostic. It reports safe activation state, never records or changes configuration. */
function AtlasActivationHealthService_(dependencies){dependencies=dependencies||{};this.identityConfig=dependencies.identityConfig||getAtlasIdentityConfig_;this.memberships=dependencies.memberships||new TenantMembershipRepository_();this.navigation=dependencies.navigation||new AtlasNavigationService_();this.followUps=dependencies.followUps;this.purchases=dependencies.purchases;this.calendarRequests=dependencies.calendarRequests;this.calendarConfig=dependencies.calendarConfig||getCalendarFollowUpConfig_;this.diagnostic=dependencies.diagnostic||function(entry){try{console.warn(JSON.stringify(entry));}catch(ignored){}};}
AtlasActivationHealthService_.prototype.get=function(context){
  if(!context||context.authoritative!==true)throw new VmosAuthorizationError_('Authoritative administrator identity is required.');
  var config=this.identityConfig(),membership=this.memberships.findActive(context.tenantId,context.userId);
  if(!membership)throw new VmosAuthorizationError_('Active tenant membership is required.');
  var self=this,capabilities=(context.capabilities||[]).slice(),roles=parseIdentityList_(membership.roles),recognizedRoles=roles.filter(function(role){return Object.prototype.hasOwnProperty.call(ATLAS_DEFAULT_ROLE_CAPABILITIES,role);});
  function eligible(){for(var index=0;index<arguments.length;index+=1)if(capabilities.indexOf(arguments[index])!==-1)return true;return false;}
  function probe(name,allowed,reader){if(!allowed)return 'NOT_AUTHORIZED';try{var rows=reader()||[];return rows.length?'READY':'EMPTY';}catch(error){self.diagnostic({event:'ATLAS_ACTIVATION_SOURCE_UNAVAILABLE',correlationId:String(context.correlationId||''),source:name,category:String(error&&error.code||'SOURCE_READ_FAILED')});return 'SOURCE_UNAVAILABLE';}}
  var calendarConfig;try{calendarConfig=this.calendarConfig();}catch(error){calendarConfig=null;}
  var calendarState=!eligible('CALENDAR_RECONCILE')?'NOT_AUTHORIZED':!calendarConfig?'SOURCE_UNAVAILABLE':!calendarConfig.enabled?'DISABLED':!(calendarConfig.provider&&calendarConfig.calendarId)?'NOT_CONFIGURED':probe('Calendar review',true,function(){return (self.calendarRequests||new ExternalChangeRequestRepository_()).list();});
  var navigation=this.navigation.getModel(context,'home'),navigationCount=navigation.groups.reduce(function(total,group){return total+(group.items||[]).length;},0);
  return serializeVmosValue_({enforcementMode:config.mode,principalResolved:true,atlasUserResolved:true,tenantResolved:Boolean(context.tenantId),activeMembership:true,recognizedRoles:recognizedRoles,unrecognizedRoleCount:roles.length-recognizedRoles.length,capabilityCount:capabilities.length,capabilities:capabilities.slice().sort(),navigationItemCount:navigationCount,sources:{followUps:probe('Follow-Ups',eligible('FOLLOWUP_READ'),function(){return (self.followUps||new FollowUpRepository_()).list();}),purchasing:probe('Purchasing',eligible('PURCHASE_APPROVE','PURCHASE_REQUEST'),function(){return (self.purchases||new PurchaseApprovalService_()).list();}),calendarReview:calendarState}});
};
