function atlasAuthRandom_(bytes){var chunks=[];while(chunks.join('').length<bytes*2)chunks.push(Utilities.getUuid().replace(/-/g,''));return chunks.join('').slice(0,bytes*2);}
function atlasAuthHash_(value){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,String(value),Utilities.Charset.UTF_8).map(function(v){return ('0'+(v<0?v+256:v).toString(16)).slice(-2);}).join('');}
function atlasAuthB64_(hex){var bytes=[];for(var i=0;i<hex.length;i+=2)bytes.push(parseInt(hex.slice(i,i+2),16));return Utilities.base64EncodeWebSafe(bytes).replace(/=+$/,'');}
function safeAtlasReturnRoute_(route,config){route=String(route||'home').trim().toLowerCase();if(!/^[a-z0-9-]+$/.test(route)||(config.allowedReturnRoutes||[]).indexOf(route)===-1)return 'home';return route;}
function AtlasAuthenticationStateStore_(dependencies){dependencies=dependencies||{};this.cache=dependencies.cache||CacheService.getScriptCache();this.clock=dependencies.clock||function(){return new Date();};this.timeoutSeconds=Number(dependencies.timeoutSeconds||300);this.lock=dependencies.lock||(typeof LockService!=='undefined'?LockService.getScriptLock():null);}
AtlasAuthenticationStateStore_.prototype.flowKey_=function(flowId){return 'ATLAS_AUTH_FLOW:'+atlasAuthHash_(flowId||'');};
AtlasAuthenticationStateStore_.prototype.stateKey_=function(stateHash){return 'ATLAS_AUTH_STATE:'+stateHash;};
AtlasAuthenticationStateStore_.prototype.withLock_=function(operation){if(this.lock)this.lock.waitLock(5000);try{return operation();}finally{if(this.lock)this.lock.releaseLock();}};
AtlasAuthenticationStateStore_.prototype.create=function(provider,returnRoute,redirectUri,flowId){var self=this;if(!/^[A-Za-z0-9_-]{32,128}$/.test(String(flowId||'')))throw new VmosAuthorizationError_('Sign-in request could not be started.');return this.withLock_(function(){var flowKey=self.flowKey_(flowId),priorHash=self.cache.get(flowKey);if(priorHash)self.cache.remove(self.stateKey_(priorHash));var state=atlasAuthRandom_(32),stateHash=atlasAuthHash_(state),nonce=atlasAuthRandom_(32),verifier=atlasAuthRandom_(48),now=self.clock(),record={provider:provider,state:state,nonce:nonce,verifier:verifier,flowId:flowId,returnRoute:returnRoute,redirectUri:redirectUri,createdAt:now.toISOString(),expiresAt:new Date(now.getTime()+self.timeoutSeconds*1000).toISOString()};self.cache.put(self.stateKey_(stateHash),JSON.stringify(record),self.timeoutSeconds);self.cache.put(flowKey,stateHash,self.timeoutSeconds);return record;});};
AtlasAuthenticationStateStore_.prototype.consume=function(state,flowId){var self=this;return this.withLock_(function(){var stateHash=atlasAuthHash_(state||''),stateKey=self.stateKey_(stateHash),flowKey=self.flowKey_(flowId),currentHash=self.cache.get(flowKey),raw=self.cache.get(stateKey);if(currentHash&&currentHash!==stateHash){self.cache.remove(stateKey);throw new VmosAuthorizationError_('Sign-in request expired or was replaced.');}self.cache.remove(stateKey);self.cache.remove(flowKey);if(!raw)throw new VmosAuthorizationError_('Sign-in request expired or was already used.');var record=JSON.parse(raw);if(record.state!==state||record.flowId!==flowId||new Date(record.expiresAt)<=self.clock())throw new VmosAuthorizationError_('Sign-in request could not be verified.');return record;});};
AtlasAuthenticationStateStore_.prototype.abort=function(flowId,state){var self=this;return this.withLock_(function(){var flowKey=self.flowKey_(flowId),currentHash=self.cache.get(flowKey),suppliedHash=state?atlasAuthHash_(state):'';if(currentHash&&(!suppliedHash||currentHash===suppliedHash)){self.cache.remove(self.stateKey_(currentHash));self.cache.remove(flowKey);}if(suppliedHash)self.cache.remove(self.stateKey_(suppliedHash));return {state:'SIGNED_OUT'};});};
function AtlasOidcAdapter_(config,dependencies){dependencies=dependencies||{};this.config=config;this.gateway=dependencies.gateway;this.clock=dependencies.clock||function(){return new Date();};}
AtlasOidcAdapter_.prototype.authorizationUrl=function(state){if(!this.config.enabled||!this.config.clientId)throw new VmosConfigurationError_('This sign-in provider is not configured.');var challenge=atlasAuthB64_(atlasAuthHash_(state.verifier));var q={client_id:this.config.clientId,response_type:'code',redirect_uri:state.redirectUri,scope:this.config.scopes.join(' '),state:state.state,nonce:state.nonce,code_challenge:challenge,code_challenge_method:'S256',prompt:'select_account'};return this.config.authorizationEndpoint+'?'+Object.keys(q).map(function(k){return encodeURIComponent(k)+'='+encodeURIComponent(q[k]);}).join('&');};
AtlasOidcAdapter_.prototype.complete=function(payload,state){if(!payload||!payload.code||!this.gateway)throw new VmosAuthorizationError_('Sign-in response could not be verified.');var claims=this.gateway.verify({provider:this.config.provider,code:String(payload.code),redirectUri:state.redirectUri,pkceVerifier:state.verifier,expectedNonce:state.nonce});return this.validateClaims_(claims,state.nonce);};
AtlasOidcAdapter_.prototype.validateClaims_=function(claims,nonce){var now=Math.floor(this.clock().getTime()/1000);if(!claims||claims.signatureVerified!==true)throw new VmosAuthorizationError_('Provider identity could not be verified.');if(this.config.issuers.indexOf(String(claims.iss))===-1)throw new VmosAuthorizationError_('Provider identity could not be verified.');var audiences=Array.isArray(claims.aud)?claims.aud:[claims.aud];if(audiences.map(String).indexOf(this.config.clientId)===-1||(audiences.length>1&&String(claims.azp)!==this.config.clientId))throw new VmosAuthorizationError_('Provider identity could not be verified.');if(!claims.sub||String(claims.nonce)!==String(nonce)||Number(claims.exp)<=now||Number(claims.nbf||0)>now+60||Number(claims.iat||0)>now+60)throw new VmosAuthorizationError_('Provider identity could not be verified.');if(this.config.provider==='MICROSOFT'&&!this.config.allowPersonalAccounts&&claims.accountType==='PERSONAL')throw new VmosAuthorizationError_('This Microsoft account type is unavailable.');var domains=this.config.allowedDomains||[],domain=String(claims.hd||'').toLowerCase();if(domains.length&&domains.indexOf(domain)===-1)throw new VmosAuthorizationError_('This organization account is unavailable.');return Object.freeze({type:this.config.provider+'_OIDC',provider:this.config.provider,issuer:String(claims.iss),subject:String(claims.sub),email:String(claims.email||''),displayName:String(claims.name||''),authenticatedAt:new Date(Number(claims.auth_time||now)*1000),verified:true});};
function ExternalOidcVerificationGateway_(config){this.url=config.verificationGatewayUrl;}
ExternalOidcVerificationGateway_.prototype.verify=function(request){if(!this.url)throw new VmosError_('Identity provider verification is unavailable.','PROVIDER_UNAVAILABLE');var response=UrlFetchApp.fetch(this.url,{method:'post',contentType:'application/json',payload:JSON.stringify(request),muteHttpExceptions:true});if(response.getResponseCode()!==200)throw new VmosError_('Identity provider verification is unavailable.','PROVIDER_UNAVAILABLE');return JSON.parse(response.getContentText());};
function AtlasSessionService_(dependencies){dependencies=dependencies||{};this.sessions=dependencies.sessions||new AtlasAuthSessionRepository_();this.clock=dependencies.clock||function(){return new Date();};this.uuid=dependencies.uuid||function(){return Utilities.getUuid().toUpperCase();};this.policy=dependencies.policy||getAtlasAuthenticationConfig_().session;}
AtlasSessionService_.prototype.create=function(principal,userId,tenantIds,selectedTenant){var raw=atlasAuthRandom_(48),now=this.clock(),expires=new Date(now.getTime()+this.policy.lifetimeSeconds*1000),record={id:'SESSION-'+this.uuid(),tokenHash:atlasAuthHash_(raw),userId:userId,provider:principal.provider,issuer:principal.issuer,subject:principal.subject,tenantId:selectedTenant||'',permittedTenants:JSON.stringify(tenantIds),issuedAt:now,expiresAt:expires,authenticatedAt:principal.authenticatedAt||now,revokedAt:'',status:selectedTenant?'ACTIVE':'PENDING_TENANT',createdAt:now,updatedAt:now};this.sessions.create(record);return {token:raw,sessionId:record.id,userId:userId,tenantId:record.tenantId,tenantSelectionRequired:!record.tenantId,expiresAt:expires,authenticatedAt:record.authenticatedAt};};
AtlasSessionService_.prototype.resolveAny_=function(token){var row=this.sessions.findByTokenHash(atlasAuthHash_(token||'')),now=this.clock(),status=String(row&&row.status||'').toUpperCase();if(!row||['ACTIVE','PENDING_TENANT'].indexOf(status)===-1||row.revokedAt||new Date(row.expiresAt)<=now)throw new VmosAuthorizationError_('Atlas session is unavailable or expired.');return row;};
AtlasSessionService_.prototype.resolve=function(token){var row=this.resolveAny_(token);if(String(row.status).toUpperCase()!=='ACTIVE'||!row.tenantId)throw new VmosAuthorizationError_('Atlas session is not active.');return row;};
AtlasSessionService_.prototype.revoke=function(token){var row=this.resolveAny_(token);this.sessions.update(row.id,{status:'REVOKED',revokedAt:this.clock(),updatedAt:this.clock()});return {signedOut:true,providerLogoutPerformed:false};};
AtlasSessionService_.prototype.selectTenant=function(token,tenantId,memberships){var row=this.resolveAny_(token),allowed=JSON.parse(row.permittedTenants||'[]');if(allowed.indexOf(tenantId)===-1||!memberships.findActive(tenantId,row.userId))throw new VmosAuthorizationError_('Tenant access is unavailable.');this.sessions.update(row.id,{tenantId:tenantId,status:'ACTIVE',updatedAt:this.clock()});return {tenantId:tenantId};};
AtlasSessionService_.prototype.requiresRecentAuthentication=function(row){return this.clock().getTime()-new Date(row.authenticatedAt).getTime()>this.policy.recentAuthSeconds*1000;};
function AtlasApplicationSessionPrincipalResolver_(sessions,tokenProvider){this.sessions=sessions||new AtlasSessionService_();this.tokenProvider=tokenProvider;}
AtlasApplicationSessionPrincipalResolver_.prototype.resolve=function(){var row=this.sessions.resolve(this.tokenProvider());return Object.freeze({type:row.provider+'_OIDC',provider:row.provider,issuer:row.issuer,subject:row.subject,sessionId:row.id,authenticatedAt:row.authenticatedAt,verified:true});};
function AtlasAuthenticationService_(dependencies){dependencies=dependencies||{};this.config=dependencies.config||getAtlasAuthenticationConfig_();this.states=dependencies.states||new AtlasAuthenticationStateStore_({timeoutSeconds:this.config.transactionTimeoutSeconds});this.identities=dependencies.identities||new ExternalIdentityReferenceRepository_();this.users=dependencies.users||new AtlasUserRepository_();this.memberships=dependencies.memberships||new TenantMembershipRepository_();this.tenants=dependencies.tenants||(typeof AtlasTenantRepository_!=='undefined'?new AtlasTenantRepository_():{list:function(){return[];}});this.sessions=dependencies.sessions||new AtlasSessionService_();this.entitlements=dependencies.entitlements||(typeof CommercialEntitlementService_!=='undefined'?new CommercialEntitlementService_():{assertAllowed:function(){throw new VmosAuthorizationError_('Commercial entitlement is unavailable.');}});this.gateway=dependencies.gateway||new ExternalOidcVerificationGateway_(this.config);this.clock=dependencies.clock||function(){return new Date();};}
AtlasAuthenticationService_.prototype.configuration=function(){var self=this;return {providers:['MICROSOFT','GOOGLE'].filter(function(k){return self.config.providers[k].enabled;}).map(function(k){return {id:k,label:k==='MICROSOFT'?'Continue with Microsoft':'Continue with Google'};}),sessionLifetimeSeconds:this.config.session.lifetimeSeconds,transactionTimeoutSeconds:this.config.transactionTimeoutSeconds};};
AtlasAuthenticationService_.prototype.begin=function(provider,returnRoute,flowId){provider=String(provider||'').toUpperCase();var cfg=this.config.providers[provider];if(!cfg||!cfg.enabled)throw new VmosConfigurationError_('This sign-in provider is not configured.');var route=safeAtlasReturnRoute_(returnRoute,this.config),state=this.states.create(provider,route,this.config.redirectUri,flowId),adapter=new AtlasOidcAdapter_(cfg,{gateway:this.gateway,clock:this.clock});return {authorizationUrl:adapter.authorizationUrl(state),state:state.state,flowId:flowId,transactionTimeoutSeconds:this.config.transactionTimeoutSeconds};};
AtlasAuthenticationService_.prototype.abort=function(flowId,state){return this.states.abort(String(flowId||''),String(state||''));};
AtlasAuthenticationService_.prototype.complete=function(payload){var state=this.states.consume(String(payload&&payload.state||''),String(payload&&payload.flowId||'')),cfg=this.config.providers[state.provider],principal=new AtlasOidcAdapter_(cfg,{gateway:this.gateway,clock:this.clock}).complete(payload,state),ref=this.identities.findActiveIdentity?this.identities.findActiveIdentity(principal.provider,principal.issuer,principal.subject):null;if(!ref)return {state:'IDENTITY_NOT_PROVISIONED'};var user=this.users.get(ref.userId);if(!user||String(user.status).toUpperCase()!=='ACTIVE')return {state:'MEMBERSHIP_INACTIVE'};var self=this,active=(this.memberships.list()||[]).filter(function(m){return String(m.userId)===String(user.id)&&String(m.status).toUpperCase()==='ACTIVE';});if(!active.length)return {state:'MEMBERSHIP_INACTIVE'};var tenantIds=active.map(function(m){return String(m.tenantId);}).filter(function(id){try{self.entitlements.assertAllowed({tenantId:id,userId:user.id,operation:'SIGN_IN'});return true;}catch(ignored){return false;}});if(!tenantIds.length)return {state:'COMMERCIAL_ACCESS_RESTRICTED'};var selected=tenantIds.length===1?tenantIds[0]:'',session=this.sessions.create(principal,user.id,tenantIds,selected),names={};(this.tenants.list()||[]).forEach(function(t){if(tenantIds.indexOf(String(t.id))!==-1)names[String(t.id)]=String(t.displayName||t.name||'Authorized organization');});return {state:selected?'SIGNED_IN':'TENANT_SELECTION_REQUIRED',session:session,tenantOptions:tenantIds.map(function(id){return {id:id,label:names[id]||'Authorized organization'};}),returnRoute:safeAtlasReturnRoute_(state.returnRoute,this.config)};};
function AtlasAccountLinkingService_(dependencies){dependencies=dependencies||{};this.identities=dependencies.identities||new ExternalIdentityReferenceRepository_();this.clock=dependencies.clock||function(){return new Date();};this.uuid=dependencies.uuid||function(){return Utilities.getUuid().toUpperCase();};}
AtlasAccountLinkingService_.prototype.link=function(context,principal,sessionService,sessionRecord){if(!context||!context.authoritative||!principal||!principal.verified||!sessionService||sessionService.requiresRecentAuthentication(sessionRecord))throw new VmosAuthorizationError_('Recent authentication is required.');var existing=this.identities.findActiveIdentity(principal.provider,principal.issuer,principal.subject);if(existing)throw new VmosConflictError('This provider identity is already linked.');return this.identities.create({id:'IDENTITY-'+this.uuid(),userId:context.userId,provider:principal.provider,issuer:principal.issuer,subject:principal.subject,status:'ACTIVE',createdAt:this.clock(),updatedAt:this.clock()});};
