/** MOS-117A provider metadata and connection model. No provider API is implemented here. */
var VMOS_CALENDAR_PROVIDER_CAPABILITIES={
  GOOGLE_CALENDAR:{providerKey:'GOOGLE_CALENDAR',canCreate:true,canUpdate:true,canObserveChanges:true,canObserveDeletion:true,supportsTwoWayReschedule:true,supportsPushNotifications:true,supportsDeltaSync:false,supportsPolling:true,supportsVersioning:true,supportsReadOnlyPublication:false},
  MICROSOFT_GRAPH_CALENDAR:{providerKey:'MICROSOFT_GRAPH_CALENDAR',canCreate:true,canUpdate:true,canObserveChanges:true,canObserveDeletion:true,supportsTwoWayReschedule:true,supportsPushNotifications:true,supportsDeltaSync:true,supportsPolling:true,supportsVersioning:true,supportsReadOnlyPublication:false},
  APPLE_ICLOUD_CALENDAR:{providerKey:'APPLE_ICLOUD_CALENDAR',canCreate:false,canUpdate:false,canObserveChanges:false,canObserveDeletion:false,supportsTwoWayReschedule:false,supportsPushNotifications:false,supportsDeltaSync:false,supportsPolling:true,supportsVersioning:false,supportsReadOnlyPublication:false},
  ICAL_PUBLICATION:{providerKey:'ICAL_PUBLICATION',canCreate:false,canUpdate:false,canObserveChanges:false,canObserveDeletion:false,supportsTwoWayReschedule:false,supportsPushNotifications:false,supportsDeltaSync:false,supportsPolling:false,supportsVersioning:false,supportsReadOnlyPublication:true}
};
function CalendarProviderRegistry(definitions){this.definitions=definitions||VMOS_CALENDAR_PROVIDER_CAPABILITIES;}
CalendarProviderRegistry.prototype.list=function(){var self=this;return Object.keys(this.definitions).map(function(key){return self.get(key);});};
CalendarProviderRegistry.prototype.get=function(providerKey){var definition=this.definitions[providerKey];if(!definition)throw new VmosValidationError('Unsupported calendar provider: '+providerKey+'.');var copy={};Object.keys(definition).forEach(function(key){copy[key]=definition[key];});return copy;};
CalendarProviderRegistry.prototype.isWritable=function(providerKey){var caps=this.get(providerKey);return caps.canCreate&&caps.canUpdate&&!caps.supportsReadOnlyPublication;};
function CalendarConnectionService(deps){this.deps=deps||{};this.repository=this.deps.repository;this.registry=this.deps.registry||new CalendarProviderRegistry();this.clock=this.deps.clock||function(){return new Date();};this.id=this.deps.id||function(prefix){return prefix+'-'+Utilities.getUuid().toUpperCase();};}
CalendarConnectionService.prototype.create=function(input){input=input||{};if(!input.userId||!input.provider)throw new VmosValidationError('User and calendar provider are required.');this.assertNoRawCredentials_(input);var caps=this.registry.get(input.provider),now=this.clock(),record={id:this.id('UCC'),userId:input.userId,provider:caps.providerKey,externalAccountId:input.externalAccountId||'',externalAccountDisplayName:input.externalAccountDisplayName||'',externalCalendarId:input.externalCalendarId||'',externalCalendarDisplayName:input.externalCalendarDisplayName||'',connectionStatus:input.connectionStatus||'NOT_CONNECTED',capabilitiesJson:JSON.stringify(caps),credentialReference:input.credentialReference||'',tokenExpiresAt:input.tokenExpiresAt||'',syncCursor:input.syncCursor||'',subscriptionId:input.subscriptionId||'',subscriptionExpiresAt:input.subscriptionExpiresAt||'',lastSyncAt:'',lastSuccessfulSyncAt:'',lastError:'',createdAt:now,updatedAt:now};return this.repository.create(record);};
CalendarConnectionService.prototype.get=function(id){return this.repository.get(id);};
CalendarConnectionService.prototype.update=function(id,changes){this.assertNoRawCredentials_(changes||{});var record=this.repository.get(id);if(!record)throw new VmosNotFoundError('Calendar connection not found.');Object.keys(changes||{}).forEach(function(key){if(['id','userId','provider','credentialReference','createdAt'].indexOf(key)===-1)record[key]=changes[key];});record.updatedAt=this.clock();return this.repository.update(id,record);};
CalendarConnectionService.prototype.resolveWritableForOwner=function(ownerUserId){var connections=this.repository.listByUserId(ownerUserId),self=this,match=connections.filter(function(connection){return connection.connectionStatus==='CONNECTED'&&self.registry.isWritable(connection.provider);})[0];return match?{state:'CONNECTED',connection:match}:{state:'NOT_CONNECTED',connection:null};};
CalendarConnectionService.prototype.assertNoRawCredentials_=function(input){['refreshToken','accessToken','password','appSpecificPassword','providerSecret','secret'].forEach(function(key){if(Object.prototype.hasOwnProperty.call(input,key))throw new VmosValidationError('Raw calendar credentials must not be persisted. Use CredentialReference.');});};
function FollowUpCalendarRoutingService(connections){this.connections=connections;}
FollowUpCalendarRoutingService.prototype.destinationFor=function(followUp){if(!followUp||!followUp.ownerUserId)throw new VmosValidationError('Follow-up owner is required for calendar routing.');return this.connections.resolveWritableForOwner(followUp.ownerUserId);};
