var ATLAS_PRODUCTION_READINESS=['READY','MISSING','UNKNOWN'];
var ATLAS_PRODUCTION_COMPLETE_STATUSES=['COMPLETE','COMPLETED','CLOSED','CANCELLED','CANCELED'];

function getAtlasBusinessTimeZone_(){var value='';try{value=PropertiesService.getScriptProperties().getProperty('ATLAS_BUSINESS_TIME_ZONE')||'';}catch(ignored){}return value||(Session.getScriptTimeZone?Session.getScriptTimeZone():'Etc/UTC')||'Etc/UTC';}
function dailyProductionDateKey_(value,timeZone){if(!value)return '';if(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value.trim()))return value.trim();var date=new Date(value);if(isNaN(date.getTime()))return '';if(typeof Utilities!=='undefined'&&Utilities.formatDate)return Utilities.formatDate(date,timeZone,'yyyy-MM-dd');return date.toISOString().slice(0,10);}
function dailyProductionSerial_(key){var p=String(key).split('-').map(Number);return Date.UTC(p[0],p[1]-1,p[2])/86400000;}
function dailyProductionBucket_(dueValue,now,timeZone){var dueKey=dailyProductionDateKey_(dueValue,timeZone),todayKey=dailyProductionDateKey_(now,timeZone);if(!dueKey||!todayKey)return '';var difference=dailyProductionSerial_(dueKey)-dailyProductionSerial_(todayKey);if(difference<0)return 'OVERDUE';if(difference===0){if(!(typeof dueValue==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(dueValue.trim()))&&new Date(dueValue).getTime()<new Date(now).getTime())return 'OVERDUE';return 'DUE_TODAY';}if(difference===1)return 'DUE_TOMORROW';var weekday=new Date(dailyProductionSerial_(todayKey)*86400000).getUTCDay(),daysThroughSunday=weekday===0?0:7-weekday;return difference<=daysThroughSunday?'THIS_WEEK':'';}
function dailyProductionReadiness_(job){var material=String(job.materialReadiness||'UNKNOWN').toUpperCase(),tooling=String(job.toolingReadiness||'UNKNOWN').toUpperCase(),blocked=job.blockerActive===true||String(job.blockerActive).toUpperCase()==='TRUE'||!!String(job.blockerReason||'').trim();if(material==='MISSING'||tooling==='MISSING'||blocked)return 'BLOCKED';if(material==='READY'&&tooling==='READY')return 'READY';return 'AT_RISK';}

function DailyProductionReadService_(dependencies){dependencies=dependencies||{};this.jobs=dependencies.jobs||new MvpService_('Job');this.customers=dependencies.customers||new MvpService_('Customer');this.users=dependencies.users||new AtlasUserRepository_();this.memberships=dependencies.memberships||new TenantMembershipRepository_();this.clock=dependencies.clock||function(){return new Date();};this.timeZone=dependencies.timeZone||getAtlasBusinessTimeZone_();this.limit=Math.min(200,Math.max(1,Number(dependencies.limit||100)));}
DailyProductionReadService_.prototype.get=function(context){var customerMap={},userMap={},tenant=String(context.tenantId),self=this,now=this.clock();(this.customers.list()||[]).filter(function(row){return String(row.securityTenantId)===tenant;}).forEach(function(row){customerMap[row.id]=row.name||row.companyName||row.id;});var activeUsers={};(this.memberships.list()||[]).filter(function(row){return String(row.tenantId)===tenant&&String(row.status).toUpperCase()==='ACTIVE';}).forEach(function(row){activeUsers[row.userId]=true;});(this.users.list()||[]).forEach(function(row){if(activeUsers[row.id]&&String(row.status||'ACTIVE').toUpperCase()==='ACTIVE')userMap[row.id]=row.displayName||row.id;});var buckets={OVERDUE:[],DUE_TODAY:[],DUE_TOMORROW:[],THIS_WEEK:[]},matching=0;
  (this.jobs.list()||[]).forEach(function(job){if(String(job.securityTenantId)!==tenant||ATLAS_PRODUCTION_COMPLETE_STATUSES.indexOf(String(job.status||'').toUpperCase())!==-1||!job.dueDate)return;var bucket=dailyProductionBucket_(job.dueDate,now,self.timeZone);if(!bucket)return;matching++;if(buckets[bucket].length>=self.limit)return;var materials=ATLAS_PRODUCTION_READINESS.indexOf(String(job.materialReadiness||'').toUpperCase())!==-1?String(job.materialReadiness).toUpperCase():'UNKNOWN',tooling=ATLAS_PRODUCTION_READINESS.indexOf(String(job.toolingReadiness||'').toUpperCase())!==-1?String(job.toolingReadiness).toUpperCase():'UNKNOWN';buckets[bucket].push({id:job.id,customerName:customerMap[job.customerId]||'Customer unavailable',description:job.description||job.partId||'Service details unavailable',dueDate:job.dueDate,ownerUserId:job.ownerUserId||job.operator||'',ownerName:userMap[job.ownerUserId||job.operator]||job.ownerUserId||job.operator||'Unassigned',currentOperation:job.currentOperation||job.program||'Not started',status:job.status||'Not started',blocker:job.blockerReason||'',materials:materials,tooling:tooling,readiness:dailyProductionReadiness_(job),version:Number(job.version||0),href:'?route=jobs&id='+encodeURIComponent(job.id)});});
  Object.keys(buckets).forEach(function(key){buckets[key].sort(function(a,b){var priority={BLOCKED:0,AT_RISK:1,READY:2};return priority[a.readiness]-priority[b.readiness]||String(a.dueDate).localeCompare(String(b.dueDate))||String(a.id).localeCompare(String(b.id));});});
  return serializeVmosValue_({generatedAt:now,timeZone:this.timeZone,buckets:buckets,owners:Object.keys(userMap).map(function(id){return {id:id,label:userMap[id]};}).sort(function(a,b){return a.label.localeCompare(b.label);}),totalMatching:matching,resultCount:Object.keys(buckets).reduce(function(sum,key){return sum+buckets[key].length;},0),truncated:matching>Object.keys(buckets).reduce(function(sum,key){return sum+buckets[key].length;},0),bounds:{perBucket:this.limit},repositoryReads:4});};

function DailyProductionMutationService_(dependencies){dependencies=dependencies||{};this.jobs=dependencies.jobs||new MvpService_('Job');this.auditUser=dependencies.auditUser||getVmosAuditUser_;this.mutationProof=dependencies.mutationProof||null;}
DailyProductionMutationService_.prototype.update=function(jobId,changes,expectedVersion,context){changes=changes||{};var job=this.jobs.get(jobId);if(!job||String(job.securityTenantId)!==String(context.tenantId))throw new VmosAuthorizationError_('Work Order is unavailable.');var version=Number(job.version||0);if(Number(expectedVersion)!==version)throw new VmosConflictError('Work Order changed. Refresh and try again.');var allowed=['ownerUserId','currentOperation','status','materialReadiness','toolingReadiness','blockerReason'],update={};Object.keys(changes).forEach(function(key){if(allowed.indexOf(key)===-1)throw new VmosValidationError_('Production update contains an unsupported field.');update[key]=changes[key];});['materialReadiness','toolingReadiness'].forEach(function(key){if(Object.prototype.hasOwnProperty.call(update,key)){update[key]=String(update[key]||'').toUpperCase();if(ATLAS_PRODUCTION_READINESS.indexOf(update[key])===-1)throw new VmosValidationError_('Readiness must be READY, MISSING, or UNKNOWN.');}});if(Object.prototype.hasOwnProperty.call(update,'blockerReason')){update.blockerReason=String(update.blockerReason||'').trim();update.blockerActive=!!update.blockerReason;}if(Object.prototype.hasOwnProperty.call(update,'status')){update.status=String(update.status||'').trim();if(!update.status)throw new VmosValidationError_('Production status is required.');}if(Object.prototype.hasOwnProperty.call(update,'ownerUserId')&&update.ownerUserId){var membership=new TenantMembershipRepository_().findActive(context.tenantId,update.ownerUserId);if(!membership)throw new VmosValidationError_('Choose an active tenant member.');}update.version=version+1;var service=new MvpService_('Job',{repository:this.jobs.repository||this.jobs,auditUser:function(){return context.userId;},mutationProof:this.mutationProof});return service.update(jobId,update);};
