/** Bounded, read-only current-state projection for shared operational displays. */
function FloorBoardService_(dependencies){dependencies=dependencies||{};this.jobs=dependencies.jobs||new MvpService_('Job');this.customers=dependencies.customers||new MvpService_('Customer');this.tokens=dependencies.tokens||new JobQrTokenRepository_();this.events=dependencies.events||new JobEventRepository_();this.clock=dependencies.clock||function(){return new Date();};this.limit=Math.min(200,Math.max(1,Number(dependencies.limit||120)));}
FloorBoardService_.prototype.get=function(cursor){var now=this.clock(),customers=floorBoardIndex_(this.customers.list()),activeTokens={};this.tokens.list().forEach(function(token){if(token.jobId&&!token.revokedAt&&!activeTokens[token.jobId])activeTokens[token.jobId]=token;});var latest={};this.events.list().forEach(function(event){if(!event.jobId)return;var prior=latest[event.jobId];if(!prior||String(event.occurredAt||'')>String(prior.occurredAt||''))latest[event.jobId]=event;});var self=this,items=this.jobs.list().map(function(job){return self.project_(job,customers[job.customerId]||{},activeTokens[job.id],latest[job.id],now);}).filter(function(item){return item.lane!=='COMPLETE'||item.recentlyCompleted;});items.sort(floorBoardSort_);var total=items.length;items=items.slice(0,this.limit);var revision=floorBoardRevision_(items),same=String(cursor||'')===revision;return serializeVmosValue_({mode:same?'DELTA':'SNAPSHOT',revision:revision,asOf:now,staleAfterSeconds:120,fullRefreshRequired:!!cursor&&!same,changes:same?[]:items.map(function(item){return {type:'UPSERT',revision:revision,item:item};}),items:same?[]:items,totalMatching:total,resultCount:items.length,truncated:total>items.length,repositoryReads:4});};
FloorBoardService_.prototype.project_=function(job,customer,token,event,now){var status=normalizeDashboardText_(job.status),lane=floorBoardLane_(status),changed=event&&event.occurredAt||job.updatedAt||job.createdAt||'';return {id:job.id,customerName:customer.name||customer.companyName||job.customerId||'Customer unavailable',description:job.description||job.partId||'Work description unavailable',partId:job.partId||'',status:job.status||'Unclassified',lane:lane,machine:job.machine||event&&event.machine||'',operator:job.operator||'',workflowId:token&&token.workflowId||'',changedAt:changed,ageLabel:floorBoardAge_(changed,now),recentlyAdded:floorBoardWithin_(job.createdAt,now,24),recentlyCompleted:lane==='COMPLETE'&&floorBoardWithin_(changed,now,24),problemReason:lane==='BLOCKED'&&event?(event.notes||event.problemType||'Attention required'):'',href:'?route=job&jobId='+encodeURIComponent(job.id)};};
function floorBoardLane_(status){status=normalizeDashboardText_(status);if(['BLOCKED','PROBLEM','STOPPED'].indexOf(status)!==-1)return 'BLOCKED';if(['RUNNING','IN PROCESS','IN_PROCESS','ACTIVE'].indexOf(status)!==-1)return 'IN_PROCESS';if(['READY','PLANNED','QUEUED'].indexOf(status)!==-1)return 'READY';if(['WAITING','ON HOLD','ON_HOLD','PENDING'].indexOf(status)!==-1)return 'WAITING';if(['COMPLETE','COMPLETED','CANCELLED'].indexOf(status)!==-1)return 'COMPLETE';return 'NEW';}
function floorBoardWithin_(value,now,hours){var time=new Date(value||0).getTime();return !!time&&new Date(now).getTime()-time<=hours*3600000;}
function floorBoardAge_(value,now){var time=new Date(value||0).getTime();if(!time)return 'Time unavailable';var minutes=Math.max(0,Math.floor((new Date(now).getTime()-time)/60000));if(minutes<60)return minutes+'m';var hours=Math.floor(minutes/60);return hours<48?hours+'h':Math.floor(hours/24)+'d';}
function floorBoardIndex_(rows){return (rows||[]).reduce(function(index,row){if(row.id)index[row.id]=row;return index;},{});}
function floorBoardSort_(a,b){var order={BLOCKED:0,IN_PROCESS:1,READY:2,WAITING:3,NEW:4,COMPLETE:5},difference=order[a.lane]-order[b.lane];return difference||String(b.changedAt||'').localeCompare(String(a.changedAt||''))||String(a.id).localeCompare(String(b.id));}
function floorBoardRevision_(items){var source=items.map(function(item){return [item.id,item.status,item.changedAt,item.workflowId].join('|');}).join('\n');if(typeof Utilities!=='undefined'&&Utilities.computeDigest){var bytes=Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,source,Utilities.Charset.UTF_8);return bytes.slice(0,8).map(function(value){var normalized=value<0?value+256:value;return ('0'+normalized.toString(16)).slice(-2);}).join('');}var hash=0;for(var index=0;index<source.length;index+=1)hash=((hash<<5)-hash+source.charCodeAt(index))|0;return 'r'+Math.abs(hash);}
