/** Generic MOS follow-up lifecycle; calendar providers are optional adapters. */
var FOLLOW_UP_STATUSES=['OPEN','COMPLETED','CANCELLED'];
function FollowUpService(deps){this.deps=deps||{};this.repository=this.deps.repository;this.events=this.deps.events;this.clock=this.deps.clock||function(){return new Date();};this.id=this.deps.id||function(prefix){return prefix+'-'+Utilities.getUuid().toUpperCase();};}
function createFollowUpService_(){return new FollowUpService({repository:new FollowUpRepository(),events:new FollowUpEventRepository()});}
FollowUpService.prototype.create=function(input,actor){if(!input||!input.customerId||!input.title||!input.dueAt||!input.ownerUserId)throw new VmosValidationError('Customer, title, due date, and owner are required.');this.assertSchedule_(input);var now=this.clock(),record={id:this.id('FUP'),customerId:input.customerId,salesActivityId:input.salesActivityId||'',title:input.title,dueAt:new Date(input.dueAt),startAt:input.startAt?new Date(input.startAt):'',endAt:input.endAt?new Date(input.endAt):'',timeZone:input.timeZone||'',ownerUserId:input.ownerUserId,status:'OPEN',version:1,createdAt:now,updatedAt:now,completedAt:'',cancelledAt:''};this.repository.create(record);this.event_(record,'CREATED',actor,'',0,1,this.schedulingClassification_(record));return record;};
FollowUpService.prototype.reschedule=function(id,dueAt,expectedVersion,actor,correlationId){var record=this.repository.get(id);this.assertOpen_(record);if(Number(record.version)!==Number(expectedVersion))throw new VmosValidationError('Follow-up changed elsewhere; refresh before rescheduling.');var previous=record.version;record.dueAt=new Date(dueAt);record.version=previous+1;record.updatedAt=this.clock();this.repository.update(id,record);this.event_(record,'RESCHEDULED',actor,correlationId,previous,record.version,'');return record;};
FollowUpService.prototype.schedule=function(id,schedule,expectedVersion,actor,correlationId){var record=this.repository.get(id);this.assertOpen_(record);if(Number(record.version)!==Number(expectedVersion))throw new VmosValidationError('Follow-up changed elsewhere; refresh before scheduling.');this.assertSchedule_(schedule||{});if(!schedule.startAt)throw new VmosValidationError('Start At, End At, and Time Zone are required for a scheduled calendar block.');var previous=record.version;record.startAt=new Date(schedule.startAt);record.endAt=new Date(schedule.endAt);record.timeZone=schedule.timeZone;record.version=previous+1;record.updatedAt=this.clock();this.repository.update(id,record);this.event_(record,'SCHEDULED',actor,correlationId,previous,record.version,this.schedulingClassification_(record));return record;};
FollowUpService.prototype.complete=function(id,expectedVersion,actor,correlationId){return this.close_(id,'COMPLETED',expectedVersion,actor,correlationId);};
FollowUpService.prototype.cancel=function(id,expectedVersion,actor,correlationId){return this.close_(id,'CANCELLED',expectedVersion,actor,correlationId);};
FollowUpService.prototype.close_=function(id,status,expectedVersion,actor,correlationId){var record=this.repository.get(id);this.assertOpen_(record);if(Number(record.version)!==Number(expectedVersion))throw new VmosValidationError('Follow-up changed elsewhere; refresh before closing.');var previous=record.version;record.status=status;record.version=previous+1;record.updatedAt=this.clock();if(status==='COMPLETED')record.completedAt=record.updatedAt;else record.cancelledAt=record.updatedAt;this.repository.update(id,record);this.event_(record,status,actor,correlationId,previous,record.version,'');return record;};
FollowUpService.prototype.assertOpen_=function(record){if(!record)throw new VmosNotFoundError('Follow-up not found.');if(record.status!=='OPEN')throw new VmosValidationError('Only open follow-ups can be changed.');};
FollowUpService.prototype.assertSchedule_=function(input){var hasStart=!!input.startAt,hasEnd=!!input.endAt,hasZone=!!input.timeZone;if(!hasStart&&!hasEnd&&!hasZone)return; if(!hasStart||!hasEnd||!hasZone)throw new VmosValidationError('Start At, End At, and Time Zone must be supplied together.');var start=new Date(input.startAt),end=new Date(input.endAt);if(isNaN(start.getTime())||isNaN(end.getTime())||end<=start)throw new VmosValidationError('Scheduled calendar blocks require a valid end after start.');if(!/^[A-Za-z][A-Za-z0-9_+.-]*(?:\/[A-Za-z0-9_+.-]+)+$/.test(String(input.timeZone)))throw new VmosValidationError('Time Zone must be an IANA identifier such as America/Los_Angeles.');};
FollowUpService.prototype.schedulingClassification_=function(record){return record&&record.startAt&&record.endAt&&record.timeZone?'SCHEDULED':'LEGACY_DEADLINE_ONLY';};
FollowUpService.prototype.event_=function(record,type,actor,correlationId,previousVersion,newVersion,details){this.events.append({id:this.id('FUE'),followUpId:record.id,eventType:type,occurredAt:this.clock(),actor:actor||'MOS',correlationId:correlationId||'',previousVersion:previousVersion,newVersion:newVersion,details:details||''});};

/** Provider capabilities make iCal publication visibly read-only. */
function GoogleCalendarFollowUpAdapter(gateway){this.gateway=gateway;}
GoogleCalendarFollowUpAdapter.prototype.capabilities=function(){return {provider:'GOOGLE_CALENDAR',providerKey:'GOOGLE_CALENDAR',twoWaySync:true,canCreate:true,canUpdate:true,canObserveChanges:true,canObserveDeletion:true,canVersion:true,supportsTwoWayReschedule:true,supportsPushNotifications:true,supportsDeltaSync:false,supportsPolling:true,supportsVersioning:true,supportsReadOnlyPublication:false,readOnlyPublication:false};};
GoogleCalendarFollowUpAdapter.prototype.upsert=function(payload){return this.gateway.upsert(payload);};
function IcalFollowUpPublicationAdapter(gateway){this.gateway=gateway;}
IcalFollowUpPublicationAdapter.prototype.capabilities=function(){return {provider:'ICAL_PUBLICATION',providerKey:'ICAL_PUBLICATION',twoWaySync:false,canCreate:false,canUpdate:false,canObserveChanges:false,canObserveDeletion:false,canVersion:false,supportsTwoWayReschedule:false,supportsPushNotifications:false,supportsDeltaSync:false,supportsPolling:false,supportsVersioning:false,supportsReadOnlyPublication:true,readOnlyPublication:true};};
IcalFollowUpPublicationAdapter.prototype.publish=function(payload){return this.gateway.publish(payload);};

function CalendarFollowUpSyncService(deps){this.deps=deps||{};this.followUps=this.deps.followUps;this.links=this.deps.links;this.requests=this.deps.requests;this.syncEvents=this.deps.syncEvents;this.provider=this.deps.provider;this.clock=this.deps.clock||function(){return new Date();};this.id=this.deps.id||function(prefix){return prefix+'-'+Utilities.getUuid().toUpperCase();};}
CalendarFollowUpSyncService.prototype.assertTwoWay_=function(){var caps=this.provider.capabilities();if(!caps.twoWaySync)throw new VmosConfigurationError(caps.provider+' is read-only publication, not two-way synchronization.');return caps;};
CalendarFollowUpSyncService.prototype.requestFields_=function(change){return {requestedDueAt:change.dueAt||'',requestedStartAt:change.startAt||'',requestedEndAt:change.endAt||'',requestedTimeZone:change.timeZone||''};};
CalendarFollowUpSyncService.prototype.syncFromExternal=function(change){this.assertTwoWay_();if(!change||!change.correlationId||!change.externalEventId)throw new VmosValidationError('Calendar change requires external event and correlation IDs.');var prior=this.syncEvents.findByCorrelation(change.provider,change.correlationId);if(prior)return prior;var link=this.links.findByExternalEvent(change.provider,change.externalEventId);if(!link)return this.record_(change,'IGNORED','No linked MOS follow-up.');if(link.lastCorrelationId===change.correlationId)return this.record_(change,'IGNORED','Loop prevented.');if(change.changeType==='DELETED'){var deletion=this.requestFields_(change),request=this.requests.create({id:this.id('ECR'),provider:change.provider,followUpId:link.followUpId,externalEventId:change.externalEventId,changeType:'DELETED',requestedDueAt:deletion.requestedDueAt,requestedStartAt:deletion.requestedStartAt,requestedEndAt:deletion.requestedEndAt,requestedTimeZone:deletion.requestedTimeZone,externalVersion:change.externalVersion||'',status:'PENDING_REVIEW',details:'Calendar event was deleted externally.',detectedAt:this.clock(),resolvedAt:'',resolvedBy:'',resolution:''});return this.record_(change,'REVIEW_REQUIRED',request.id);}
var follow=this.followUps.repository.get(link.followUpId);if(change.mosVersion!==undefined&&Number(change.mosVersion)!==Number(follow.version)){var fields=this.requestFields_(change),conflict=this.requests.create({id:this.id('ECR'),provider:change.provider,followUpId:link.followUpId,externalEventId:change.externalEventId,changeType:'CONFLICT',requestedDueAt:fields.requestedDueAt,requestedStartAt:fields.requestedStartAt,requestedEndAt:fields.requestedEndAt,requestedTimeZone:fields.requestedTimeZone,externalVersion:change.externalVersion||'',status:'PENDING_REVIEW',details:'MOS version differs from calendar change.',detectedAt:this.clock(),resolvedAt:'',resolvedBy:'',resolution:''});return this.record_(change,'CONFLICT',conflict.id);}
var updated=change.startAt||change.endAt||change.timeZone?this.followUps.schedule(follow.id,{startAt:change.startAt,endAt:change.endAt,timeZone:change.timeZone},follow.version,'CALENDAR:'+change.provider,change.correlationId):this.followUps.reschedule(follow.id,change.dueAt,follow.version,'CALENDAR:'+change.provider,change.correlationId);link.externalVersion=change.externalVersion||link.externalVersion;link.lastCorrelationId=change.correlationId;link.lastSyncOrigin='CALENDAR';link.lastSyncedFollowUpVersion=updated.version;link.updatedAt=this.clock();this.links.update(link.id,link);return this.record_(change,'APPLIED',updated.id);};
CalendarFollowUpSyncService.prototype.syncToExternal=function(followUpId,correlationId){this.assertTwoWay_();var follow=this.followUps.repository.get(followUpId);if(this.followUps.schedulingClassification_(follow)!=='SCHEDULED')throw new VmosValidationError('A deadline-only FollowUp must be given a Start At, End At, and Time Zone before calendar projection.');var link=this.links.findByFollowUpId(followUpId),payload={followUp:follow,externalEventId:link&&link.externalEventId||'',correlationId:correlationId};try{var result=this.provider.upsert(payload),saved=link||{id:this.id('FCL'),followUpId:followUpId,connectionId:'',provider:this.provider.capabilities().provider,calendarId:'',externalEventId:'',externalVersion:'',lastSyncOrigin:'',lastCorrelationId:'',lastSyncedFollowUpVersion:0,createdAt:this.clock()};saved.externalEventId=result.externalEventId;saved.externalVersion=result.externalVersion||'';saved.lastCorrelationId=correlationId;saved.lastSyncOrigin='MOS';saved.lastSyncedFollowUpVersion=follow.version;saved.updatedAt=this.clock();if(link)this.links.update(saved.id,saved);else this.links.create(saved);return this.record_({provider:saved.provider,correlationId:correlationId,externalEventId:saved.externalEventId},'PUSHED',followUpId);}catch(error){return this.record_({provider:this.provider.capabilities().provider,correlationId:correlationId,externalEventId:''},'FAILED',error.message);}};
CalendarFollowUpSyncService.prototype.resolveExternalChange=function(requestId,action,actor,dueAt){var request=this.requests.get(requestId);if(!request||request.status!=='PENDING_REVIEW')throw new VmosValidationError('External change request is not pending.');var follow=this.followUps.repository.get(request.followUpId),updated=follow;if(action==='RESCHEDULE')updated=this.followUps.reschedule(follow.id,dueAt,follow.version,actor,'review:'+requestId);else if(action==='MARK_COMPLETE')updated=this.followUps.complete(follow.id,follow.version,actor,'review:'+requestId);else if(action==='CANCEL_FOLLOW_UP')updated=this.followUps.cancel(follow.id,follow.version,actor,'review:'+requestId);else if(action!=='KEEP_FOLLOW_UP')throw new VmosValidationError('Select Keep, Reschedule, Mark Complete, or Cancel Follow-up.');request.status='RESOLVED';request.resolvedAt=this.clock();request.resolvedBy=actor;request.resolution=action;this.requests.update(request.id,request);return updated;};
CalendarFollowUpSyncService.prototype.record_=function(change,result,details){var event={id:this.id('CSE'),provider:change.provider||'',externalEventId:change.externalEventId||'',correlationId:change.correlationId||'',result:result,details:details||'',occurredAt:this.clock()};this.syncEvents.append(event);return event;};
