/** MOS-117B Google adapter. The injected gateway is the only provider boundary. */
function GoogleCalendarProviderAdapter(gateway){this.gateway=gateway;}
GoogleCalendarProviderAdapter.prototype.capabilities=function(){return new GoogleCalendarFollowUpAdapter(this.gateway).capabilities();};
GoogleCalendarProviderAdapter.prototype.upsert=function(payload){var follow=payload.followUp,connection=payload.connection;if(!connection||connection.provider!=='GOOGLE_CALENDAR'||!connection.externalCalendarId)throw new VmosConfigurationError('A connected Google calendar selection is required.');var event={summary:follow.title,startAt:follow.startAt,endAt:follow.endAt,timeZone:follow.timeZone,extendedPrivate:{mosFollowUpId:follow.id,mosCorrelationId:payload.correlationId}};return this.gateway.upsertEvent({connection:connection,externalEventId:payload.externalEventId,expectedEtag:payload.expectedExternalVersion,event:event});};
GoogleCalendarProviderAdapter.prototype.fetchEvent=function(connection,eventId){return this.gateway.fetchEvent({connection:connection,externalEventId:eventId});};
GoogleCalendarProviderAdapter.prototype.listChanges=function(connection,cursor){return this.gateway.listChanges({connection:connection,syncCursor:cursor||''});};
GoogleCalendarProviderAdapter.prototype.createOrRenewWatch=function(connection){return this.gateway.createOrRenewWatch({connection:connection});};
function GoogleCalendarFollowUpService(deps){this.deps=deps||{};this.followUps=this.deps.followUps;this.links=this.deps.links;this.connections=this.deps.connections;this.routing=this.deps.routing;this.sync=this.deps.sync;this.provider=this.deps.provider;this.clock=this.deps.clock||function(){return new Date();};}
GoogleCalendarFollowUpService.prototype.project=function(followUpId,correlationId){var follow=this.followUps.repository.get(followUpId);if(this.followUps.schedulingClassification_(follow)!=='SCHEDULED')return {result:'NOT_SCHEDULED',followUpId:followUpId};var route=this.routing.destinationFor(follow);if(route.state!=='CONNECTED'||route.connection.provider!=='GOOGLE_CALENDAR')return {result:'NOT_CONNECTED',followUpId:followUpId};return this.sync.syncToExternal(followUpId,correlationId,route.connection);};
GoogleCalendarFollowUpService.prototype.handleWatchSignal=function(connectionId,externalEventId,correlationId){var connection=this.connections.get(connectionId),link=this.links.findByExternalEvent('GOOGLE_CALENDAR',externalEventId);if(!connection||connection.connectionStatus!=='CONNECTED')return {result:'NOT_CONNECTED'};var event=this.provider.fetchEvent(connection,externalEventId);if(event&&event.extendedPrivate&&event.extendedPrivate.mosCorrelationId&&link&&event.extendedPrivate.mosCorrelationId===link.lastCorrelationId)return {result:'IGNORED',details:'Loop prevented.'};if(!event||event.deleted)return this.sync.syncFromExternal({provider:'GOOGLE_CALENDAR',externalEventId:externalEventId,externalVersion:event&&event.etag||'',changeType:'DELETED',mosVersion:link&&link.lastSyncedFollowUpVersion,correlationId:correlationId});return this.sync.syncFromExternal({provider:'GOOGLE_CALENDAR',externalEventId:externalEventId,externalVersion:event.etag||'',changeType:'UPSERT',startAt:event.startAt,endAt:event.endAt,timeZone:event.timeZone,actor:event.actor||'',mosVersion:link&&link.lastSyncedFollowUpVersion,correlationId:correlationId});};
GoogleCalendarFollowUpService.prototype.recover=function(connectionId,correlationFactory){var connection=this.connections.get(connectionId);if(!connection||connection.connectionStatus!=='CONNECTED')return {result:'NOT_CONNECTED',processed:0};var page=this.provider.listChanges(connection,connection.syncCursor),self=this,processed=[];(page.events||[]).forEach(function(event,index){var correlation=correlationFactory?correlationFactory(event,index):'recovery:'+connectionId+':'+event.externalEventId+':'+(event.etag||index);processed.push(self.handleWatchSignal(connectionId,event.externalEventId,correlation));});this.connections.update(connectionId,{syncCursor:page.nextSyncCursor||connection.syncCursor,lastSyncAt:this.clock(),lastSuccessfulSyncAt:this.clock(),lastError:''});return {result:'RECOVERED',processed:processed.length,changes:processed};};
GoogleCalendarFollowUpService.prototype.renewWatch=function(connectionId){var connection=this.connections.get(connectionId);if(!connection||connection.connectionStatus!=='CONNECTED')return {result:'NOT_CONNECTED'};try{var watch=this.provider.createOrRenewWatch(connection);return this.connections.update(connectionId,{subscriptionId:watch.subscriptionId||'',subscriptionExpiresAt:watch.expiresAt||'',lastError:''});}catch(error){this.connections.update(connectionId,{lastError:error.message});return {result:'FAILED',error:error.message};}};
