/** MOS-117B Google adapter. The injected gateway is the only provider boundary. */
function GoogleCalendarProviderAdapter_(gateway){this.gateway=gateway;}
GoogleCalendarProviderAdapter_.prototype.capabilities=function(){return new GoogleCalendarFollowUpAdapter_(this.gateway).capabilities();};
GoogleCalendarProviderAdapter_.prototype.upsert=function(payload){var follow=payload.followUp,connection=payload.connection;if(!connection||connection.provider!=='GOOGLE_CALENDAR'||!connection.externalCalendarId)throw new VmosConfigurationError_('A connected Google calendar selection is required.');var event={summary:follow.title,startAt:follow.startAt,endAt:follow.endAt,timeZone:follow.timeZone,extendedPrivate:{mosFollowUpId:follow.id,mosCorrelationId:payload.correlationId}};return this.gateway.upsertEvent({connection:connection,externalEventId:payload.externalEventId,expectedEtag:payload.expectedExternalVersion,event:event});};
GoogleCalendarProviderAdapter_.prototype.fetchEvent=function(connection,eventId){return this.gateway.fetchEvent({connection:connection,externalEventId:eventId});};
GoogleCalendarProviderAdapter_.prototype.listChanges=function(connection,cursor){return this.gateway.listChanges({connection:connection,syncCursor:cursor||''});};
GoogleCalendarProviderAdapter_.prototype.createOrRenewWatch=function(connection){return this.gateway.createOrRenewWatch({connection:connection});};
GoogleCalendarProviderAdapter_.prototype.remove=function(payload){if(!this.gateway.deleteEvent)throw new VmosConfigurationError_('Google calendar cleanup is not configured.');return this.gateway.deleteEvent({connection:payload.connection,externalEventId:payload.externalEventId,expectedEtag:payload.expectedExternalVersion,correlationId:payload.correlationId});};
function GoogleCalendarFollowUpService_(deps){this.deps=deps||{};this.followUps=this.deps.followUps;this.links=this.deps.links;this.connections=this.deps.connections;this.routing=this.deps.routing;this.sync=this.deps.sync;this.provider=this.deps.provider;this.clock=this.deps.clock||function(){return new Date();};this.timer=this.deps.timer||function(){return new Date().getTime();};}
GoogleCalendarFollowUpService_.prototype.project=function(followUpId,correlationId){var follow=this.followUps.repository.get(followUpId);if(this.followUps.schedulingClassification_(follow)!=='SCHEDULED')return {result:'NOT_SCHEDULED',followUpId:followUpId};var route=this.routing.destinationFor(follow);if(route.state!=='CONNECTED'||route.connection.provider!=='GOOGLE_CALENDAR')return {result:'NOT_CONNECTED',followUpId:followUpId};return this.sync.syncToExternal(followUpId,correlationId,route.connection);};
GoogleCalendarFollowUpService_.prototype.removeExternalEvent=function(connection,externalEventId,externalVersion,correlationId){try{var response=this.provider.remove({connection:connection,externalEventId:externalEventId,expectedExternalVersion:externalVersion,correlationId:correlationId});return {result:response&&response.notFound?'ALREADY_REMOVED':'REMOVED',externalEventId:externalEventId};}catch(error){return {result:'FAILED',error:error.message,externalEventId:externalEventId};}};
GoogleCalendarFollowUpService_.prototype.removeProjection=function(followUpId,connection,correlationId){var link=this.links.findByFollowUpId(followUpId);if(!link||!link.externalEventId)return {result:'NOT_LINKED'};return this.removeExternalEvent(connection,link.externalEventId,link.externalVersion,correlationId);};
GoogleCalendarFollowUpService_.prototype.handleWatchSignal=function(connectionId,externalEventId,correlationId){var connection=this.connections.get(connectionId),link=this.links.findByExternalEvent('GOOGLE_CALENDAR',externalEventId);if(!connection||connection.connectionStatus!=='CONNECTED')return {result:'NOT_CONNECTED'};var started=this.timer(),event=this.provider.fetchEvent(connection,externalEventId),duration=this.timer()-started,change={provider:'GOOGLE_CALENDAR',externalEventId:externalEventId,externalVersion:event&&event.etag||'',changeType:!event||event.deleted?'DELETED':'UPSERT',startAt:event&&event.startAt||'',endAt:event&&event.endAt||'',timeZone:event&&event.timeZone||'',actor:event&&event.actor||'',mosVersion:link&&link.lastSyncedFollowUpVersion,correlationId:correlationId,providerCorrelationId:event&&event.extendedPrivate&&event.extendedPrivate.mosCorrelationId||'',providerDurationMs:duration};return this.sync.syncFromExternal(change);};
GoogleCalendarFollowUpService_.prototype.recover=function(connectionId,correlationFactory){var connection=this.connections.get(connectionId);if(!connection||connection.connectionStatus!=='CONNECTED')return {result:'NOT_CONNECTED',processed:0};var page=this.provider.listChanges(connection,connection.syncCursor),self=this,processed=[];(page.events||[]).forEach(function(event,index){var correlation=correlationFactory?correlationFactory(event,index):'recovery:'+connectionId+':'+event.externalEventId+':'+(event.etag||index);processed.push(self.handleWatchSignal(connectionId,event.externalEventId,correlation));});this.connections.update(connectionId,{syncCursor:page.nextSyncCursor||connection.syncCursor,lastSyncAt:this.clock(),lastSuccessfulSyncAt:this.clock(),lastError:''});return {result:'RECOVERED',processed:processed.length,changes:processed};};
GoogleCalendarFollowUpService_.prototype.renewWatch=function(connectionId){var connection=this.connections.get(connectionId);if(!connection||connection.connectionStatus!=='CONNECTED')return {result:'NOT_CONNECTED'};try{var watch=this.provider.createOrRenewWatch(connection);return this.connections.update(connectionId,{subscriptionId:watch.subscriptionId||'',subscriptionExpiresAt:watch.expiresAt||'',lastError:''});}catch(error){this.connections.update(connectionId,{lastError:error.message});return {result:'FAILED',error:error.message};}};
