/** Bounded, capability-projected read model for the Job / Work Order canvas. */
function JobCanvasService_(dependencies){
  dependencies=dependencies||{};
  this.jobs=dependencies.jobs||new MvpService_('Job');this.customers=dependencies.customers||new MvpService_('Customer');this.quotes=dependencies.quotes||new MvpService_('Quote');this.rfqs=dependencies.rfqs||new MvpService_('RFQ');this.invoices=dependencies.invoices||new MvpService_('Invoice');
  this.revisions=dependencies.revisions||(typeof QuoteRevisionRepository_!=='undefined'?new QuoteRevisionRepository_():null);this.events=dependencies.events||(typeof JobEventRepository_!=='undefined'?new JobEventRepository_():null);this.tokens=dependencies.tokens||(typeof JobQrTokenRepository_!=='undefined'?new JobQrTokenRepository_():null);
  this.purchases=dependencies.purchases||null;this.vendors=dependencies.vendors||(typeof VendorRepository_!=='undefined'?new VendorRepository_():null);this.sourceLinks=dependencies.sourceLinks||(typeof QuoteSourceDocumentLinkRepository_!=='undefined'?new QuoteSourceDocumentLinkRepository_():null);this.documents=dependencies.documents||(typeof SourceDocumentRepository_!=='undefined'?new SourceDocumentRepository_():null);
  this.receipts=dependencies.receipts||(typeof CashReceiptRepository_!=='undefined'?new CashReceiptRepository_():null);this.firearms=dependencies.firearms||(typeof SerializedFirearmRepository_!=='undefined'?new SerializedFirearmRepository_():null);this.users=dependencies.users||(typeof AtlasUserRepository_!=='undefined'?new AtlasUserRepository_():null);this.memberships=dependencies.memberships||(typeof TenantMembershipRepository_!=='undefined'?new TenantMembershipRepository_():null);this.workflow=dependencies.workflow||(typeof getShopWorkflow_!=='undefined'?getShopWorkflow_:function(){return null;});
  this.limits={purchases:20,documents:25,invoices:10,receipts:25,firearms:10,history:30};
}
JobCanvasService_.prototype.has_=function(context,capability){return (context.capabilities||[]).indexOf(capability)!==-1;};
JobCanvasService_.prototype.tenant_=function(row,context,label){if(!row||String(row.securityTenantId||row.tenantId)!==String(context.tenantId))throw new VmosAuthorizationError_((label||'Record')+' is unavailable.');return row;};
JobCanvasService_.prototype.safe_=function(name,reader,failures){try{return reader();}catch(error){failures.push({section:name,message:name+' is temporarily unavailable. Retry this section without leaving the Work Order.'});return null;}};
JobCanvasService_.prototype.href_=function(route,id){var key={customers:'id',rfqs:'id',quotes:'quoteId',purchasing:'id',invoices:'id',firearms:'id'}[route]||'id';return '?route='+route+(id?'&'+key+'='+encodeURIComponent(id):'');};
JobCanvasService_.prototype.get=function(jobId,context){
  if(!jobId)throw new VmosValidationError_('Choose a Work Order.');
  var self=this,job=this.tenant_(this.jobs.get(jobId),context,'Work Order'),failures=[],caps=context.capabilities||[],tenant=String(context.tenantId),customer=this.safe_('Customer',function(){return self.tenant_(self.customers.get(job.customerId),context,'Customer');},failures),quote=job.quoteId?this.safe_('Commercial',function(){return self.tenant_(self.quotes.get(job.quoteId),context,'Quote');},failures):null,rfq=null,accepted=null;
  if(quote&&quote.rfqId)rfq=this.safe_('Commercial',function(){return self.tenant_(self.rfqs.get(quote.rfqId),context,'RFQ');},failures);if(job.acceptedQuoteRevisionId&&this.revisions)accepted=this.safe_('Commercial',function(){return self.tenant_(self.revisions.get(job.acceptedQuoteRevisionId),context,'Accepted Quote revision');},failures);
  var ownerLabel=job.ownerUserId||job.operator||'Unassigned';this.safe_('Owner',function(){var active={};(self.memberships?self.memberships.list():[]).filter(function(row){return String(row.tenantId)===tenant&&String(row.status||'ACTIVE').toUpperCase()==='ACTIVE';}).forEach(function(row){active[row.userId]=true;});(self.users?self.users.list():[]).some(function(row){if(active[row.id]&&String(row.id)===String(job.ownerUserId||job.operator)){ownerLabel=row.displayName||ownerLabel;return true;}return false;});if((job.ownerUserId||job.operator)&&!active[job.ownerUserId||job.operator])ownerLabel='Referenced owner unavailable';return active;},failures);
  var workflowId='',operationOptions=[];this.safe_('Production',function(){var token=(self.tokens?self.tokens.findActiveByJobId(job.id):[])[0];workflowId=token&&token.workflowId||'';var flow=workflowId?self.workflow(workflowId):null;operationOptions=flow?(flow.states||[]).map(function(value){return {id:value,label:String(value).replace(/_/g,' ')};}):[];return flow;},failures);
  var readiness=typeof dailyProductionReadiness_==='function'?dailyProductionReadiness_(job):'UNKNOWN',blocked=!!String(job.blockerReason||'').trim()||job.blockerActive===true;
  var commercial=this.has_(context,'RFQ_READ')?{customer:customer?{id:customer.id,label:customer.name||customer.companyName||'Customer'}:{id:job.customerId,label:'Referenced Customer unavailable',referenceState:'UNAVAILABLE'},rfq:rfq?{id:rfq.id,label:rfq.customerRfqNumber||rfq.description||'RFQ',status:rfq.status||''}:null,quote:quote?{id:quote.id,label:quote.quoteNumber||'Quote '+quote.id,status:quote.status||'',href:this.href_('quotes',quote.id)}:null,acceptedRevision:accepted?{id:accepted.id,label:'Revision '+accepted.revisionNumber,status:accepted.status||'ACCEPTED'}:(job.acceptedQuoteRevisionId?{id:job.acceptedQuoteRevisionId,label:'Accepted revision unavailable',referenceState:'UNAVAILABLE'}:null)}:null;
  var production={currentOperation:job.currentOperation||job.status||'Not started',status:job.status||'Not started',workflowId:workflowId,operationOptions:operationOptions,owner:{id:job.ownerUserId||job.operator||'',label:ownerLabel},materialReadiness:job.materialReadiness||'UNKNOWN',toolingReadiness:job.toolingReadiness||'UNKNOWN',readiness:readiness,blocker:job.blockerReason||'',links:{dailyProduction:'?route=daily-production&jobId='+encodeURIComponent(job.id),shopFloor:'?route=shop-floor&jobId='+encodeURIComponent(job.id)}};
  var purchasing=null;if(this.has_(context,'PURCHASE_REQUEST')||this.has_(context,'PURCHASE_APPROVE'))purchasing=this.safe_('Purchasing',function(){var service=self.purchases||new PurchaseApprovalService_(undefined,undefined,function(){return context.userId;},undefined,undefined,undefined,self.vendors,context,self.jobs),result=service.listForJob(job.id,self.limits.purchases);return {items:result.items.map(function(row){return {id:row.id,label:row.description||'Purchase Request '+row.id,status:row.status||'',approvalState:row.approvalRequired?'Approval required':'No approval required',receiptState:row.receiptReference?'Received':'Not received',vendorLabel:row.vendor||'Referenced Vendor unavailable',href:self.href_('purchasing',row.id)};}),bound:result.bound,hasMore:result.hasMore,createHref:self.has_(context,'PURCHASE_REQUEST')?'?route=purchasing&jobId='+encodeURIComponent(job.id):'',emptyMessage:'No canonically linked Purchase Requests. Create one from this Work Order when purchasing is required.'};},failures);
  var documents=null;if(this.has_(context,'QUOTE_COST_READ'))documents=this.safe_('Documents',function(){var links=job.quoteId?(self.sourceLinks?self.sourceLinks.byField(context.tenantId,'quoteId',job.quoteId,self.limits.documents):[]):[],documentIds={},cache={};links=links.filter(function(row){var keep=String(row.status||'ACTIVE').toUpperCase()==='ACTIVE'&&(String(row.jobId||'')===String(job.id)||String(row.relationshipType||'').toUpperCase()!=='JOB');if(keep)documentIds[String(row.documentId)]=true;return keep;}).slice(0,self.limits.documents);(self.documents?self.documents.forTenant(context.tenantId):[]).forEach(function(document){if(documentIds[String(document.id)])cache[String(document.id)]=document;});return {items:links.map(function(link){var doc=cache[String(link.documentId)]||null;return {id:link.id,documentId:link.documentId,label:doc&&doc.title||'Referenced document unavailable',type:doc&&doc.documentType||'',purpose:link.purpose||'',visibility:link.visibility||'INTERNAL',referenceState:doc?'AVAILABLE':'UNAVAILABLE'};}),bound:self.limits.documents};},failures);
  var billing=null;if(this.has_(context,'FINANCE_READ')||this.has_(context,'FINANCE_WRITE'))billing=this.safe_('Billing',function(){var invoices=(self.invoices.listByField('jobId',job.id,self.limits.invoices)||[]).filter(function(row){return String(row.securityTenantId||row.tenantId)===tenant;}).slice(0,self.limits.invoices),receiptRows=self.receipts?self.receipts.list():[];return {items:invoices.map(function(invoice){var receipts=receiptRows.filter(function(row){return String(row.securityTenantId||row.tenantId)===tenant&&String(row.invoiceId)===String(invoice.id);}).slice(0,self.limits.receipts),received=receipts.reduce(function(sum,row){return sum+Number(row.amount||0);},0);return {id:invoice.id,label:invoice.invoiceNumber||'Invoice '+invoice.id,status:invoice.status||'',amount:invoice.total,recordedReceiptTotal:received,receiptCount:receipts.length,balanceSemantics:'RECORDED_RECEIPTS_ONLY',href:self.href_('invoices',invoice.id)};}),bound:self.limits.invoices,canRecordPayment:self.has_(context,'FINANCE_WRITE')};},failures);
  var firearms=null;if(this.has_(context,'FIREARMS_READ')&&(context.enabledModules||[]).indexOf('FIREARMS')!==-1)firearms=this.safe_('Firearms',function(){return {items:(self.firearms?self.firearms.list():[]).filter(function(row){return String(row.tenantId)===tenant&&String(row.jobId)===String(job.id);}).slice(0,self.limits.firearms).map(function(row){return {id:row.id,label:[row.manufacturer,row.model].filter(Boolean).join(' ')||'Serialized firearm',serial:row.serialNumber||'',custody:[row.custodyLocation,row.custodyStatus].filter(Boolean).join(' · '),status:row.lifecycleStatus||'',href:self.href_('firearms',row.id)};}),bound:self.limits.firearms};},failures);
  var history=this.safe_('History',function(){return (self.events?self.events.listByJobId(job.id):[]).slice().sort(function(a,b){return String(b.occurredAt||'').localeCompare(String(a.occurredAt||''));}).slice(0,self.limits.history).map(function(row){return {id:row.id,type:String(row.eventType||'Job update').replace(/_/g,' '),occurredAt:row.occurredAt||'',actor:row.actor||'Atlas user',summary:row.notes||[row.previousStatus,row.newStatus].filter(Boolean).join(' → ')||'Work Order updated'};});},failures)||[];
  var persona=typeof atlasPresentationPersona_==='function'?atlasPresentationPersona_(caps):'NEUTRAL',primary=blocked?{label:'Resolve blocker',href:production.links.dailyProduction}:{label:(persona==='SHOP_OPERATOR'?'Open Shop Floor':'Open Daily Production'),href:persona==='SHOP_OPERATOR'?production.links.shopFloor:production.links.dailyProduction};
  return serializeVmosValue_({job:{id:job.id,number:job.woNumber||job.jobNumber||job.id,description:job.description||job.partId||'Work description unavailable',status:job.status||'Not started',dueDate:job.dueDate||'',quantity:job.quantity,poNumber:job.poNumber||'',version:Number(job.version||0)},customer:commercial&&commercial.customer||{id:job.customerId,label:customer&&(customer.name||customer.companyName)||'Referenced Customer unavailable'},header:{owner:production.owner,currentOperation:production.currentOperation,readiness:readiness,blocker:production.blocker,materialReadiness:production.materialReadiness,toolingReadiness:production.toolingReadiness},primaryAction:primary,sections:{commercial:commercial,production:production,purchasing:purchasing,documents:documents,billing:billing,firearms:firearms,history:{items:history,bound:this.limits.history}},sectionFailures:failures,persona:persona,bounds:this.limits,repositoryReadModel:'BOUNDED_JOB_CANVAS',links:{jobs:'?route=jobs',customer:customer?this.href_('customers',customer.id):'',quote:quote?this.href_('quotes',quote.id):''}});
};
