/** MOS-117C Microsoft Graph adapter. The gateway is injected; no live Graph client is configured here. */
function MicrosoftGraphCalendarProviderAdapter(gateway,registry){this.gateway=gateway;this.registry=registry||new CalendarProviderRegistry();}
MicrosoftGraphCalendarProviderAdapter.prototype.capabilities=function(){var caps=this.registry.get('MICROSOFT_GRAPH_CALENDAR');caps.provider='MICROSOFT_GRAPH_CALENDAR';caps.twoWaySync=caps.supportsTwoWayReschedule;caps.canVersion=caps.supportsVersioning;caps.readOnlyPublication=caps.supportsReadOnlyPublication;return caps;};
MicrosoftGraphCalendarProviderAdapter.prototype.upsert=function(payload){var follow=payload.followUp,connection=payload.connection;if(!connection||connection.provider!=='MICROSOFT_GRAPH_CALENDAR'||!connection.externalCalendarId)throw new VmosConfigurationError('A connected Microsoft calendar selection is required.');var event={subject:follow.title,startAt:follow.startAt,endAt:follow.endAt,timeZone:follow.timeZone,extensions:{mosFollowUpId:follow.id,mosCorrelationId:payload.correlationId}};return this.gateway.upsertEvent({connection:connection,externalEventId:payload.externalEventId,expectedChangeKey:payload.expectedExternalVersion,event:event});};
MicrosoftGraphCalendarProviderAdapter.prototype.fetchEvent=function(connection,eventId){return this.gateway.fetchEvent({connection:connection,externalEventId:eventId});};
MicrosoftGraphCalendarProviderAdapter.prototype.delta=function(connection,cursor){return this.gateway.delta({connection:connection,deltaCursor:cursor||''});};
MicrosoftGraphCalendarProviderAdapter.prototype.createOrRenewSubscription=function(connection){return this.gateway.createOrRenewSubscription({connection:connection});};
MicrosoftGraphCalendarProviderAdapter.prototype.remove=function(payload){if(!this.gateway.deleteEvent)throw new VmosConfigurationError('Microsoft calendar cleanup is not configured.');return this.gateway.deleteEvent({connection:payload.connection,externalEventId:payload.externalEventId,expectedChangeKey:payload.expectedExternalVersion,correlationId:payload.correlationId});};
function MicrosoftGraphCalendarFollowUpService(deps){this.deps=deps||{};this.followUps=this.deps.followUps;this.links=this.deps.links;this.connections=this.deps.connections;this.routing=this.deps.routing;this.sync=this.deps.sync;this.provider=this.deps.provider;this.clock=this.deps.clock||function(){return new Date();};}
MicrosoftGraphCalendarFollowUpService.prototype.project=function(followUpId,correlationId){var follow=this.followUps.repository.get(followUpId);if(this.followUps.schedulingClassification_(follow)!=='SCHEDULED')return {result:'NOT_SCHEDULED',followUpId:followUpId};var route=this.routing.destinationFor(follow);if(route.state!=='CONNECTED'||route.connection.provider!=='MICROSOFT_GRAPH_CALENDAR')return {result:'NOT_CONNECTED',followUpId:followUpId};return this.sync.syncToExternal(followUpId,correlationId,route.connection);};
MicrosoftGraphCalendarFollowUpService.prototype.removeExternalEvent=function(connection,externalEventId,externalVersion,correlationId){try{var response=this.provider.remove({connection:connection,externalEventId:externalEventId,expectedExternalVersion:externalVersion,correlationId:correlationId});return {result:response&&response.notFound?'ALREADY_REMOVED':'REMOVED',externalEventId:externalEventId};}catch(error){return {result:'FAILED',error:error.message,externalEventId:externalEventId};}};
MicrosoftGraphCalendarFollowUpService.prototype.removeProjection=function(followUpId,connection,correlationId){var link=this.links.findByFollowUpId(followUpId);if(!link||!link.externalEventId)return {result:'NOT_LINKED'};return this.removeExternalEvent(connection,link.externalEventId,link.externalVersion,correlationId);};
MicrosoftGraphCalendarFollowUpService.prototype.handleChangeNotification=function(connectionId,externalEventId,correlationId){var connection=this.connections.get(connectionId),link=this.links.findByExternalEvent('MICROSOFT_GRAPH_CALENDAR',externalEventId);if(!connection||connection.connectionStatus!=='CONNECTED')return {result:'NOT_CONNECTED'};try{var event=this.provider.fetchEvent(connection,externalEventId);if(event&&event.extensions&&event.extensions.mosCorrelationId&&link&&event.extensions.mosCorrelationId===link.lastCorrelationId)return {result:'IGNORED',details:'Loop prevented.'};if(!event||event.deleted)return this.sync.syncFromExternal({provider:'MICROSOFT_GRAPH_CALENDAR',externalEventId:externalEventId,externalVersion:event&&event.changeKey||'',changeType:'DELETED',mosVersion:link&&link.lastSyncedFollowUpVersion,correlationId:correlationId});return this.sync.syncFromExternal({provider:'MICROSOFT_GRAPH_CALENDAR',externalEventId:externalEventId,externalVersion:event.changeKey||'',changeType:'UPSERT',startAt:event.startAt,endAt:event.endAt,timeZone:event.timeZone,actor:event.actor||'',mosVersion:link&&link.lastSyncedFollowUpVersion,correlationId:correlationId});}catch(error){this.connections.update(connectionId,{lastError:error.message,lastSyncAt:this.clock()});return {result:'FAILED',error:error.message};}};
MicrosoftGraphCalendarFollowUpService.prototype.recoverDelta=function(connectionId,correlationFactory){var connection=this.connections.get(connectionId);if(!connection||connection.connectionStatus!=='CONNECTED')return {result:'NOT_CONNECTED',processed:0};try{var page=this.provider.delta(connection,connection.syncCursor),self=this,processed=[];(page.events||[]).forEach(function(event,index){var correlation=correlationFactory?correlationFactory(event,index):'delta:'+connectionId+':'+event.externalEventId+':'+(event.changeKey||index);processed.push(self.handleChangeNotification(connectionId,event.externalEventId,correlation));});this.connections.update(connectionId,{syncCursor:page.nextDeltaCursor||connection.syncCursor,lastSyncAt:this.clock(),lastSuccessfulSyncAt:this.clock(),lastError:''});return {result:'RECOVERED',processed:processed.length,changes:processed};}catch(error){this.connections.update(connectionId,{lastError:error.message,lastSyncAt:this.clock()});return {result:'FAILED',processed:0,error:error.message};}};
MicrosoftGraphCalendarFollowUpService.prototype.renewSubscription=function(connectionId){var connection=this.connections.get(connectionId);if(!connection||connection.connectionStatus!=='CONNECTED')return {result:'NOT_CONNECTED'};try{var subscription=this.provider.createOrRenewSubscription(connection);return this.connections.update(connectionId,{subscriptionId:subscription.subscriptionId||'',subscriptionExpiresAt:subscription.expiresAt||'',lastError:''});}catch(error){var changes={lastError:error.message};if(error.code==='AUTHORIZATION_REVOKED')changes.connectionStatus='ATTENTION_REQUIRED';this.connections.update(connectionId,changes);return {result:'FAILED',error:error.message};}};
