/** Bounded personal execution projection. It does not create a task or ownership model. */
function MyWorkService_(dependencies){dependencies=dependencies||{};this.followUps=dependencies.followUps;this.jobs=dependencies.jobs;this.purchases=dependencies.purchases;this.customers=dependencies.customers;this.clock=dependencies.clock||function(){return new Date();};this.diagnostic=dependencies.diagnostic||function(entry){try{console.warn(JSON.stringify(entry));}catch(ignored){}};this.perSourceLimit=Math.min(50,Math.max(1,Number(dependencies.perSourceLimit||25)));this.totalLimit=Math.min(100,Math.max(1,Number(dependencies.totalLimit||50)));}
MyWorkService_.prototype.get=function(context){context=context||{};var self=this,caps=context.capabilities||[],tenant=String(context.tenantId||''),actor=String(context.userId||''),items=[],unavailable=[],sources=[],failedSources=[],overflow={};if(!actor||!tenant)throw new VmosAuthorizationError_('Authenticated Atlas work context is unavailable.');
  function can(value){return caps.indexOf(value)!==-1;}function read(name,allowed,reader,projector){if(!allowed)return;sources.push(name);try{var rows=reader()||[],projected=projector(rows)||[];overflow[name]=Math.max(0,projected.length-self.perSourceLimit);items=items.concat(projected.slice(0,self.perSourceLimit));}catch(error){failedSources.push(name);unavailable.push({source:name,message:name+' work is temporarily unavailable. Retry without leaving My Work.'});self.diagnostic({event:'MY_WORK_SOURCE_UNAVAILABLE',source:name,category:String(error&&error.code||'SOURCE_READ_FAILED'),correlationId:String(context.correlationId||'')});}}
  var customers={};function customerLabel(id){return customers[String(id)]||'Customer context unavailable';}
  if(can('FOLLOWUP_READ')||can('OPERATIONS_READ')){try{(this.customers||new MvpService_('Customer')).list().forEach(function(row){if(String(row.securityTenantId||tenant)===tenant)customers[String(row.id)]=row.name||row.companyName||'Customer';});}catch(error){unavailable.push({source:'Customer context',message:'Some Customer labels are temporarily unavailable.'});}}
  read('Follow-Ups',can('FOLLOWUP_READ'),function(){return (self.followUps||new FollowUpRepository_()).list();},function(rows){return rows.filter(function(row){return (!row.securityTenantId||String(row.securityTenantId)===tenant)&&String(row.ownerUserId||'')===actor&&!self.terminal_(row.status);}).map(function(row){var due=self.due_(row.dueAt),urgency=self.urgency_(due,false,false);return self.item_('FOLLOW_UP',row.id,row.title||'Follow-Up',customerLabel(row.customerId),'Assigned to you',due,urgency,row.status||'OPEN','Open Follow-Up','?route=follow-ups&id='+encodeURIComponent(row.id),'Follow-Ups');});});
  read('Production',can('OPERATIONS_READ'),function(){return (self.jobs||new MvpService_('Job')).list();},function(rows){return rows.filter(function(row){return String(row.securityTenantId||'')===tenant&&(String(row.ownerUserId||'')===actor||String(row.operator||'')===actor)&&!self.terminal_(row.status);}).map(function(row){var blocked=!!String(row.blockerReason||'').trim()||row.blockerActive===true,status=String(row.status||'UNKNOWN').toUpperCase(),due=self.due_(row.dueDate),label=row.woNumber||row.jobNumber||row.id,classification=typeof atlasJobClassification_==='function'?atlasJobClassification_(row):(String(row.workClassification||'').toUpperCase()||(row.customerId||row.quoteId?'CUSTOMER':'')),display=typeof atlasJobDisplay_==='function'?atlasJobDisplay_(row):{classification:classification,label:classification==='INTERNAL'?'INTERNAL · '+String(row.internalWorkType||'').replace(/_/g,' '):'CUSTOMER'},party=display.classification==='INTERNAL'?display.label:customerLabel(row.customerId),context=[row.title||row.partId||row.description||'Work description unavailable',party+(row.assetId?' · '+row.assetId:''),row.currentOperation||status].join(' / '),reason=blocked?'Blocked work assigned to you':'Work Order assigned to you';return self.item_('JOB',row.id,label,context,reason,due,self.urgency_(due,blocked,false),status,'Open Job','?route=job&jobId='+encodeURIComponent(row.id),'Production');});});
  read('Approvals',can('PURCHASE_APPROVE'),function(){return (self.purchases||new PurchaseApprovalRepository_()).list();},function(rows){return rows.filter(function(row){return String(row.securityTenantId||'')===tenant&&String(row.status||'').toUpperCase()==='PENDING_APPROVAL'&&row.approvalRequired===true&&String(row.requester||'')!==actor;}).map(function(row){return self.item_('PURCHASE_APPROVAL',row.id,row.description||'Purchase Request',[row.vendor||'Vendor unavailable',row.jobId?'Work Order '+row.jobId:'Unlinked request'].join(' / '),'Approval required from an authorized approver',self.due_(row.requiredBy||''),'WAITING_ON_ME',row.status,'Review Purchase Request','?route=purchasing&id='+encodeURIComponent(row.id),'Approvals');});});
  items.sort(this.compare_);var totalOverflow=Math.max(0,items.length-this.totalLimit);items=items.slice(0,this.totalLimit);return serializeVmosValue_({generatedAt:this.clock(),identity:{scope:'AUTHENTICATED_ACTOR'},items:items,groups:this.groups_(items),availableFilters:this.filters_(items),unavailable:unavailable,sourceCount:sources.length,successfulSourceCount:sources.length-failedSources.length,state:!sources.length?'PERMISSION_LIMITED':failedSources.length===sources.length?'TOTAL_FAILURE':unavailable.length?'PARTIAL_FAILURE':items.length?'READY':'EMPTY',bounds:{perSource:this.perSourceLimit,total:this.totalLimit},overflow:{bySource:overflow,total:totalOverflow,hasMore:totalOverflow>0||Object.keys(overflow).some(function(key){return overflow[key]>0;})},excludedDomains:['Commercial: no canonical personal assignment semantics','Finance: no canonical personal assignment semantics','Firearms: no canonical personal assignment semantics','Tenant Admin: no actor-specific required-action assignment']});};
MyWorkService_.prototype.terminal_=function(status){return ['COMPLETED','COMPLETE','CANCELLED','CANCELED','CLOSED','ACCEPTED','RECEIVED'].indexOf(String(status||'').toUpperCase())!==-1;};
MyWorkService_.prototype.due_=function(value){if(!value)return '';var text=String(value),dateOnly=/^(\d{4})-(\d{2})-(\d{2})$/.exec(text),parsed=dateOnly?new Date(Number(dateOnly[1]),Number(dateOnly[2])-1,Number(dateOnly[3])):new Date(value);return isNaN(parsed)?'':parsed;};
MyWorkService_.prototype.urgency_=function(due,blocked,waiting){if(!due)return blocked?'BLOCKED':waiting?'WAITING_ON_ME':'ASSIGNED';var today=new Date(this.clock());today.setHours(0,0,0,0);var target=new Date(due);target.setHours(0,0,0,0);var days=Math.round((target-today)/86400000);if(days<0)return 'OVERDUE';if(blocked)return 'BLOCKED';if(days===0)return 'DUE_TODAY';if(waiting)return 'WAITING_ON_ME';if(days===1)return 'DUE_TOMORROW';if(days<=7)return 'THIS_WEEK';return 'ASSIGNED';};
MyWorkService_.prototype.item_=function(type,id,label,context,reason,due,urgency,status,actionLabel,href,filter){return {key:type+':'+id,type:type,label:label,context:context,reason:reason,dueAt:due||'',urgency:urgency,status:status||'UNKNOWN',actionLabel:actionLabel,href:href,filter:filter};};
MyWorkService_.prototype.compare_=function(a,b){var order={OVERDUE:0,BLOCKED:1,DUE_TODAY:2,WAITING_ON_ME:3,DUE_TOMORROW:4,THIS_WEEK:5,ASSIGNED:6,UNKNOWN:7},left=Object.prototype.hasOwnProperty.call(order,a.urgency)?order[a.urgency]:7,right=Object.prototype.hasOwnProperty.call(order,b.urgency)?order[b.urgency]:7;return left-right||String(a.dueAt||'9999').localeCompare(String(b.dueAt||'9999'))||String(a.type).localeCompare(String(b.type))||String(a.key).localeCompare(String(b.key));};
MyWorkService_.prototype.groups_=function(items){var definitions=[['NEEDS_ATTENTION','Needs attention',['OVERDUE','BLOCKED','WAITING_ON_ME']],['TODAY','Today',['DUE_TODAY']],['UP_NEXT','Up next',['DUE_TOMORROW','THIS_WEEK']],['ASSIGNED','Assigned',['ASSIGNED','UNKNOWN']]];return definitions.map(function(definition){return {id:definition[0],label:definition[1],items:items.filter(function(item){return definition[2].indexOf(item.urgency)!==-1;})};}).filter(function(group){return group.items.length;});};
MyWorkService_.prototype.filters_=function(items){var values=['All'];['Due','Blocked','Follow-Ups','Production','Approvals'].forEach(function(filter){if(items.some(function(item){return filter==='Due'?['OVERDUE','DUE_TODAY','DUE_TOMORROW','THIS_WEEK'].indexOf(item.urgency)!==-1:filter==='Blocked'?item.urgency==='BLOCKED':item.filter===filter;}))values.push(filter);});return values;};
