/** Exact-decimal helpers. Money is an integer minor-unit string; operands are normalized decimal strings. */
function atlasDecimal_(value,maxScale,label){var text=String(value===undefined||value===null?'':value).trim();if(!/^\d+(\.\d+)?$/.test(text))throw new VmosValidationError_((label||'Value')+' must be a non-negative decimal.');var parts=text.split('.'),fraction=parts[1]||'';if(fraction.length>maxScale)throw new VmosValidationError_((label||'Value')+' supports at most '+maxScale+' decimal places.');return {units:BigInt(parts[0]+fraction),scale:fraction.length,text:parts[0]+(fraction?'.'+fraction:'')};}
function atlasMinor_(value,label){var text=String(value===undefined||value===null?'':value).trim();if(!/^\d+$/.test(text))throw new VmosValidationError_((label||'Amount')+' must be an exact non-negative minor-unit string.');return text.replace(/^0+(?=\d)/,'');}
function atlasRoundDivide_(numerator,denominator){if(denominator<=0n)throw new VmosValidationError_('Allocation quantity must be greater than zero.');var quotient=numerator/denominator,remainder=numerator%denominator;return quotient+(remainder*2n>=denominator?1n:0n);}
function atlasMultiplyMinorByDecimal_(minor,decimal){var d=atlasDecimal_(decimal,4,'Quantity'),factor=10n**BigInt(d.scale);return String(atlasRoundDivide_(BigInt(atlasMinor_(minor))*d.units,factor));}
function atlasHourlyMinor_(rateMinor,hours,quantity){return atlasMultiplyMinorByDecimal_(atlasMultiplyMinorByDecimal_(rateMinor,hours),quantity);}
function atlasFormatMinor_(minor){var value=String(BigInt(minor||'0')).padStart(3,'0');return value.slice(0,-2)+'.'+value.slice(-2);}

function QuoteCostEngine_(){}
QuoteCostEngine_.prototype.calculateLine=function(input,quoteQuantity){input=input||{};var basis=String(input.basis||''),purpose=String(input.purpose||'INTERNAL_COST_DETAIL'),summary=purpose==='SUPPLIER_SUMMARY'||input.summaryOnly===true,include=summary?false:input.includeInRollup!==false,extended,costEach='';atlasDecimal_(quoteQuantity,4,'Quote quantity');
  if(['INTERNAL_COST_DETAIL','SUPPLIER_SUMMARY','INTERNAL_NOTE'].indexOf(purpose)===-1)throw new VmosValidationError_('Cost-line purpose is invalid.');
  if(purpose==='INTERNAL_NOTE')return Object.assign({},input,{purpose:purpose,summaryOnly:false,includeInRollup:false,extendedCostMinor:'0',costEachMinor:''});
  if(basis==='BATCH_TOTAL'||basis==='ONE_TIME'){extended=atlasMinor_(input.sourceAmountMinor,'Source amount');if(basis==='BATCH_TOTAL')costEach=String(atlasRoundDivide_(BigInt(extended)*10000n,atlasDecimal_(input.allocationQuantity||quoteQuantity,4,'Allocation quantity').units*10n**BigInt(4-atlasDecimal_(input.allocationQuantity||quoteQuantity,4,'Allocation quantity').scale)));}
  else if(basis==='PER_PART'){costEach=atlasMinor_(input.costEachMinor,'Cost each');extended=atlasMultiplyMinorByDecimal_(costEach,quoteQuantity);}
  else if(basis==='HOURLY_PER_PART'){var hours=atlasDecimal_(input.hoursPerPart,4,'Hours per part');costEach=atlasMultiplyMinorByDecimal_(input.rateMinor,hours.text);extended=atlasMultiplyMinorByDecimal_(costEach,quoteQuantity);}
  else if(basis==='QUANTITY_BASED'){atlasDecimal_(input.quantity,4,'Basis quantity');costEach=atlasMinor_(input.rateMinor,'Unit rate');extended=atlasMultiplyMinorByDecimal_(costEach,input.quantity);}
  else throw new VmosValidationError_('An explicit supported cost basis is required.');
  return Object.assign({},input,{purpose:purpose,summaryOnly:summary,includeInRollup:include,costEachMinor:costEach,extendedCostMinor:String(extended),currency:String(input.currency||'USD').toUpperCase()});
};
QuoteCostEngine_.prototype.rollup=function(lines,quoteQuantity,customerRecurringMinor,customerOneTimeMinor){var that=this,calculated=(lines||[]).map(function(line){return that.calculateLine(line,quoteQuantity);}),recurring=0n,oneTime=0n;calculated.forEach(function(line){if(!line.includeInRollup)return;if(line.timing==='ONE_TIME'||line.basis==='ONE_TIME')oneTime+=BigInt(line.extendedCostMinor);else recurring+=BigInt(line.extendedCostMinor);});var customer=BigInt(atlasMinor_(customerRecurringMinor||'0'))+BigInt(atlasMinor_(customerOneTimeMinor||'0')),total=recurring+oneTime;return {lines:calculated,recurringCostMinor:String(recurring),oneTimeCostMinor:String(oneTime),totalCostMinor:String(total),customerTotalMinor:String(customer),contributionMinor:String(customer-total)};};
QuoteCostEngine_.prototype.reconcileSuppliers=function(lines){var groups={};(lines||[]).forEach(function(line){if(!line.summaryGroupKey)return;var key=[line.vendorId,line.currency,line.summaryGroupKey].join('|'),g=groups[key]||(groups[key]={detailMinor:0n,summaryMinor:null});if(line.purpose==='SUPPLIER_SUMMARY')g.summaryMinor=BigInt(line.extendedCostMinor);else if(line.includeInRollup)g.detailMinor+=BigInt(line.extendedCostMinor);});return Object.keys(groups).map(function(key){var g=groups[key],variance=g.summaryMinor===null?null:g.summaryMinor-g.detailMinor;return {groupKey:key,detailMinor:String(g.detailMinor),summaryMinor:g.summaryMinor===null?'':String(g.summaryMinor),varianceMinor:variance===null?'':String(variance),matches:variance===0n};});};

function VendorService_(deps){deps=deps||{};this.vendors=deps.vendors||new VendorRepository_();this.capabilities=deps.capabilities||new VendorCapabilityRepository_();this.locations=deps.locations||new VendorLocationRepository_();this.contacts=deps.contacts||new VendorContactRepository_();this.estimates=deps.estimates||new VendorEstimateRepository_();this.uuid=deps.uuid||function(){return Utilities.getUuid().toUpperCase();};this.clock=deps.clock||function(){return new Date();};}
VendorService_.prototype.assertTenant_=function(row,context){if(!row||String(row.tenantId)!==String(context.tenantId))throw new VmosAuthorizationError_('Vendor record is unavailable.');return row;};
VendorService_.prototype.create=function(input,context,id){input=input||{};if(!String(input.name||'').trim())throw new VmosValidationError_('Vendor name is required.');var supply=String(input.supplyType||'BOTH').toUpperCase();if(['GOODS','SERVICES','BOTH'].indexOf(supply)===-1)throw new VmosValidationError_('Vendor supply type is invalid.');var record=this.vendors.create({id:id||'VND-'+this.uuid(),tenantId:context.tenantId,name:String(input.name).trim(),supplyType:supply,status:'ACTIVE',website:input.website||'',paymentTerms:input.paymentTerms||'',typicalLeadTime:input.typicalLeadTime||'',minimumOrderMinor:input.minimumOrderMinor?atlasMinor_(input.minimumOrderMinor):'',currency:String(input.currency||'USD').toUpperCase(),preferred:input.preferred===true,notes:input.notes||'',version:1,createdAt:this.clock(),createdBy:context.userId,updatedAt:this.clock(),updatedBy:context.userId,securityOperationId:context.operationId,securityOperationFingerprint:context.requestFingerprint,securityActorId:context.userId});var that=this;(input.capabilities||[]).forEach(function(value){if(ATLAS_VENDOR_CAPABILITIES.indexOf(value)===-1)throw new VmosValidationError_('Vendor capability is invalid.');that.capabilities.create({id:'VCAP-'+that.uuid(),tenantId:context.tenantId,vendorId:record.id,capability:value,createdAt:that.clock(),createdBy:context.userId});});return record;};
VendorService_.prototype.search=function(query,context,limit,capability){var ids=null;if(capability){ids=this.capabilities.forTenant(context.tenantId).filter(function(row){return row.capability===capability;}).map(function(row){return row.vendorId;});}return this.vendors.search(context.tenantId,query,limit).filter(function(row){return !ids||ids.indexOf(row.id)!==-1;}).map(function(row){return {id:row.id,label:row.name,secondary:[row.supplyType,row.status].filter(Boolean).join(' · '),preferred:row.preferred===true};});};
VendorService_.prototype.detail=function(id,context){var vendor=this.assertTenant_(this.vendors.get(id),context);return {vendor:vendor,capabilities:this.capabilities.byField(context.tenantId,'vendorId',id,50),locations:this.locations.byField(context.tenantId,'vendorId',id,50),contacts:this.contacts.byField(context.tenantId,'vendorId',id,50),recentEstimates:this.estimates.byField(context.tenantId,'vendorId',id,20)};};

function QuoteCostingService_(deps){deps=deps||{};this.estimates=deps.estimates||new QuoteCostEstimateRepository_();this.lines=deps.lines||new QuoteCostLineRepository_();this.pricing=deps.pricing||new QuotePricingDecisionRepository_();this.documents=deps.documents||new QuoteSourceDocumentLinkRepository_();this.engine=deps.engine||new QuoteCostEngine_();this.uuid=deps.uuid||function(){return Utilities.getUuid().toUpperCase();};this.clock=deps.clock||function(){return new Date();};}
QuoteCostingService_.prototype.save=function(model,context,estimateId){model=model||{};if(!model.quoteId||!model.quoteRevisionId)throw new VmosValidationError_('Quote and revision are required.');var currency=String(model.currency||'USD').toUpperCase();if(!/^[A-Z]{3}$/.test(currency))throw new VmosValidationError_('Currency code is invalid.');var rollup=this.engine.rollup(model.lines||[],model.quoteQuantity,model.customerRecurringMinor||'0',model.customerOneTimeMinor||'0'),now=this.clock(),id=estimateId||model.id||'QCE-'+this.uuid(),record={id:id,tenantId:context.tenantId,quoteId:model.quoteId,quoteRevisionId:model.quoteRevisionId,estimateVersion:Number(model.estimateVersion||1),status:'DRAFT',currency:currency,recurringCostMinor:rollup.recurringCostMinor,oneTimeCostMinor:rollup.oneTimeCostMinor,totalCostMinor:rollup.totalCostMinor,rollupVersion:1,version:Number(model.version||1),createdAt:now,createdBy:context.userId,updatedAt:now,updatedBy:context.userId,securityOperationId:context.operationId,securityOperationFingerprint:context.requestFingerprint,securityActorId:context.userId};this.estimates.create(record);var that=this;rollup.lines.forEach(function(line,index){that.lines.create(Object.assign({},line,{id:line.id||'QCL-'+that.uuid(),tenantId:context.tenantId,estimateId:id,sequence:index+1,version:1,createdAt:now,createdBy:context.userId,updatedAt:now,updatedBy:context.userId,securityOperationId:context.operationId,securityOperationFingerprint:context.requestFingerprint,securityActorId:context.userId}));});return {estimate:record,rollup:rollup,reconciliation:this.engine.reconcileSuppliers(rollup.lines)};};
QuoteCostingService_.prototype.read=function(quoteId,context,options){options=options||{};var estimates=this.estimates.byField(context.tenantId,'quoteId',quoteId,10).sort(function(a,b){return Number(b.estimateVersion)-Number(a.estimateVersion);}),estimate=estimates[0]||null;if(!estimate)return {estimate:null,lines:[],pricing:[],documents:[],warning:'Internal costing has not been completed.'};var lines=this.lines.byField(context.tenantId,'estimateId',estimate.id,options.limit||50),pricing=options.canManagePricing||options.canReadMargin?this.pricing.byField(context.tenantId,'estimateId',estimate.id,50):[];return {estimate:estimate,lines:lines,pricing:pricing,documents:this.documents.byField(context.tenantId,'estimateId',estimate.id,50),reconciliation:this.engine.reconcileSuppliers(lines)};};
QuoteCostingService_.prototype.customerProjection=function(quote,revision,customerLines){return {quote:{id:quote.id,status:quote.status,currency:quote.currency||'USD'},revision:{id:revision.id,revision:revision.revision,status:revision.status},lines:(customerLines||[]).map(function(line){return {description:line.description,quantity:line.quantity,unitPriceMinor:line.unitPriceMinor,extendedPriceMinor:line.extendedPriceMinor,lineType:line.lineType||'RECURRING'};})};};
