/** Exact-decimal helpers. Money is an integer minor-unit string; operands are decimal digit strings. */
function atlasUnsigned_(value){var text=String(value===undefined||value===null?'':value);if(!/^\d+$/.test(text))throw new VmosValidationError_('Exact arithmetic requires non-negative integer strings.');return text.replace(/^0+(?=\d)/,'');}
function atlasCompareUnsigned_(left,right){left=atlasUnsigned_(left);right=atlasUnsigned_(right);if(left.length!==right.length)return left.length>right.length?1:-1;return left===right?0:(left>right?1:-1);}
function atlasAddUnsigned_(left,right){left=atlasUnsigned_(left);right=atlasUnsigned_(right);var i=left.length-1,j=right.length-1,carry=0,out='';while(i>=0||j>=0||carry){var sum=(i>=0?Number(left.charAt(i--)):0)+(j>=0?Number(right.charAt(j--)):0)+carry;out=String(sum%10)+out;carry=Math.floor(sum/10);}return atlasUnsigned_(out);}
function atlasSubtractUnsigned_(left,right){left=atlasUnsigned_(left);right=atlasUnsigned_(right);if(atlasCompareUnsigned_(left,right)<0)throw new VmosValidationError_('Exact arithmetic subtraction underflow.');var i=left.length-1,j=right.length-1,borrow=0,out='';while(i>=0){var digit=Number(left.charAt(i--))-borrow-(j>=0?Number(right.charAt(j--)):0);if(digit<0){digit+=10;borrow=1;}else borrow=0;out=String(digit)+out;}return atlasUnsigned_(out);}
function atlasSignedSubtract_(left,right){var comparison=atlasCompareUnsigned_(left,right);return comparison===0?'0':(comparison>0?atlasSubtractUnsigned_(left,right):'-'+atlasSubtractUnsigned_(right,left));}
function atlasMultiplyUnsigned_(left,right){left=atlasUnsigned_(left);right=atlasUnsigned_(right);if(left==='0'||right==='0')return '0';var result=[],i,j;for(i=0;i<left.length+right.length;i++)result[i]=0;for(i=left.length-1;i>=0;i--)for(j=right.length-1;j>=0;j--){var position=i+j+1,total=result[position]+Number(left.charAt(i))*Number(right.charAt(j));result[position]=total%10;result[position-1]+=Math.floor(total/10);}return atlasUnsigned_(result.join(''));}
function atlasPow10_(scale){return '1'+new Array(Number(scale)+1).join('0');}
function atlasDecimal_(value,maxScale,label){var text=String(value===undefined||value===null?'':value).trim();if(!/^\d+(\.\d+)?$/.test(text))throw new VmosValidationError_((label||'Value')+' must be a non-negative decimal.');var parts=text.split('.'),fraction=parts[1]||'';if(fraction.length>maxScale)throw new VmosValidationError_((label||'Value')+' supports at most '+maxScale+' decimal places.');return {units:atlasUnsigned_(parts[0]+fraction),scale:fraction.length,text:parts[0]+(fraction?'.'+fraction:'')};}
function atlasMinor_(value,label){var text=String(value===undefined||value===null?'':value).trim();if(!/^\d+$/.test(text))throw new VmosValidationError_((label||'Amount')+' must be an exact non-negative minor-unit string.');return text.replace(/^0+(?=\d)/,'');}
function atlasRoundDivide_(numerator,denominator){numerator=atlasUnsigned_(numerator);denominator=atlasUnsigned_(denominator);if(denominator==='0')throw new VmosValidationError_('Allocation quantity must be greater than zero.');var quotient='',remainder='0';for(var i=0;i<numerator.length;i++){remainder=atlasUnsigned_(remainder+numerator.charAt(i));var digit=0;while(atlasCompareUnsigned_(remainder,denominator)>=0){remainder=atlasSubtractUnsigned_(remainder,denominator);digit++;}quotient+=String(digit);}quotient=atlasUnsigned_(quotient);return atlasCompareUnsigned_(atlasMultiplyUnsigned_(remainder,'2'),denominator)>=0?atlasAddUnsigned_(quotient,'1'):quotient;}
function atlasMultiplyMinorByDecimal_(minor,decimal){var d=atlasDecimal_(decimal,4,'Quantity');return atlasRoundDivide_(atlasMultiplyUnsigned_(atlasMinor_(minor),d.units),atlasPow10_(d.scale));}
function atlasHourlyMinor_(rateMinor,hours,quantity){var h=atlasDecimal_(hours,4,'Hours per part'),q=atlasDecimal_(quantity,4,'Quote quantity');return atlasRoundDivide_(atlasMultiplyUnsigned_(atlasMultiplyUnsigned_(atlasMinor_(rateMinor,'Hourly rate'),h.units),q.units),atlasPow10_(h.scale+q.scale));}
function atlasFormatMinor_(minor){var value=String(minor===undefined||minor===null?'0':minor),negative=value.charAt(0)==='-';if(negative)value=value.slice(1);value=atlasUnsigned_(value);while(value.length<3)value='0'+value;return (negative?'-':'')+value.slice(0,-2)+'.'+value.slice(-2);}

function QuoteCostEngine_(){}
QuoteCostEngine_.prototype.calculateLine=function(input,quoteQuantity){input=input||{};var basis=String(input.basis||''),purpose=String(input.purpose||'INTERNAL_COST_DETAIL'),summary=purpose==='SUPPLIER_SUMMARY'||input.summaryOnly===true,include=summary?false:input.includeInRollup!==false,extended,costEach='';atlasDecimal_(quoteQuantity,4,'Quote quantity');
  if(['INTERNAL_COST_DETAIL','SUPPLIER_SUMMARY','INTERNAL_NOTE'].indexOf(purpose)===-1)throw new VmosValidationError_('Cost-line purpose is invalid.');
  if(purpose==='INTERNAL_NOTE')return Object.assign({},input,{purpose:purpose,summaryOnly:false,includeInRollup:false,extendedCostMinor:'0',costEachMinor:''});
  if(basis==='BATCH_TOTAL'||basis==='ONE_TIME'){extended=atlasMinor_(input.sourceAmountMinor,'Source amount');if(basis==='BATCH_TOTAL'){var allocation=atlasDecimal_(input.allocationQuantity||quoteQuantity,4,'Allocation quantity');costEach=atlasRoundDivide_(atlasMultiplyUnsigned_(extended,'10000'),atlasMultiplyUnsigned_(allocation.units,atlasPow10_(4-allocation.scale)));}}
  else if(basis==='PER_PART'){costEach=atlasMinor_(input.costEachMinor,'Cost each');extended=atlasMultiplyMinorByDecimal_(costEach,quoteQuantity);}
  else if(basis==='HOURLY_PER_PART'){var hours=atlasDecimal_(input.hoursPerPart,4,'Hours per part');costEach=atlasMultiplyMinorByDecimal_(input.rateMinor,hours.text);extended=atlasHourlyMinor_(input.rateMinor,hours.text,quoteQuantity);}
  else if(basis==='QUANTITY_BASED'){atlasDecimal_(input.quantity,4,'Basis quantity');costEach=atlasMinor_(input.rateMinor,'Unit rate');extended=atlasMultiplyMinorByDecimal_(costEach,input.quantity);}
  else throw new VmosValidationError_('An explicit supported cost basis is required.');
  return Object.assign({},input,{purpose:purpose,summaryOnly:summary,includeInRollup:include,costEachMinor:costEach,extendedCostMinor:String(extended),currency:String(input.currency||'USD').toUpperCase()});
};
QuoteCostEngine_.prototype.rollup=function(lines,quoteQuantity,customerRecurringMinor,customerOneTimeMinor){var that=this,calculated=(lines||[]).map(function(line){return that.calculateLine(line,quoteQuantity);}),recurring='0',oneTime='0';calculated.forEach(function(line){if(!line.includeInRollup)return;if(line.timing==='ONE_TIME'||line.basis==='ONE_TIME')oneTime=atlasAddUnsigned_(oneTime,line.extendedCostMinor);else recurring=atlasAddUnsigned_(recurring,line.extendedCostMinor);});var customer=atlasAddUnsigned_(atlasMinor_(customerRecurringMinor||'0'),atlasMinor_(customerOneTimeMinor||'0')),total=atlasAddUnsigned_(recurring,oneTime);return {lines:calculated,recurringCostMinor:recurring,oneTimeCostMinor:oneTime,totalCostMinor:total,customerTotalMinor:customer,contributionMinor:atlasSignedSubtract_(customer,total)};};
QuoteCostEngine_.prototype.reconcileSuppliers=function(lines){var groups={};(lines||[]).forEach(function(line){if(!line.summaryGroupKey)return;var key=[line.vendorId,line.currency,line.summaryGroupKey].join('|'),g=groups[key]||(groups[key]={detailMinor:'0',summaryMinor:null});if(line.purpose==='SUPPLIER_SUMMARY')g.summaryMinor=atlasMinor_(line.extendedCostMinor);else if(line.includeInRollup)g.detailMinor=atlasAddUnsigned_(g.detailMinor,line.extendedCostMinor);});return Object.keys(groups).map(function(key){var g=groups[key],variance=g.summaryMinor===null?null:atlasSignedSubtract_(g.summaryMinor,g.detailMinor);return {groupKey:key,detailMinor:g.detailMinor,summaryMinor:g.summaryMinor===null?'':g.summaryMinor,varianceMinor:variance===null?'':variance,matches:variance==='0'};});};

function VendorService_(deps){deps=deps||{};this.vendors=deps.vendors||new VendorRepository_();this.capabilities=deps.capabilities||new VendorCapabilityRepository_();this.locations=deps.locations||new VendorLocationRepository_();this.contacts=deps.contacts||new VendorContactRepository_();this.estimates=deps.estimates||new VendorEstimateRepository_();this.uuid=deps.uuid||function(){return Utilities.getUuid().toUpperCase();};this.clock=deps.clock||function(){return new Date();};}
VendorService_.prototype.assertTenant_=function(row,context){if(!row||String(row.tenantId)!==String(context.tenantId))throw new VmosAuthorizationError_('Vendor record is unavailable.');return row;};
VendorService_.prototype.create=function(input,context,id){input=input||{};if(!String(input.name||'').trim())throw new VmosValidationError_('Vendor name is required.');var supply=String(input.supplyType||'BOTH').toUpperCase();if(['GOODS','SERVICES','BOTH'].indexOf(supply)===-1)throw new VmosValidationError_('Vendor supply type is invalid.');var record=this.vendors.create({id:id||'VND-'+this.uuid(),tenantId:context.tenantId,name:String(input.name).trim(),supplyType:supply,status:'ACTIVE',website:input.website||'',paymentTerms:input.paymentTerms||'',typicalLeadTime:input.typicalLeadTime||'',minimumOrderMinor:input.minimumOrderMinor?atlasMinor_(input.minimumOrderMinor):'',currency:String(input.currency||'USD').toUpperCase(),preferred:input.preferred===true,notes:input.notes||'',version:1,createdAt:this.clock(),createdBy:context.userId,updatedAt:this.clock(),updatedBy:context.userId,securityOperationId:context.operationId,securityOperationFingerprint:context.requestFingerprint,securityActorId:context.userId});var that=this;(input.capabilities||[]).forEach(function(value){if(ATLAS_VENDOR_CAPABILITIES.indexOf(value)===-1)throw new VmosValidationError_('Vendor capability is invalid.');that.capabilities.create({id:'VCAP-'+that.uuid(),tenantId:context.tenantId,vendorId:record.id,capability:value,createdAt:that.clock(),createdBy:context.userId});});return record;};
VendorService_.prototype.search=function(query,context,limit,capability){var ids=null;if(capability){ids=this.capabilities.forTenant(context.tenantId).filter(function(row){return row.capability===capability;}).map(function(row){return row.vendorId;});}return this.vendors.search(context.tenantId,query,limit).filter(function(row){return String(row.status||'ACTIVE').toUpperCase()==='ACTIVE'&&(!ids||ids.indexOf(row.id)!==-1);}).map(function(row){return {id:row.id,label:row.name,secondary:[row.supplyType,row.status].filter(Boolean).join(' · '),preferred:row.preferred===true};});};
VendorService_.prototype.detail=function(id,context){var vendor=this.assertTenant_(this.vendors.get(id),context);return {vendor:vendor,capabilities:this.capabilities.byField(context.tenantId,'vendorId',id,50),locations:this.locations.byField(context.tenantId,'vendorId',id,50),contacts:this.contacts.byField(context.tenantId,'vendorId',id,50),recentEstimates:this.estimates.byField(context.tenantId,'vendorId',id,20)};};

function QuoteCostingService_(deps){deps=deps||{};this.estimates=deps.estimates||(typeof QuoteCostEstimateRepository_!=='undefined'?new QuoteCostEstimateRepository_():null);this.lines=deps.lines||(typeof QuoteCostLineRepository_!=='undefined'?new QuoteCostLineRepository_():null);this.pricing=deps.pricing||(typeof QuotePricingDecisionRepository_!=='undefined'?new QuotePricingDecisionRepository_():null);this.documents=deps.documents||(typeof QuoteSourceDocumentLinkRepository_!=='undefined'?new QuoteSourceDocumentLinkRepository_():null);this.quotes=deps.quotes||(typeof MvpService_!=='undefined'?new MvpService_('Quote'):null);this.revisions=deps.revisions||(typeof QuoteRevisionRepository_!=='undefined'?new QuoteRevisionRepository_():null);this.quoteLines=deps.quoteLines||(typeof QuoteLineItemRepository_!=='undefined'?new QuoteLineItemRepository_():null);this.vendors=deps.vendors||(typeof VendorRepository_!=='undefined'?new VendorRepository_():null);this.vendorEstimates=deps.vendorEstimates||(typeof VendorEstimateRepository_!=='undefined'?new VendorEstimateRepository_():null);this.sourceDocuments=deps.sourceDocuments||(typeof SourceDocumentRepository_!=='undefined'?new SourceDocumentRepository_():null);this.mutationCheckpoints=deps.mutationCheckpoints||(typeof QuoteMutationCheckpointRepository_!=='undefined'?new QuoteMutationCheckpointRepository_():null);this.engine=deps.engine||new QuoteCostEngine_();this.checkpoint=deps.checkpoint||function(){};this.uuid=deps.uuid||function(){return Utilities.getUuid().toUpperCase();};this.clock=deps.clock||function(){return new Date();};}
QuoteCostingService_.prototype.persistIntents_=function(rows,context,aggregateId,aggregateType){if(!this.mutationCheckpoints)return;var self=this;rows.forEach(function(row){var id='QMCP-'+context.operationId+'-'+row.id,type=row.__aggregateMarker?'AggregateMarker':String(row.id).indexOf(aggregateId+'-P')===0||String(row.id).indexOf('QPD-')===0?'QuotePricingDecision':'QuoteCostLine',record={id:id,tenantId:context.tenantId,operationId:context.operationId,aggregateType:aggregateType,aggregateId:aggregateId,resourceType:type,resourceId:row.id,payloadJson:JSON.stringify(row),status:'INTENT',createdAt:self.clock(),createdBy:context.userId,completedAt:'',completedBy:''},existing=self.mutationCheckpoints.get(id);if(existing){if(String(existing.operationId)!==String(context.operationId)||String(existing.aggregateId)!==String(aggregateId)||String(existing.resourceId)!==String(row.id)||String(existing.resourceType)!==String(type))throw new VmosConflictError('Quote costing recovery checkpoint conflicts with another operation.');var intended=JSON.parse(existing.payloadJson||'{}');Object.keys(row).forEach(function(key){delete row[key];});Object.keys(intended).forEach(function(key){row[key]=intended[key];});}else self.mutationCheckpoints.create(record);});};
QuoteCostingService_.prototype.tenant_=function(row,context,label){if(!row||String(row.securityTenantId||row.tenantId)!==String(context.tenantId))throw new VmosAuthorizationError_((label||'Related record')+' is unavailable.');return row;};
QuoteCostingService_.prototype.childId_=function(prefix,used,index,repository,context){var id=prefix+'-'+context.operationId+'-'+String(index+1);if(used[id]||repository.get(id))throw new VmosConflictError('Atlas could not allocate a unique Quote costing identity. Try saving again.');used[id]=true;return id;};
QuoteCostingService_.prototype.validateRelationships_=function(model,context){var quote=this.tenant_(this.quotes.get(model.quoteId),context,'Quote'),revision=this.tenant_(this.revisions.get(model.quoteRevisionId),context,'Quote revision'),self=this;if(String(revision.quoteId)!==String(quote.id))throw new VmosValidationError_('Quote revision does not belong to this Quote.');function quoteLine_(id){var quoteLine=self.tenant_(self.quoteLines.get(id),context,'Quote line');if(String(quoteLine.quoteRevisionId)!==String(revision.id))throw new VmosValidationError_('Quote line does not belong to this revision.');return quoteLine;}(model.lines||[]).forEach(function(line){if(line.vendorId)self.tenant_(self.vendors.get(line.vendorId),context,'Vendor');if(line.vendorEstimateId){var vendorEstimate=self.tenant_(self.vendorEstimates.get(line.vendorEstimateId),context,'Vendor estimate');if(line.vendorId&&String(vendorEstimate.vendorId)!==String(line.vendorId))throw new VmosValidationError_('Vendor estimate does not belong to the selected Vendor.');}if(line.sourceDocumentId)self.tenant_(self.sourceDocuments.get(line.sourceDocumentId),context,'Source document');if(line.quoteLineItemId)quoteLine_(line.quoteLineItemId);});(model.pricing||[]).forEach(function(item){if(item.quoteLineItemId)quoteLine_(item.quoteLineItemId);});return {quote:quote,revision:revision};};
QuoteCostingService_.prototype.save=function(model,context,estimateId){
  model=model||{};if(!model.quoteId||!model.quoteRevisionId)throw new VmosValidationError_('Quote and revision are required.');this.validateRelationships_(model,context);
  var currency=String(model.currency||'USD').toUpperCase();if(!/^[A-Z]{3}$/.test(currency))throw new VmosValidationError_('Currency code is invalid.');
  var rollup=this.engine.rollup(model.lines||[],model.quoteQuantity,model.customerRecurringMinor||'0',model.customerOneTimeMinor||'0'),now=this.clock(),id=model.id||estimateId||'QCE-'+this.uuid(),current=model.id?this.tenant_(this.estimates.get(model.id),context,'Cost estimate'):null;
  if(current&&Number(current.version)!==Number(model.version))throw new VmosConflictError('Internal costing changed. Refresh before saving.');
  var version=current?Number(current.version||1)+1:1,record={id:id,tenantId:context.tenantId,quoteId:model.quoteId,quoteRevisionId:model.quoteRevisionId,estimateVersion:Number(model.estimateVersion||current&&current.estimateVersion||1),status:'DRAFT',currency:currency,recurringCostMinor:rollup.recurringCostMinor,oneTimeCostMinor:rollup.oneTimeCostMinor,totalCostMinor:rollup.totalCostMinor,rollupVersion:Number(current&&current.rollupVersion||0)+1,version:version,createdAt:current?current.createdAt:now,createdBy:current?current.createdBy:context.userId,updatedAt:now,updatedBy:context.userId,securityOperationId:context.operationId,securityOperationFingerprint:context.requestFingerprint,securityActorId:context.userId},oldLines=current?this.lines.byField(context.tenantId,'estimateId',id,200):[],oldPricing=current?this.pricing.byField(context.tenantId,'estimateId',id,200):[],lineById={},pricingById={},lineUsed={},pricingUsed={},self=this;
  oldLines.forEach(function(row){if(String(row.status||'ACTIVE')!=='REMOVED')lineById[row.id]=row;});oldPricing.forEach(function(row){if(String(row.status||'ACTIVE')!=='REMOVED')pricingById[row.id]=row;});
  var prepared=rollup.lines.map(function(line,index){var prior=null,childId;if(line.id){prior=lineById[line.id];if(!prior||lineUsed[line.id])throw new VmosAuthorizationError_('Quote cost-line identity is unavailable for this estimate.');childId=line.id;lineUsed[childId]=true;}else childId=self.childId_('QCL',lineUsed,index,self.lines,context);return Object.assign({},line,{id:childId,tenantId:context.tenantId,estimateId:id,sequence:index+1,status:'ACTIVE',version:version,createdAt:prior?prior.createdAt:now,createdBy:prior?prior.createdBy:context.userId,updatedAt:now,updatedBy:context.userId,securityOperationId:context.operationId,securityOperationFingerprint:context.requestFingerprint,securityActorId:context.userId});});
  var pricing=(model.pricing||[]).map(function(item,index){var prior=null,childId;if(item.id){prior=pricingById[item.id];if(!prior||pricingUsed[item.id])throw new VmosAuthorizationError_('Quote pricing identity is unavailable for this estimate.');childId=item.id;pricingUsed[childId]=true;}else childId=self.childId_('QPD',pricingUsed,index,self.pricing,context);return Object.assign({},item,{id:childId,tenantId:context.tenantId,estimateId:id,quoteRevisionId:model.quoteRevisionId,status:'ACTIVE',version:version,createdAt:prior?prior.createdAt:now,createdBy:prior?prior.createdBy:context.userId,updatedAt:now,updatedBy:context.userId,securityOperationId:context.operationId,securityOperationFingerprint:context.requestFingerprint,securityActorId:context.userId});});
  this.persistIntents_(prepared.concat(pricing).concat([{id:id+'-MARKER',tenantId:context.tenantId,estimateId:id,securityOperationId:context.operationId,__aggregateMarker:true}]),context,id,'QUOTE_COST_AGGREGATE');if(current)this.estimates.update(id,record);else this.estimates.create(record);this.checkpoint({id:id,version:version},{aggregateType:'QUOTE_COST_AGGREGATE',quoteId:model.quoteId,quoteRevisionId:model.quoteRevisionId});
  var that=this;
  oldLines.forEach(function(x){if(!prepared.some(function(y){return y.id===x.id;}))that.lines.update(x.id,{status:'REMOVED',version:version,updatedAt:now,updatedBy:context.userId});});
  prepared.forEach(function(x){if(lineById[x.id])that.lines.update(x.id,x);else that.lines.create(x);if(that.mutationCheckpoints)that.mutationCheckpoints.update('QMCP-'+context.operationId+'-'+x.id,{status:'COMPLETED',completedAt:that.clock(),completedBy:context.userId});});
  oldPricing.forEach(function(x){if(!pricing.some(function(y){return y.id===x.id;}))that.pricing.update(x.id,{status:'REMOVED',version:version,updatedAt:now,updatedBy:context.userId});});
  pricing.forEach(function(x){if(pricingById[x.id])that.pricing.update(x.id,x);else that.pricing.create(x);if(that.mutationCheckpoints)that.mutationCheckpoints.update('QMCP-'+context.operationId+'-'+x.id,{status:'COMPLETED',completedAt:that.clock(),completedBy:context.userId});});
  if(this.mutationCheckpoints)this.mutationCheckpoints.update('QMCP-'+context.operationId+'-'+id+'-MARKER',{status:'COMPLETED',completedAt:this.clock(),completedBy:context.userId});
  return {estimate:record,rollup:Object.assign({},rollup,{lines:prepared}),pricing:pricing,reconciliation:this.engine.reconcileSuppliers(prepared)};
};
QuoteCostingService_.prototype.read=function(quoteId,context,options){options=options||{};this.tenant_(this.quotes.get(quoteId),context,'Quote');var estimates=this.estimates.byField(context.tenantId,'quoteId',quoteId,10).sort(function(a,b){return Number(b.estimateVersion)-Number(a.estimateVersion);}),estimate=estimates[0]||null;if(!estimate)return {estimate:null,lines:[],pricing:[],documents:[],warning:'Internal costing has not been completed.'};var lines=this.lines.byField(context.tenantId,'estimateId',estimate.id,options.limit||50).filter(function(x){return String(x.status||'ACTIVE')!=='REMOVED';}),pricing=options.canManagePricing||options.canReadMargin?this.pricing.byField(context.tenantId,'estimateId',estimate.id,50).filter(function(x){return String(x.status||'ACTIVE')!=='REMOVED';}):[],vendorMap={};this.vendors.forTenant(context.tenantId).filter(function(vendor){return String(vendor.status||'ACTIVE').toUpperCase()==='ACTIVE';}).forEach(function(vendor){vendorMap[vendor.id]=vendor;});lines=lines.map(function(line){var copy=Object.assign({},line),vendor=line.vendorId&&vendorMap[line.vendorId];if(line.vendorId){copy.vendorName=vendor?String(vendor.name||''):'Vendor unavailable';copy.vendorReferenceState=vendor?'AVAILABLE':'UNAVAILABLE';}return copy;});return {estimate:estimate,lines:lines,pricing:pricing,documents:this.documents.byField(context.tenantId,'estimateId',estimate.id,50),reconciliation:this.engine.reconcileSuppliers(lines)};};
QuoteCostingService_.prototype.customerProjection=function(quote,revision,customerLines){return {quote:{id:quote.id,status:quote.status,currency:quote.currency||'USD'},revision:{id:revision.id,revision:revision.revision,status:revision.status},lines:(customerLines||[]).map(function(line){return {description:line.description,quantity:line.quantity,unitPriceMinor:line.unitPriceMinor,extendedPriceMinor:line.extendedPriceMinor,lineType:line.lineType||'RECURRING'};})};};
