/** Bounded Quote Builder read model and contextual human-readable pickers. */
function QuoteBuilderReadService_(deps){deps=deps||{};this.customers=deps.customers||new MvpService_('Customer');this.rfqs=deps.rfqs||new MvpService_('RFQ');this.quotes=deps.quotes||new MvpService_('Quote');this.vendors=deps.vendors||new VendorService_();this.costing=deps.costing||new QuoteCostingService_();this.sources=deps.sources||(typeof QuoteSourceDocumentService_!=='undefined'?new QuoteSourceDocumentService_({quotes:this.quotes,rfqs:this.rfqs,customers:this.customers}):{searchDocuments:function(){return {items:[],bounded:true,limit:50};},list:function(){return[];}});this.limit=Math.min(100,Math.max(1,Number(deps.limit||50)));}
QuoteBuilderReadService_.prototype.tenant_=function(rows,context){return (rows||[]).filter(function(row){return String(row.securityTenantId||row.tenantId)===String(context.tenantId);});};
QuoteBuilderReadService_.prototype.customerMap_=function(context){var map={};this.tenant_(this.customers.list(),context).forEach(function(row){map[row.id]=row.name;});return map;};
QuoteBuilderReadService_.prototype.search=function(type,query,contextId,limit,context){var max=Math.min(100,Math.max(1,Number(limit||this.limit))),term=String(query||'').trim().toLowerCase(),customers=this.customerMap_(context),items=[];
  if(type==='VENDOR')return {items:this.vendors.search(query,context,max,contextId||''),bounded:true,limit:max};
  if(type==='DOCUMENT')return this.sources.searchDocuments(query,context,Math.min(50,max));
  if(type==='CUSTOMER')items=this.tenant_(this.customers.list(),context).filter(function(row){return !term||String(row.name+' '+row.id).toLowerCase().indexOf(term)!==-1;}).map(function(row){return {id:row.id,label:row.name,secondary:row.status||''};});
  else if(type==='RFQ'){var quoted={};this.tenant_(this.quotes.list(),context).forEach(function(row){quoted[row.rfqId]=true;});items=this.tenant_(this.rfqs.list(),context).filter(function(row){var text=String(row.customerRfqNumber+' '+customers[row.customerId]+' '+row.description+' '+row.id).toLowerCase();return !quoted[row.id]&&(!contextId||row.customerId===contextId)&&(!term||text.indexOf(term)!==-1);}).sort(function(a,b){return String(b.receivedDate||b.createdAt||'').localeCompare(String(a.receivedDate||a.createdAt||''));}).map(function(row){return {id:row.id,label:(row.customerRfqNumber||row.id)+' — '+(customers[row.customerId]||'Customer')+' — '+(row.description||'RFQ'),secondary:[row.receivedDate,row.status].filter(Boolean).join(' · '),customerId:row.customerId};});}
  else throw new VmosValidationError_('Record picker type is invalid.');
  return {items:items.slice(0,max),bounded:true,limit:max,hasMore:items.length>max};
};
QuoteBuilderReadService_.prototype.get=function(request,context){request=request||{};var quote=null,rfq=null,customer=null;if(request.quoteId){quote=this.tenant_([this.quotes.get(request.quoteId)],context)[0];if(!quote)throw new VmosAuthorizationError_('Quote is unavailable.');rfq=this.tenant_([this.rfqs.get(quote.rfqId)],context)[0];customer=this.tenant_([this.customers.get(quote.customerId)],context)[0];}else if(request.rfqId){rfq=this.tenant_([this.rfqs.get(request.rfqId)],context)[0];if(!rfq)throw new VmosAuthorizationError_('RFQ is unavailable.');customer=this.tenant_([this.customers.get(rfq.customerId)],context)[0];}else if(request.customerId){customer=this.tenant_([this.customers.get(request.customerId)],context)[0];if(!customer)throw new VmosAuthorizationError_('Customer is unavailable.');}
  var caps=context.capabilities||[],canCost=caps.indexOf('QUOTE_COST_READ')!==-1,costing=quote&&canCost?this.costing.read(quote.id,context,{canManagePricing:caps.indexOf('QUOTE_PRICING_MANAGE')!==-1,canReadMargin:caps.indexOf('QUOTE_MARGIN_READ')!==-1}):null,sources=[],sourceState='AVAILABLE';if(quote&&canCost){try{sources=this.sources.list(quote.id,context,50);}catch(error){sourceState='CONFIGURATION_UNAVAILABLE';}}
  return {quote:quote,rfq:rfq,customer:customer,currency:quote&&quote.currency||'USD',costing:costing,sources:sources,sourceState:sourceState,permissions:{costRead:canCost,costWrite:caps.indexOf('QUOTE_COST_WRITE')!==-1,pricingManage:caps.indexOf('QUOTE_PRICING_MANAGE')!==-1,marginRead:caps.indexOf('QUOTE_MARGIN_READ')!==-1,approve:caps.indexOf('QUOTE_APPROVE')!==-1,issue:caps.indexOf('QUOTE_ISSUE')!==-1,createJob:caps.indexOf('OPERATIONS_WRITE')!==-1},bounds:{picker:50,costLines:50,sourceDocuments:50},costingWarning:!costing||!costing.estimate?'Internal costing is incomplete. Quote issuance remains available to authorized users.':''};
};
