/** MOS-126F customer-commercial revision boundary. Internal costing is never projected here. */
var ATLAS_QUOTE_REVISION_STATUSES=['DRAFT','ISSUED','ACCEPTED','SUPERSEDED','EXPIRED','VOIDED'];
function QuoteRevisionService_(deps){deps=deps||{};this.revisions=deps.revisions||new QuoteRevisionRepository_();this.lines=deps.lines||new QuoteLineItemRepository_();this.quotes=deps.quotes||new MvpService_('Quote');this.customers=deps.customers||new MvpService_('Customer');this.clock=deps.clock||function(){return new Date();};this.uuid=deps.uuid||function(){return Utilities.getUuid().toUpperCase();};}
QuoteRevisionService_.prototype.assertTenant_=function(row,context,label){if(!row||String(row.tenantId||row.securityTenantId)!==String(context.tenantId))throw new VmosAuthorizationError_((label||'Quote')+' is unavailable.');return row;};
QuoteRevisionService_.prototype.linesFor_=function(id,tenantId){return this.lines.byField(tenantId,'quoteRevisionId',id,100).filter(function(x){return x.status!=='REPLACED';}).sort(function(a,b){return Number(a.sequence)-Number(b.sequence);});};
QuoteRevisionService_.prototype.totals_=function(lines){var recurring=0n,oneTime=0n;lines.forEach(function(line){var extended=atlasMultiplyMinorByDecimal_(line.unitPriceMinor,line.quantity);if(String(extended)!==String(atlasMinor_(line.extendedPriceMinor,'Extended price')))throw new VmosValidationError_('Quote line total does not reconcile.');if(line.lineType==='ONE_TIME')oneTime+=BigInt(extended);else recurring+=BigInt(extended);});return {recurring:String(recurring),oneTime:String(oneTime),total:String(recurring+oneTime)};};
QuoteRevisionService_.prototype.saveDraft=function(model,context,revisionId){
  model=model||{};var quote=this.assertTenant_(this.quotes.get(model.quoteId),context),customer=this.assertTenant_(this.customers.get(quote.customerId),context,'Customer'),current=model.id?this.assertTenant_(this.revisions.get(model.id),context,'Quote revision'):null;
  if(current&&current.status!=='DRAFT')throw new VmosConflictError('Issued Quote revisions are immutable. Create a new revision.');if(!model.lines||!model.lines.length)throw new VmosValidationError_('At least one customer line is required.');
  var existing=this.revisions.byField(context.tenantId,'quoteId',quote.id,100),number=current?Number(current.revisionNumber):existing.reduce(function(n,x){return Math.max(n,Number(x.revisionNumber||0));},0)+1,id=current?current.id:(revisionId||'QREV-'+this.uuid()),now=this.clock();
  var prepared=model.lines.map(function(line,index){var quantity=atlasDecimal_(line.quantity,4,'Quantity').text,unit=atlasMinor_(line.unitPriceMinor,'Unit price'),extended=atlasMultiplyMinorByDecimal_(unit,quantity),type=String(line.lineType||'RECURRING').toUpperCase();if(['RECURRING','ONE_TIME'].indexOf(type)===-1)throw new VmosValidationError_('Customer line type is invalid.');return {id:id+'-L'+String(index+1),tenantId:context.tenantId,quoteRevisionId:id,sequence:index+1,lineType:type,description:String(line.description||'').trim(),quantity:quantity,unitPriceMinor:unit,extendedPriceMinor:extended,currency:String(model.currency||'USD').toUpperCase(),status:'ACTIVE',version:current?Number(current.version||1)+1:1,createdAt:current?current.createdAt:now,createdBy:current?current.createdBy:context.userId,updatedAt:now,updatedBy:context.userId,securityOperationId:context.operationId,securityOperationFingerprint:context.requestFingerprint,securityActorId:context.userId};}),totals=this.totals_(prepared);
  var record={id:id,tenantId:context.tenantId,quoteId:quote.id,rfqId:quote.rfqId,customerId:quote.customerId,revisionNumber:number,status:'DRAFT',currency:String(model.currency||'USD').toUpperCase(),customerName:customer.name||'',quoteNumber:quote.id,description:String(model.description||prepared[0].description||''),recurringTotalMinor:totals.recurring,oneTimeTotalMinor:totals.oneTime,totalMinor:totals.total,paymentTerms:String(model.paymentTerms||quote.paymentTerms||''),customerNotes:String(model.customerNotes||''),validThrough:model.validThrough||'',version:current?Number(current.version||1)+1:1,createdAt:current?current.createdAt:now,createdBy:current?current.createdBy:context.userId,updatedAt:now,updatedBy:context.userId,securityOperationId:context.operationId,securityOperationFingerprint:context.requestFingerprint,securityActorId:context.userId};
  if(current)this.revisions.update(id,record);else this.revisions.create(record);var old=current?this.linesFor_(id,context.tenantId):[],that=this;old.forEach(function(x){if(!prepared.some(function(y){return y.id===x.id;}))that.lines.update(x.id,{status:'REPLACED',updatedAt:now,updatedBy:context.userId});});prepared.forEach(function(x){if(that.lines.get(x.id))that.lines.update(x.id,x);else that.lines.create(x);});return {revision:record,lines:prepared};
};
QuoteRevisionService_.prototype.issue=function(id,expectedVersion,context){
  var row=this.assertTenant_(this.revisions.get(id),context,'Quote revision');if(row.status==='ISSUED')return this.output(id,context);if(row.status!=='DRAFT'||Number(row.version)!==Number(expectedVersion))throw new VmosConflictError('Quote revision changed. Refresh before issuing.');if(!this.linesFor_(id,context.tenantId).length)throw new VmosValidationError_('Customer pricing is required before issue.');
  var now=this.clock(),that=this;this.revisions.byField(context.tenantId,'quoteId',row.quoteId,100).forEach(function(prior){if(prior.id!==id&&prior.status==='ISSUED')that.revisions.update(prior.id,{status:'SUPERSEDED',supersededAt:now,updatedAt:now,updatedBy:context.userId,version:Number(prior.version||1)+1});});row=this.revisions.update(id,{status:'ISSUED',issueDate:now,issuedAt:now,issuedBy:context.userId,updatedAt:now,updatedBy:context.userId,version:Number(row.version)+1});
  var quote=this.assertTenant_(this.quotes.get(row.quoteId),context);new MvpService_('Quote',{repository:this.quotes.repository||this.quotes,auditUser:function(){return context.userId;}}).update(quote.id,{status:'Issued',currentRevisionId:id,issuedRevisionId:id,total:Number(row.totalMinor)/100,notes:'Issued customer revision '+row.revisionNumber});return this.output(id,context);
};
QuoteRevisionService_.prototype.accept=function(id,expectedVersion,context){
  var row=this.assertTenant_(this.revisions.get(id),context,'Quote revision');if(row.status==='ACCEPTED')return this.output(id,context);if(row.status!=='ISSUED'||Number(row.version)!==Number(expectedVersion))throw new VmosConflictError('Only the current issued revision can be accepted. Refresh first.');var newer=this.revisions.byField(context.tenantId,'quoteId',row.quoteId,100).some(function(x){return x.id!==row.id&&(x.status==='ISSUED'||x.status==='ACCEPTED')&&Number(x.revisionNumber)>Number(row.revisionNumber);});if(newer)throw new VmosConflictError('This Quote revision has been superseded.');
  var now=this.clock();row=this.revisions.update(id,{status:'ACCEPTED',acceptedAt:now,acceptedBy:context.userId,updatedAt:now,updatedBy:context.userId,version:Number(row.version)+1});var quote=this.assertTenant_(this.quotes.get(row.quoteId),context);new MvpService_('Quote',{repository:this.quotes.repository||this.quotes,auditUser:function(){return context.userId;}}).update(quote.id,{status:'Accepted',currentRevisionId:id,acceptedRevisionId:id,notes:'Accepted customer revision '+row.revisionNumber});return this.output(id,context);
};
QuoteRevisionService_.prototype.output=function(id,context){var r=this.assertTenant_(this.revisions.get(id),context,'Quote revision');if(['ISSUED','ACCEPTED','SUPERSEDED','EXPIRED','VOIDED'].indexOf(r.status)===-1)throw new VmosConflictError('A customer Quote is available only after issue.');return {quoteNumber:r.quoteNumber,revision:r.revisionNumber,status:r.status,customer:r.customerName,description:r.description,currency:r.currency,issueDate:r.issueDate,validThrough:r.validThrough,paymentTerms:r.paymentTerms,customerNotes:r.customerNotes,recurringTotalMinor:r.recurringTotalMinor,oneTimeTotalMinor:r.oneTimeTotalMinor,totalMinor:r.totalMinor,lines:this.linesFor_(id,context.tenantId).map(function(x){return {description:x.description,quantity:x.quantity,unitPriceMinor:x.unitPriceMinor,extendedPriceMinor:x.extendedPriceMinor,lineType:x.lineType};})};};
QuoteRevisionService_.prototype.current=function(quoteId,context){this.assertTenant_(this.quotes.get(quoteId),context);var rows=this.revisions.byField(context.tenantId,'quoteId',quoteId,100).sort(function(a,b){return Number(b.revisionNumber)-Number(a.revisionNumber);});return rows[0]?{revision:rows[0],lines:this.linesFor_(rows[0].id,context.tenantId)}:null;};
