/** Beta CRM module: all persistence and authorization collaborators are injected. */
var SALES_ACTIVITY_TYPES=['IN_PERSON_VISIT','PHONE_CALL','TEXT_MESSAGE','EMAIL','MATERIAL_DROP_OFF','FOLLOW_UP','REFERRAL','SOCIAL_MEDIA','MEETING','OTHER'];
var SALES_ACTIVITY_OUTCOMES=['INTERESTED','FOLLOW_UP_REQUIRED','NOT_INTERESTED','DECISION_MAKER_UNAVAILABLE','LEFT_MATERIALS','REQUESTED_PRICING','REQUESTED_SAMPLE','REQUESTED_CALLBACK','REFERRED_ELSEWHERE','NO_RESPONSE','WON','LOST','OTHER'];
var SALES_MATERIAL_TYPES=['BUSINESS_CARDS','DEALER_PACKET','PRICE_SHEET','SAMPLE','DISPLAY','FLYER','OTHER'];
var SALES_OPEN_STATUSES=['OPEN','FOLLOW_UP_DUE','OVERDUE'];
function SalesActivityService(deps){this.deps=deps||{};this.repository=this.deps.repository;this.accounts=this.deps.accounts;this.authorizer=this.deps.authorizer||{can:function(){return true;}};this.clock=this.deps.clock||function(){return new Date();};this.idGenerator=this.deps.idGenerator||function(){return 'SACT-'+Utilities.getUuid().toUpperCase();};}
SalesActivityService.prototype.create=function(input,actor){input=input||{};this.requirePermission_(actor,'sales:write',input);this.validate_(input);if(this.accounts&&this.accounts.get&&!this.accounts.get(input.customerId))throw new VmosNotFoundError('Customer account not found.');var now=this.clock(),status=this.resolveStatus_(input,now),record={id:this.idGenerator(),customerId:input.customerId,contactId:input.contactId||'',opportunityId:input.opportunityId||'',activityType:input.activityType,activityDatetime:new Date(input.activityDatetime),ownerUserId:input.ownerUserId||actor,createdByUserId:actor,summary:input.summary,notes:input.notes||'',outcome:input.outcome,materialsLeft:!!input.materialsLeft,materialType:input.materialType||'',quantityLeft:input.quantityLeft===undefined||input.quantityLeft===''?'':Number(input.quantityLeft),location:input.location||'',nextAction:input.nextAction||'',nextActionDueAt:input.nextActionDueAt?new Date(input.nextActionDueAt):'',followUpOwnerUserId:input.followUpOwnerUserId||input.ownerUserId||actor,status:status,createdAt:now,updatedAt:now};return this.repository.create(record);};
SalesActivityService.prototype.update=function(id,changes,actor){var existing=this.repository.get(id);if(!existing)throw new VmosNotFoundError('Sales activity not found.');if(existing.ownerUserId!==actor&&!this.authorizer.can(actor,'sales:manage',existing))throw new VmosValidationError('Only the activity owner or a manager can update this activity.');var proposed={};Object.keys(existing).forEach(function(k){proposed[k]=existing[k];});Object.keys(changes||{}).forEach(function(k){if(k!=='id'&&k!=='customerId'&&k!=='createdByUserId'&&k!=='createdAt')proposed[k]=changes[k];});this.validate_(proposed);proposed.status=this.resolveStatus_(proposed,this.clock());proposed.updatedAt=this.clock();return this.repository.update(id,proposed);};
SalesActivityService.prototype.listTimeline=function(customerId){return this.repository.listByCustomerId(customerId).sort(function(a,b){return new Date(b.activityDatetime)-new Date(a.activityDatetime);});};
SalesActivityService.prototype.followUpQueue=function(now){now=now||this.clock();var groups={dueToday:[],overdue:[],upcoming:[]};this.repository.listOpen().forEach(function(activity){var due=new Date(activity.nextActionDueAt),today=new Date(now);today.setHours(0,0,0,0);var tomorrow=new Date(today);tomorrow.setDate(tomorrow.getDate()+1);if(due<today)groups.overdue.push(activity);else if(due<tomorrow)groups.dueToday.push(activity);else groups.upcoming.push(activity);});Object.keys(groups).forEach(function(k){groups[k].sort(function(a,b){return new Date(a.nextActionDueAt)-new Date(b.nextActionDueAt);});});return groups;};
SalesActivityService.prototype.accountFollowUpHealth=function(customerId,now){now=now||this.clock();var timeline=this.listTimeline(customerId),last=timeline[0];if(!last)return {customerId:customerId,lastContactAt:'',staleness:'SERIOUSLY_STALE',openWithoutNextAction:true};var days=Math.floor((now-new Date(last.activityDatetime))/86400000),open=SALES_OPEN_STATUSES.indexOf(last.status)!==-1;return {customerId:customerId,lastContactAt:last.activityDatetime,daysSinceLastContact:days,staleness:open?(days>=30?'SERIOUSLY_STALE':days>=14?'STALE':days>=7?'REMINDER':'CURRENT'):'CLOSED',openWithoutNextAction:open&&(!last.nextAction||!last.nextActionDueAt)};};
SalesActivityService.prototype.resolveStatus_=function(input,now){if(input.outcome==='WON')return 'CLOSED_WON';if(input.outcome==='LOST')return 'CLOSED_LOST';if(new Date(input.nextActionDueAt)<new Date(now).setHours(0,0,0,0))return 'OVERDUE';if(new Date(input.nextActionDueAt).toDateString()===new Date(now).toDateString())return 'FOLLOW_UP_DUE';return 'OPEN';};
SalesActivityService.prototype.validate_=function(input){if(!input.customerId)throw new VmosValidationError('Customer account is required.');if(SALES_ACTIVITY_TYPES.indexOf(input.activityType)===-1)throw new VmosValidationError('A valid activity type is required.');if(SALES_ACTIVITY_OUTCOMES.indexOf(input.outcome)===-1)throw new VmosValidationError('A valid outcome is required.');if(!input.activityDatetime||isNaN(new Date(input.activityDatetime)))throw new VmosValidationError('Activity date and time are required.');if(!String(input.summary||'').trim())throw new VmosValidationError('A short activity summary is required.');if(input.activityType==='MATERIAL_DROP_OFF'&&input.materialType&&SALES_MATERIAL_TYPES.indexOf(input.materialType)===-1)throw new VmosValidationError('A valid material type is required.');if(input.outcome!=='WON'&&input.outcome!=='LOST'&&(!String(input.nextAction||'').trim()||!input.nextActionDueAt))throw new VmosValidationError('Open sales activity requires a next action and due date.');};
SalesActivityService.prototype.requirePermission_=function(actor,permission,subject){if(!actor||!this.authorizer.can(actor,permission,subject))throw new VmosValidationError('You do not have permission to record sales activity.');};
