var SALES_ACTIVITY_TYPES=['IN_PERSON_VISIT','PHONE_CALL','TEXT_MESSAGE','EMAIL','MATERIAL_DROP_OFF','FOLLOW_UP','REFERRAL','SOCIAL_MEDIA','MEETING','OTHER'];
var SALES_ACTIVITY_OUTCOMES=['INTERESTED','FOLLOW_UP_REQUIRED','NOT_INTERESTED','DECISION_MAKER_UNAVAILABLE','LEFT_MATERIALS','REQUESTED_PRICING','REQUESTED_SAMPLE','REQUESTED_CALLBACK','REFERRED_ELSEWHERE','NO_RESPONSE','WON','LOST','OTHER'];
var SALES_MATERIAL_TYPES=['BUSINESS_CARDS','DEALER_PACKET','PRICE_SHEET','SAMPLE','DISPLAY','FLYER','OTHER'];
function SalesActivityService_(deps){this.deps=deps||{};this.repository=this.deps.repository;this.accounts=this.deps.accounts;this.authorizer=this.deps.authorizer||{can:function(){return true;}};this.clock=this.deps.clock||function(){return new Date();};this.idGenerator=this.deps.idGenerator||function(repository){return generateVmosId_('SACT',repository);};}
SalesActivityService_.prototype.create=function(input,actor){input=input||{};this.require_(actor,'sales:write',input);this.validate_(input);if(this.accounts&&this.accounts.get&&!this.accounts.get(input.customerId))throw new VmosNotFoundError_('Customer account not found.');var now=this.clock(),record={id:this.idGenerator(this.repository),customerId:input.customerId,contactId:input.contactId||'',opportunityId:input.opportunityId||'',activityType:input.activityType,activityDatetime:new Date(input.activityDatetime),ownerUserId:input.ownerUserId||actor,createdByUserId:actor,summary:input.summary,notes:input.notes||'',outcome:input.outcome,materialsLeft:!!input.materialsLeft,materialType:input.materialType||'',quantityLeft:input.quantityLeft===undefined||input.quantityLeft===''?'':Number(input.quantityLeft),location:input.location||'',nextAction:input.nextAction||'',nextActionDueAt:input.nextActionDueAt?new Date(input.nextActionDueAt):'',followUpOwnerUserId:input.followUpOwnerUserId||input.ownerUserId||actor,status:this.lifecycleStatus_(input),createdAt:now,updatedAt:now};return this.decorate_(this.repository.create(record),now);};
SalesActivityService_.prototype.update=function(id,changes,actor){var existing=this.repository.get(id);if(!existing)throw new VmosNotFoundError_('Sales activity not found.');if(existing.ownerUserId!==actor&&!this.authorizer.can(actor,'sales:manage',existing))throw new VmosValidationError_('Only the activity owner or a manager can update this activity.');var proposed={};Object.keys(existing).forEach(function(k){proposed[k]=existing[k];});Object.keys(changes||{}).forEach(function(k){if(['id','customerId','createdByUserId','createdAt'].indexOf(k)===-1)proposed[k]=changes[k];});this.validate_(proposed);proposed.status=this.lifecycleStatus_(proposed);proposed.updatedAt=this.clock();return this.decorate_(this.repository.update(id,proposed),this.clock());};
SalesActivityService_.prototype.listTimeline=function(customerId,now){var self=this;return this.repository.listByCustomerId(customerId).map(function(a){return self.decorate_(a,now||self.clock());}).sort(function(a,b){return new Date(b.activityDatetime)-new Date(a.activityDatetime);});};
SalesActivityService_.prototype.followUpQueue=function(now){var self=this,groups={dueToday:[],overdue:[],upcoming:[]},today=new Date(now||this.clock());today.setHours(0,0,0,0);var tomorrow=new Date(today);tomorrow.setDate(tomorrow.getDate()+1);this.repository.listOpen().forEach(function(activity){var decorated=self.decorate_(activity,now),due=new Date(activity.nextActionDueAt);if(decorated.status==='OVERDUE')groups.overdue.push(decorated);else if(due<tomorrow)groups.dueToday.push(decorated);else groups.upcoming.push(decorated);});Object.keys(groups).forEach(function(key){groups[key].sort(function(a,b){return new Date(a.nextActionDueAt)-new Date(b.nextActionDueAt);});});return groups;};
SalesActivityService_.prototype.accountFollowUpHealth=function(customerId,now){var timeline=this.listTimeline(customerId,now),last=timeline[0],today=now||this.clock();if(!last)return {customerId:customerId,lastContactAt:'',daysSinceLastContact:null,staleness:'SERIOUSLY_STALE',openWithoutNextAction:true};var days=Math.floor((new Date(today)-new Date(last.activityDatetime))/86400000),open=last.status!=='CLOSED_WON'&&last.status!=='CLOSED_LOST';return {customerId:customerId,lastContactAt:last.activityDatetime,daysSinceLastContact:days,staleness:open?(days>=30?'SERIOUSLY_STALE':days>=14?'STALE':days>=7?'REMINDER':'CURRENT'):'CLOSED',openWithoutNextAction:open&&(!last.nextAction||!last.nextActionDueAt)};};
SalesActivityService_.prototype.metrics=function(now){var self=this,at=now||this.clock(),weekAgo=new Date(at);weekAgo.setDate(weekAgo.getDate()-7);var rows=this.repository.list(),byCustomer={};rows.forEach(function(row){(byCustomer[row.customerId]||(byCustomer[row.customerId]=[])).push(row);});var queue=this.followUpQueue(at),health=Object.keys(byCustomer).map(function(id){return self.accountFollowUpHealth(id,at);}),recent={};rows.forEach(function(row){if(new Date(row.activityDatetime)>=weekAgo)recent[row.customerId]=true;});var lastDays=health.filter(function(h){return h.daysSinceLastContact!==null;}).map(function(h){return h.daysSinceLastContact;});return {accountsContactedThisWeek:Object.keys(recent).length,followUpsDueToday:queue.dueToday.length,overdueFollowUps:queue.overdue.length,openAccountFollowUps:health.filter(function(h){return h.staleness!=='CLOSED';}).length,conversions:rows.filter(function(r){return r.outcome==='WON';}).length,averageDaysSinceLastContact:lastDays.length?lastDays.reduce(function(a,b){return a+b;},0)/lastDays.length:0,materialsDroppedOff:rows.filter(function(r){return r.activityType==='MATERIAL_DROP_OFF';}).length,accountsWithNoNextAction:health.filter(function(h){return h.openWithoutNextAction;}).length};};
SalesActivityService_.prototype.lifecycleStatus_=function(input){return input.outcome==='WON'?'CLOSED_WON':input.outcome==='LOST'?'CLOSED_LOST':'OPEN';};
SalesActivityService_.prototype.decorate_=function(activity,now){var out={};Object.keys(activity).forEach(function(k){out[k]=activity[k];});if(out.status==='CLOSED_WON'||out.status==='CLOSED_LOST')return out;var due=new Date(out.nextActionDueAt),today=new Date(now||this.clock());today.setHours(0,0,0,0);var tomorrow=new Date(today);tomorrow.setDate(tomorrow.getDate()+1);out.status=due<today?'OVERDUE':due<tomorrow?'FOLLOW_UP_DUE':'OPEN';return out;};
SalesActivityService_.prototype.validate_=function(input){if(!input.customerId)throw new VmosValidationError_('Customer account is required.');if(SALES_ACTIVITY_TYPES.indexOf(input.activityType)===-1)throw new VmosValidationError_('A valid activity type is required.');if(SALES_ACTIVITY_OUTCOMES.indexOf(input.outcome)===-1)throw new VmosValidationError_('A valid outcome is required.');if(!input.activityDatetime||isNaN(new Date(input.activityDatetime)))throw new VmosValidationError_('Activity date and time are required.');if(!String(input.summary||'').trim())throw new VmosValidationError_('A short activity summary is required.');if(input.activityType==='MATERIAL_DROP_OFF'&&input.materialType&&SALES_MATERIAL_TYPES.indexOf(input.materialType)===-1)throw new VmosValidationError_('A valid material type is required.');if(input.outcome!=='WON'&&input.outcome!=='LOST'&&(!String(input.nextAction||'').trim()||!input.nextActionDueAt))throw new VmosValidationError_('Open sales activity requires a next action and due date.');};
SalesActivityService_.prototype.require_=function(actor,permission,subject){if(!actor||!this.authorizer.can(actor,permission,subject))throw new VmosValidationError_('You do not have permission to record sales activity.');};
SalesActivityService_.prototype.allocateId=function(){return this.idGenerator(this.repository);};
function createSalesActivityService_(authorizedActor){var repository=new SalesActivityRepository_(),actor=authorizedActor||getVmosAuditUser_();return new SalesActivityService_({repository:repository,accounts:new MvpService_('Customer'),authorizer:{can:function(candidate,permission){if(permission==='sales:write')return candidate===actor;return candidate===actor;}}});}
