function CommercialRepository_(entity,mapping,adapter){this.repository=adapter||new SheetsRepository_(entity,mapping,SpreadsheetApp.openById(getVmosConfig_().spreadsheetId));}
CommercialRepository_.prototype.list=function(){return this.repository.list();}; CommercialRepository_.prototype.get=function(id){return this.repository.findById(id);}; CommercialRepository_.prototype.create=function(record){return this.repository.insert(record);}; CommercialRepository_.prototype.update=function(id,changes){return this.repository.updateById(id,changes);};
function commercialBounded_(rows,limit){return rows.slice(0,Math.min(200,Math.max(1,Number(limit||50))));}
function AtlasTenantRepository_(adapter){CommercialRepository_.call(this,'AtlasTenant',ATLAS_COMMERCIAL_MAPPINGS.Tenant,adapter);} AtlasTenantRepository_.prototype=Object.create(CommercialRepository_.prototype); AtlasTenantRepository_.prototype.search=function(query,limit){var needle=String(query||'').toLowerCase();return commercialBounded_(this.list().filter(function(row){return !needle||String(row.id+' '+row.displayName+' '+row.commercialState).toLowerCase().indexOf(needle)!==-1;}),limit);};
function AtlasPlanVersionRepository_(adapter){CommercialRepository_.call(this,'AtlasPlanVersion',ATLAS_COMMERCIAL_MAPPINGS.PlanVersion,adapter);} AtlasPlanVersionRepository_.prototype=Object.create(CommercialRepository_.prototype);
function AtlasSubscriptionRepository_(adapter){CommercialRepository_.call(this,'AtlasSubscription',ATLAS_COMMERCIAL_MAPPINGS.Subscription,adapter);} AtlasSubscriptionRepository_.prototype=Object.create(CommercialRepository_.prototype); AtlasSubscriptionRepository_.prototype.findForTenant=function(tenantId){return this.list().filter(function(row){return String(row.tenantId)===String(tenantId);});};
function AtlasEntitlementRepository_(adapter){CommercialRepository_.call(this,'AtlasEntitlement',ATLAS_COMMERCIAL_MAPPINGS.Entitlement,adapter);} AtlasEntitlementRepository_.prototype=Object.create(CommercialRepository_.prototype); AtlasEntitlementRepository_.prototype.listForTenant=function(tenantId){return this.list().filter(function(row){return String(row.tenantId)===String(tenantId);});};
function AtlasSeatAssignmentRepository_(adapter){CommercialRepository_.call(this,'AtlasSeatAssignment',ATLAS_COMMERCIAL_MAPPINGS.SeatAssignment,adapter);} AtlasSeatAssignmentRepository_.prototype=Object.create(CommercialRepository_.prototype); AtlasSeatAssignmentRepository_.prototype.listForTenant=function(tenantId){return this.list().filter(function(row){return String(row.tenantId)===String(tenantId);});};
function AtlasTenantInvitationRepository_(adapter){CommercialRepository_.call(this,'AtlasTenantInvitation',ATLAS_COMMERCIAL_MAPPINGS.Invitation,adapter);} AtlasTenantInvitationRepository_.prototype=Object.create(CommercialRepository_.prototype); AtlasTenantInvitationRepository_.prototype.listForTenant=function(tenantId,limit){return commercialBounded_(this.list().filter(function(row){return String(row.tenantId)===String(tenantId);}),limit);};
function AtlasInvoiceSnapshotRepository_(adapter){CommercialRepository_.call(this,'AtlasInvoiceSnapshot',ATLAS_COMMERCIAL_MAPPINGS.InvoiceSnapshot,adapter);} AtlasInvoiceSnapshotRepository_.prototype=Object.create(CommercialRepository_.prototype); AtlasInvoiceSnapshotRepository_.prototype.recentForTenant=function(tenantId,limit){return commercialBounded_(this.list().filter(function(row){return String(row.tenantId)===String(tenantId);}).sort(function(a,b){return String(b.invoiceDate).localeCompare(String(a.invoiceDate));}),limit);};
function AtlasBillingProviderEventRepository_(adapter){CommercialRepository_.call(this,'AtlasBillingProviderEvent',ATLAS_COMMERCIAL_MAPPINGS.ProviderEvent,adapter);} AtlasBillingProviderEventRepository_.prototype=Object.create(CommercialRepository_.prototype); AtlasBillingProviderEventRepository_.prototype.findByProviderEvent=function(providerKey,eventId){return this.list().filter(function(row){return row.providerKey===providerKey&&row.providerEventId===eventId;})[0];};
function AtlasBillingReconciliationRepository_(adapter){CommercialRepository_.call(this,'AtlasBillingReconciliation',ATLAS_COMMERCIAL_MAPPINGS.Reconciliation,adapter);} AtlasBillingReconciliationRepository_.prototype=Object.create(CommercialRepository_.prototype); AtlasBillingReconciliationRepository_.prototype.recentAttention=function(limit){return commercialBounded_(this.list().filter(function(row){return ['PENDING','REVIEW_REQUIRED','FAILED'].indexOf(row.status)!==-1;}),limit);};
function AtlasCommercialAuditRepository_(adapter){CommercialRepository_.call(this,'AtlasCommercialAuditEvent',ATLAS_COMMERCIAL_MAPPINGS.AuditEvent,adapter);} AtlasCommercialAuditRepository_.prototype=Object.create(CommercialRepository_.prototype); AtlasCommercialAuditRepository_.prototype.findByCommand=function(tenantId,commandId){return this.list().filter(function(row){return String(row.tenantId)===String(tenantId)&&String(row.commandId)===String(commandId);})[0];}; AtlasCommercialAuditRepository_.prototype.recentForTenant=function(tenantId,limit){return commercialBounded_(this.list().filter(function(row){return String(row.tenantId)===String(tenantId);}).sort(function(a,b){return String(b.occurredAt).localeCompare(String(a.occurredAt));}),limit);};
