/** Additive MOS-126 Vendor and Quote-costing stores. No live sheets are created here. */
var ATLAS_QUOTE_COSTING_MAPPINGS={
  Vendor:{sheetName:'Vendors',idField:'VendorID',fields:{id:['VendorID'],tenantId:['TenantID'],name:['Vendor Name'],supplyType:['Supply Type'],status:['Status'],website:['Website'],paymentTerms:['Payment Terms'],typicalLeadTime:['Typical Lead Time'],minimumOrderMinor:['Minimum Order Minor'],currency:['Currency'],preferred:['Preferred Vendor'],notes:['Notes'],version:['Version'],createdAt:['Created At'],createdBy:['Created By'],updatedAt:['Updated At'],updatedBy:['Updated By'],securityOperationId:['Security Operation ID'],securityOperationFingerprint:['Security Operation Fingerprint'],securityActorId:['Security Actor ID']}},
  VendorCapability:{sheetName:'VendorCapabilities',idField:'VendorCapabilityID',fields:{id:['VendorCapabilityID'],tenantId:['TenantID'],vendorId:['VendorID'],capability:['Capability'],createdAt:['Created At'],createdBy:['Created By']}},
  VendorLocation:{sheetName:'VendorLocations',idField:'VendorLocationID',fields:{id:['VendorLocationID'],tenantId:['TenantID'],vendorId:['VendorID'],label:['Label'],addressJson:['Address JSON'],phone:['Phone'],status:['Status'],createdAt:['Created At'],createdBy:['Created By'],updatedAt:['Updated At'],updatedBy:['Updated By']}},
  VendorContact:{sheetName:'VendorContacts',idField:'VendorContactID',fields:{id:['VendorContactID'],tenantId:['TenantID'],vendorId:['VendorID'],name:['Contact Name'],role:['Contact Role'],email:['Email'],phone:['Phone'],locationId:['VendorLocationID'],status:['Status'],createdAt:['Created At'],createdBy:['Created By'],updatedAt:['Updated At'],updatedBy:['Updated By']}},
  VendorEstimate:{sheetName:'VendorEstimates',idField:'VendorEstimateID',fields:{id:['VendorEstimateID'],tenantId:['TenantID'],vendorId:['VendorID'],referenceNumber:['Reference Number'],estimateDate:['Estimate Date'],expirationDate:['Expiration Date'],amountMinor:['Amount Minor'],currency:['Currency'],sourceDocumentId:['Source Document ID'],purpose:['Purpose'],status:['Status'],notes:['Notes'],createdAt:['Created At'],createdBy:['Created By']}},
  QuoteCostEstimate:{sheetName:'QuoteCostEstimates',idField:'QuoteCostEstimateID',fields:{id:['QuoteCostEstimateID'],tenantId:['TenantID'],quoteId:['QuoteID'],quoteRevisionId:['QuoteRevisionID'],estimateVersion:['Estimate Version'],status:['Status'],currency:['Currency'],recurringCostMinor:['Recurring Estimated Cost Minor'],oneTimeCostMinor:['One-Time Estimated Cost Minor'],totalCostMinor:['Total Estimated Cost Minor'],rollupVersion:['Rollup Version'],version:['Version'],createdAt:['Created At'],createdBy:['Created By'],updatedAt:['Updated At'],updatedBy:['Updated By'],securityOperationId:['Security Operation ID'],securityOperationFingerprint:['Security Operation Fingerprint'],securityActorId:['Security Actor ID']}},
  QuoteCostLine:{sheetName:'QuoteCostLines',idField:'QuoteCostLineID',fields:{id:['QuoteCostLineID'],tenantId:['TenantID'],estimateId:['QuoteCostEstimateID'],quoteLineItemId:['QuoteLineItemID'],partId:['PartID'],vendorId:['VendorID'],vendorEstimateId:['VendorEstimateID'],sequence:['Sequence'],purpose:['Purpose'],category:['Category'],description:['Description'],basis:['Cost Basis'],timing:['Cost Timing'],quantity:['Quantity Decimal'],unitOfMeasure:['Unit Of Measure'],hoursPerPart:['Hours Per Part Decimal'],rateMinor:['Rate Minor'],sourceAmountMinor:['Source Amount Minor'],allocationQuantity:['Allocation Quantity Decimal'],costEachMinor:['Cost Each Minor'],extendedCostMinor:['Authoritative Extended Cost Minor'],currency:['Currency'],summaryOnly:['Summary Only'],includeInRollup:['Include In Cost Rollup'],summaryGroupKey:['Summary Group Key'],sourceDocumentId:['Source Document ID'],internalNotes:['Internal Notes'],version:['Version'],createdAt:['Created At'],createdBy:['Created By'],updatedAt:['Updated At'],updatedBy:['Updated By'],securityOperationId:['Security Operation ID'],securityOperationFingerprint:['Security Operation Fingerprint'],securityActorId:['Security Actor ID']}},
  QuotePricingDecision:{sheetName:'QuotePricingDecisions',idField:'QuotePricingDecisionID',fields:{id:['QuotePricingDecisionID'],tenantId:['TenantID'],quoteRevisionId:['QuoteRevisionID'],quoteLineItemId:['QuoteLineItemID'],estimateId:['QuoteCostEstimateID'],method:['Pricing Method'],costBasisMinor:['Cost Basis Minor'],markupPercent:['Markup Percent Decimal'],markupAmountMinor:['Markup Amount Minor'],sellUnitPriceMinor:['Sell Unit Price Minor'],sellExtendedPriceMinor:['Sell Extended Price Minor'],currency:['Currency'],rationale:['Rationale'],version:['Version'],createdAt:['Created At'],createdBy:['Created By'],updatedAt:['Updated At'],updatedBy:['Updated By']}},
  QuoteSourceDocumentLink:{sheetName:'QuoteSourceDocumentLinks',idField:'QuoteSourceDocumentLinkID',fields:{id:['QuoteSourceDocumentLinkID'],tenantId:['TenantID'],documentId:['DocumentID'],relationshipType:['Relationship Type'],quoteId:['QuoteID'],quoteRevisionId:['QuoteRevisionID'],quoteLineItemId:['QuoteLineItemID'],estimateId:['QuoteCostEstimateID'],costLineId:['QuoteCostLineID'],rfqId:['RFQID'],partId:['PartID'],vendorId:['VendorID'],jobId:['JobID'],purpose:['Purpose'],visibility:['Visibility'],sourceFingerprint:['Source Fingerprint'],sourceVersion:['Source Version'],createdAt:['Created At'],createdBy:['Created By']}}
};
var ATLAS_VENDOR_CAPABILITIES=['MATERIAL_SUPPLIER','TOOLING_SUPPLIER','WELDING_FABRICATION','COATING_FINISHING','CERAKOTE_FINISHING','HEAT_TREAT','PLATING_ANODIZING','OUTSIDE_MACHINING','GRINDING','EDM','LASER_WATERJET','INSPECTION_METROLOGY','ENGINEERING_PROGRAMMING','FREIGHT_LOGISTICS','PACKAGING','GENERAL_SERVICE','OTHER'];
var ATLAS_QUOTE_COST_CATEGORIES=['MATERIAL','FREIGHT','SUPPLIER_TAX','PREPARATION','MACHINING','LABOR','WELDING','OUTSIDE_PROCESS','COATING_FINISHING','TOOLING','NRE','OTHER'];
