/** Additive provider-neutral commercial stores. No initializer or live activation is included. */
var ATLAS_COMMERCIAL_MAPPINGS = {
  Tenant: {sheetName:'AtlasTenants',idField:'TenantID',fields:{id:['TenantID'],displayName:['Display Name'],status:['Status'],commercialState:['Commercial State'],billingOrganizationReference:['Billing Organization Reference'],billingContactJson:['Billing Contact JSON'],billingAddressJson:['Billing Address JSON'],createdAt:['Created At'],updatedAt:['Updated At']}},
  PlanVersion: {sheetName:'AtlasPlanVersions',idField:'PlanVersionID',fields:{id:['PlanVersionID'],planKey:['Plan Key'],version:['Version'],status:['Status'],includedModulesJson:['Included Modules JSON'],includedSeats:['Included Seats'],selfServiceSeatCap:['Self-Service Seat Cap'],seatPolicy:['Seat Policy'],effectiveAt:['Effective At'],retiredAt:['Retired At'],createdAt:['Created At']}},
  Subscription: {sheetName:'AtlasSubscriptions',idField:'SubscriptionID',fields:{id:['SubscriptionID'],tenantId:['TenantID'],planVersionId:['PlanVersionID'],state:['State'],purchasedSeats:['Purchased Seats'],billingFrequency:['Billing Frequency'],billingAnchorDay:['Billing Anchor Day'],periodStart:['Period Start'],periodEnd:['Period End'],nextBillingAt:['Next Billing At'],providerKey:['Provider Key'],providerCustomerReference:['Provider Customer Reference'],providerSubscriptionReference:['Provider Subscription Reference'],paymentMethodCategory:['Payment Method Category'],paymentMethodSummary:['Payment Method Summary'],paymentStatus:['Payment Status'],trialEndsAt:['Trial Ends At'],graceEndsAt:['Grace Ends At'],createdAt:['Created At'],updatedAt:['Updated At']}},
  Entitlement: {sheetName:'AtlasEntitlements',idField:'EntitlementID',fields:{id:['EntitlementID'],tenantId:['TenantID'],subscriptionId:['SubscriptionID'],type:['Type'],key:['Key'],quantity:['Quantity'],state:['State'],effectiveAt:['Effective At'],expiresAt:['Expires At'],overrideReason:['Override Reason'],createdAt:['Created At'],updatedAt:['Updated At']}},
  SeatAssignment: {sheetName:'AtlasSeatAssignments',idField:'SeatAssignmentID',fields:{id:['SeatAssignmentID'],tenantId:['TenantID'],userId:['UserID'],state:['State'],assignedAt:['Assigned At'],releasedAt:['Released At'],createdAt:['Created At'],updatedAt:['Updated At']}},
  Invitation: {sheetName:'AtlasTenantInvitations',idField:'InvitationID',fields:{id:['InvitationID'],tenantId:['TenantID'],emailReference:['Email Reference'],roleKeysJson:['Role Keys JSON'],status:['Status'],invitedBy:['Invited By'],invitedAt:['Invited At'],expiresAt:['Expires At'],acceptedByUserId:['Accepted By UserID'],acceptedAt:['Accepted At'],cancelledAt:['Cancelled At'],updatedAt:['Updated At']}},
  InvoiceSnapshot: {sheetName:'AtlasInvoiceSnapshots',idField:'InvoiceSnapshotID',fields:{id:['InvoiceSnapshotID'],tenantId:['TenantID'],subscriptionId:['SubscriptionID'],providerKey:['Provider Key'],providerInvoiceReference:['Provider Invoice Reference'],invoiceNumber:['Invoice Number'],periodStart:['Period Start'],periodEnd:['Period End'],invoiceDate:['Invoice Date'],dueDate:['Due Date'],seatsBilled:['Seats Billed'],prorationJson:['Proration JSON'],modulesJson:['Modules JSON'],currency:['Currency'],subtotal:['Subtotal'],tax:['Tax'],total:['Total'],paymentStatus:['Payment Status'],paidAt:['Paid At'],paymentMethodCategory:['Payment Method Category'],invoiceUrlReference:['Invoice URL Reference'],snapshotJson:['Snapshot JSON'],createdAt:['Created At']}},
  ProviderEvent: {sheetName:'AtlasBillingProviderEvents',idField:'BillingProviderEventID',fields:{id:['BillingProviderEventID'],providerKey:['Provider Key'],providerEventId:['Provider Event ID'],eventType:['Event Type'],tenantId:['TenantID'],subscriptionId:['SubscriptionID'],providerSubscriptionReference:['Provider Subscription Reference'],occurredAt:['Occurred At'],receivedAt:['Received At'],signatureStatus:['Signature Status'],processingStatus:['Processing Status'],payloadFingerprint:['Payload Fingerprint'],attemptCount:['Attempt Count'],lastError:['Last Error'],processedAt:['Processed At']}},
  Reconciliation: {sheetName:'AtlasBillingReconciliation',idField:'BillingReconciliationID',fields:{id:['BillingReconciliationID'],tenantId:['TenantID'],subscriptionId:['SubscriptionID'],providerKey:['Provider Key'],reason:['Reason'],atlasState:['Atlas State'],providerState:['Provider State'],status:['Status'],outcome:['Outcome'],correlationId:['Correlation ID'],createdAt:['Created At'],updatedAt:['Updated At'],resolvedAt:['Resolved At']}},
  AuditEvent: {sheetName:'AtlasCommercialAuditEvents',idField:'CommercialAuditEventID',fields:{id:['CommercialAuditEventID'],tenantId:['TenantID'],eventType:['Event Type'],resourceType:['Resource Type'],resourceId:['Resource ID'],actorType:['Actor Type'],actorId:['Actor ID'],correlationId:['Correlation ID'],commandId:['Command ID'],previousJson:['Previous JSON'],proposedJson:['Proposed JSON'],reason:['Reason'],occurredAt:['Occurred At'],outcome:['Outcome']}}
};
var ATLAS_COMMERCIAL_STATES=['TRIAL','ACTIVE','PAYMENT_PENDING','PAYMENT_FAILED','PAST_DUE','GRACE','SUSPENDED','CANCELLED'];
var ATLAS_ENTITLEMENT_TYPES=['PRODUCT','MODULE','SEAT'];
var ATLAS_PAYMENT_METHOD_CATEGORIES=['CARD','BANK_ACH','PAYPAL','OTHER_WALLET','CRYPTO_STABLECOIN'];
var ATLAS_PLATFORM_COMMERCIAL_CAPABILITIES=['PLATFORM_TENANT_READ','PLATFORM_TENANT_MANAGE','PLATFORM_SUBSCRIPTION_READ','PLATFORM_SUBSCRIPTION_MANAGE','PLATFORM_BILLING_READ','PLATFORM_BILLING_MANAGE','PLATFORM_ENTITLEMENT_MANAGE'];
