/** Optional calendar configuration; disabled unless explicitly true. */
function getCalendarFollowUpConfig_(){var properties=PropertiesService.getScriptProperties(),enabled=properties.getProperty('VMOS_CALENDAR_FOLLOWUP_ENABLED')==='true';return {enabled:enabled,provider:properties.getProperty('VMOS_CALENDAR_FOLLOWUP_PROVIDER')||'',calendarId:properties.getProperty('VMOS_CALENDAR_FOLLOWUP_CALENDAR_ID')||''};}
function assertCalendarFollowUpEnabled_(){var config=getCalendarFollowUpConfig_();if(!config.enabled)throw new VmosConfigurationError_('Calendar follow-up synchronization is disabled. MOS follow-ups continue without calendar integration.');if(config.provider!=='GOOGLE_CALENDAR')throw new VmosConfigurationError_('Configure a supported calendar provider before enabling synchronization.');if(!config.calendarId)throw new VmosConfigurationError_('VMOS_CALENDAR_FOLLOWUP_CALENDAR_ID is required when calendar synchronization is enabled.');return config;}

var VMOS_DEFAULT_FOLLOW_UP_MAPPINGS={
  followUps:{sheetName:'FollowUps',idField:'FollowUpID',fields:{id:['FollowUpID'],customerId:['CustomerID'],salesActivityId:['SalesActivityID'],title:['Title'],dueAt:['Due At'],startAt:['Start At'],endAt:['End At'],timeZone:['Time Zone'],ownerUserId:['Owner User ID'],status:['Status'],version:['Version'],createdAt:['Created At'],updatedAt:['Updated At'],completedAt:['Completed At'],cancelledAt:['Cancelled At']}},
  events:{sheetName:'FollowUpEvents',idField:'FollowUpEventID',fields:{id:['FollowUpEventID'],followUpId:['FollowUpID'],eventType:['Event Type'],occurredAt:['Occurred At'],actor:['Actor'],correlationId:['Correlation ID'],previousVersion:['Previous Version'],newVersion:['New Version'],details:['Details']}},
  links:{sheetName:'CalendarFollowUpLinks',idField:'CalendarFollowUpLinkID',fields:{id:['CalendarFollowUpLinkID'],followUpId:['FollowUpID'],connectionId:['ConnectionID'],provider:['Provider'],calendarId:['Calendar ID'],externalEventId:['External Event ID'],externalVersion:['External Version'],lastSyncOrigin:['Last Sync Origin'],lastCorrelationId:['Last Correlation ID'],lastSyncedFollowUpVersion:['Last Synced FollowUp Version'],createdAt:['Created At'],updatedAt:['Updated At']}},
  requests:{sheetName:'ExternalChangeRequests',idField:'ExternalChangeRequestID',fields:{id:['ExternalChangeRequestID'],provider:['Provider'],followUpId:['FollowUpID'],previousConnectionId:['Previous ConnectionID'],externalEventId:['External Event ID'],changeType:['Change Type'],cleanupOperation:['Cleanup Operation'],requestedDueAt:['Requested Due At'],requestedStartAt:['Requested Start At'],requestedEndAt:['Requested End At'],requestedTimeZone:['Requested Time Zone'],externalVersion:['External Version'],status:['Status'],details:['Details'],attemptCount:['Attempt Count'],lastAttemptAt:['Last Attempt At'],lastError:['Last Error'],detectedAt:['Detected At'],resolvedAt:['Resolved At'],resolvedBy:['Resolved By'],resolution:['Resolution']}},
  syncEvents:{sheetName:'CalendarSyncEvents',idField:'CalendarSyncEventID',fields:{id:['CalendarSyncEventID'],provider:['Provider'],followUpId:['FollowUpID'],connectionId:['ConnectionID'],externalEventId:['External Event ID'],operation:['Operation'],changeType:['Change Type'],correlationId:['Correlation ID'],mosVersion:['MOS Version'],externalVersion:['External Version'],result:['Result'],details:['Details'],providerDurationMs:['Provider Duration Ms'],repositoryDurationMs:['Repository Duration Ms'],totalDurationMs:['Total Duration Ms'],recoveryRequired:['Recovery Required'],occurredAt:['Occurred At']}},
  connections:{sheetName:'UserCalendarConnections',idField:'ConnectionID',fields:{id:['ConnectionID'],userId:['UserID'],provider:['Provider'],externalAccountId:['ExternalAccountID'],externalAccountDisplayName:['ExternalAccountDisplayName'],externalCalendarId:['ExternalCalendarID'],externalCalendarDisplayName:['ExternalCalendarDisplayName'],connectionStatus:['ConnectionStatus'],capabilitiesJson:['CapabilitiesJSON'],credentialReference:['CredentialReference'],tokenExpiresAt:['TokenExpiresAt'],syncCursor:['SyncCursor'],subscriptionId:['SubscriptionID'],subscriptionExpiresAt:['SubscriptionExpiresAt'],lastSyncAt:['LastSyncAt'],lastSuccessfulSyncAt:['LastSuccessfulSyncAt'],lastError:['LastError'],createdAt:['CreatedAt'],updatedAt:['UpdatedAt']}}
};

function getFollowUpStorageConfig_(){var base=getVmosConfig_(),raw=PropertiesService.getScriptProperties().getProperty('VMOS_FOLLOW_UP_MAPPING'),mappings=raw?JSON.parse(raw):VMOS_DEFAULT_FOLLOW_UP_MAPPINGS;['followUps','events','links','requests'].forEach(function(key){if(!mappings[key]||!mappings[key].sheetName||!mappings[key].idField)throw new VmosConfigurationError_('VMOS_FOLLOW_UP_MAPPING.'+key+' is incomplete. No worksheet was changed.');});return {spreadsheetId:base.spreadsheetId,mappings:mappings};}
function getCalendarSyncEventStorageConfig_(){var config=getFollowUpStorageConfig_(),mapping=config.mappings.syncEvents;if(!mapping||!mapping.sheetName||!mapping.idField)throw new VmosConfigurationError_('VMOS_FOLLOW_UP_MAPPING.syncEvents is required for writable calendar synchronization. MOS FollowUps remain available. No worksheet was changed.');return {spreadsheetId:config.spreadsheetId,mapping:mapping};}
function getCalendarConnectionStorageConfig_(){var config=getFollowUpStorageConfig_(),mapping=config.mappings.connections;if(!mapping||!mapping.sheetName||!mapping.idField)throw new VmosConfigurationError_('VMOS_FOLLOW_UP_MAPPING.connections is incomplete. No worksheet was changed.');return {spreadsheetId:config.spreadsheetId,mapping:mapping};}
