import { createHash,randomUUID } from 'node:crypto';
import { errors } from './errors.js';

export const LEAD_SOURCES=Object.freeze(['WEBSITE','EMAIL_IMPORT','PHONE','DEALER_REFERRAL','MANUAL','SOCIAL']);
export const LEAD_STATUSES=Object.freeze(['NEW','QUALIFIED','CALLBACK_REQUIRED','CONTACTED','QUOTED','WON','LOST']);
const TRANSITIONS=Object.freeze({NEW:['QUALIFIED','CALLBACK_REQUIRED','CONTACTED','LOST'],QUALIFIED:['CALLBACK_REQUIRED','CONTACTED','QUOTED','LOST'],CALLBACK_REQUIRED:['QUALIFIED','CONTACTED','LOST'],CONTACTED:['QUALIFIED','CALLBACK_REQUIRED','QUOTED','WON','LOST'],QUOTED:['CALLBACK_REQUIRED','CONTACTED','WON','LOST'],WON:[],LOST:[]});
const SAFE=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,199}$/;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const MAX_LIMIT=100;
function safe(value,required=true){const v=String(value||'').trim();if((required&&!v)||(v&&!SAFE.test(v)))throw errors.invalidInput();return v||null;}
function canonical(value,prefix){const v=String(value||'');if(!v.startsWith(prefix)||!UUID.test(v.slice(prefix.length)))throw errors.invalidInput();return v;}
function words(value,max,required=false){const v=String(value??'').trim();if((required&&!v)||v.length>max)throw errors.invalidInput();return v||null;}
function instant(value){const d=new Date(value);if(Number.isNaN(d.getTime()))throw errors.invalidInput();return d.toISOString();}
function hash(value){return createHash('sha256').update(value).digest('hex');}
function scope(context,capability){if(!context?.authoritative||!SAFE.test(context.tenantId||'')||!SAFE.test(context.userId||'')||String(context.tenantId).startsWith('PLATFORM_')||!(context.capabilities||[]).includes(capability))throw errors.forbidden();return Object.freeze({tenantId:String(context.tenantId),userId:String(context.userId),correlationId:safe(context.correlationId||`LEAD-${context.userId}`)});}
function id(prefix){return `${prefix}${randomUUID()}`;}
function payload(x){return JSON.stringify({source:x.source,sourceReference:x.sourceReference||null,companyName:x.companyName||null,contactName:x.contactName||null,email:x.email||null,phone:x.phone||null,summary:x.summary,ownerUserId:x.ownerUserId});}

export class LeadIntakeService{
  constructor({repository,crmActivity,clock=()=>new Date()}={}){if(!repository||!crmActivity)throw new Error('Lead intake requires repository and canonical CRM activity services.');this.repository=repository;this.crmActivity=crmActivity;this.clock=clock;}
  async ingest(context,input={}){const s=scope(context,'LEAD_INTAKE_WRITE');if(!LEAD_SOURCES.includes(input.source))throw errors.invalidInput();const x={leadId:id('LEAD-'),eventId:id('LEAD-EVT-'),source:input.source,sourceReference:words(input.sourceReference,300),companyName:words(input.companyName,200),contactName:words(input.contactName,200),email:words(input.email,320),phone:words(input.phone,80),summary:words(input.summary,1000,true),ownerUserId:safe(input.ownerUserId||s.userId),createdByUserId:s.userId,createdAt:instant(input.createdAt||this.clock())};const key=safe(input.idempotencyKey);x.ingestionKeyHash=hash(`${x.source}\0${key}`);x.ingestionPayloadHash=hash(payload(x));return this.repository.ingest(s,x);}
  async transition(context,input={}){const s=scope(context,'LEAD_WORKFLOW_WRITE'),next=String(input.status||'');if(!LEAD_STATUSES.includes(next)||!Number.isInteger(input.expectedVersion)||input.expectedVersion<1)throw errors.invalidInput();return this.repository.transition(s,{leadId:canonical(input.leadId,'LEAD-'),eventId:id('LEAD-EVT-'),expectedVersion:input.expectedVersion,nextStatus:next,disposition:words(input.disposition,500,next==='LOST'),at:instant(input.changedAt||this.clock()),transitions:TRANSITIONS});}
  async recordActivity(context,input={}){scope(context,'LEAD_WORKFLOW_WRITE');const leadId=canonical(input.leadId,'LEAD-');return this.crmActivity.createActivity(context,{leadId,ownerUserId:input.ownerUserId,activityType:input.activityType,direction:input.direction,occurredAt:input.occurredAt,summary:input.summary,notes:input.notes,sourceChannel:input.sourceChannel||'LEAD_WORKSPACE',nextAction:input.nextAction,nextActionDueAt:input.nextActionDueAt,disposition:input.disposition});}
  async convert(context,input={}){const s=scope(context,'LEAD_CONVERT'),expected=input.expectedVersion;if(!Number.isInteger(expected)||expected<1)throw errors.invalidInput();return this.repository.convert(s,{leadId:canonical(input.leadId,'LEAD-'),customerId:safe(input.customerId),contactId:safe(input.contactId,false),expectedVersion:expected,eventId:id('LEAD-EVT-'),at:instant(input.convertedAt||this.clock())});}
  async queue(context,{status=null,source=null,ownerUserId=null,limit=25}={}){const s=scope(context,'LEAD_READ');if(status&&!LEAD_STATUSES.includes(status)||source&&!LEAD_SOURCES.includes(source)||!Number.isInteger(limit)||limit<1||limit>MAX_LIMIT)throw errors.invalidInput();return this.repository.queue(s,{status,source,ownerUserId:safe(ownerUserId,false),limit});}
  async get(context,leadId){const s=scope(context,'LEAD_READ');return this.repository.get(s,canonical(leadId,'LEAD-'));}
}

export class PostgresLeadRepository{
  constructor({runtime,executor=null}={}){if(!runtime?.query||!runtime?.withTransaction)throw new Error('PostgreSQL lead repository configuration is unavailable.');this.runtime=runtime;this.executor=executor;}
  query(sql,values,operation){return this.executor?this.executor.query(sql,values,operation):this.runtime.query(sql,values,operation);}
  transaction(work){if(this.executor)return work(this);return this.runtime.withTransaction('LEAD_MUTATION',tx=>work(new PostgresLeadRepository({runtime:this.runtime,executor:tx})));}
  async event(s,x){await this.query('INSERT INTO atlas_lead_events(tenant_id,lead_event_id,lead_id,event_type,occurred_at,actor_user_id,correlation_id,previous_status,next_status,previous_version,new_version,details_json) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12::jsonb)',[s.tenantId,x.eventId,x.leadId,x.type,x.at,s.userId,s.correlationId,x.previousStatus||null,x.nextStatus,x.previousVersion??null,x.newVersion,JSON.stringify(x.details||{})],'LEAD_EVENT_APPEND');}
  async ingest(s,x){return this.transaction(async repo=>{const existing=await repo.query('SELECT * FROM atlas_leads WHERE tenant_id=$1 AND ingestion_key_hash=$2',[s.tenantId,x.ingestionKeyHash],'LEAD_IDEMPOTENCY_READ');if(existing.rowCount){if(existing.rows[0].ingestion_payload_hash!==x.ingestionPayloadHash)throw errors.persistenceConflict();return {lead:existing.rows[0],created:false};}const inserted=await repo.query("INSERT INTO atlas_leads(tenant_id,lead_id,source,ingestion_key_hash,ingestion_payload_hash,source_reference,company_name,contact_name,email,phone,summary,owner_user_id,status,created_by_user_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,'NEW',$13,$14,$14) ON CONFLICT (tenant_id,ingestion_key_hash) DO NOTHING RETURNING *",[s.tenantId,x.leadId,x.source,x.ingestionKeyHash,x.ingestionPayloadHash,x.sourceReference,x.companyName,x.contactName,x.email,x.phone,x.summary,x.ownerUserId,x.createdByUserId,x.createdAt],'LEAD_INGEST');if(!inserted.rowCount){const replay=await repo.query('SELECT * FROM atlas_leads WHERE tenant_id=$1 AND ingestion_key_hash=$2',[s.tenantId,x.ingestionKeyHash],'LEAD_IDEMPOTENCY_REPLAY');if(!replay.rowCount||replay.rows[0].ingestion_payload_hash!==x.ingestionPayloadHash)throw errors.persistenceConflict();return {lead:replay.rows[0],created:false};}await repo.event(s,{eventId:x.eventId,leadId:x.leadId,type:'INGESTED',at:x.createdAt,nextStatus:'NEW',newVersion:1,details:{source:x.source,sourceReference:x.sourceReference}});return {lead:inserted.rows[0],created:true};});}
  async transition(s,x){return this.transaction(async repo=>{const current=await repo.query('SELECT status,version FROM atlas_leads WHERE tenant_id=$1 AND lead_id=$2 AND archived_at IS NULL FOR UPDATE',[s.tenantId,x.leadId],'LEAD_TRANSITION_LOCK');if(!current.rowCount)throw errors.notFound();const before=current.rows[0];if(before.version!==x.expectedVersion||!(x.transitions[before.status]||[]).includes(x.nextStatus))throw errors.persistenceConflict();const updated=await repo.query('UPDATE atlas_leads SET status=$4,disposition=$5,version=version+1,updated_at=$6 WHERE tenant_id=$1 AND lead_id=$2 AND version=$3 RETURNING *',[s.tenantId,x.leadId,x.expectedVersion,x.nextStatus,x.disposition,x.at],'LEAD_TRANSITION');await repo.event(s,{eventId:x.eventId,leadId:x.leadId,type:'STATUS_CHANGED',at:x.at,previousStatus:before.status,nextStatus:x.nextStatus,previousVersion:x.expectedVersion,newVersion:x.expectedVersion+1,details:{disposition:x.disposition}});return updated.rows[0];});}
  async convert(s,x){return this.transaction(async repo=>{const lead=await repo.query('SELECT status,version FROM atlas_leads WHERE tenant_id=$1 AND lead_id=$2 AND archived_at IS NULL FOR UPDATE',[s.tenantId,x.leadId],'LEAD_CONVERT_LOCK');if(!lead.rowCount)throw errors.notFound();const before=lead.rows[0];if(before.version!==x.expectedVersion||['WON','LOST'].includes(before.status))throw errors.persistenceConflict();const customer=await repo.query('SELECT customer_id FROM atlas_customers WHERE tenant_id=$1 AND customer_id=$2 AND archived_at IS NULL',[s.tenantId,x.customerId],'LEAD_CONVERT_CUSTOMER');if(!customer.rowCount)throw errors.notFound();if(x.contactId){const contact=await repo.query('SELECT contact_id FROM atlas_contacts WHERE tenant_id=$1 AND customer_id=$2 AND contact_id=$3 AND archived_at IS NULL',[s.tenantId,x.customerId,x.contactId],'LEAD_CONVERT_CONTACT');if(!contact.rowCount)throw errors.notFound();}const updated=await repo.query("UPDATE atlas_leads SET status='WON',customer_id=$4,contact_id=$5,converted_at=$6,converted_by_user_id=$7,version=version+1,updated_at=$6 WHERE tenant_id=$1 AND lead_id=$2 AND version=$3 RETURNING *",[s.tenantId,x.leadId,x.expectedVersion,x.customerId,x.contactId,x.at,s.userId],'LEAD_CONVERT');await repo.event(s,{eventId:x.eventId,leadId:x.leadId,type:'CONVERTED',at:x.at,previousStatus:before.status,nextStatus:'WON',previousVersion:x.expectedVersion,newVersion:x.expectedVersion+1,details:{customerId:x.customerId,contactId:x.contactId}});return updated.rows[0];});}
  async queue(s,x){let sql='SELECT lead_id,source,source_reference,company_name,contact_name,email,phone,summary,owner_user_id,status,version,created_at,updated_at FROM atlas_leads WHERE tenant_id=$1 AND archived_at IS NULL',values=[s.tenantId];if(x.status){values.push(x.status);sql+=` AND status=$${values.length}`;}if(x.source){values.push(x.source);sql+=` AND source=$${values.length}`;}if(x.ownerUserId){values.push(x.ownerUserId);sql+=` AND owner_user_id=$${values.length}`;}values.push(x.limit);sql+=` ORDER BY CASE status WHEN 'CALLBACK_REQUIRED' THEN 0 WHEN 'NEW' THEN 1 WHEN 'QUALIFIED' THEN 2 ELSE 3 END,created_at,lead_id LIMIT $${values.length}`;return (await this.query(sql,values,'LEAD_QUEUE')).rows;}
  async get(s,leadId){const row=await this.query('SELECT * FROM atlas_leads WHERE tenant_id=$1 AND lead_id=$2 AND archived_at IS NULL',[s.tenantId,leadId],'LEAD_GET');if(!row.rowCount)throw errors.notFound();return row.rows[0];}
}
