function doGet(e) {
  if (e && e.parameter && e.parameter.sales === '1') return HtmlService.createTemplateFromFile('UI/SalesActivity').evaluate().setTitle('VMOS Sales Activity').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  if (e && e.parameter && e.parameter.ideas === '1') return HtmlService.createTemplateFromFile('UI/Ideas').evaluate().setTitle('VMOS Ideas Backlog').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  if (e && e.parameter && e.parameter.dashboard === '1') return HtmlService.createTemplateFromFile('UI/OperationsDashboard').evaluate().setTitle('VMOS Operations Dashboard').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  if (e && e.parameter && e.parameter.traveler === '1') return HtmlService.createTemplateFromFile('UI/Traveler').evaluate().setTitle('VMOS Job Traveler').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  if (e && e.parameter && e.parameter.shop === '1') return HtmlService.createTemplateFromFile('UI/ShopFloor').evaluate().setTitle('VMOS Shop Floor').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  if (e && e.parameter && e.parameter.calendar === '1') return HtmlService.createTemplateFromFile('UI/CalendarFollowUps').evaluate().setTitle('VMOS Follow-up Calendar').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  return HtmlService.createTemplateFromFile('UI/Index').evaluate().setTitle('VMOS MVP').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}
function callable_(name,abusePolicy,operation,abuseKey,capabilityOverride,operationOptions){try{var result=executeCallable_(name,abusePolicy,operation,abuseKey,capabilityOverride,operationOptions);if(result&&result.__atlasAuthorizedResult){if(result.auditStatus==='RECOVERY_REQUIRED')return {ok:false,data:result.value,auditStatus:'RECOVERY_REQUIRED',refreshRequired:true,error:{code:'RECOVERY_REQUIRED',message:'Your change may have been saved, but Atlas could not confirm all follow-up work. Refresh the record before taking another action.',referenceId:result.auditEventId}};if(result.replayed)return {ok:false,data:result.value,auditStatus:'COMPLETED',refreshRequired:true,replayed:true,error:{code:'ALREADY_PROCESSED',message:'This request was already processed. Refresh to load the authoritative result before taking another action.',referenceId:result.auditEventId}};return {ok:true,data:result.value,auditStatus:result.auditStatus,correlationId:result.auditEventId,replayed:false};}return {ok:true,data:result};}catch(error){return toClientError_(error);}}
function securityMutationProof_(a){return {operationId:a.operationId,fingerprint:a.requestFingerprint,tenantId:a.tenantId,actorId:a.userId};}
function createSalesActivity(input){var service,options=prepareSecurityResource_(securityOperationOptions_('createSalesActivity','SalesActivity','',{input:input}),function(context){service=service||createSalesActivityService_(context.userId);return service.allocateId();});return callable_('createSalesActivity','NORMAL_WRITE',function(a){service=service||createSalesActivityService_(a.userId);service.idGenerator=function(){return a.resourceId;};service.mutationProof=securityMutationProof_(a);return service.create(input,a.userId);},null,null,options);}
function updateSalesActivity(id,changes){return callable_('updateSalesActivity','NORMAL_WRITE',function(a){return createSalesActivityService_(a.userId).update(id,changes,a.userId);},null,null,securityOperationOptions_('updateSalesActivity','SalesActivity',id,{id:id,changes:changes}));}
function getSalesActivityTimeline(customerId){return callable_('getSalesActivityTimeline','EXPENSIVE_READ',function(){return createSalesActivityService_().listTimeline(customerId);});}
function getSalesFollowUpQueue(){return callable_('getSalesFollowUpQueue','EXPENSIVE_READ',function(){return createSalesActivityService_().followUpQueue(new Date());});}
function getSalesAccountHealth(customerId){return callable_('getSalesAccountHealth','EXPENSIVE_READ',function(){return createSalesActivityService_().accountFollowUpHealth(customerId,new Date());});}
function getSalesActivityMetrics(){return callable_('getSalesActivityMetrics','EXPENSIVE_READ',function(){return createSalesActivityService_().metrics(new Date());});}
function createFollowUp(input){var resourceId=preallocateSecurityResourceId_('FUP');return callable_('createFollowUp','NORMAL_WRITE',function(a){return createFollowUpService_(false,a.checkpoint).create(input,a.userId,a.correlationId,resourceId);},null,null,securityOperationOptions_('createFollowUp','FollowUp',resourceId,{input:input},'FOLLOW_UP_DOMAIN_EVENT',{eventType:'CREATED',expectedVersion:0}));}
function rescheduleFollowUp(id,dueAt,expectedVersion){return callable_('rescheduleFollowUp','NORMAL_WRITE',function(a){return createFollowUpService_(false,a.checkpoint).reschedule(id,dueAt,expectedVersion,a.userId,a.correlationId);},null,null,securityOperationOptions_('rescheduleFollowUp','FollowUp',id,{id:id,dueAt:dueAt,version:expectedVersion},'FOLLOW_UP_DOMAIN_EVENT',{eventType:'RESCHEDULED',expectedVersion:expectedVersion,dueAt:dueAt}));}
function scheduleFollowUp(id,schedule,expectedVersion){return callable_('scheduleFollowUp','NORMAL_WRITE',function(a){return createCalendarFollowUpOrchestration_(a.checkpoint).schedule(id,schedule,expectedVersion,a.userId,a.correlationId);},null,null,securityOperationOptions_('scheduleFollowUp','FollowUp',id,{id:id,schedule:schedule,version:expectedVersion},'FOLLOW_UP_DOMAIN_EVENT',{eventType:'SCHEDULED',expectedVersion:expectedVersion,schedule:schedule}));}
function reassignFollowUp(id,ownerUserId,expectedVersion){return callable_('reassignFollowUp','HIGH_RISK_WRITE',function(a){return createCalendarFollowUpOrchestration_(a.checkpoint).reassign(id,ownerUserId,expectedVersion,a.userId,a.correlationId);},null,null,securityOperationOptions_('reassignFollowUp','FollowUp',id,{id:id,ownerUserId:ownerUserId,version:expectedVersion},'FOLLOW_UP_DOMAIN_EVENT',{eventType:'REASSIGNED',expectedVersion:expectedVersion,newOwner:ownerUserId}));}
function getCalendarWorkspace(){return callable_('getCalendarWorkspace','EXPENSIVE_READ',function(a){return new CalendarWorkspaceReadService_().get(a.userId);});}
function disconnectCalendarConnection(connectionId){return callable_('disconnectCalendarConnection','HIGH_RISK_WRITE',function(a){return createCalendarFollowUpOrchestration_().disconnect(connectionId,a.userId,a.correlationId);},null,null,securityOperationOptions_('disconnectCalendarConnection','UserCalendarConnection',connectionId,{connectionId:connectionId}));}
function retryCalendarConnection(connectionId){return callable_('retryCalendarConnection','NORMAL_WRITE',function(a){var service=new CalendarConnectionService_({repository:new UserCalendarConnectionRepository_()}),connection=service.get(connectionId);if(connection.userId!==a.userId)throw new VmosAuthorizationError_();return service.update(connectionId,{lastError:'',connectionStatus:'CONNECTED'});},null,null,securityOperationOptions_('retryCalendarConnection','UserCalendarConnection',connectionId,{connectionId:connectionId}));}
function resolveCalendarExternalChange(requestId,action,schedule){return callable_('resolveCalendarExternalChange','HIGH_RISK_WRITE',function(a){var requests=new ExternalChangeRequestRepository_(),sync=new CalendarFollowUpSyncService_({followUps:createFollowUpService_(true),requests:requests,links:new CalendarFollowUpLinkRepository_(),syncEvents:new CalendarSyncEventRepository_()}),request=requests.get(requestId),follow=new FollowUpRepository_().get(request.followUpId),orchestration=createCalendarFollowUpOrchestration_(),result,keepMos=action==='KEEP_FOLLOW_UP';if(action==='USE_CALENDAR_TIME'){action='RESCHEDULE';schedule={startAt:request.requestedStartAt,endAt:request.requestedEndAt,timeZone:request.requestedTimeZone};}if(action==='CHOOSE_ANOTHER_TIME')action='RESCHEDULE';if(action==='RESCHEDULE'&&schedule&&(schedule.startAt||schedule.date)){result=orchestration.schedule(follow.id,schedule,follow.version,a.userId,'review:'+requestId);request.status='RESOLVED';request.resolvedAt=new Date();request.resolvedBy=a.userId;request.resolution='RESCHEDULE';requests.update(request.id,request);return result;}result=sync.resolveExternalChange(requestId,action,a.userId,schedule&&schedule.dueAt);if(keepMos&&result.startAt&&result.endAt&&result.timeZone)return request.changeType==='DELETED'?orchestration.recreateExisting(result.id,'review:'+requestId+':recreate'):orchestration.projectExisting(result.id,'review:'+requestId+':use-mos');return result;},null,null,securityOperationOptions_('resolveCalendarExternalChange','ExternalChangeRequest',requestId,{requestId:requestId,action:action,schedule:schedule}));}
function retryCalendarCleanup(requestId){return callable_('retryCalendarCleanup','HIGH_RISK_WRITE',function(a){return createCalendarFollowUpOrchestration_().retryCleanup(requestId,a.userId,a.correlationId);},null,null,securityOperationOptions_('retryCalendarCleanup','ExternalChangeRequest',requestId,{requestId:requestId}));}
function acknowledgeCalendarCleanup(requestId){return callable_('acknowledgeCalendarCleanup','HIGH_RISK_WRITE',function(a){return createCalendarFollowUpOrchestration_().acknowledgeCleanup(requestId,a.userId,a.correlationId);},null,null,securityOperationOptions_('acknowledgeCalendarCleanup','ExternalChangeRequest',requestId,{requestId:requestId}));}
function completeFollowUp(id,expectedVersion){return callable_('completeFollowUp','HIGH_RISK_WRITE',function(a){return createFollowUpService_(false,a.checkpoint).complete(id,expectedVersion,a.userId,a.correlationId);},null,null,securityOperationOptions_('completeFollowUp','FollowUp',id,{id:id,version:expectedVersion},'FOLLOW_UP_DOMAIN_EVENT',{eventType:'COMPLETED',expectedVersion:expectedVersion}));}
function cancelFollowUp(id,expectedVersion){return callable_('cancelFollowUp','HIGH_RISK_WRITE',function(a){return createFollowUpService_(false,a.checkpoint).cancel(id,expectedVersion,a.userId,a.correlationId);},null,null,securityOperationOptions_('cancelFollowUp','FollowUp',id,{id:id,version:expectedVersion},'FOLLOW_UP_DOMAIN_EVENT',{eventType:'CANCELLED',expectedVersion:expectedVersion}));}
function getMvpBootstrap(){return callable_('getMvpBootstrap','EXPENSIVE_READ',function(a){var data={},caps=a.capabilities||[];Object.keys(ATLAS_MVP_ENTITY_CAPABILITIES).forEach(function(entity){if(caps.indexOf(getMvpEntityCapability_(entity,'read'))!==-1)data[entity]=new MvpService_(entity).list();});return data;});}
function createMvpRecord(entity,input){var businessInput=stripOperationMetadata_(input),service,options=prepareSecurityResource_(securityOperationOptions_('createMvpRecord',entity,'',{entity:entity,input:input}),function(){service=service||new MvpService_(entity);return service.allocateId();});return callable_('createMvpRecord','NORMAL_WRITE',function(a){if((entity==='Quote'&&businessInput.status&&businessInput.status!=='Draft')||(entity==='Job'&&businessInput.status&&businessInput.status!=='Planned'))throw new VmosAuthorizationError_('Use the authorized lifecycle action.');service=service||new MvpService_(entity);service.auditUser=function(){return a.userId;};service.mutationProof=securityMutationProof_(a);return service.create(businessInput,a.resourceId);},null,function(){return getMvpEntityCapability_(entity,'write');},options);}
function stripOperationMetadata_(input){var result={};Object.keys(input||{}).forEach(function(key){if(key!=='_operationId')result[key]=input[key];});return result;}
function updateMvpRecord(entity,id,changes){return callable_('updateMvpRecord','NORMAL_WRITE',function(a){changes=changes||{};if((entity==='Quote'||entity==='Job')&&Object.prototype.hasOwnProperty.call(changes,'status'))throw new VmosAuthorizationError_('Use the authorized lifecycle action.');return new MvpService_(entity,{auditUser:function(){return a.userId;}}).update(id,changes);},null,function(){return getMvpEntityCapability_(entity,'write');},securityOperationOptions_('updateMvpRecord',entity,id,{entity:entity,id:id,changes:changes}));}
function approveQuote(id){return callable_('approveQuote','HIGH_RISK_WRITE',function(a){return new MvpLifecycleService_('Quote',a.userId).transition(id,'Draft','Approved');},null,null,securityOperationOptions_('approveQuote','Quote',id,{id:id,from:'Draft'},'',{expectedState:{status:'Approved'}}));}
function issueQuote(id){return callable_('issueQuote','HIGH_RISK_WRITE',function(a){return new MvpLifecycleService_('Quote',a.userId).transition(id,'Approved','Issued');},null,null,securityOperationOptions_('issueQuote','Quote',id,{id:id,from:'Approved'},'',{expectedState:{status:'Issued'}}));}
function configureShopFloorJob(jobId,workflowId,initialStatus){return callable_('configureShopFloorJob','ADMINISTRATIVE',function(a){return new ShopFloorService_({auditUser:function(){return a.userId;},checkpoint:a.checkpoint}).configureJob(jobId,workflowId,initialStatus,a.correlationId);},null,null,securityOperationOptions_('configureShopFloorJob','Job',jobId,{jobId:jobId,workflowId:workflowId,initialStatus:initialStatus},'SHOP_FLOOR_DOMAIN_EVENT',{eventTypes:['QR_ASSIGNED'],workflowId:workflowId,workflowVersion:'1'}));}
function resolveShopJobByQr(token){return callable_('resolveShopJobByQr','QR_LOOKUP',function(){return new ShopFloorService_().resolveByQr(token);},token);}
function getShopFloorJob(jobId){return callable_('getShopFloorJob','EXPENSIVE_READ',function(){return new ShopFloorService_().getJob(jobId);});}
function transitionShopFloorJob(jobId,targetStatus,commandId,notes,qrToken){return callable_('transitionShopFloorJob','SHOP_FLOOR_COMMAND',function(a){return new ShopFloorService_({auditUser:function(){return a.userId;},checkpoint:a.checkpoint}).transition(jobId,targetStatus,commandId,notes,qrToken);},qrToken,null,securityOperationOptions_('transitionShopFloorJob','Job',jobId,{jobId:jobId,commandId:commandId},'SHOP_FLOOR_DOMAIN_EVENT',{eventType:'STATUS_CHANGED',commandId:commandId,targetStatus:targetStatus}));}
function reportJobProblem(jobId,payload,commandId,qrToken){return callable_('reportJobProblem','SHOP_FLOOR_COMMAND',function(a){return new ShopFloorService_({auditUser:function(){return a.userId;},checkpoint:a.checkpoint}).reportProblem(jobId,payload,commandId,qrToken);},qrToken,null,securityOperationOptions_('reportJobProblem','Job',jobId,{jobId:jobId,commandId:commandId},'SHOP_FLOOR_DOMAIN_EVENT',{eventType:'STOP_PROBLEM',commandId:commandId}));}
function resolveJobBlock(jobId,payload,commandId,qrToken){return callable_('resolveJobBlock','SHOP_FLOOR_COMMAND',function(a){return new ShopFloorService_({auditUser:function(){return a.userId;},checkpoint:a.checkpoint}).resolveBlock(jobId,payload,commandId,qrToken);},qrToken,null,securityOperationOptions_('resolveJobBlock','Job',jobId,{jobId:jobId,commandId:commandId},'SHOP_FLOOR_DOMAIN_EVENT',{eventType:'BLOCK_RESOLVED',commandId:commandId,targetStatus:payload&&payload.nextStatus}));}
function listJobEvents(jobId){return callable_('listJobEvents','EXPENSIVE_READ',function(){return new ShopFloorService_().listEvents(jobId);});}
function getTravelerPrintData(token){return callable_('getTravelerPrintData','QR_LOOKUP',function(){return new ShopFloorService_().getTravelerData(token);},token);}
function getShopDashboard(){return callable_('getShopDashboard','EXPENSIVE_READ',function(){return new ShopDashboardService_().getLiveWip();});}
function getShopOperatorWorkloads(){return callable_('getShopOperatorWorkloads','EXPENSIVE_READ',function(){return new ShopDashboardService_().listOperatorWorkloads();});}
function listIdeas(){return callable_('listIdeas','EXPENSIVE_READ',function(){return new IdeasService_().list();});}
function captureIdea(input){var resourceId=preallocateSecurityResourceId_('IDEA');return callable_('captureIdea','NORMAL_WRITE',function(a){return new IdeasService_(undefined,undefined,function(){return a.userId;},a.checkpoint).capture(input,resourceId,a.correlationId);},null,null,securityOperationOptions_('captureIdea','Idea',resourceId,{input:input},'IDEA_DOMAIN_EVENT',{eventType:'IDEA_CAPTURED',note:input&&input.note||'Idea captured.'}));}
function requestIdeaPromotion(id,confirmation,note){return callable_('requestIdeaPromotion','HIGH_RISK_WRITE',function(a){return new IdeasService_(undefined,undefined,function(){return a.userId;},a.checkpoint).requestPromotion(id,confirmation,note,a.correlationId);},null,null,securityOperationOptions_('requestIdeaPromotion','Idea',id,{id:id,confirmation:confirmation,note:note},'IDEA_DOMAIN_EVENT',{eventType:'PROMOTION_REQUESTED',note:note||'Explicitly requested for architecture/client review.'}));}
function recordProcessTrial(input){var resourceId=preallocateSecurityResourceId_('PTR'),options=securityOperationOptions_('recordProcessTrial','ProcessTrial',resourceId,{input:input});return callable_('recordProcessTrial','NORMAL_WRITE',function(a){return new ProcessTrialService_({actor:function(){return a.userId;},uuid:function(){return a.resourceId.slice(4);},mutationProof:securityMutationProof_(a)}).record(input);},null,null,options);}
function listProcessTrials(jobId){return callable_('listProcessTrials','EXPENSIVE_READ',function(){return new ProcessTrialService_().listForJob(jobId);});}
function recordCashReceipt(input){var intent={receiptCommandId:input&&input.receiptCommandId,invoiceId:input&&input.invoiceId,customerId:input&&input.customerId,amount:input&&Number(input.amount),paymentMethod:input&&input.paymentMethod,receivedDate:input&&input.receivedDate,referenceNumber:input&&input.referenceNumber};return callable_('recordCashReceipt','HIGH_RISK_WRITE',function(a){return new CashReceiptService_({auditUser:function(){return a.userId;},mutationProof:securityMutationProof_(a)}).recordReceipt(input);},null,null,securityOperationOptions_('recordCashReceipt','CashReceipt','',intent,'',{receiptCommandId:input&&input.receiptCommandId}));}
function depositCashReceipt(id,input){return callable_('depositCashReceipt','HIGH_RISK_WRITE',function(a){return new CashReceiptService_({auditUser:function(){return a.userId;}}).depositReceipt(id,input);},null,null,securityOperationOptions_('depositCashReceipt','CashReceipt',id,{id:id,depositCommandId:input&&input.depositCommandId},'',{expectedState:{depositStatus:'DEPOSITED',depositCommandId:input&&input.depositCommandId}}));}
function getUndepositedPaymentSummary(){return callable_('getUndepositedPaymentSummary','EXPENSIVE_READ',function(){return new CashReceiptService_().getUndepositedExceptionSummary(new Date());});}
function submitPurchaseRequest(input){var resourceId=preallocateSecurityResourceId_('PUR');return callable_('submitPurchaseRequest','NORMAL_WRITE',function(a){return new PurchaseApprovalService_(undefined,undefined,function(){return a.userId;},undefined,function(){return a.resourceId;},securityMutationProof_(a)).submit(input);},null,null,securityOperationOptions_('submitPurchaseRequest','PurchaseRequest',resourceId,{input:input}));}
function approvePurchaseRequest(id,approver,notes){return callable_('approvePurchaseRequest','HIGH_RISK_WRITE',function(a){return new PurchaseApprovalService_(undefined,undefined,function(){return a.userId;},LockService.getScriptLock()).approve(id,a.userId,notes);},null,null,securityOperationOptions_('approvePurchaseRequest','PurchaseRequest',id,{id:id,notes:notes},'',{expectedState:{status:'APPROVED'}}));}
function recordPurchaseReceipt(id,reference,actor){return callable_('recordPurchaseReceipt','HIGH_RISK_WRITE',function(a){return new PurchaseApprovalService_(undefined,undefined,function(){return a.userId;},LockService.getScriptLock()).recordReceipt(id,reference,undefined,a.userId);},null,null,securityOperationOptions_('recordPurchaseReceipt','PurchaseRequest',id,{id:id,reference:reference},'',{expectedState:{receiptReference:reference}}));}
