function doGet(e) {
  if (e && e.parameter && e.parameter.sales === '1') return HtmlService.createTemplateFromFile('UI/SalesActivity').evaluate().setTitle('VMOS Sales Activity').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  if (e && e.parameter && e.parameter.ideas === '1') return HtmlService.createTemplateFromFile('UI/Ideas').evaluate().setTitle('VMOS Ideas Backlog').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  if (e && e.parameter && e.parameter.dashboard === '1') return HtmlService.createTemplateFromFile('UI/OperationsDashboard').evaluate().setTitle('VMOS Operations Dashboard').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  if (e && e.parameter && e.parameter.traveler === '1') return HtmlService.createTemplateFromFile('UI/Traveler').evaluate().setTitle('VMOS Job Traveler').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  if (e && e.parameter && e.parameter.shop === '1') return HtmlService.createTemplateFromFile('UI/ShopFloor').evaluate().setTitle('VMOS Shop Floor').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  if (e && e.parameter && e.parameter.calendar === '1') return HtmlService.createTemplateFromFile('UI/CalendarFollowUps').evaluate().setTitle('VMOS Follow-up Calendar').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
  return HtmlService.createTemplateFromFile('UI/Index').evaluate().setTitle('VMOS MVP').setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}
function createSalesActivity(input) { try { return { ok: true, data: createSalesActivityService_().create(input, getVmosAuditUser_()) }; } catch (error) { return toClientError_(error); } }
function updateSalesActivity(id, changes) { try { return { ok: true, data: createSalesActivityService_().update(id, changes, getVmosAuditUser_()) }; } catch (error) { return toClientError_(error); } }
function getSalesActivityTimeline(customerId) { try { return { ok: true, data: createSalesActivityService_().listTimeline(customerId) }; } catch (error) { return toClientError_(error); } }
function getSalesFollowUpQueue() { try { return { ok: true, data: createSalesActivityService_().followUpQueue(new Date()) }; } catch (error) { return toClientError_(error); } }
function getSalesAccountHealth(customerId) { try { return { ok: true, data: createSalesActivityService_().accountFollowUpHealth(customerId, new Date()) }; } catch (error) { return toClientError_(error); } }
function getSalesActivityMetrics() { try { return { ok: true, data: createSalesActivityService_().metrics(new Date()) }; } catch (error) { return toClientError_(error); } }
function createFollowUp(input) { try { return { ok: true, data: createFollowUpService_().create(input, getVmosAuditUser_()) }; } catch (error) { return toClientError_(error); } }
function rescheduleFollowUp(id, dueAt, expectedVersion) { try { return { ok: true, data: createFollowUpService_().reschedule(id, dueAt, expectedVersion, getVmosAuditUser_(), Utilities.getUuid()) }; } catch (error) { return toClientError_(error); } }
function scheduleFollowUp(id, schedule, expectedVersion) { try { return { ok: true, data: createCalendarFollowUpOrchestration_().schedule(id, schedule, expectedVersion, getVmosAuditUser_(), Utilities.getUuid()) }; } catch (error) { return toClientError_(error); } }
function reassignFollowUp(id, ownerUserId, expectedVersion) { try { return { ok: true, data: createCalendarFollowUpOrchestration_().reassign(id, ownerUserId, expectedVersion, getVmosAuditUser_(), Utilities.getUuid()) }; } catch (error) { return toClientError_(error); } }
function getCalendarWorkspace() { try { var actor=getVmosAuditUser_(),connections=new UserCalendarConnectionRepository().listByUserId(actor),links=new CalendarFollowUpLinkRepository().list(),requests=new ExternalChangeRequestRepository().list().filter(function(r){return r.status==='PENDING_REVIEW';}),followUps=new FollowUpRepository().list(),customers=new MvpService('Customer').list(),registry=new CalendarProviderRegistry(),configured=getConfiguredCalendarProviderKeys_();var providers=registry.list().map(function(provider){provider.authorizationConfigured=configured.indexOf(provider.providerKey)!==-1;return provider;}); return {ok:true,data:{actor:actor,calendarIntegrationEnabled:getCalendarFollowUpConfig_().enabled,connections:connections,followUps:followUps,links:links,requests:requests,customers:customers,providers:providers}}; } catch (error) { return toClientError_(error); } }
function disconnectCalendarConnection(connectionId) { try { var actor=getVmosAuditUser_();return {ok:true,data:createCalendarFollowUpOrchestration_().disconnect(connectionId,actor,Utilities.getUuid())}; } catch (error) { return toClientError_(error); } }
function retryCalendarConnection(connectionId) { try { var actor=getVmosAuditUser_(),service=new CalendarConnectionService({repository:new UserCalendarConnectionRepository()}),connection=service.get(connectionId);if(connection.userId!==actor)throw new VmosValidationError('You may retry only your own calendar.');return {ok:true,data:service.update(connectionId,{lastError:'',connectionStatus:'CONNECTED'})}; } catch (error) { return toClientError_(error); } }
function resolveCalendarExternalChange(requestId, action, schedule) { try { var sync=new CalendarFollowUpSyncService({followUps:createFollowUpService_(),requests:new ExternalChangeRequestRepository(),links:new CalendarFollowUpLinkRepository(),syncEvents:{append:function(){},findByCorrelation:function(){}}}),request=new ExternalChangeRequestRepository().get(requestId),follow=new FollowUpRepository().get(request.followUpId),actor=getVmosAuditUser_(),orchestration=createCalendarFollowUpOrchestration_(),result,keepMos=action==='KEEP_FOLLOW_UP';if(action==='USE_CALENDAR_TIME'){action='RESCHEDULE';schedule={startAt:request.requestedStartAt,endAt:request.requestedEndAt,timeZone:request.requestedTimeZone};}if(action==='CHOOSE_ANOTHER_TIME')action='RESCHEDULE';if(action==='RESCHEDULE'&&schedule&&(schedule.startAt||schedule.date)) { result=orchestration.schedule(follow.id,schedule,follow.version,actor,'review:'+requestId);request.status='RESOLVED';request.resolvedAt=new Date();request.resolvedBy=actor;request.resolution='RESCHEDULE';new ExternalChangeRequestRepository().update(request.id,request);return {ok:true,data:result}; } result=sync.resolveExternalChange(requestId,action,actor,schedule&&schedule.dueAt);if(keepMos&&result.startAt&&result.endAt&&result.timeZone)return {ok:true,data:request.changeType==='DELETED'?orchestration.recreateExisting(result.id,'review:'+requestId+':recreate'):orchestration.projectExisting(result.id,'review:'+requestId+':use-mos')};return {ok:true,data:result}; } catch (error) { return toClientError_(error); } }
function retryCalendarCleanup(requestId) { try { return {ok:true,data:createCalendarFollowUpOrchestration_().retryCleanup(requestId,getVmosAuditUser_(),'cleanup-retry:'+Utilities.getUuid())}; } catch (error) { return toClientError_(error); } }
function acknowledgeCalendarCleanup(requestId) { try { return {ok:true,data:createCalendarFollowUpOrchestration_().acknowledgeCleanup(requestId,getVmosAuditUser_(),'cleanup-ack:'+Utilities.getUuid())}; } catch (error) { return toClientError_(error); } }
function completeFollowUp(id, expectedVersion) { try { return { ok: true, data: createFollowUpService_().complete(id, expectedVersion, getVmosAuditUser_(), Utilities.getUuid()) }; } catch (error) { return toClientError_(error); } }
function cancelFollowUp(id, expectedVersion) { try { return { ok: true, data: createFollowUpService_().cancel(id, expectedVersion, getVmosAuditUser_(), Utilities.getUuid()) }; } catch (error) { return toClientError_(error); } }
function getMvpBootstrap() { try { var data = {}; ['Customer', 'RFQ', 'Quote', 'Job', 'Invoice'].forEach(function (entity) { data[entity] = new MvpService(entity).list(); }); return { ok: true, data: data }; } catch (error) { return toClientError_(error); } }
function createMvpRecord(entity, input) { try { if (['Customer', 'RFQ', 'Quote', 'Job', 'Invoice'].indexOf(entity) === -1) throw new VmosValidationError('Unsupported entity.'); return { ok: true, data: new MvpService(entity).create(input) }; } catch (error) { return toClientError_(error); } }
function updateMvpRecord(entity, id, changes) { try { if (['Customer', 'RFQ', 'Quote', 'Job', 'Invoice'].indexOf(entity) === -1) throw new VmosValidationError('Unsupported entity.'); return { ok: true, data: new MvpService(entity).update(id, changes) }; } catch (error) { return toClientError_(error); } }
function configureShopFloorJob(jobId, workflowId, initialStatus) { try { return { ok: true, data: new ShopFloorService().configureJob(jobId, workflowId, initialStatus) }; } catch (error) { return toClientError_(error); } }
function resolveShopJobByQr(token) { try { return { ok: true, data: new ShopFloorService().resolveByQr(token) }; } catch (error) { return toClientError_(error); } }
function getShopFloorJob(jobId) { try { return { ok: true, data: new ShopFloorService().getJob(jobId) }; } catch (error) { return toClientError_(error); } }
function transitionShopFloorJob(jobId, targetStatus, commandId, notes) { try { return { ok: true, data: new ShopFloorService().transition(jobId, targetStatus, commandId, notes) }; } catch (error) { return toClientError_(error); } }
function reportJobProblem(jobId, payload, commandId) { try { return { ok: true, data: new ShopFloorService().reportProblem(jobId, payload, commandId) }; } catch (error) { return toClientError_(error); } }
function resolveJobBlock(jobId, payload, commandId) { try { return { ok: true, data: new ShopFloorService().resolveBlock(jobId, payload, commandId) }; } catch (error) { return toClientError_(error); } }
function listJobEvents(jobId) { try { return { ok: true, data: new ShopFloorService().listEvents(jobId) }; } catch (error) { return toClientError_(error); } }
function getTravelerPrintData(token) { try { return { ok: true, data: new ShopFloorService().getTravelerData(token) }; } catch (error) { return toClientError_(error); } }
function getShopDashboard() { try { return { ok: true, data: new ShopDashboardService().getLiveWip() }; } catch (error) { return toClientError_(error); } }
function getShopOperatorWorkloads() { try { return { ok: true, data: new ShopDashboardService().listOperatorWorkloads() }; } catch (error) { return toClientError_(error); } }
function listIdeas() { try { return { ok: true, data: new IdeasService().list() }; } catch (error) { return toClientError_(error); } }
function captureIdea(input) { try { return { ok: true, data: new IdeasService().capture(input) }; } catch (error) { return toClientError_(error); } }
function requestIdeaPromotion(id, confirmation, note) { try { return { ok: true, data: new IdeasService().requestPromotion(id, confirmation, note) }; } catch (error) { return toClientError_(error); } }
function recordProcessTrial(input) { try { return { ok: true, data: new ProcessTrialService().record(input) }; } catch (error) { return toClientError_(error); } }
function listProcessTrials(jobId) { try { return { ok: true, data: new ProcessTrialService().listForJob(jobId) }; } catch (error) { return toClientError_(error); } }
function recordCashReceipt(input) { try { return { ok: true, data: new CashReceiptService().recordReceipt(input) }; } catch (error) { return toClientError_(error); } }
function depositCashReceipt(id, input) { try { return { ok: true, data: new CashReceiptService().depositReceipt(id, input) }; } catch (error) { return toClientError_(error); } }
function getUndepositedPaymentSummary() { try { return { ok: true, data: new CashReceiptService().getUndepositedExceptionSummary(new Date()) }; } catch (error) { return toClientError_(error); } }
function submitPurchaseRequest(input) { try { return { ok: true, data: new PurchaseApprovalService().submit(input) }; } catch (error) { return toClientError_(error); } }
function approvePurchaseRequest(id, approver, notes) { try { return { ok: true, data: new PurchaseApprovalService().approve(id, approver, notes) }; } catch (error) { return toClientError_(error); } }
function recordPurchaseReceipt(id, reference, actor) { try { return { ok: true, data: new PurchaseApprovalService().recordReceipt(id, reference, actor) }; } catch (error) { return toClientError_(error); } }
