const assert = require('assert');
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const base = path.join(__dirname, '..', 'appscript', 'src');
const context = vm.createContext({ JSON, String, Array, Object, VmosNotFoundError: function (message) { this.message = message; }, VmosValidationError: function (message) { this.message = message; } });
['Utilities/AtlasModuleRegistry.gs', 'Utilities/AtlasTenantConfig.gs', 'Services/AtlasQuotePresentationService.gs'].forEach(file => vm.runInContext(fs.readFileSync(path.join(base, file), 'utf8'), context));

const vmos = context.getAtlasConceptBootstrap_('VMOS').data;
const ipm = context.getAtlasConceptBootstrap_('IPM').data;
assert.equal(vmos.tenant.deploymentKey, 'vmos');
assert.equal(ipm.tenant.identity.deploymentName, 'IPM Operations');
assert.ok(vmos.tenant.branding.accentColor && ipm.tenant.branding.accentColor, 'neutral defaults resolve missing IPM colors');
assert.ok(!Object.keys(ipm.tenant).some(key => /key|secret|token/i.test(key) && key !== 'key' && key !== 'deploymentKey'), 'profile contains no credential fields');
assert.ok(vmos.navigation.includes('Firearms Intake') && vmos.navigation.includes('Coating Queue'));
assert.ok(!ipm.navigation.includes('Firearms Intake') && !ipm.navigation.includes('Coating Queue'), 'disabled specialty modules are absent');
assert.ok(!ipm.kanban.columns.includes('COATING'), 'generic IPM workflow does not require coatings');
assert.equal(ipm.tenant.terminology.jobs, 'Jobs'); assert.equal(vmos.tenant.terminology.jobs, 'Work Orders');
assert.ok(vmos.commandCenter.some(card => card.key === 'PURCHASES'));
assert.ok(!context.getAtlasCommandCenterCards_(context.resolveAtlasDeploymentProfile_({ deploymentKey: 'minimal', identity: { organizationName: 'Test', deploymentName: 'Test' }, modules: ['CRM'] })).some(card => card.key === 'PURCHASES'), 'command cards require their module');
const quote = { id: 'VQT-26-0100', customerName: 'Acme', total: 1250, lines: [] };
const vmosQuote = context.buildAtlasQuotePresentation_(vmos.tenant, quote), ipmQuote = context.buildAtlasQuotePresentation_(ipm.tenant, quote);
assert.equal(vmosQuote.seller.organizationName, 'Vitality Modification Company'); assert.equal(ipmQuote.seller.organizationName, 'International Precision Machine');
const portableTemplate = fs.readFileSync(path.join(base, 'UI', 'AtlasQuoteTemplate.html'), 'utf8');
['Vitality', 'VMOS', 'Firearms', 'Cerakote'].forEach(term => assert.ok(!portableTemplate.includes(term), 'portable quote template must not contain ' + term));
const ipmRendered = JSON.stringify({ tenant: ipm.tenant, navigation: ipm.navigation, cards: ipm.commandCenter, kanban: ipm.kanban, quote: ipmQuote });
['Vitality', 'VMOS', 'Firearms', 'Cerakote'].forEach(term => assert.ok(!ipmRendered.includes(term), 'IPM-facing output must not contain ' + term));
assert.ok(!fs.readFileSync(path.join(base, 'Utilities', 'AtlasTenantConfig.gs'), 'utf8').includes('SpreadsheetApp'), 'profile resolver is storage independent');
console.log('Atlas product concept tests passed');
