const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto');
const root=path.join(__dirname,'..','appscript','src');let serial=0,now=new Date('2026-08-15T12:00:00Z'),data={};
function AuthError(m){this.message=m;this.code='AUTHORIZATION_ERROR'}function ConfigError(m){this.message=m;this.code='CONFIGURATION_ERROR'}function Conflict(m){this.message=m;this.code='CONFLICT'}function ProviderError(m,c){this.message=m;this.code=c}
const cache={put:(k,v)=>data[k]=v,get:k=>data[k]||null,remove:k=>delete data[k]},c=vm.createContext({Date,String,Number,Boolean,Object,Array,JSON,Math,isFinite,encodeURIComponent,VmosAuthorizationError_:AuthError,VmosConfigurationError_:ConfigError,VmosConflictError:Conflict,VmosError_:ProviderError,CacheService:{getScriptCache:()=>cache},Utilities:{getUuid:()=>('00000000-0000-4000-8000-'+String(++serial).padStart(12,'0')),computeDigest:(a,v)=>[...crypto.createHash('sha256').update(String(v)).digest()],base64EncodeWebSafe:b=>Buffer.from(b).toString('base64url'),DigestAlgorithm:{SHA_256:'SHA'},Charset:{UTF_8:'UTF8'}}});vm.runInContext(fs.readFileSync(path.join(root,'Services','AuthenticationService.gs'),'utf8'),c);
const flowA='FLOWAAAAAAAAAAAAAAAAAAAAAAAAAAAA',flowB='FLOWBBBBBBBBBBBBBBBBBBBBBBBBBBBB',flowC='FLOWCCCCCCCCCCCCCCCCCCCCCCCCCCCC',store=new c.AtlasAuthenticationStateStore_({cache,clock:()=>now,timeoutSeconds:120});
let first=store.create('GOOGLE','home','https://atlas.invalid/callback',flowA),second=store.create('GOOGLE','home','https://atlas.invalid/callback',flowA);assert.throws(()=>store.consume(first.state,flowA),'superseded callback cannot authenticate');assert.equal(store.consume(second.state,flowA).flowId,flowA,'replacement remains consumable');
let aborted=store.create('GOOGLE','home','https://atlas.invalid/callback',flowB);assert.equal(store.abort(flowB,aborted.state).state,'SIGNED_OUT');assert.throws(()=>store.consume(aborted.state,flowB),'aborted transaction is gone');
let expired=store.create('GOOGLE','home','https://atlas.invalid/callback',flowC);now=new Date('2026-08-15T12:02:01Z');assert.throws(()=>store.consume(expired.state,flowC),'expired transaction rejected');assert(!data['ATLAS_AUTH_STATE:'+c.atlasAuthHash_(expired.state)],'expired state removed');
now=new Date('2026-08-15T12:00:00Z');const cfg={provider:'GOOGLE',enabled:true,clientId:'client',authorizationEndpoint:'https://accounts.google.com/o/oauth2/v2/auth',issuers:['https://accounts.google.com'],allowPersonalAccounts:false,scopes:['openid']},config={providers:{GOOGLE:cfg},redirectUri:'https://atlas.invalid/callback',allowedReturnRoutes:['home'],transactionTimeoutSeconds:120,session:{lifetimeSeconds:3600,recentAuthSeconds:900}},sessionRows=[],sessions={create:r=>(sessionRows.push(r),r),findByTokenHash:h=>sessionRows.find(r=>r.tokenHash===h),update:(id,ch)=>Object.assign(sessionRows.find(r=>r.id===id),ch)},sessionService=new c.AtlasSessionService_({sessions,clock:()=>now,uuid:()=>String(++serial),policy:config.session}),identity={findActiveIdentity:()=>({userId:'U1',status:'ACTIVE'})},users={get:()=>({id:'U1',status:'ACTIVE'})},memberships={list:()=>[{tenantId:'T1',userId:'U1',status:'ACTIVE'}]},entitlements={assertAllowed(){}};
function service(gateway){return new c.AtlasAuthenticationService_({config,states:new c.AtlasAuthenticationStateStore_({cache,clock:()=>now,timeoutSeconds:120}),identities:identity,users,memberships,sessions:sessionService,gateway,clock:()=>now,entitlements});}
let bad=service({verify:()=>{throw new ProviderError('unavailable','PROVIDER_UNAVAILABLE')}}),badFlow='FLOWDDDDDDDDDDDDDDDDDDDDDDDDDDDD',attempt=bad.begin('GOOGLE','home',badFlow);assert.throws(()=>bad.complete({state:attempt.state,flowId:badFlow,code:'bad'}));assert.equal(sessionRows.length,0,'failed assertion creates no session');assert.throws(()=>bad.complete({state:attempt.state,flowId:badFlow,code:'replay'}),'failed callback transaction cannot be reused');
const claims={signatureVerified:true,iss:'https://accounts.google.com',aud:'client',sub:'stable-subject',exp:Math.floor(now/1000)+300,auth_time:Math.floor(now/1000)},good=service({verify:req=>Object.assign({},claims,{nonce:req.expectedNonce})}),goodFlow='FLOWEEEEEEEEEEEEEEEEEEEEEEEEEEEE',retry=good.begin('GOOGLE','home',goodFlow),success=good.complete({state:retry.state,flowId:goodFlow,code:'good'});assert.equal(success.state,'SIGNED_IN','fresh retry succeeds');assert.equal(sessionRows.length,1);
const activeToken=success.session.token,validation=service({verify:req=>Object.assign({},claims,{nonce:'foreign'})}),reauthFlow='FLOWFFFFFFFFFFFFFFFFFFFFFFFFFFFF',reauth=validation.begin('GOOGLE','home',reauthFlow);assert.throws(()=>validation.complete({state:reauth.state,flowId:reauthFlow,code:'bad-nonce'}));assert.equal(sessionService.resolve(activeToken).userId,'U1','failed reauthentication leaves unrelated session intact');assert.equal(sessionRows.length,1,'no partial reauthentication session');
const signIn=fs.readFileSync(path.join(root,'UI','SignIn.html'),'utf8'),callback=fs.readFileSync(path.join(root,'UI','AuthCallback.html'),'utf8'),serviceSource=fs.readFileSync(path.join(root,'Services','AuthenticationService.gs'),'utf8');['if(signing)return','providerButtons(true)','providerButtons(false)','setTimeout','abortAtlasSignIn','forgetTransaction','SIGNED_OUT'].forEach(x=>assert(signIn.includes(x),x));['finishFailure','clearTransaction','location.replace','access_denied','atlasPendingSessionToken','logoutAtlasSession'].forEach(x=>assert(callback.includes(x),x));assert(callback.includes("sessionStorage.removeItem('atlasPendingSessionToken')"));assert(!callback.includes("sessionStorage.removeItem('atlasSessionToken')"),'failed callback does not corrupt active session');assert(serviceSource.includes("status:selectedTenant?'ACTIVE':'PENDING_TENANT'"));
console.log('MOS-125 authentication failure cleanup, supersession, retry, timeout, and session-isolation tests passed');
