const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const base=path.join(__dirname,'..','appscript','src'),stores={Customer:[],RFQ:[],Quote:[],Job:[],Invoice:[]};
function conflict(message){this.name='VmosConflictError';this.message=message;}function denied(message){this.name='VmosAuthorizationError';this.message=message;}function missing(message){this.name='VmosNotFoundError';this.message=message;}
function service(type){return {repository:null,list:()=>stores[type],get:id=>{const row=stores[type].find(item=>item.id===id);if(!row)throw new missing('Record was not found.');return row;},findFirstByField:(field,value)=>stores[type].find(item=>item[field]===value)||null,listByField:(field,value,limit)=>stores[type].filter(item=>item[field]===value).slice(0,limit),update:(id,changes)=>{const row=stores[type].find(item=>item.id===id);Object.assign(row,changes);return row;}};}
function MvpService(type,options){const target=service(type);target.repository=target;target.create=(input,id)=>{const proof=options&&options.mutationProof||{};const row=Object.assign({id},input,{securityOperationId:proof.operationId,securityOperationFingerprint:proof.fingerprint,securityTenantId:proof.tenantId,securityActorId:proof.actorId});stores[type].push(row);return row;};return target;}
const context=vm.createContext({Date,Math,Number,String,Object,Array,JSON,MvpService_:MvpService,VmosConflictError:conflict,VmosAuthorizationError_:denied,VmosNotFoundError_:missing,serializeVmosValue_:value=>JSON.parse(JSON.stringify(value))});
vm.runInContext(fs.readFileSync(path.join(base,'Services','CommercialWorkflowService.gs'),'utf8'),context);
stores.Customer.push({id:'CUS-1',name:'Atlas Customer',status:'Active',securityTenantId:'TENANT-A',securityOperationId:'SECRET-PROOF'});
const deps={customers:service('Customer'),rfqs:service('RFQ'),quotes:service('Quote'),jobs:service('Job'),invoices:service('Invoice'),quoteRevisions:{accept:(id,version,actor)=>{const quote=stores.Quote[0];assert.equal(id,'QREV-1');quote.status='Accepted';quote.acceptedRevisionId=id;return quote;}},limit:1};Object.values(deps).filter(value=>value&&value.list).forEach(value=>value.repository=value);
const workflow=new context.CommercialWorkflowService_(deps),actor={tenantId:'TENANT-A',userId:'SALES-A',operationId:'OP-1',requestFingerprint:'FP-1',capabilities:['RFQ_WRITE','QUOTE_WRITE','QUOTE_APPROVE','QUOTE_ISSUE','OPERATIONS_WRITE','FINANCE_WRITE','SALES_WRITE','FOLLOWUP_WRITE']};
let workspace=workflow.get({route:'customers',id:'CUS-1'},actor);assert.equal(workspace.selected.name,'Atlas Customer');assert.equal(workspace.selected.securityOperationId,undefined,'storage proof fields must not reach the browser');assert.equal(workspace.bounds.directory,1);assert.equal(workspace.actions.createRfq,true);
assert.throws(()=>workflow.get({route:'customers',id:'CUS-1'},Object.assign({},actor,{tenantId:'TENANT-B'})),error=>/unavailable/.test(error.message));
assert.throws(()=>workflow.createRfq('CUS-1',{description:'Forged relationship'},Object.assign({},actor,{tenantId:'TENANT-B'}),'RFQ-X'),error=>/unavailable/.test(error.message));
const rfq=workflow.createRfq('CUS-1',{description:'Bound request'},actor,'RFQ-1');assert.equal(rfq.customerId,'CUS-1');assert.equal(rfq.securityActorId,'SALES-A');
const quote=workflow.createQuote('RFQ-1',{total:'1250'},actor,'QUO-1');assert.equal(quote.rfqId,'RFQ-1');assert.strictEqual(workflow.createQuote('RFQ-1',{},actor,'QUO-2'),quote,'one RFQ must not silently create duplicate Quotes');
assert.throws(()=>workflow.convertQuoteToJob('QUO-1',{},actor,'JOB-X'),error=>/accepted/.test(error.message));quote.status='Issued';quote.issuedRevisionId='QREV-1';quote.issuedRevisionVersion=2;workflow.acceptQuote('QUO-1',actor);assert.equal(quote.status,'Accepted');
const job=workflow.convertQuoteToJob('QUO-1',{quantity:'4'},actor,'JOB-1');assert.equal(job.customerId,'CUS-1');assert.equal(job.acceptedQuoteRevisionId,'QREV-1');assert.strictEqual(workflow.convertQuoteToJob('QUO-1',{},actor,'JOB-2'),job);
const invoice=workflow.createInvoice('JOB-1',{},actor,'INV-1');assert.equal(invoice.total,1250);assert.strictEqual(workflow.createInvoice('JOB-1',{},actor,'INV-2'),invoice);
workspace=workflow.get({route:'jobs',id:'JOB-1'},actor);assert.equal(workspace.context.customer.id,'CUS-1');assert.equal(workspace.context.rfq.id,'RFQ-1');assert.equal(workspace.context.quote.id,'QUO-1');assert.equal(workspace.related.invoice.id,'INV-1');
const html=fs.readFileSync(path.join(base,'UI','CommercialWorkflow.html'),'utf8'),sales=fs.readFileSync(path.join(base,'UI','SalesActivity.html'),'utf8'),followups=fs.readFileSync(path.join(base,'UI','CalendarFollowUps.html'),'utf8'),code=fs.readFileSync(path.join(base,'UI','Code.gs'),'utf8'),registry=fs.readFileSync(path.join(base,'Services','EndpointAuthorizationRegistry.gs'),'utf8');
assert.match(html,/Customer request to Work Order and Invoice/);assert.match(html,/quote-builder&quoteId=/);assert.doesNotMatch(html,/Approve internally|Issue to Customer|Record Customer acceptance/);assert.match(html,/@media\(max-width:520px\)/);assert.doesNotMatch(html,/Customer ID<\/label>|RFQ ID<\/label>|Job ID<\/label>/);assert.match(sales,/URLSearchParams\(location\.search\)/);assert.match(followups,/createContextFollowUp/);assert.match(code,/preallocateSecurityResourceId_\('RFQ'\)/);assert.match(code,/securityOperationOptions_\('convertQuoteToJob'/);
assert.match(registry,/createQuoteFromRfq:\{kind:'WRITE',capability:'QUOTE_WRITE'\}/);assert.match(registry,/convertQuoteToJob:\{kind:'HIGH_RISK_WRITE',capability:'OPERATIONS_WRITE'\}/);assert.match(registry,/createInvoiceFromJob:\{kind:'HIGH_RISK_WRITE',capability:'FINANCE_WRITE'\}/);
console.log('Atlas contextual commercial workflow tests passed');
