const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');const base=path.join(__dirname,'..','appscript','src');
const c=vm.createContext({Date,String,Number,Boolean,Object,Array,Math,JSON,encodeURIComponent,PropertiesService:{getScriptProperties:()=>({getProperty:()=>''})},Session:{getScriptTimeZone:()=> 'America/Los_Angeles'},Utilities:{formatDate:(value,tz)=>new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(value))},serializeVmosValue_:v=>JSON.parse(JSON.stringify(v)),VmosValidationError_:function(m){this.message=m},VmosAuthorizationError_:function(m){this.message=m},VmosConflictError:function(m){this.message=m}});
c.TenantMembershipRepository_=function(){this.findActive=(tenant,user)=>tenant==='T1'&&user==='U2'?{id:'M2'}:null;};c.MvpService_=function(entity,deps){this.update=(id,changes)=>deps.repository.updateById(id,changes);};vm.runInContext(fs.readFileSync(path.join(base,'Services','DailyProductionService.gs'),'utf8'),c);
const context={tenantId:'T1',userId:'U1',capabilities:['OPERATIONS_READ','OPERATIONS_WRITE']},now=new Date('2026-08-14T16:00:00Z'); // Friday 09:00 Pacific
const jobs=[
 {id:'OVER',customerId:'C1',dueDate:'2026-08-13',status:'RUNNING',ownerUserId:'U1',materialReadiness:'READY',toolingReadiness:'READY',securityTenantId:'T1',version:1},
 {id:'TODAY',customerId:'C1',dueDate:'2026-08-14',status:'PLANNED',ownerUserId:'U1',materialReadiness:'UNKNOWN',toolingReadiness:'READY',securityTenantId:'T1',version:0},
 {id:'SAT',customerId:'C1',dueDate:'2026-08-15',status:'NOT STARTED',ownerUserId:'U2',materialReadiness:'READY',toolingReadiness:'UNKNOWN',blockerReason:'Awaiting fixture confirmation',securityTenantId:'T1',version:2},
 {id:'SUN',customerId:'C1',dueDate:'2026-08-16',status:'PLANNED',materialReadiness:'MISSING',toolingReadiness:'READY',securityTenantId:'T1'},
 {id:'NEXT',customerId:'C1',dueDate:'2026-08-17',status:'PLANNED',securityTenantId:'T1'},
 {id:'DONE',customerId:'C1',dueDate:'2026-08-14',status:'COMPLETED',securityTenantId:'T1'},
 {id:'CANCEL',customerId:'C1',dueDate:'2026-08-13',status:'CANCELLED',securityTenantId:'T1'},
 {id:'NODUE',customerId:'C1',status:'PLANNED',securityTenantId:'T1'},
 {id:'FOREIGN',customerId:'C2',dueDate:'2026-08-14',status:'PLANNED',securityTenantId:'T2'}
];
const customers=[{id:'C1',name:'H2',securityTenantId:'T1'},{id:'C2',name:'Foreign',securityTenantId:'T2'}],users=[{id:'U1',displayName:'Alex Operator',status:'ACTIVE'},{id:'U2',displayName:'Morgan Lead',status:'ACTIVE'}],members=[{tenantId:'T1',userId:'U1',status:'ACTIVE'},{tenantId:'T1',userId:'U2',status:'ACTIVE'}];
const list=rows=>({list:()=>rows,get:id=>rows.find(x=>x.id===id)});const service=new c.DailyProductionReadService_({jobs:list(jobs),customers:list(customers),users:list(users),memberships:list(members),clock:()=>now,timeZone:'America/Los_Angeles',limit:100});let model=service.get(context);
assert.deepEqual(model.buckets.OVERDUE.map(x=>x.id),['OVER']);assert.deepEqual(model.buckets.DUE_TODAY.map(x=>x.id),['TODAY']);assert.deepEqual(model.buckets.DUE_TOMORROW.map(x=>x.id),['SAT']);assert.deepEqual(model.buckets.THIS_WEEK.map(x=>x.id),['SUN']);assert.equal(model.totalMatching,4);assert.equal(model.repositoryReads,4);assert.equal(JSON.stringify(model).includes('FOREIGN'),false);
const defect=model.buckets.DUE_TOMORROW[0];assert.equal(defect.status,'NOT STARTED');assert.equal(defect.ownerName,'Morgan Lead');assert.equal(defect.materials,'READY');assert.equal(defect.tooling,'UNKNOWN');assert.equal(defect.blocker,'Awaiting fixture confirmation');assert.equal(defect.readiness,'BLOCKED');
assert.equal(c.dailyProductionReadiness_({materialReadiness:'READY',toolingReadiness:'READY'}),'READY');assert.equal(c.dailyProductionReadiness_({materialReadiness:'UNKNOWN',toolingReadiness:'READY'}),'AT_RISK');assert.equal(c.dailyProductionReadiness_({materialReadiness:'MISSING',toolingReadiness:'READY'}),'BLOCKED');assert.equal(c.dailyProductionReadiness_({materialReadiness:'READY',toolingReadiness:'MISSING'}),'BLOCKED');assert.equal(c.dailyProductionReadiness_({materialReadiness:'READY',toolingReadiness:'READY',blockerReason:'Problem'}),'BLOCKED');
assert.equal(c.dailyProductionBucket_('2026-08-14T15:59:59Z',now,'America/Los_Angeles'),'OVERDUE');assert.equal(c.dailyProductionBucket_('2026-08-14T23:00:00Z',now,'America/Los_Angeles'),'DUE_TODAY');assert.equal(c.dailyProductionBucket_('2026-08-17',now,'America/Los_Angeles'),'');
const repo={findById:id=>jobs.find(x=>x.id===id),updateById(id,changes){Object.assign(this.findById(id),changes);return this.findById(id)}};const mutations=new c.DailyProductionMutationService_({jobs:{get:repo.findById.bind(repo),repository:repo},auditUser:()=> 'U1',mutationProof:{operationId:'OP1',fingerprint:'FP',tenantId:'T1',actorId:'U1'}});let changed=mutations.update('SAT',{ownerUserId:'U2',currentOperation:'Welding',materialReadiness:'READY',toolingReadiness:'READY',blockerReason:''},2,context);assert.equal(changed.version,3);assert.equal(changed.blockerActive,false);model=service.get(context);assert.equal(model.buckets.DUE_TOMORROW[0].readiness,'READY');assert.equal(model.buckets.DUE_TOMORROW[0].currentOperation,'Welding');assert.throws(()=>mutations.update('SAT',{status:'COMPLETE'},2,context),e=>/changed/.test(e.message));changed=mutations.update('SAT',{status:'COMPLETE'},3,context);assert.equal(changed.status,'COMPLETE');assert.equal(service.get(context).buckets.DUE_TOMORROW.length,0);assert.throws(()=>mutations.update('FOREIGN',{status:'COMPLETE'},0,context),e=>/unavailable/.test(e.message));
const ui=fs.readFileSync(path.join(base,'UI','DailyProductionBoard.html'),'utf8'),server=fs.readFileSync(path.join(base,'UI','Code.gs'),'utf8'),registry=fs.readFileSync(path.join(base,'Services','EndpointAuthorizationRegistry.gs'),'utf8');['Overdue','Due today','Due tomorrow','This week','Materials','Tooling','BLOCKER:','Open Work Order','Complete Work Order','aria-live','Skip to committed work','<option>NOT STARTED</option>'].forEach(x=>assert(ui.includes(x),x));assert(/@media\(max-width:620px\)/.test(ui));assert(/min-height:44px/.test(ui));assert(!ui.includes('getMvpBootstrap'));assert.match(server,/function getDailyProductionBoard/);assert.match(server,/function updateDailyProductionJob/);assert.match(registry,/getDailyProductionBoard:\{kind:'READ',capability:'OPERATIONS_READ'\}/);assert.match(registry,/updateDailyProductionJob:\{kind:'HIGH_RISK_WRITE',capability:'OPERATIONS_WRITE'\}/);assert.match(registry,/updateDailyProductionJob:'EXPLICIT_REVIEW'/);
console.log('MOS-127 Daily Production bucket, readiness, mutation, security, and UI tests passed');
