const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const base=path.join(__dirname,'..','appscript','src');let n=0;
const c=vm.createContext({Date,Number,String,Object,Array,JSON,Utilities:{getUuid:()=>String(++n)},VmosValidationError:function(m){this.message=m},VmosNotFoundError:function(m){this.message=m},VmosConfigurationError:function(m){this.message=m}});
vm.runInContext(fs.readFileSync(path.join(base,'Services','FollowUpCalendarService.gs'),'utf8'),c);
let props={};c.PropertiesService={getScriptProperties:()=>({getProperty:k=>props[k]||null})};
vm.runInContext(fs.readFileSync(path.join(base,'ConfigFollowUpCalendar.gs'),'utf8'),c);
vm.runInContext(fs.readFileSync(path.join(base,'Services','CalendarProviderFramework.gs'),'utf8'),c);
assert.equal(c.getCalendarFollowUpConfig_().enabled,false);assert.throws(()=>c.assertCalendarFollowUpEnabled_(),e=>/disabled/.test(e.message));
c.getVmosConfig_=()=>({spreadsheetId:'test'});const legacyMapping=JSON.parse(JSON.stringify(c.VMOS_DEFAULT_FOLLOW_UP_MAPPINGS));delete legacyMapping.syncEvents;props.VMOS_FOLLOW_UP_MAPPING=JSON.stringify(legacyMapping);assert.ok(c.getFollowUpStorageConfig_().mappings.followUps,'legacy mapping without sync events preserves core FollowUps');assert.throws(()=>c.getCalendarSyncEventStorageConfig_(),e=>/required for writable calendar/.test(e.message));props={};
const follows=[],events=[],links=[],requests=[],syncEvents=[];
const repo={create:r=>{follows.push(r);return r},get:id=>follows.find(r=>r.id===id),update:(id,r)=>{follows[follows.findIndex(x=>x.id===id)]=r;return r}};
const follow=new c.FollowUpService({repository:repo,events:{append:e=>events.push(e)},clock:()=>new Date('2026-08-08T12:00:00Z'),id:p=>p+'-'+(++n)});
const f=follow.create({customerId:'CUST-1',salesActivityId:'SACT-1',title:'Call owner',dueAt:'2026-08-12T09:00:00Z',ownerUserId:'Josh'},'Josh');
assert.equal(follow.schedulingClassification_(f),'LEGACY_DEADLINE_ONLY');
assert.throws(()=>follow.schedule(f.id,{startAt:'2026-08-12T15:00:00Z',endAt:'2026-08-12T14:30:00Z',timeZone:'America/Los_Angeles'},f.version,'Josh','bad'),e=>/end after start/.test(e.message));
const linkRepo={findByExternalEvent:(p,id)=>links.find(x=>x.provider===p&&x.externalEventId===id),findByFollowUpId:id=>links.find(x=>x.followUpId===id),create:r=>{links.push(r);return r},update:(id,r)=>{links[links.findIndex(x=>x.id===id)]=r;return r}};
const requestRepo={create:r=>{requests.push(r);return r},get:id=>requests.find(r=>r.id===id),update:(id,r)=>{requests[requests.findIndex(x=>x.id===id)]=r;return r}};
const syncRepo={findByCorrelation:(p,id)=>syncEvents.find(x=>x.provider===p&&x.correlationId===id),append:e=>{syncEvents.push(e);return e}};
let gatewayCalls=0,gatewayFailure=false;const gateway={upsert:p=>{gatewayCalls++;if(gatewayFailure)throw new Error('uncertain provider outcome');return {externalEventId:p.externalEventId||'gcal-1',externalVersion:'v1'}}};const provider=new c.GoogleCalendarFollowUpAdapter(gateway);
let lockWaits=0,lockReleases=0;const sync=new c.CalendarFollowUpSyncService({followUps:follow,links:linkRepo,requests:requestRepo,syncEvents:syncRepo,provider,lock:{waitLock:()=>lockWaits++,releaseLock:()=>lockReleases++},clock:()=>new Date('2026-08-08T12:00:00Z'),id:p=>p+'-'+(++n)});
assert.throws(()=>sync.syncToExternal(f.id,'legacy'),e=>/deadline-only/.test(e.message),'legacy follow-up cannot automatically project');
follow.schedule(f.id,{startAt:'2026-08-12T15:00:00Z',endAt:'2026-08-12T15:30:00Z',timeZone:'America/Los_Angeles'},f.version,'Josh','schedule-1');
assert.equal(follow.schedulingClassification_(f),'SCHEDULED');assert.equal(f.timeZone,'America/Los_Angeles');assert.equal(f.dueAt.toISOString(),'2026-08-12T09:00:00.000Z','Due At remains independent deadline');
const pushed=sync.syncToExternal(f.id,'mos-1');assert.equal(pushed.result,'PUSHED');assert.equal(links[0].externalEventId,'gcal-1');assert.equal(links[0].connectionId,'');
assert.equal(pushed.followUpId,f.id);assert.equal(pushed.operation,'OUTBOUND_PROJECTION');assert.equal(pushed.mosVersion,f.version);assert.ok(pushed.totalDurationMs>=0&&pushed.providerDurationMs>=0&&pushed.repositoryDurationMs>=0,'sync event retains measurement fields');
assert.equal(sync.syncToExternal(f.id,'mos-1'),pushed,'outbound replay returns durable prior event');assert.equal(gatewayCalls,1,'outbound replay never repeats provider mutation');
gatewayFailure=true;const failed=sync.syncToExternal(f.id,'mos-failed');assert.equal(failed.result,'FAILED');assert.equal(failed.recoveryRequired,true);assert.match(failed.details,/uncertain provider outcome/);gatewayFailure=false;
const before=f.version;const applied=sync.syncFromExternal({provider:'GOOGLE_CALENDAR',externalEventId:'gcal-1',externalVersion:'v2',changeType:'UPSERT',dueAt:'2026-08-13T09:00:00Z',mosVersion:before,correlationId:'cal-1'});assert.equal(applied.result,'APPLIED');assert.equal(f.version,before+1);assert.match(String(f.dueAt),/Aug 13/);
assert.equal(applied.followUpId,f.id);assert.equal(applied.operation,'INBOUND_RECONCILE');assert.equal(applied.changeType,'UPSERT');assert.equal(applied.externalVersion,'v2');
assert.equal(sync.syncFromExternal({provider:'GOOGLE_CALENDAR',externalEventId:'gcal-1',changeType:'UPSERT',dueAt:'2026-08-13T09:00:00Z',mosVersion:before,correlationId:'cal-1'}),applied,'duplicate event is idempotent');
assert.equal(lockWaits,lockReleases,'every serialized sync path releases its lock');assert.ok(lockWaits>=4,'inbound and outbound correlation checks are serialized');
const conflict=sync.syncFromExternal({provider:'GOOGLE_CALENDAR',externalEventId:'gcal-1',changeType:'UPSERT',startAt:'2026-08-14T16:00:00Z',endAt:'2026-08-14T16:30:00Z',timeZone:'America/Los_Angeles',mosVersion:1,correlationId:'cal-conflict'});assert.equal(conflict.result,'CONFLICT');assert.equal(requests[0].requestedStartAt,'2026-08-14T16:00:00Z');assert.equal(requests[0].requestedTimeZone,'America/Los_Angeles');
const deleted=sync.syncFromExternal({provider:'GOOGLE_CALENDAR',externalEventId:'gcal-1',changeType:'DELETED',externalVersion:'v3',correlationId:'cal-delete'});assert.equal(deleted.result,'REVIEW_REQUIRED');assert.equal(f.status,'OPEN','calendar deletion never closes MOS follow-up');
const deletionRequest=requests.find(r=>r.changeType==='DELETED');sync.resolveExternalChange(deletionRequest.id,'KEEP_FOLLOW_UP','Josh');assert.equal(f.status,'OPEN');
const deletionRequest2=requestRepo.create({id:'ECR-manual',followUpId:f.id,status:'PENDING_REVIEW'});sync.resolveExternalChange(deletionRequest2.id,'MARK_COMPLETE','Josh');assert.equal(f.status,'COMPLETED');
const ical=new c.IcalFollowUpPublicationAdapter({publish:()=>({})});assert.equal(ical.capabilities().providerKey,'ICAL_PUBLICATION');assert.equal(ical.capabilities().supportsTwoWayReschedule,false);
const registry=new c.CalendarProviderRegistry();assert.deepEqual(registry.list().map(x=>x.providerKey),['GOOGLE_CALENDAR','MICROSOFT_GRAPH_CALENDAR','APPLE_ICLOUD_CALENDAR','ICAL_PUBLICATION']);assert.equal(registry.get('MICROSOFT_GRAPH_CALENDAR').supportsDeltaSync,true);assert.equal(registry.get('APPLE_ICLOUD_CALENDAR').supportsPolling,true);assert.equal(registry.isWritable('ICAL_PUBLICATION'),false);
const connections=[];const connectionRepo={create:r=>{connections.push(r);return r},listByUserId:id=>connections.filter(r=>r.userId===id)};
const connectionService=new c.CalendarConnectionService({repository:connectionRepo,registry,clock:()=>new Date('2026-08-08T12:00:00Z'),id:p=>p+'-'+(++n)});
connectionService.create({userId:'Josh',provider:'GOOGLE_CALENDAR',externalCalendarId:'sales',credentialReference:'script-property:calendar-josh',connectionStatus:'CONNECTED'});
connectionService.create({userId:'Brendan',provider:'MICROSOFT_GRAPH_CALENDAR',externalCalendarId:'outlook',credentialReference:'secure-ref:brendan',connectionStatus:'CONNECTED'});
assert.equal(connectionService.resolveWritableForOwner('Josh').connection.provider,'GOOGLE_CALENDAR');assert.equal(connectionService.resolveWritableForOwner('Brendan').connection.provider,'MICROSOFT_GRAPH_CALENDAR');assert.equal(connectionService.resolveWritableForOwner('Other').state,'NOT_CONNECTED');
assert.throws(()=>connectionService.create({userId:'Josh',provider:'GOOGLE_CALENDAR',refreshToken:'no'}),e=>/Raw calendar credentials/.test(e.message));assert.ok(!Object.keys(connections[0]).some(k=>/token|password|secret/i.test(k)&&k!=='tokenExpiresAt'),'no raw credential field persisted');
const routing=new c.FollowUpCalendarRoutingService(connectionService);assert.equal(routing.destinationFor({ownerUserId:'Josh'}).state,'CONNECTED');assert.equal(routing.destinationFor({ownerUserId:'Other'}).state,'NOT_CONNECTED');
console.log('VMOS follow-up calendar tests passed');
