const assert=require('assert'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),doc=fs.readFileSync(path.join(root,'docs','Architecture','MOS-129A-Unified-Atlas-UX-Architecture.md'),'utf8'),prototype=fs.readFileSync(path.join(root,'docs','prototypes','MOS-129A-Unified-Atlas-UX.html'),'utf8'),routes=fs.readFileSync(path.join(root,'appscript','src','Services','NavigationService.gs'),'utf8');
['Mission Control','Record Canvas / 360','My Work','Shop Floor','Command / Search'].forEach(term=>assert(doc.includes(term),term));
['Owner / Manager','Sales / PM','Shop Operator','Purchasing','Finance','Tenant Admin'].forEach(term=>assert(doc.includes(term),term));
['Command Center','Customers','Sales Activity','Follow-Ups','RFQs','Quotes / Quote Builder','Jobs','Daily Production','Shop Floor','Floor Board','Purchasing','Invoices','Vendor','Firearms','Tenant Admin','Ideas','Traveler'].forEach(surface=>assert(doc.includes(surface),surface));
['MOS-129B','MOS-129C','MOS-129D','MOS-129E','MOS-129F1','MOS-129G'].forEach(story=>assert(doc.includes(story),story));
['loading','empty','validation','permission','uncertain outcome','stale conflict','session expiry','unavailable-reference'].forEach(state=>assert(doc.toLowerCase().includes(state.toLowerCase()),state));
['1440+','~1024','~768','~390'].forEach(size=>assert(doc.includes(size),size));
['mission','canvas','work','floor','command'].forEach(mode=>assert(new RegExp(`id="${mode}"`).test(prototype),mode));
assert.match(prototype,/Non-production UX architecture prototype/);
assert.match(prototype,/Northstar Fabrication/);
assert.doesNotMatch(prototype,/google\.script|sessionStorage|localStorage|fetch\(|XMLHttpRequest/,'Prototype has no production/runtime integration.');
assert.doesNotMatch(routes,/MOS-129A|Unified-Atlas-UX|unified-atlas-ux/,'Prototype is not registered as a production route.');
assert.match(prototype,/@media\(max-width:1024px\)/);
assert.match(prototype,/@media\(max-width:768px\)/);
assert.match(prototype,/@media\(max-width:480px\)/);
assert.match(prototype,/min-height:44px/);
assert.match(prototype,/:focus-visible/);
console.log('MOS-129A unified UX architecture and non-production prototype contracts passed');
