const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..','appscript','src'),rows={Customer:[{id:'C-1',tenantId:'T1',name:'Acme Industries',status:'ACTIVE'},{id:'C-X',tenantId:'T2',name:'Acme Foreign'}],RFQ:[{id:'RFQ-1',tenantId:'T1',customerRfqNumber:'ACME-77',description:'Bracket',status:'OPEN'}],Quote:[{id:'Q-1',tenantId:'T1',quoteNumber:'Q-100',status:'ISSUED'}],Job:[{id:'WO-42',tenantId:'T1',partId:'Plate',status:'BLOCKED'}],Invoice:[{id:'INV-8',tenantId:'T1',invoiceNumber:'INV-8',status:'OPEN'}],PurchaseRequest:[{id:'PR-9',tenantId:'T1',description:'Acme tooling',status:'PENDING'}],Vendor:[{id:'V-2',tenantId:'T1',name:'Acme Supply',status:'ACTIVE'}],Firearm:[{id:'F-3',tenantId:'T1',manufacturer:'Atlas Arms',model:'A1',serialNumber:'ABC123'}]};
const sources={};Object.keys(rows).forEach(type=>sources[type]={list:()=>rows[type],forTenant:tenant=>rows[type].filter(r=>r.tenantId===tenant)});const context={console,Object,Array,String,Number,encodeURIComponent,VmosValidationError_:Error};vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(root,'Services','UnifiedSearchService.gs'),'utf8'),context);
const service=new context.UnifiedSearchService_({sources,limit:5}),base={tenantId:'T1',enabledModules:['FIREARMS'],capabilities:['CORE_RECORD_READ','RFQ_READ','OPERATIONS_READ','FINANCE_READ','PURCHASE_REQUEST','QUOTE_COST_READ','FIREARMS_READ']};
let result=service.search('acme',base,5);assert.equal(result.bounded,true);assert.equal(result.limit,5);assert(result.items.length<=5);assert(!result.items.some(x=>x.recordId==='C-X'),'foreign tenant records never leak');assert(result.items.every(x=>x.label&&x.type&&x.href));assert(result.items.some(x=>x.type==='Customer'&&x.label==='Acme Industries'));
result=service.search('abc123',base,5);assert.equal(result.items[0].type,'Firearm');assert.equal(result.items[0].label,'Atlas Arms A1 ABC123');
result=service.search('acme',{tenantId:'T1',enabledModules:[],capabilities:['CORE_RECORD_READ']},5);assert.deepEqual(Array.from(result.items).map(x=>x.type),['Customer']);
assert.equal(service.search('a',base,5).minimumQueryLength,2);assert.equal(service.search('a',base,5).items.length,0);
console.log('MOS-129B bounded tenant-safe command search tests passed');
