const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm'),base=path.join(__dirname,'..','appscript','src');
function E(message,code){this.message=message;this.code=code;}E.prototype=Object.create(Error.prototype);
const context=vm.createContext({Date,Math,Number,String,Object,Array,JSON,VmosValidationError_:function(m){return new E(m,'VALIDATION_ERROR')},VmosAuthorizationError_:function(m){return new E(m||'Denied','AUTHORIZATION_ERROR')},VmosNotFoundError_:function(m){return new E(m,'NOT_FOUND')},VmosConfigurationError_:function(m){return new E(m,'CONFIGURATION_ERROR')},VmosConflictError:function(m){return new E(m,'CONFLICT')}});
vm.runInContext(fs.readFileSync(path.join(base,'Services','SerializedFirearmService.gs'),'utf8'),context);
const records=[],events=[],customers=[{id:'C-1',securityTenantId:'T-1',name:'Casey Customer',email:'casey@example.test'},{id:'C-2',securityTenantId:'T-1',name:'Different Customer'},{id:'C-X',securityTenantId:'T-2',name:'Foreign Customer'}],jobs=[{id:'J-1',securityTenantId:'T-1',customerId:'C-1',partId:'Slide work',status:'IN_PROCESS'},{id:'J-WRONG',securityTenantId:'T-1',customerId:'C-2',partId:'Wrong customer work',status:'PLANNED'},{id:'J-DONE',securityTenantId:'T-1',customerId:'C-1',partId:'Closed work',status:'COMPLETE'},{id:'J-X',securityTenantId:'T-2',customerId:'C-X',partId:'Foreign work',status:'PLANNED'}],ffls=[{id:'FFL-1',tenantId:'T-1',displayName:'Partner Arms',licenseReference:'9-99-001',premisesAddress:'Reno, NV',status:'ACTIVE'},{id:'FFL-INACTIVE',tenantId:'T-1',displayName:'Former FFL',status:'INACTIVE'},{id:'FFL-X',tenantId:'T-2',displayName:'Foreign FFL',status:'ACTIVE'}];
const repo=rows=>({list:()=>rows.map(x=>({...x})),get:id=>{const row=rows.find(x=>x.id===id);if(!row)throw new E('missing','NOT_FOUND');return {...row}}}),recordRepo={...repo(records),create:r=>(records.push({...r}),{...r}),update:(id,c)=>{const i=records.findIndex(x=>x.id===id);records[i]={...records[i],...c};return {...records[i]}},findDuplicate:(t,m,i,s)=>records.find(r=>r.tenantId===t&&r.manufacturer.toUpperCase()===String(m).toUpperCase()&&r.importer.toUpperCase()===String(i).toUpperCase()&&r.serialNormalized===s)},eventRepo={listByFirearm:(t,id)=>events.filter(e=>e.tenantId===t&&e.firearmId===id),get:id=>{const e=events.find(x=>x.id===id);if(!e)throw new E('missing','NOT_FOUND');return e},append:e=>{if(!events.some(x=>x.id===e.id))events.push({...e});return e}};
let n=0;const service=new context.SerializedFirearmService_({records:recordRepo,events:eventRepo,customers:repo(customers),jobs:repo(jobs),ffls:repo(ffls),clock:()=>new Date('2026-08-15T12:00:00Z'),uuid:()=>String(++n)}),actor={tenantId:'T-1',userId:'USER-1',operationId:'OP-1',correlationId:'CORR-1'};
const intake={manufacturer:'Acme',importer:'',model:'M1',serialNumber:'AA-123',caliberGauge:'9mm',classification:'Pistol',acquisitionDate:'2026-08-15',acquisitionSourceType:'CUSTOMER',acquisitionSourceName:'FORGED NAME',customerId:'C-1',custodyLocation:'Intake safe'};
let firearm=service.intake(intake,actor,'FIREARM-1');assert.equal(firearm.acquisitionSourceName,'Casey Customer','Server must hydrate the canonical source name.');assert.throws(()=>service.intake({...intake,serialNumber:'BB-1',customerId:'C-X'},{...actor,operationId:'OP-X'},'FIREARM-X'),e=>e.code==='NOT_FOUND');
assert.deepEqual(JSON.parse(JSON.stringify(service.searchRelationships('CUSTOMER','Casey','',actor).items.map(x=>x.label))),['Casey Customer']);assert.deepEqual(JSON.parse(JSON.stringify(service.searchRelationships('FFL','','',actor).items.map(x=>x.id))),['FFL-1']);assert.deepEqual(JSON.parse(JSON.stringify(service.searchRelationships('JOB','',firearm.id,actor).items.map(x=>x.id))),['J-1']);
assert.throws(()=>service.assignJob(firearm.id,'J-WRONG',firearm.version,{...actor,operationId:'OP-2'}),/linked Customer/);assert.throws(()=>service.assignJob(firearm.id,'J-X',firearm.version,{...actor,operationId:'OP-3'}),e=>e.code==='NOT_FOUND');assert.throws(()=>service.assignJob(firearm.id,'J-DONE',firearm.version,{...actor,operationId:'OP-4'}),/active Job/);
firearm=service.assignJob(firearm.id,'J-1',firearm.version,{...actor,operationId:'OP-5'});assert.equal(firearm.jobId,'J-1');assert.throws(()=>service.moveCustody(firearm.id,'Unknown','TELEPORTED',firearm.version,{...actor,operationId:'OP-6'}),/available custody state/);firearm=service.moveCustody(firearm.id,'Bench 4','IN_WORK',firearm.version,{...actor,operationId:'OP-7'});
assert.throws(()=>service.correctField(firearm.id,'lifecycleStatus','ACQUIRED','bad','',firearm.version,{...actor,operationId:'OP-8'}),/available correction field/);const before=events.length;firearm=service.correctField(firearm.id,'SERIAL_NUMBER','AA-124','Source document correction','',firearm.version,{...actor,operationId:'OP-9'});assert.equal(firearm.serialNumber,'AA-124');assert.equal(events.length,before+1);assert.equal(JSON.parse(events.at(-1).previousJson).serialNumber,'AA-123');
firearm=service.dispose(firearm.id,{recipientType:'FFL',externalFflId:'FFL-1',recipientName:'FORGED',dispositionDate:'2026-08-16'},firearm.version,{...actor,operationId:'OP-10'});assert.equal(firearm.recipientName,'Partner Arms');assert.throws(()=>service.dispose(firearm.id,{recipientType:'FFL',externalFflId:'FFL-INACTIVE',dispositionDate:'2026-08-16'},firearm.version,{...actor,operationId:'OP-11'}),/active External FFL/);
records[0].customerId='C-MISSING';records[0].externalFflId='FFL-INACTIVE';records[0].jobId='J-MISSING';const selected=service.workspace({id:'FIREARM-1'},actor).selected;assert.equal(selected.customerReference.state,'UNAVAILABLE');assert.equal(selected.customerReference.label,'Referenced Customer unavailable');assert.equal(selected.fflReference.state,'UNAVAILABLE');assert.equal(selected.fflReference.label,'Former FFL');assert.equal(selected.jobReference.state,'UNAVAILABLE');

const ui=fs.readFileSync(path.join(base,'UI','FirearmsWorkspace.html'),'utf8'),code=fs.readFileSync(path.join(base,'UI','Code.gs'),'utf8'),registry=fs.readFileSync(path.join(base,'Services','EndpointAuthorizationRegistry.gs'),'utf8');new vm.Script((ui.match(/<script>([\s\S]*?)<\/script>/)||[])[1]);assert.doesNotMatch(ui,/\bprompt\s*\(|\bconfirm\s*\(/);assert.doesNotMatch(ui,/workspace\.(customers|jobs|ffls)/);assert.match(ui,/role="combobox"/);assert.match(ui,/role="dialog"/);assert.match(ui,/aria-live="polite"/);assert.match(ui,/modalReturnFocus/);assert.match(ui,/e\.key==='Tab'/);assert.match(ui,/Saving intake…|Moving custody…|Recording disposition…|Applying correction…|Reconciling…/);assert.match(ui,/if\(actionBusy\)return/);assert.match(ui,/cannot confirm the result[\s\S]*authoritative record/);assert.match(ui,/Select the .* from the search results/);assert.match(code,/searchFirearmsRelationships/);assert.match(code,/correctSerializedFirearmField/);assert.match(registry,/searchFirearmsRelationships:\{kind:'READ',capability:'FIREARMS_READ'\}/);assert.match(registry,/correctSerializedFirearmField:'EXPLICIT_REVIEW'/);
console.log('MOS-128D contextual Firearms selectors, hydration, controlled correction, and stable-state UX tests passed');
