const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');
const html=fs.readFileSync(path.join(__dirname,'..','appscript','src','UI','UnifiedCommandPalette.html'),'utf8'),script=(html.match(/<script>([\s\S]*?)<\/script>/)||[])[1];assert(script,'command palette script exists');
const elements={};function element(id){return elements[id]||(elements[id]={id,value:'',hidden:id==='atlas-command-backdrop',textContent:'',innerHTML:'',className:'',attrs:{},listeners:{},dataset:{},setAttribute(k,v){this.attrs[k]=v;},addEventListener(k,v){this.listeners[k]=v;},focus(){document.activeElement=this;},querySelectorAll(){return[];}});}
['atlas-command-trigger','atlas-command-backdrop','atlas-command-input','atlas-command-close','atlas-command-status','atlas-command-results'].forEach(element);const document={activeElement:null,getElementById:element,addEventListener(){}};
const requests=[],runner={success:null,failure:null,withSuccessHandler(fn){this.success=fn;return this;},withFailureHandler(fn){this.failure=fn;return this;},searchAtlasCommand(query,limit){requests.push({query,limit,success:this.success,failure:this.failure});return this;}};
const context=vm.createContext({document,google:{script:{run:runner}},location:{assign(){}},clearTimeout(){},setTimeout(fn){fn();return 1;},String,Array,Object});vm.runInContext(script,context);
const input=element('atlas-command-input'),status=element('atlas-command-status'),results=element('atlas-command-results');function query(value){input.value=value;input.listeners.input();}
query('alpha');query('bravo');assert.equal(input.attrs['aria-busy'],'true');requests[1].success({ok:true,data:{items:[{type:'Customer',label:'Bravo Company',secondary:'Active',status:'',href:'?route=customers&id=C2'}]}});assert.match(results.innerHTML,/Bravo Company/);requests[0].success({ok:true,data:{items:[{type:'Customer',label:'Alpha Company',secondary:'Active',status:'',href:'?route=customers&id=C1'}]}});assert.match(results.innerHTML,/Bravo Company/);assert.doesNotMatch(results.innerHTML,/Alpha Company/);
query('charlie');query('delta');requests[2].failure(new Error('stale'));assert.equal(input.attrs['aria-busy'],'true');requests[3].success({ok:true,data:{items:[]}});assert.equal(input.attrs['aria-busy'],'false');assert.match(status.textContent,/No matching authorized records/);
query('echo');requests[4].failure(new Error('active'));assert.equal(input.attrs['aria-busy'],'false');assert.match(status.textContent,/temporarily unavailable/);query('foxtrot');requests[5].success({ok:true,data:{items:[{type:'Job',label:'Foxtrot Job',secondary:'Ready',href:'?route=jobs&id=J1'}]}});assert.match(results.innerHTML,/Foxtrot Job/);assert.equal(input.attrs['aria-busy'],'false');
console.log('MOS-129B command palette stale-response and busy-state tests passed');
