const assert=require('assert'),path=require('path');
const harness=require(path.join('..','tools','performance','atlas-performance-harness.js'));
const first=harness.generate('SMALL'),second=harness.generate('SMALL');
assert.deepEqual(first.counts,harness.TIERS.SMALL);
assert.equal(first.customers[42].id,second.customers[42].id,'fixtures are deterministic');
assert.equal(first.salesActivities[1100].customerId,first.customers[0].id,'activities retain customer relationships');
assert.equal(first.quotes[300].rfqId,first.rfqs[50].id,'quotes retain RFQ relationships');
assert.equal(first.jobEvents[2500].jobId,first.jobs[100].id,'history retains Job relationships');
assert.equal(first.calendarSyncEvents[999].followUpId,first.followUps[99].id,'sync events retain FollowUp relationships');
const results=harness.scenarios(first),byName=Object.fromEntries(results.map(row=>[row.scenario,row]));
assert.equal(results.length,13,'all required workload families are represented');
assert.equal(byName['CRM customer and timeline'].rowsExamined,1251,'customer open plus full activity timeline scan is characterized');
assert.equal(byName['Floor board ten refreshes'].reads,20,'long-running floor board models repeated refresh reads');
assert.ok(byName['Floor board ten refreshes'].rowsExamined>=10*(first.jobs.length+first.jobEvents.length));
assert.equal(byName['Calendar correlation lookup'].reads,1);assert.ok(byName['Calendar correlation lookup'].rowsExamined>0);
assert.equal(byName['Calendar sync persistence'].writes,1);
['operationDurationMs','serializationDurationMs','totalMeasuredMs','reads','writes','rowsExamined','payloadBytes','resultCount'].forEach(field=>results.forEach(row=>assert.ok(Object.prototype.hasOwnProperty.call(row,field),row.scenario+' reports '+field)));
results.forEach(row=>assert.ok(row.totalMeasuredMs>=row.operationDurationMs,'total measurement includes operation cost'));
const medium=harness.generate('MEDIUM');assert.ok(medium.jobEvents.length>first.jobEvents.length);assert.ok(harness.scenarios(medium).find(row=>row.scenario==='Job detail and history').rowsExamined>byName['Job detail and history'].rowsExamined,'history cost grows with tier');
console.log('Atlas deterministic performance harness tests passed');
