const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');const root=path.join(__dirname,'..','appscript','src');
const c=vm.createContext({String,Number,Boolean,Array,Object,Math,VmosValidationError_:function(m){this.message=m},VmosAuthorizationError_:function(m){this.message=m}});vm.runInContext(fs.readFileSync(path.join(root,'Services','QuoteBuilderReadService.gs'),'utf8'),c);
function svc(rows){return {list:()=>rows,get:id=>rows.find(x=>x.id===id)}}
const customers=svc([{id:'C1',name:'H2',status:'Active',securityTenantId:'T1'},{id:'C2',name:'Foreign',securityTenantId:'T2'}]);
const rfqs=svc([{id:'R1',customerId:'C1',customerRfqNumber:'VMC-0128',description:'H2 Plate Assemblies',receivedDate:'2026-08-12',status:'Open',securityTenantId:'T1'},{id:'R2',customerId:'C1',customerRfqNumber:'OLD',description:'Older work',receivedDate:'2026-01-01',status:'Open',securityTenantId:'T1'},{id:'R3',customerId:'C2',description:'Foreign',securityTenantId:'T2'}]);
const quotes=svc([{id:'Q2',rfqId:'R2',customerId:'C1',securityTenantId:'T1'}]);const vendorService={search:(q,ctx,l,cap)=>[{id:'V1',label:'OnlineMetals',secondary:cap}]};const costing={read:()=>({estimate:{id:'E1'},lines:[]})};
const service=new c.QuoteBuilderReadService_({customers,rfqs,quotes,vendors:vendorService,costing,limit:50});const context={tenantId:'T1',capabilities:['QUOTE_WRITE','QUOTE_COST_READ','QUOTE_MARGIN_READ']};
let result=service.search('RFQ','plate','C1',50,context);assert.equal(result.items.length,1);assert.equal(result.items[0].label,'VMC-0128 — H2 — H2 Plate Assemblies');assert.equal(result.items.some(x=>x.id==='R2'),false);assert.equal(result.items.some(x=>x.id==='R3'),false);assert.equal(result.bounded,true);
assert.equal(service.search('CUSTOMER','H2','',50,context).items[0].label,'H2');assert.equal(service.search('VENDOR','Online','WELDING_FABRICATION',50,context).items[0].label,'OnlineMetals');
let workspace=service.get({rfqId:'R1'},context);assert.equal(workspace.customer.name,'H2');assert.equal(workspace.costingWarning.includes('incomplete'),true);assert.equal(workspace.permissions.marginRead,true);
const html=fs.readFileSync(path.join(root,'UI','QuoteBuilder.html'),'utf8');['role="combobox"','aria-expanded','role="listbox"','ArrowDown','Escape','Customer preview','Internal costing','No unquoted RFQs are available.','setTimeout(function'].forEach(x=>assert(html.includes(x),x));assert(/@media\(max-width:600px\)/.test(html));assert(!/getMvpBootstrap/.test(html));
console.log('MOS-126D bounded record picker and Quote Builder tests passed');
