const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm');const root=path.join(__dirname,'..','appscript','src');
function Validation(m){this.message=m;this.code='VALIDATION_ERROR'}function Authorization(m){this.message=m;this.code='AUTHORIZATION_ERROR'}function Conflict(m){this.message=m;this.code='CONFLICT'}function VmosError(m,code){this.message=m;this.code=code}
const c=vm.createContext({String,Number,Boolean,Date,Object,Array,Math,JSON,VmosValidationError_:Validation,VmosAuthorizationError_:Authorization,VmosConflictError:Conflict,VmosError_:VmosError});['ConfigQuoteCosting.gs','Services/QuoteSourceDocumentService.gs','Services/SecurityOperationRecoveryService.gs'].forEach(file=>vm.runInContext(fs.readFileSync(path.join(root,file),'utf8'),c));
function memory(rows=[]){return {rows,get(id){return this.rows.find(row=>row.id===id)},list(){return this.rows.slice()},forTenant(t){return this.rows.filter(row=>row.tenantId===t)},byField(t,f,v,l){return this.rows.filter(row=>row.tenantId===t&&String(row[f])===String(v)).slice(0,l)},create(row){this.rows.push(row);return row},update(id,changes){let row=this.get(id);Object.assign(row,changes);return row},search(t,q,l){let term=String(q||'').toLowerCase();return this.rows.filter(row=>row.tenantId===t&&String(row.status||'ACTIVE')==='ACTIVE'&&String(row.title+' '+row.documentType).toLowerCase().includes(term)).slice(0,l)}}}
function entity(rows){return {rows,get(id){return rows.find(row=>row.id===id)},list(){return rows.slice()}}}
const quotes=entity([{id:'Q1',customerId:'C1',rfqId:'R1',securityTenantId:'T1'},{id:'QX',customerId:'CX',rfqId:'RX',securityTenantId:'T2'}]),rfqs=entity([{id:'R1',customerId:'C1',securityTenantId:'T1'}]),customers=entity([{id:'C1',securityTenantId:'T1'}]),jobs=entity([{id:'J1',quoteId:'Q1',partId:'P1',securityTenantId:'T1'},{id:'J2',quoteId:'QX',securityTenantId:'T1'}]),vendors=memory([{id:'V1',tenantId:'T1',name:'OnlineMetals',status:'ACTIVE'},{id:'VX',tenantId:'T2',name:'Foreign'}]),estimates=memory([{id:'E1',tenantId:'T1',quoteId:'Q1'}]),costLines=memory([{id:'L1',tenantId:'T1',estimateId:'E1',partId:'P1',description:'H2 material',category:'MATERIAL'}]),revisions=memory([{id:'REV1',tenantId:'T1',quoteId:'Q1'},{id:'REVX',tenantId:'T2',quoteId:'QX'}]),quoteLines=memory([{id:'QL1',tenantId:'T1',quoteRevisionId:'REV1'},{id:'QLX',tenantId:'T2',quoteRevisionId:'REVX'}]),documents=memory([{id:'D1',tenantId:'T1',title:'H2 costing workbook',documentType:'WORKBOOK',customerEligible:false,status:'ACTIVE',sourceFingerprint:'FP1',sourceVersion:'7'},{id:'D2',tenantId:'T1',title:'Customer drawing',documentType:'DRAWING',customerEligible:true,status:'ACTIVE'},{id:'DX',tenantId:'T2',title:'Foreign workbook',status:'ACTIVE'}]),links=memory(),context={tenantId:'T1',userId:'USER-A',operationId:'OP-A',requestFingerprint:'REQ-A',capabilities:['QUOTE_COST_WRITE','QUOTE_WRITE']},service=new c.QuoteSourceDocumentService_({links,documents,quotes,rfqs,customers,jobs,vendors,estimates,costLines,revisions,quoteLines,clock:()=>new Date('2026-08-15T12:00:00Z')});
let created=service.add({documentId:'D1',quoteId:'Q1',relationshipType:'QUOTE',purpose:'WORKBOOK',visibility:'INTERNAL'},context,'QSDL-1');assert.equal(created.duplicate,false);assert.equal(created.link.createdBy,'USER-A');assert.equal(created.link.securityActorId,'USER-A');assert.equal(created.link.sourceFingerprint,'FP1');assert.equal(created.link.visibility,'INTERNAL');
const recovery=Object.create(c.SecurityOperationRecoveryService_.prototype);recovery.quoteSourceLinks=links;let proofRecord={resourceType:'QuoteSourceDocumentLink',resourceId:'QSDL-1',id:'OP-A',requestFingerprint:'REQ-A',tenantId:'T1',userId:'USER-A'};assert.equal(recovery.resource_(proofRecord).id,'QSDL-1');assert.equal(recovery.matchesOperationProof_(proofRecord,created.link),true,'dual-ledger recovery proves the exact tenant/operation/actor-bound link');assert.equal(recovery.matchesOperationProof_(Object.assign({},proofRecord,{userId:'USER-B'}),created.link),false,'foreign actor cannot adopt link proof');
let duplicate=service.add({documentId:'D1',quoteId:'Q1',relationshipType:'QUOTE',purpose:'WORKBOOK',visibility:'INTERNAL'},Object.assign({},context,{operationId:'OP-B'}),'QSDL-2');assert.equal(duplicate.duplicate,true);assert.equal(links.rows.length,1,'duplicate relationship is deterministic');assert.equal(duplicate.link.createdBy,'USER-A','duplicate cannot rewrite authoritative attribution');
assert.throws(()=>service.add({documentId:'DX',quoteId:'Q1',relationshipType:'QUOTE',purpose:'WORKBOOK',visibility:'INTERNAL'},context,'BAD-1'),e=>e.code==='AUTHORIZATION_ERROR','cross-tenant document denied');assert.throws(()=>service.add({documentId:'D1',quoteId:'QX',relationshipType:'QUOTE',purpose:'WORKBOOK',visibility:'INTERNAL'},context,'BAD-2'),e=>e.code==='AUTHORIZATION_ERROR','cross-tenant quote denied');assert.throws(()=>service.add({documentId:'D1',quoteId:'Q1',relationshipType:'JOB',jobId:'J2',purpose:'WORKBOOK',visibility:'INTERNAL'},context,'BAD-3'),e=>e.code==='VALIDATION_ERROR','unrelated Work Order denied');assert.throws(()=>service.add({documentId:'D1',quoteId:'Q1',relationshipType:'VENDOR',vendorId:'VX',purpose:'SUPPLIER_ESTIMATE',visibility:'INTERNAL'},context,'BAD-4'),e=>e.code==='AUTHORIZATION_ERROR','cross-tenant Vendor denied');
assert.throws(()=>service.add({documentId:'D1',quoteId:'Q1',relationshipType:'QUOTE',purpose:'WORKBOOK',visibility:'CUSTOMER_APPROVED'},context,'BAD-5'),e=>e.code==='AUTHORIZATION_ERROR','internal workbook cannot be customer approved');let customerLink=service.add({documentId:'D2',quoteId:'Q1',relationshipType:'RFQ',rfqId:'R1',purpose:'DRAWING',visibility:'CUSTOMER_APPROVED'},context,'QSDL-3');assert.equal(customerLink.link.visibility,'CUSTOMER_APPROVED');
let visibilityChange=service.add({documentId:'D2',quoteId:'Q1',relationshipType:'RFQ',rfqId:'R1',purpose:'DRAWING',visibility:'INTERNAL'},Object.assign({},context,{operationId:'OP-VIS'}),'QSDL-VIS');assert.equal(visibilityChange.link.visibility,'INTERNAL','duplicate relationship applies intended visibility change');assert.equal(visibilityChange.link.version,2);
assert.throws(()=>service.add({documentId:'D1',quoteId:'Q1',relationshipType:'PART',partId:'OTHER',jobId:'J1',purpose:'DRAWING',visibility:'INTERNAL'},context,'BAD-6'),e=>e.code==='VALIDATION_ERROR','Part must belong to selected Work Order');
assert.throws(()=>service.add({documentId:'D1',quoteId:'Q1',quoteRevisionId:'REVX',relationshipType:'QUOTE',purpose:'DRAWING',visibility:'INTERNAL'},context,'BAD-7'),e=>e.code==='AUTHORIZATION_ERROR','cross-tenant Quote revision denied');assert.throws(()=>service.add({documentId:'D1',quoteId:'Q1',quoteRevisionId:'REV1',quoteLineItemId:'QLX',relationshipType:'QUOTE',purpose:'DRAWING',visibility:'INTERNAL'},context,'BAD-8'),e=>e.code==='AUTHORIZATION_ERROR','cross-tenant Quote line denied');
let costLink=service.add({documentId:'D1',quoteId:'Q1',relationshipType:'QUOTE_COST_LINE',estimateId:'E1',costLineId:'L1',purpose:'SUPPLIER_ESTIMATE',visibility:'INTERNAL'},context,'QSDL-4');assert.equal(costLink.link.costLineId,'L1');let partLink=service.add({documentId:'D1',quoteId:'Q1',relationshipType:'PART',partId:'P1',costLineId:'L1',purpose:'DRAWING',visibility:'INTERNAL'},context,'QSDL-5');assert.equal(partLink.link.partId,'P1');
assert.throws(()=>service.remove('QSDL-1',2,context),e=>e.code==='CONFLICT','stale unlink conflicts');let removed=service.remove('QSDL-1',1,context);assert.equal(removed.link.status,'REMOVED');assert.equal(removed.link.removedBy,'USER-A');assert.equal(service.remove('QSDL-1',2,context).alreadyRemoved,true,'unlink replay is idempotent');
let listed=service.list('Q1',context,50);assert.equal(listed.some(row=>row.id==='QSDL-1'),false,'removed link excluded');documents.rows=documents.rows.filter(row=>row.id!=='D2');assert.equal(service.list('Q1',context,50).find(row=>row.id==='QSDL-3').status,'REFERENCE_UNAVAILABLE','missing reference degrades safely');assert.equal(service.searchDocuments('workbook',context,25).items.length,1);assert(service.searchTargets('VENDOR','online','Q1',context,25).items[0].label==='OnlineMetals');assert(service.searchTargets('JOB','J1','Q1',context,25).items[0].id==='J1');assert(service.searchTargets('QUOTE_COST_LINE','material','Q1',context,25).items[0].id==='L1');
const ui=fs.readFileSync(path.join(root,'UI','QuoteBuilder.html'),'utf8'),code=fs.readFileSync(path.join(root,'UI','Code.gs'),'utf8'),registry=fs.readFileSync(path.join(root,'Services','EndpointAuthorizationRegistry.gs'),'utf8'),costing=fs.readFileSync(path.join(root,'Services','QuoteCostingService.gs'),'utf8');['searchQuoteSourceDocuments','searchQuoteSourceTargets','addQuoteSourceDocumentLink','removeQuoteSourceDocumentLink','Refresh links','Atlas could not confirm','sourceBusy','role="combobox"'].forEach(value=>assert(ui.includes(value)||code.includes(value),value));assert(!/Document ID<\/span>|Quote ID<\/span>|Vendor ID<\/span>/.test(ui),'operator does not type raw relationship IDs');assert(registry.includes("addQuoteSourceDocumentLink:'PREALLOCATED_RESOURCE_ID'"));assert(registry.includes("removeQuoteSourceDocumentLink:'EXPLICIT_REVIEW'"));assert(!/documents\s*:/.test(costing.match(/customerProjection[\s\S]*$/)[0].split('};')[0]),'customer projection does not expose source links');
console.log('MOS-126E source-document linking, tenant isolation, privacy, idempotency, and recovery UX tests passed');
