const assert=require('assert'),fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..','appscript','src');
const shop=fs.readFileSync(path.join(root,'UI','ShopFloor.html'),'utf8');
const service=fs.readFileSync(path.join(root,'Services','ShopFloorService.gs'),'utf8');
const code=fs.readFileSync(path.join(root,'UI','Code.gs'),'utf8');
const registry=fs.readFileSync(path.join(root,'Services','EndpointAuthorizationRegistry.gs'),'utf8');
assert.match(code,/function getShopFloorWorkspace\(token\)/);
assert.match(registry,/getShopFloorWorkspace:\{kind:'READ',capability:'OPERATIONS_READ'\}/);
assert.match(service,/getWorkspaceByQr/);
assert.match(service,/slice\(0,maximum\)/,'recent event history is bounded server-side');
assert.match(service,/Math\.min\(Number\(limit\)\|\|12,25\)/,'event bound has a hard cap');
assert.match(service,/capabilities\.indexOf\('SHOP_FLOOR_OPERATE'\)/,'actions derive from trusted capability context');
assert.match(shop,/getShopFloorWorkspace\(shopState\.token\)/,'one authoritative read model refreshes Job and history');
assert.doesNotMatch(shop,/\.listJobEvents\(/,'UI no longer issues a second history request');
assert.doesNotMatch(shop,/window\.prompt|window\.confirm/,'routine tablet workflow uses no browser prompts');
assert.match(shop,/Identity confirmation unavailable/);
assert.match(shop,/Assigned operator/);
assert.match(shop,/Only actions valid for the current authoritative state are shown/);
assert.match(shop,/problemDraft:\{reason:'',notes:''\}/);
assert.match(shop,/oninput="shopState\.problemDraft\.notes=this\.value"/,'problem notes survive rerender and failure');
assert.match(shop,/Your note is preserved; refresh before retrying/);
assert.match(shop,/The result could not be confirmed\. Refresh current Job state before retrying/);
assert.match(shop,/if\(shopState\.busy/,'duplicate mutation taps are guarded');
assert.match(shop,/button\[disabled\]/);
assert.match(shop,/min-height:68px/);
assert.match(shop,/min-height:56px/);
assert.match(shop,/@media\(max-width:900px\)/,'tablet portrait changes to one operational column');
assert.match(shop,/@media\(max-width:600px\)/,'mobile fallback is explicit');
assert.match(shop,/:focus-visible/);
assert.match(shop,/prefers-reduced-motion:reduce/);
assert.match(shop,/role="status"/);
assert.match(shop,/Scanning does not start or change the Job/,'QR entry is explicitly read-only');
assert.doesNotMatch(shop,/Firearms|Cerakote|Vitality|Asana/i,'shared operator UI stays tenant and vertical neutral');
assert.doesNotMatch(shop,/SpreadsheetApp|openById|getSheetByName|getRange\s*\(/);
assert.equal((shop.match(/\.getShopFloorWorkspace\(/g)||[]).length,2,'initial load and post-mutation refresh share one bounded endpoint');
console.log('MOS-122D shop-floor tablet UX, async recovery, accessibility, and bounded payload contracts passed');
