const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm'),crypto=require('crypto');
const base=path.join(__dirname,'..','appscript','src');
const callableSource=fs.readFileSync(path.join(base,'UI','Code.gs'),'utf8');
assert.match(callableSource,/function configureShopFloorJob[^\n]+a\.checkpoint[^\n]+SHOP_FLOOR_DOMAIN_EVENT/,'Shop-floor configuration must enter durable domain-event recovery.');
assert.doesNotMatch(callableSource,/recoverSecurityOperation_?\(/,'Recovery must not be exposed as a browser callable.');
const context=vm.createContext({console,Date,JSON,String,Number,Error,Object,Array,Math,isNaN,isFinite,
  Utilities:{getUuid:()=>String(Math.random()).slice(2),DigestAlgorithm:{SHA_256:'SHA_256'},Charset:{UTF_8:'UTF_8'},computeDigest:(algorithm,value)=>Array.from(crypto.createHash('sha256').update(String(value)).digest()).map(value=>value>127?value-256:value)},
  LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},PropertiesService:{getScriptProperties:()=>({getProperty:()=>null})},ScriptApp:{getService:()=>({getUrl:()=>''})},SecurityAuditEventRepository_:function(){}});
['Utilities/Errors.gs','Utilities/Serialization.gs','Utilities/WorkflowConfig.gs','Repository/OperationalRepositories.gs','Services/IdentityAuthorizationService.gs','Services/ShopFloorService.gs','Services/SecurityOperationRecoveryService.gs'].forEach(file=>vm.runInContext(fs.readFileSync(path.join(base,file),'utf8'),context));
context.MvpService_=function(entity){if(entity==='Customer')this.get=()=>({id:'C1',name:'Test Customer'});};
const lock={waitLock(){},releaseLock(){}};
function memoryLedger(){const rows=[];return {rows,findByOperationIdentity:(tenant,user,operation,key)=>rows.find(row=>row.tenantId===tenant&&row.userId===user&&row.operation===operation&&row.idempotencyKey===key),create:record=>(rows.push({...record}),rows[rows.length-1]),get:id=>rows.find(row=>row.id===id),update(id,changes){const row=this.get(id);Object.assign(row,changes);return row;}};}
function auditContext(correlation){return {tenantId:'TENANT-A',userId:'USR-OPERATOR',principalType:'TEST',principalSubject:'operator@test',operation:'configureShopFloorJob',correlationId:correlation,actorType:'USER',occurredAt:new Date('2026-08-10T10:00:00Z'),capabilities:['OPERATIONS_WRITE']};}
function fixture(failEventType){
  const job={id:'JOB-1',customerId:'C1',status:'PLANNED'},tokens=[],events=[],ledgerRepository=memoryLedger();let tokenCreates=0,failed=false;
  const jobs={get:id=>{assert.equal(id,'JOB-1');return job;},update:(id,changes)=>(Object.assign(job,changes),job)};
  const qrTokens={list:()=>tokens,listByJobId:id=>tokens.filter(token=>token.jobId===id),findActiveByJobId:id=>tokens.filter(token=>token.jobId===id&&!token.revokedAt),create:record=>{tokenCreates++;tokens.push({...record});return tokens[tokens.length-1];}};
  const jobEvents={listByJobId:id=>events.filter(event=>event.jobId===id),append:event=>{if(!failed&&event.eventType===failEventType){failed=true;throw new Error('JobEvent unavailable');}events.push({...event});return event;}};
  const ledger=new context.SecurityAuditService_({repository:ledgerRepository,lock,clock:()=>new Date('2026-08-10T10:00:00Z'),uuid:()=> 'LEDGER-1'});
  const options={idempotencyKey:'configure:JOB-1',resourceType:'Job',resourceId:'JOB-1',recoveryType:'SHOP_FLOOR_DOMAIN_EVENT',recoveryContext:{eventTypes:['QR_ASSIGNED'],workflowId:'MACHINING',workflowVersion:'1'}};
  const operation=operationContext=>new context.ShopFloorService_({jobs,events:jobEvents,qrTokens,auditUser:()=>operationContext.userId,checkpoint:operationContext.checkpoint,tokenGenerator:()=> '11111111222243338444555555555555',clock:()=>new Date('2026-08-10T10:00:00Z')}).configureJob('JOB-1','MACHINING','SETUP',operationContext.correlationId);
  return {job,tokens,events,ledgerRepository,ledger,jobs,qrTokens,jobEvents,options,operation,get tokenCreates(){return tokenCreates;}};
}

// QR creation and workflow state survive a QR_ASSIGNED append failure with non-secret deterministic recovery context.
const qrFailure=fixture('QR_ASSIGNED');
assert.throws(()=>qrFailure.ledger.execute(auditContext('CORR-QR'),'OPERATIONS_WRITE',qrFailure.operation,qrFailure.options),error=>error.code==='UNKNOWN_OUTCOME');
const qrRecord=qrFailure.ledgerRepository.rows[0],qrContext=JSON.parse(qrRecord.recoveryJson);
assert.equal(qrFailure.tokens.length,1);assert.equal(qrFailure.tokenCreates,1);assert.equal(qrFailure.job.status,'SETUP');assert.equal(qrRecord.resourceId,'JOB-1');assert.equal(qrRecord.recoveryType,'SHOP_FLOOR_DOMAIN_EVENT');assert.equal(qrRecord.userId,'USR-OPERATOR');assert.deepEqual(Array.from(qrContext.eventTypes),['WORKFLOW_ASSIGNED','QR_ASSIGNED']);assert.equal(qrContext.workflowId,'MACHINING');assert.equal(qrContext.qrTokenFingerprint.length,64);assert.ok(!JSON.stringify(qrRecord).includes(qrFailure.tokens[0].id),'Raw QR token must not enter the security ledger.');
const recovery=new context.SecurityOperationRecoveryService_({securityEvents:qrFailure.ledgerRepository,jobs:qrFailure.jobs,jobEvents:qrFailure.jobEvents,qrTokens:qrFailure.qrTokens,followUps:{},followUpEvents:{},ideas:{},ideaEvents:{},ledger:qrFailure.ledger,lock});
recovery.reconcile(qrRecord.id,{tenantId:'TENANT-A',actor:'SYSTEM:SECURITY_OPERATION_RECOVERY',correlationId:'RECOVERY-1'});recovery.reconcile(qrRecord.id,{tenantId:'TENANT-A',actor:'SYSTEM:SECURITY_OPERATION_RECOVERY',correlationId:'RECOVERY-2'});
assert.equal(qrFailure.tokenCreates,1,'Recovery must never recreate the QR token.');assert.equal(qrFailure.events.filter(event=>event.eventType==='WORKFLOW_ASSIGNED').length,1);assert.equal(qrFailure.events.filter(event=>event.eventType==='QR_ASSIGNED').length,1);assert.ok(qrFailure.events.every(event=>event.actor==='USR-OPERATOR'));assert.equal(qrFailure.ledgerRepository.get(qrRecord.id).recoveryActor,'SYSTEM:SECURITY_OPERATION_RECOVERY');assert.ok(!JSON.stringify(qrFailure.events).includes(qrFailure.tokens[0].id));
assert.throws(()=>recovery.reconcile(qrRecord.id,{tenantId:'TENANT-B',actor:'SYSTEM'}),error=>error.code==='AUTHORIZATION_ERROR');

// Failure of the first required event reconstructs both events exactly once.
const workflowFailure=fixture('WORKFLOW_ASSIGNED');assert.throws(()=>workflowFailure.ledger.execute(auditContext('CORR-WORKFLOW'),'OPERATIONS_WRITE',workflowFailure.operation,workflowFailure.options),error=>error.code==='UNKNOWN_OUTCOME');
const workflowRecord=workflowFailure.ledgerRepository.rows[0],workflowRecovery=new context.SecurityOperationRecoveryService_({securityEvents:workflowFailure.ledgerRepository,jobs:workflowFailure.jobs,jobEvents:workflowFailure.jobEvents,qrTokens:workflowFailure.qrTokens,followUps:{},followUpEvents:{},ideas:{},ideaEvents:{},ledger:workflowFailure.ledger,lock});workflowRecovery.reconcile(workflowRecord.id,{tenantId:'TENANT-A',actor:'SYSTEM:SECURITY_OPERATION_RECOVERY',correlationId:'REC-W'});assert.deepEqual(workflowFailure.events.map(event=>event.eventType),['WORKFLOW_ASSIGNED','QR_ASSIGNED']);assert.equal(workflowFailure.tokenCreates,1);

// Existing/late events win races; revoked tokens remain valid historical evidence, while missing/changed state requires review.
const late=fixture('NEVER');late.ledger.execute(auditContext('CORR-LATE'),'OPERATIONS_WRITE',late.operation,late.options);const lateRecord=late.ledgerRepository.rows[0];lateRecord.status='RECOVERY_REQUIRED';lateRecord.recoveryStatus='PENDING';late.tokens[0].revokedAt=new Date('2026-08-10T11:00:00Z');const before=late.events.length;new context.SecurityOperationRecoveryService_({securityEvents:late.ledgerRepository,jobs:late.jobs,jobEvents:late.jobEvents,qrTokens:late.qrTokens,followUps:{},followUpEvents:{},ideas:{},ideaEvents:{},ledger:late.ledger,lock}).reconcile(lateRecord.id,{tenantId:'TENANT-A',actor:'SYSTEM',correlationId:'REC-LATE'});assert.equal(late.events.length,before,'Already-present events must not duplicate, even after token revocation.');
const changed=fixture('QR_ASSIGNED');assert.throws(()=>changed.ledger.execute(auditContext('CORR-CHANGED'),'OPERATIONS_WRITE',changed.operation,changed.options),error=>error.code==='UNKNOWN_OUTCOME');changed.job.status='RUNNING';const changedRecord=changed.ledgerRepository.rows[0],changedRecovery=new context.SecurityOperationRecoveryService_({securityEvents:changed.ledgerRepository,jobs:changed.jobs,jobEvents:changed.jobEvents,qrTokens:changed.qrTokens,followUps:{},followUpEvents:{},ideas:{},ideaEvents:{},ledger:changed.ledger,lock});const changedResult=changedRecovery.reconcile(changedRecord.id,{tenantId:'TENANT-A',actor:'SYSTEM',correlationId:'REC-CHANGED'});assert.equal(changedResult.outcome,'UNCERTAIN');assert.equal(changed.ledgerRepository.get(changedRecord.id).status,'RECOVERY_REQUIRED');assert.equal(changed.events.some(event=>event.eventType==='QR_ASSIGNED'),false);
const forged=fixture('QR_ASSIGNED');assert.throws(()=>forged.ledger.execute(auditContext('CORR-FORGED'),'OPERATIONS_WRITE',forged.operation,forged.options),error=>error.code==='UNKNOWN_OUTCOME');const forgedRecord=forged.ledgerRepository.rows[0],forgedContext=JSON.parse(forgedRecord.recoveryJson);forgedContext.qrTokenFingerprint='0'.repeat(64);forgedRecord.recoveryJson=JSON.stringify(forgedContext);const forgedRecovery=new context.SecurityOperationRecoveryService_({securityEvents:forged.ledgerRepository,jobs:forged.jobs,jobEvents:forged.jobEvents,qrTokens:forged.qrTokens,followUps:{},followUpEvents:{},ideas:{},ideaEvents:{},ledger:forged.ledger,lock});assert.equal(forgedRecovery.reconcile(forgedRecord.id,{tenantId:'TENANT-A',actor:'SYSTEM',correlationId:'REC-FORGED'}).outcome,'UNCERTAIN');assert.equal(forged.events.some(event=>event.eventType==='QR_ASSIGNED'),false);
const wrongType=fixture('QR_ASSIGNED');assert.throws(()=>wrongType.ledger.execute(auditContext('CORR-WRONG-TYPE'),'OPERATIONS_WRITE',wrongType.operation,wrongType.options),error=>error.code==='UNKNOWN_OUTCOME');const wrongRecord=wrongType.ledgerRepository.rows[0],wrongContext=JSON.parse(wrongRecord.recoveryJson);wrongContext.eventTypes=['QR_ASSIGNED','ADMIN_GRANTED'];wrongRecord.recoveryJson=JSON.stringify(wrongContext);const wrongRecovery=new context.SecurityOperationRecoveryService_({securityEvents:wrongType.ledgerRepository,jobs:wrongType.jobs,jobEvents:wrongType.jobEvents,qrTokens:wrongType.qrTokens,followUps:{},followUpEvents:{},ideas:{},ideaEvents:{},ledger:wrongType.ledger,lock});assert.equal(wrongRecovery.reconcile(wrongRecord.id,{tenantId:'TENANT-A',actor:'SYSTEM',correlationId:'REC-WRONG'}).outcome,'UNCERTAIN');assert.equal(wrongType.events.some(event=>event.eventType==='ADMIN_GRANTED'),false);

console.log('MOS-121L shop-floor QR assignment durable recovery tests passed');
