const assert=require('assert'),fs=require('fs'),path=require('path'),vm=require('vm'),base=path.join(__dirname,'..','appscript','src');
function Validation(message){this.message=message;}function Authorization(message){this.message=message;}function Missing(message){this.message=message;}
const users=[{id:'U-1',displayName:'Admin',status:'ACTIVE'},{id:'U-2',displayName:'Buyer',status:'ACTIVE'}],memberships=[{id:'M-1',tenantId:'T-1',userId:'U-1',status:'ACTIVE',roles:'["ADMIN"]'},{id:'M-2',tenantId:'T-1',userId:'U-2',status:'ACTIVE',roles:'["FINANCE"]'},{id:'M-X',tenantId:'T-2',userId:'U-X',status:'ACTIVE',roles:'["ADMIN"]'}],invitations=[];
const repo=rows=>({list:()=>rows.slice(),get:id=>rows.find(x=>x.id===id),update:(id,c)=>Object.assign(rows.find(x=>x.id===id),c),create:r=>(rows.push(r),r)}),invites=Object.assign(repo(invitations),{listForTenant:(tenant,limit)=>invitations.filter(x=>x.tenantId===tenant).slice(0,limit)});
const context=vm.createContext({Date,Math,Number,String,Object,Array,JSON,Utilities:{getUuid:()=> 'UUID'},VmosValidationError_:Validation,VmosAuthorizationError_:Authorization,VmosNotFoundError_:Missing,parseIdentityList_:value=>{try{return JSON.parse(value)}catch(e){return Array.isArray(value)?value:String(value||'').split(',').filter(Boolean)}},ATLAS_DEFAULT_ROLE_CAPABILITIES:{SHOP_OPERATOR:[],SALES:[],MANAGER:[],FINANCE:[],ADMIN:[]},serializeVmosValue_:v=>JSON.parse(JSON.stringify(v))});
vm.runInContext(fs.readFileSync(path.join(base,'Services','TenantOperationalAdminService.gs'),'utf8'),context);
const admin=new context.TenantOperationalAdminService_({users:repo(users),memberships:repo(memberships),invitations:invites,clock:()=>new Date('2026-08-12'),uuid:()=> '1'}),actor={tenantId:'T-1',userId:'U-1'};
let workspace=admin.workspace(actor);assert.equal(workspace.memberships.length,2);assert(!workspace.memberships.some(x=>x.userId==='U-X'));assert(!workspace.approvedRoles.some(x=>x.startsWith('PLATFORM_')));
const invitation=admin.invite({email:'buyer@example.com',roles:['FINANCE']},actor,'INVITE-1');assert.equal(invitation.tenantId,'T-1');assert.equal(invitation.invitedBy,'U-1');assert.throws(()=>admin.invite({email:'x@example.com',roles:['PLATFORM_OWNER']},actor,'INVITE-X'),error=>/approved tenant roles/.test(error.message));
admin.updateMembership('M-2',{roles:['MANAGER']},actor);assert.equal(memberships[1].roles,'["MANAGER"]');assert.throws(()=>admin.updateMembership('M-X',{status:'INACTIVE'},actor),error=>/unavailable/.test(error.message));assert.throws(()=>admin.updateMembership('M-1',{status:'INACTIVE'},actor),error=>/own active/.test(error.message));
const purchases=[{id:'P-1',securityTenantId:'T-1',vendor:'Readable Vendor',description:'Tooling',status:'PENDING_APPROVAL',requester:'U-2',amount:100,classification:'CAPEX',approvalRequired:true},{id:'P-X',securityTenantId:'T-2',vendor:'Foreign',description:'Hidden',status:'PENDING_APPROVAL'}];
vm.runInContext(fs.readFileSync(path.join(base,'Services','PurchasingWorkspaceService.gs'),'utf8'),context);const purchasing=new context.PurchasingWorkspaceService_({purchases:{list:()=>purchases,get:id=>purchases.find(x=>x.id===id)},limit:50});workspace=purchasing.get({id:'P-1'},Object.assign({},actor,{capabilities:['PURCHASE_REQUEST','PURCHASE_APPROVE']}));assert.equal(workspace.items.length,1);assert.equal(workspace.selected.vendor,'Readable Vendor');assert.equal(workspace.actions.approve,true);assert.throws(()=>purchasing.get({id:'P-X'},Object.assign({},actor,{capabilities:['PURCHASE_REQUEST']})),error=>/unavailable/.test(error.message));
const adminHtml=fs.readFileSync(path.join(base,'UI','AdminSettings.html'),'utf8'),purchaseHtml=fs.readFileSync(path.join(base,'UI','PurchasingWorkspace.html'),'utf8'),commercialHtml=fs.readFileSync(path.join(base,'UI','CommercialWorkflow.html'),'utf8'),code=fs.readFileSync(path.join(base,'UI','Code.gs'),'utf8'),registry=fs.readFileSync(path.join(base,'Services','EndpointAuthorizationRegistry.gs'),'utf8');
assert.match(adminHtml,/cannot grant PLATFORM_\*/);assert.match(adminHtml,/Create invitation/);assert.match(purchaseHtml,/New purchase request/);assert.doesNotMatch(purchaseHtml,/Purchase Request ID<\/label>|Requester ID<\/label>/);assert.match(purchaseHtml,/Rejection is not available/);assert.match(commercialHtml,/Record Payment \/ Cash Receipt/);assert.match(code,/recordInvoicePayment/);assert.match(registry,/inviteTenantUser:\{kind:'ADMINISTRATIVE',capability:'ADMIN_IDENTITY'\}/);assert.match(purchaseHtml,/@media\(max-width:480px\)/);
console.log('Atlas tenant administration, purchasing, and contextual payment tests passed');
